#!/usr/bin/env python3
"""
Activity Drop Rate Calculator

Shows expected steps per item drop for a given activity with your current gear.
"""

from util.autogenerated.activities import Activity
from util.gearset_utils import decode_gearset, calculate_gear_stats, Gearset
from util.walkscape_constants import Skill, Location

# Paste your gearset export string here
ACTIVITY = Activity.RESCUE_TEAM
GEARSET_EXPORT = "H4sIAAAAAAAAA62VW27bMBBF96LvDMD3IxvoIupAGJJDW40suZLc1Aiy945SoECQuDWq/EgAQUqHd+7ceW66hY5zc//1uVkuJ2rumwNhae6abij0s7kXd687eP1513Rl19zvXhdgOg9DN+zbH908TqAcGlUCgVfOg7G1QNLFQqCsUpZC2aB2zd2u+X7Gvlsur9/J4/E4Dq/LC+55aTj3/Qv/m6ZpnFaoh5e7P1wZ+fVvrnVbO9b2gH0FzIeOftAEWTlFunooWAqYVDQgVQlV21yVtFIWt5EvYX68gW/8ednT0C44PIJVJtRMDqSwFQwGDUnkBKpQ0CLLKJPYqtqB5uUGrGUinM8TtYfzsNDUfuPb0AIqJfIkIiSlWTfDJU0+SUBppJISEZPeSHiauiNOl48Y13PXjs2Ux6H8x8EDDmW+TRFq58zXYpfnHp9mqCZHWjWQYlXDshDRugJO1OBywIK+bFSjp/2NcG/KdcJhmdnl2kVrDUSfApjsAoTEkEIUqt7kal3ayDfQv1wuEmNYDOBSVNxqRgCKECCWLJMVzscY30F8GcdyK0IlusXRIz6282M3gySpKlICIVNeq+YgOuQoUCGWpKwvZDeqMrFH/o7kbQyo1gaPPnJprOVw4qavgjVhD5E0WxvpLYS8qktf2v36WPeDQh294cx2SPhbHBRcMu1SSWSTrRY3ci3j2N9QLyzjStRWHNp5weVMq2/RFFlAqJA4fTzLZ7QFZ4TlltOiRPpUuOuiHYcO1r3ghZbFKA3GKe4xwb5KSiComKWy6LUT5lOZ1DWm2o9Pq2CncY3qJ1zyAaTLZIPhwRaJEwoFcULVCD5qFVX1PsutNntLp6/RMQ/nUhqXpScwZIIxTITFGzAReaBQjpC1UCSEVdnVT8Uy17D2nOrl0p66/f7SpnUIhyplzJWg+shsfh12OWnQZGuq3KOpyE9lszeNqdPHIff+yMPLL7CU3iLFCQAA"
LOCATION = None # None = use first location from activity

SKILL_LEVEL = None # None = auto-detect from character

# ============================================================================
# CALCULATION
# ============================================================================

def main():
    print("=" * 80)
    print(f"Activity Drop Rate Analysis: {ACTIVITY.name}")
    print("=" * 80)
    print()
    
    # Check if activity is unlocked
    is_unlocked = ACTIVITY.is_unlocked(GEARSET_EXPORT)
    if not is_unlocked:
        print("⚠" * 40)
        print("WARNING: This activity is NOT UNLOCKED!")
        print("⚠" * 40)
        print()
        print("Missing requirements:")
        
        # Check what's missing
        from my_config import get_character
        character = get_character()
        
        # Check skill requirements
        for skill, required_level in ACTIVITY.skill_requirements.items():
            char_level = character.get_skill_level(skill.lower())
            if char_level < required_level:
                print(f"  ✗ {skill} level {required_level} (you have {char_level})")
            else:
                print(f"  ✓ {skill} level {required_level}")
        
        # Check reputation
        for faction, required_amount in ACTIVITY.requirements.get("reputation", {}).items():
            char_rep = character.reputation.get(faction, 0)
            if char_rep < required_amount:
                print(f"  ✗ {faction} reputation {required_amount} (you have {char_rep})")
            else:
                print(f"  ✓ {faction} reputation {required_amount}")
        
        # Check achievement points
        required_ap = ACTIVITY.requirements.get("achievement_points", 0)
        if required_ap > 0:
            from util.walkscape_globals import ACHIEVEMENT_POINTS
            if int(ACHIEVEMENT_POINTS) < required_ap:
                print(f"  ✗ {required_ap} achievement points (you have {int(ACHIEVEMENT_POINTS)})")
            else:
                print(f"  ✓ {required_ap} achievement points")
        
        # Check gearset requirements using keyword_counts
        if GEARSET_EXPORT:
            gearset = Gearset(GEARSET_EXPORT)
            
            # Check all keyword requirements from keyword_counts
            keyword_counts = ACTIVITY.requirements.get("keyword_counts", {})
            for keyword, required_count in keyword_counts.items():
                if required_count <= 0:
                    continue
                
                # Count items with this keyword
                count = sum(
                    1 for slot, item in gearset.get_all_items()
                    if item and hasattr(item, "keywords") and 
                    any(keyword.lower() in kw.lower() for kw in item.keywords)
                )
                if count < required_count:
                    print(f"  ✗ {required_count} {keyword} (you have {count})")
                else:
                    print(f"  ✓ {required_count} {keyword}")
        
        print()
        print("=" * 80)
        print("Continuing with analysis anyway...")
        print("=" * 80)
        print()
    
    # Auto-detect skill level if not provided
    skill_level = SKILL_LEVEL
    if skill_level is None:
        # Try to get from character export
        try:
            from my_config import get_character
            character = get_character()
            skill_level = character.get_skill_level(ACTIVITY.primary_skill.lower())
            print(f"Auto-detected {ACTIVITY.primary_skill} level: {skill_level}")
        except:
            skill_level = 1
            print(f"⚠ Could not auto-detect skill level, using level 1")
    
    # Auto-detect location if not provided
    location = LOCATION
    if location is None and ACTIVITY.locations:
        location = ACTIVITY.locations[0]
    print(f"Using location: {location.name}")
    
    print()
    
    # Show activity info
    print(f"Primary Skill: {ACTIVITY.primary_skill}")
    print(f"Base Steps: {ACTIVITY.base_steps}")
    print(f"Base XP: {ACTIVITY.base_xp}")
    print(f"Locations: {', '.join([loc.name for loc in ACTIVITY.locations])}")
    
    # Show requirements
    if ACTIVITY.requirements:
        print(f"\nRequirements:")
        reqs = ACTIVITY.requirements
        
        # Show keyword requirements
        keyword_counts = reqs.get('keyword_counts', {})
        for keyword, count in keyword_counts.items():
            if count > 0:
                print(f"  - {count} {keyword}")
    
    print()
    print("-" * 80)
    
    # Calculate stats from gearset
    if GEARSET_EXPORT:
        print("\nCalculating stats from gearset...")
        
        # Use primary skill name directly (calculate_gear_stats expects string)
        skill = ACTIVITY.primary_skill
        
        # calculate_gear_stats signature: (gearset_export, skill, location, return_breakdown)
        # Note: skill_level is not used by this function
        gearset = Gearset(GEARSET_EXPORT)
        stats = gearset.get_total_stats(skill, location)
        
        print(f"Gear Stats for {ACTIVITY.primary_skill}:")
        print(f"  Work Efficiency: {stats.get('work_efficiency', 0)*100:.1f}%")
        print(f"  Double Action: {stats.get('double_action', 0)*100:.1f}%")
        print(f"  Double Rewards: {stats.get('double_rewards', 0)*100:.1f}%")
        print(f"  Flat Steps: {stats.get('steps_add', 0)}")
        print(f"  % Steps: {stats.get('steps_percent', 0)*100:.1f}%")
    else:
        print("\n⚠ No gearset provided - using base stats only")
        stats = {'we': 0.0, 'da': 0.0, 'dr': 0.0, 'flat': 0, 'pct': 0.0}
    
    print()
    print("-" * 80)
    
    # Calculate drop rates with verbose details
    drop_rates, details = ACTIVITY.get_expected_drop_rate(stats, location, verbose=True)
    
    # Show comprehensive calculation details
    print("\n" + "=" * 80)
    print("CALCULATION BREAKDOWN")
    print("=" * 80)
    print(f"Primary Skill: {details['primary_skill']}")
    print(f"Skill Level: {details['skill_level']}")
    print(f"Base Steps: {details['base_steps']}")
    print(f"Base XP: {details['base_xp']}")
    print()
    
    # Show all intermediate values
    print("INTERMEDIATE VALUES:")
    print(f"  Level Bonus WE: {details['level_bonus_we_pct']:.2f}%")
    print(f"  Gear WE: {stats.get('work_efficiency', 0.0) * 100:.2f}%")
    print(f"  Collectible %: {details.get('find_collectibles_pct', 0.0):.2f}%")
    print(f"  Total WE (before max): {details['work_efficiency_before_max_pct']:.2f}%")
    print(f"  Max Efficiency: {details['work_efficiency_max_pct']:.2f}%")
    print(f"  Total Efficiency: {details['work_efficiency_pct']:.2f}%")
    print(f"  Fine Material Finding: {details['fine_material_finding_pct']:.1f}%")
    print()
    
    # Show all collectible stats
    # collectible_stats_found = {k: v for k, v in details.items() if k.startswith('collectible_')}
    
    print(f"  Min Steps (at max eff): {details['min_steps']}")
    print(f"  Steps with Efficiency: {details.get('steps_with_efficiency', 'N/A')}")
    print(f"  Steps after Min Check: {details.get('steps_after_min', 'N/A')}")
    print(f"  Steps with % Reduction: {details.get('steps_with_pct', 'N/A')}")
    print(f"  Steps with Flat Reduction: {details.get('steps_with_flat', 'N/A')}")
    print(f"  Current Steps (1 action): {details['current_steps']}")
    print()
    print(f"  Double Action: {details['double_action_pct']:.2f}%")
    print(f"  Expected Paid Actions: {details.get('expected_paid_actions', 'N/A'):.4f}")
    print(f"  Expected Steps/Action (with DA): {details['expected_steps_per_action']}")
    print()
    print(f"  Reward Rolls/Completion: {details['rewards_per_completion']:.2f}")
    print()
    
    print("-" * 80)
    print("\nExpected Steps Per Item Drop:")
    print("-" * 80)
    
    if not drop_rates:
        print("\n⚠ No drops found for this activity")
        return
    
    # Calculate drop rates (includes fine materials automatically)
    from my_config import get_character
    character = get_character()
    drop_rates = ACTIVITY.get_expected_drop_rate(stats, location, character=character)
    
    # Calculate fine material chance for display
    base_fine_chance = 0.01  # 1%
    fine_material_finding = stats.get('fine_material_finding', 0.0)
    fine_chance_multiplier = 1.0 + fine_material_finding
    fine_chance = base_fine_chance * fine_chance_multiplier
    
    # Separate regular and fine materials
    regular_drops = {k: v for k, v in drop_rates.items() if "(Fine)" not in k}
    fine_drops = {k.replace(" (Fine)", ""): v for k, v in drop_rates.items() if "(Fine)" in k}
    
    # Sort by steps (most common first)
    sorted_drops = sorted(regular_drops.items(), key=lambda x: x[1])
    
    # Print table header
    has_fine = len(fine_drops) > 0
    bar_length = 80
    if has_fine:
        print(f"\n{'Item Name':<40} {'Steps/Item':>15} {'Items/1000 Steps':>18} {'Steps/Fine':>15}")
        bar_length = 95
    else:
        print(f"\n{'Item Name':<40} {'Steps/Item':>15} {'Items/1000 Steps':>18}")
    print("-" * bar_length)
    
    for item_name, steps_per_item in sorted_drops:
        items_per_1000 = 1000.0 / steps_per_item if steps_per_item > 0 else 0
        
        # Check if this item has a fine version
        if item_name in fine_drops:
            fine_steps = fine_drops[item_name]
            print(f"{item_name:<40} {steps_per_item:>15.1f} {items_per_1000:>18.2f} {fine_steps:>15,.0f}")
        else:
            print(f"{item_name:<40} {steps_per_item:>15.1f} {items_per_1000:>18.2f}")
    
    print("=" * bar_length)
    
    # Show summary stats
    total_drops = len(sorted_drops)
    most_common = sorted_drops[0] if sorted_drops else None
    rarest = sorted_drops[-1] if sorted_drops else None
    
    print(f"\nSummary:")
    print(f"  Total unique drops: {total_drops}")
    if most_common:
        print(f"  Most common: {most_common[0]} ({most_common[1]:.1f} steps)")
    if rarest:
        print(f"  Rarest: {rarest[0]} ({rarest[1]:.1f} steps)")
    
    if has_fine:
        print(f"  Materials with fine versions: {len(fine_drops)}")
    print()


if __name__ == '__main__':
    main()
