#!/usr/bin/env python3
"""
Calculate the expected coin value from opening a skill chest and selling everything.

Each chest gives 4 rolls. Each roll independently picks from the loot tables.
For each drop: expected_coins_per_roll = (chance/100) * avg_quantity * coin_value

Optionally includes fine material drops (1% chance of fine per material drop).

Usage:
    python3 chest_coin_value.py
"""

import sys
sys.path.insert(0, '.')

# Import via walkscape_constants to avoid circular import
# (walkscape_constants re-exports Item after resolving the cycle)
from util.walkscape_constants import Item  # noqa: F401
from util.autogenerated.containers import Container, ROLLS_PER_CHEST

# ============================================================================
# CONFIGURATION
# ============================================================================

# Which chest to analyze
CHEST = Container.MINING_CHEST

# Include fine material value? (1/100 chance per material drop)
INCLUDE_FINE = False

# Fine drop rate (1% of base material rate)
FINE_RATE = 0.01

# ============================================================================
# HELPERS
# ============================================================================

def get_item_value(drop):
    """Get coin value for a drop entry."""
    if drop.item_ref is None:
        # Coins drop - item_name is 'Coins'
        if drop.item_name == 'Coins':
            return 1  # Each coin = 1 coin
        return 0

    try:
        ref = drop.item_ref
        # Resolve manually to avoid circular import through item_object
        if ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            attr_name = ref.split('.', 1)[1]
            if hasattr(Material, attr_name):
                obj = getattr(Material, attr_name)
                return obj.value or 0
        elif ref.startswith('Item.'):
            from util.autogenerated.equipment import Item
            attr_name = ref.split('.', 1)[1]
            if hasattr(Item, attr_name):
                obj = getattr(Item, attr_name)
                return obj.value or 0
        elif ref.startswith('Consumable.'):
            from util.autogenerated.consumables import Consumable
            attr_name = ref.split('.', 1)[1]
            if hasattr(Consumable, attr_name):
                obj = getattr(Consumable, attr_name)
                if hasattr(obj, 'value'):
                    return obj.value or 0
        elif ref == 'Currency.COIN':
            return 1
        # Collectibles, Containers, Eggs - typically no sell value
    except Exception as e:
        print(f"  Warning: Could not resolve value for {drop.item_ref}: {e}")
    return 0


def get_fine_value(drop):
    """Get fine version coin value for a material drop."""
    if not drop.item_ref or not drop.item_ref.startswith('Material.'):
        return 0
    try:
        from util.autogenerated.materials import Material
        material_name = drop.item_ref.replace('Material.', '')
        fine_name = f"{material_name}_FINE"
        if hasattr(Material, fine_name):
            fine_obj = getattr(Material, fine_name)
            return fine_obj.value or 0
    except Exception:
        pass
    return 0


def get_ag_token_value(drop):
    """Get AG token value for a drop entry (from special_sell)."""
    if drop.item_ref is None:
        return 0
    try:
        if drop.item_ref == 'Currency.ADVENTURERS_GUILD_TOKEN':
            return 1
        if drop.item_ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            attr_name = drop.item_ref.split('.', 1)[1]
            if hasattr(Material, attr_name):
                obj = getattr(Material, attr_name)
                if hasattr(obj, 'special_sell') and obj.special_sell:
                    qty, currency_obj = obj.special_sell
                    if hasattr(currency_obj, 'name') and 'guild token' in currency_obj.name.lower():
                        return qty
    except Exception:
        pass
    return 0

# ============================================================================
# MAIN
# ============================================================================

def analyze_chest(chest, include_fine=False):
    """Analyze expected coin value per chest."""
    print(f"\n{'='*70}")
    print(f"  {chest.name} - Expected Value Analysis")
    print(f"  Rolls per chest: {ROLLS_PER_CHEST}")
    print(f"  Include fine materials: {include_fine}")
    print(f"{'='*70}\n")

    all_drops = chest.get_all_drops()

    total_coins_per_roll = 0.0
    total_ag_per_roll = 0.0

    print(f"{'Item':<35} {'%/roll':>8} {'Avg Qty':>8} {'Value':>6} {'Fine':>6} {'Coins/roll':>11} {'AG/roll':>9}")
    print("-" * 90)

    for drop in all_drops:
        chance = drop.chance_percent or 0
        if chance <= 0:
            continue

        avg_qty = drop.quantity.average if drop.quantity else 0
        coin_val = get_item_value(drop)
        fine_val = get_fine_value(drop) if include_fine else 0
        ag_val = get_ag_token_value(drop)

        # Expected coins per roll from normal drops
        coins_per_roll = (chance / 100.0) * avg_qty * coin_val

        # Add fine contribution if enabled
        fine_coins_per_roll = 0
        if include_fine and fine_val > 0:
            # Fine drops at FINE_RATE of the base rate
            fine_coins_per_roll = (chance / 100.0) * FINE_RATE * avg_qty * fine_val
            coins_per_roll += fine_coins_per_roll

        # AG tokens per roll
        ag_per_roll = (chance / 100.0) * avg_qty * ag_val

        total_coins_per_roll += coins_per_roll
        total_ag_per_roll += ag_per_roll

        fine_str = str(fine_val) if fine_val > 0 else '-'
        ag_str = f"{ag_per_roll:.4f}" if ag_per_roll > 0 else '-'

        print(f"{drop.item_name:<35} {chance:>7.3f}% {avg_qty:>8.1f} {coin_val:>6} {fine_str:>6} {coins_per_roll:>11.4f} {ag_str:>9}")

    total_coins_per_chest = total_coins_per_roll * ROLLS_PER_CHEST
    total_ag_per_chest = total_ag_per_roll * ROLLS_PER_CHEST

    print("-" * 90)
    print(f"{'TOTAL per roll':<35} {'':>8} {'':>8} {'':>6} {'':>6} {total_coins_per_roll:>11.4f} {total_ag_per_roll:>9.4f}")
    print(f"{'TOTAL per chest (x4 rolls)':<35} {'':>8} {'':>8} {'':>6} {'':>6} {total_coins_per_chest:>11.2f} {total_ag_per_chest:>9.4f}")

    print(f"\n  Summary:")
    print(f"    Expected coins per chest:     {total_coins_per_chest:.2f}")
    if total_ag_per_chest > 0:
        print(f"    Expected AG tokens per chest: {total_ag_per_chest:.4f}")

    return total_coins_per_chest, total_ag_per_chest


if __name__ == '__main__':
    print("\n--- WITHOUT fine materials ---")
    coins_no_fine, ag_no_fine = analyze_chest(CHEST, include_fine=False)

    print("\n\n--- WITH fine materials (1% chance) ---")
    coins_with_fine, ag_with_fine = analyze_chest(CHEST, include_fine=True)

    print(f"\n\n{'='*70}")
    print(f"  Comparison:")
    print(f"    Without fine: {coins_no_fine:.2f} coins/chest")
    print(f"    With fine:    {coins_with_fine:.2f} coins/chest")
    print(f"    Fine adds:    {coins_with_fine - coins_no_fine:.2f} coins/chest")
    print(f"{'='*70}")
