"""build_item_ids — populate the master index of (slug, quality) pairs.

Append-only invariant enforced by AUTOINCREMENT (no id reuse on delete) +
migration discipline (this builder only INSERTs missing rows, never deletes
or renumbers).

Row count breakdown (full catalog):
  Equipment ItemInstance / AchievementItem  : 1 row each, quality='normal'
  Equipment CraftedItem                     : 6 rows each (Normal..Eternal)
  Consumables                               : 2 rows each (normal + fine)
  Pets                                      : 1 row each, quality='normal'
                                              (level-dependent stats handled
                                              via items_requiring_runtime_eval)
"""

from typing import Iterable, Optional, Set, Tuple

# Quality labels MUST match the optimizer/snapshot quality names produced by
# state_snapshot._RARITY_TO_QUALITY (normal/good/great/excellent/perfect/eternal).
# The game's internal CraftedItem stat key for this tier is "Excellent" (mapped
# in _tier_to_crafted_key), but from_char_config emits "excellent". Storing
# "great_plus" here made every Excellent-quality owned item miss the
# item_id_map lookup in effective_bitmap, so quality changes to Excellent items
# (e.g. golden cutting mat Excellent->Perfect) never flipped a dominance bit.
QUALITY_TIERS = ("normal", "good", "great", "excellent", "perfect", "eternal")


def _enumerate_catalog_items() -> Iterable[Tuple[str, str]]:
    """Yield every (slug, quality) pair that should appear in item_ids."""
    # Import lazily to break circular deps with util.walkscape_constants
    import util.walkscape_constants  # noqa: F401  (sets up Skill / Location)
    from util.autogenerated.equipment import (
        Item, ItemInstance, AchievementItem, CraftedItem,
    )
    from util.autogenerated.consumables import Consumable, ConsumableItem
    from util.autogenerated.pets import PETS_BY_NAME

    # Equipment
    for attr_name in dir(Item):
        if attr_name.startswith("_"):
            continue
        v = getattr(Item, attr_name, None)
        if isinstance(v, (ItemInstance, AchievementItem)):
            yield (attr_name.lower(), "normal")
        elif isinstance(v, CraftedItem):
            for tier in QUALITY_TIERS:
                # Map our tier names to the CraftedItem internal quality keys
                tier_key = _tier_to_crafted_key(tier)
                if tier_key in v._quality_stats or tier == "normal":
                    yield (attr_name.lower(), tier)

    # Consumables (Normal + Fine)
    for attr_name in dir(Consumable):
        if attr_name.startswith("_"):
            continue
        v = getattr(Consumable, attr_name, None)
        if isinstance(v, ConsumableItem):
            yield (attr_name.lower(), "normal")
            yield (attr_name.lower(), "fine")

    # Pets (single entry per pet; level handled separately)
    for pet_name in PETS_BY_NAME:
        # PETS_BY_NAME is keyed by the display name; convert to slug
        slug = pet_name.lower().replace(" ", "_").replace("'", "")
        yield (slug, "normal")


def _tier_to_crafted_key(tier: str) -> str:
    """Map our snake_case quality tier name to CraftedItem._quality_stats key."""
    return {
        "normal": "Normal",
        "good": "Good",
        "great": "Great",
        "excellent": "Excellent",
        "perfect": "Perfect",
        "eternal": "Eternal",
    }[tier]


def build_item_ids(db, migration_id: str, changed_slugs: Optional[Set[str]] = None) -> int:
    """Populate item_ids by INSERT-OR-IGNORE.

    Args:
        db: sqlite3 connection
        migration_id: identifier stamped into added_in_migration column
                      (typically YYYYMMDD_HHMMSS or scraper run id)
        changed_slugs: optional restriction. If provided, only candidate
                       (slug, quality) pairs whose slug is in this set are
                       considered. Pass None to process the full catalog.

    Returns:
        Number of rows inserted (new (slug, quality) pairs).
    """
    cursor = db.cursor()
    inserted = 0

    # Determine sort order: alphabetical by (slug, quality_ordinal)
    quality_ordinal = {q: i for i, q in enumerate(QUALITY_TIERS)}

    candidates = list(_enumerate_catalog_items())
    if changed_slugs is not None:
        candidates = [(s, q) for s, q in candidates if s in changed_slugs]

    # Sort deterministically
    candidates.sort(key=lambda sq: (sq[0], quality_ordinal.get(sq[1], 99)))

    # INSERT OR IGNORE preserves existing ids (append-only invariant)
    for slug, quality in candidates:
        cursor.execute(
            "INSERT OR IGNORE INTO item_ids (import_name, quality, added_in_migration) "
            "VALUES (?, ?, ?)",
            (slug, quality, migration_id),
        )
        if cursor.rowcount > 0:
            inserted += 1

    db.commit()
    return inserted


def get_item_id_map(db) -> dict:
    """Return {(slug, quality): id} for the entire master index."""
    cursor = db.cursor()
    cursor.execute("SELECT id, import_name, quality FROM item_ids")
    return {(row[1], row[2]): row[0] for row in cursor.fetchall()}


def get_max_item_id(db) -> int:
    """Highest id in item_ids (or 0 if empty). Used to size bitmaps."""
    cursor = db.cursor()
    cursor.execute("SELECT MAX(id) FROM item_ids")
    row = cursor.fetchone()
    return row[0] if row[0] is not None else 0
