"""build_applicability — populate item_applicability_lookup +
recipe_applicability_lookup.

For each (activity, location) and (recipe, location, service), build the
bitmap of items whose stats can possibly affect that source given the
PRIMARY skill (per spec C6 — only primary skill matters for activity/recipe
stat scope; secondary XP doesn't bring secondary scope items in).

Item is applicable iff:
  - Item's slot is one the activity/recipe can use (gear, tools, ring, pet,
    consumable, etc.)
  - Item's stat scope includes the (activity_primary_skill, location) tuple
    OR is global / location-global / skill-global
  - Item's scope doesn't EXPLICITLY exclude the location (handled naturally
    by !-prefix logic)

Items in items_requiring_runtime_eval are INCLUDED in applicability bitmap
(they're applicable, just evaluated at request time per character).
"""

import time
from typing import Dict, List, Optional, Set, Tuple


def _get_primary_skill_for_activity(activity) -> Optional[str]:
    """Return the activity's primary skill key (lowercase)."""
    # ActivityInfo has a `skill` attribute (or `primary_skill`)
    for attr in ("primary_skill", "skill"):
        v = getattr(activity, attr, None)
        if isinstance(v, str):
            return v.lower()
        if v is not None:
            # SkillInstance object — get its name
            name = getattr(v, "name", None)
            if name:
                return name.lower()
    return None


def _activity_locations(activity) -> List[str]:
    """Return list of location slugs the activity can be performed at."""
    locs = getattr(activity, "locations", None) or []
    out = []
    for loc in locs:
        if isinstance(loc, str):
            out.append(loc)
        elif loc is not None:
            name = getattr(loc, "name", None) or getattr(loc, "slug", None)
            if name:
                out.append(str(name).lower())
    return out


def _recipe_viable_at(recipe) -> List[Tuple[str, str]]:
    """Return list of (location, service) tuples where recipe is viable.

    Service is 'NONE' for no-service recipes. Recipe has a single `service`
    attribute (string name) — we look up the Service object to get its
    location. If the recipe has no service, we use 'NONE' for service AND
    location 'global' (recipes without a service can be done anywhere with
    the right tools).
    """
    out: List[Tuple[str, str]] = []
    svc = getattr(recipe, "service", None)

    if not svc or svc in ("None", "NONE", ""):
        # No-service recipe: use global location
        out.append(("global", "NONE"))
        return out

    # Service-based recipe: look up service to find its location
    try:
        from util.autogenerated.services import SERVICES_BY_NAME
        svc_name = svc if isinstance(svc, str) else getattr(svc, "name", str(svc))
        svc_obj = SERVICES_BY_NAME.get(svc_name)
        if svc_obj is None:
            return [("global", svc_name.lower().replace(" ", "_") if svc_name else "NONE")]
        loc = getattr(svc_obj, "location", None)
        loc_str = loc if isinstance(loc, str) else (getattr(loc, "name", "") or "")
        loc_slug = loc_str.lower().replace(" ", "_").replace("'", "") or "global"
        svc_slug = svc_name.lower().replace(" ", "_").replace("'", "")
        out.append((loc_slug, svc_slug))
    except Exception:
        out.append(("global", "NONE"))

    return out


def _item_applicable_in_scope(item, skill: str, location: str) -> bool:
    """Return True iff item's stats include any contribution to (skill, location)."""
    from .build_dominators import _effective_stats_in_scope, QM_ACTIVITY
    eff = _effective_stats_in_scope(item, skill, location, QM_ACTIVITY)
    return bool(eff)


def _empty_bitmap(max_id: int) -> bytearray:
    return bytearray((max_id + 1 + 7) // 8)


def _set_bit(bm: bytearray, idx: int) -> None:
    if 0 <= idx < len(bm) * 8:
        bm[idx // 8] |= 1 << (idx % 8)


def build_applicability(
    db,
    changed_slugs: Optional[Set[str]] = None,
    full_rebuild: bool = False,
) -> Tuple[int, int]:
    """Populate both applicability tables.

    Returns:
        (item_applicability_rows_written, recipe_applicability_rows_written)
    """
    import util.walkscape_constants  # noqa: F401
    from util.autogenerated.activities import ACTIVITIES_BY_NAME
    from util.autogenerated.recipes import RECIPES_BY_NAME
    from .build_item_ids import get_item_id_map, get_max_item_id
    from .build_dominators import _enumerate_all_catalog_items

    item_id_map = get_item_id_map(db)
    max_id = get_max_item_id(db)
    if max_id == 0:
        return (0, 0)

    catalog = _enumerate_all_catalog_items()
    # Build lookup: for each (slug, quality) -> (item_obj, item_id)
    catalog_lookup: Dict[Tuple[str, str], Tuple[object, int]] = {}
    for slug, qty, item in catalog:
        item_id = item_id_map.get((slug, qty))
        if item_id is not None:
            catalog_lookup[(slug, qty)] = (item, item_id)

    cursor = db.cursor()
    now = int(time.time())
    rows_act = 0
    rows_rec = 0

    # Compute affected scope filter for incremental refresh
    incremental = (changed_slugs is not None) and not full_rebuild
    changed = changed_slugs or set()

    # ── Activities ──────────────────────────────────────────────────────────
    for activity in ACTIVITIES_BY_NAME.values():
        primary_skill = _get_primary_skill_for_activity(activity)
        if not primary_skill:
            continue
        for location in _activity_locations(activity):
            # Skip if incremental and no changed item participates here
            if incremental:
                # Heuristic: only re-run if any changed item has stats in this (skill, location).
                # For correctness of v1, we just rebuild all rows when ANY change happens.
                pass

            # Clear existing
            cursor.execute(
                "DELETE FROM item_applicability_lookup WHERE activity_name = ? AND location = ?",
                (activity.name, location),
            )

            bm = _empty_bitmap(max_id)
            any_set = False
            for (slug, quality), (item, item_id) in catalog_lookup.items():
                if _item_applicable_in_scope(item, primary_skill, location):
                    _set_bit(bm, item_id)
                    any_set = True

            if any_set or not incremental:
                cursor.execute(
                    "INSERT INTO item_applicability_lookup "
                    "(activity_name, location, applicable_item_bitmap, last_computed_at) "
                    "VALUES (?, ?, ?, ?)",
                    (activity.name, location, bytes(bm), now),
                )
                rows_act += 1

    # ── Recipes ─────────────────────────────────────────────────────────────
    for recipe in RECIPES_BY_NAME.values():
        primary_skill = None
        for attr in ("skill", "primary_skill"):
            v = getattr(recipe, attr, None)
            if isinstance(v, str):
                primary_skill = v.lower()
                break
            if v is not None:
                primary_skill = (getattr(v, "name", None) or "").lower() or None
                break
        if not primary_skill:
            continue

        for location, service in _recipe_viable_at(recipe):
            cursor.execute(
                "DELETE FROM recipe_applicability_lookup "
                "WHERE recipe_name = ? AND location = ? AND service = ?",
                (recipe.name, location, service),
            )

            bm = _empty_bitmap(max_id)
            any_set = False
            for (slug, quality), (item, item_id) in catalog_lookup.items():
                if _item_applicable_in_scope(item, primary_skill, location):
                    _set_bit(bm, item_id)
                    any_set = True

            cursor.execute(
                "INSERT INTO recipe_applicability_lookup "
                "(recipe_name, location, service, applicable_item_bitmap, last_computed_at) "
                "VALUES (?, ?, ?, ?, ?)",
                (recipe.name, location, service, bytes(bm), now),
            )
            rows_rec += 1

    db.commit()
    return (rows_act, rows_rec)
