"""scraper_hook — invoked at the end of each scraper's main() to refresh
the stats_report precomputed tables.

Usage in scraper:

    from util.stats_report.precompute.scraper_hook import refresh_after_scrape

    def main():
        # ... do scraper work, write autogenerated/<entity>.py ...
        refresh_after_scrape()  # ← single line

The hook:
  - Locates the local sessions.db (skip if not present)
  - Calls precompute_all() — incremental mode is a future optimization
  - Logs progress and result
  - Never raises (scraper succeeds even if precompute fails)

If you want to provide a specific set of changed_slugs for partial refresh,
call `refresh_after_scrape(changed_slugs={'rusty_pickaxe', ...})` instead.
"""

import os
import sqlite3
from typing import Optional, Set


def refresh_after_scrape(changed_slugs: Optional[Set[str]] = None) -> bool:
    """Refresh the stats_report precomputed tables.

    Args:
        changed_slugs: when provided, do an incremental refresh restricted
                       to scopes touched by these slugs. When None, do a
                       full rebuild.

    Returns:
        True if precompute ran successfully, False otherwise (skipped or
        error). Never raises.
    """
    db_path = _find_sessions_db()
    if db_path is None:
        print("[stats_report precompute] No local sessions.db found — skip")
        return False

    try:
        conn = sqlite3.connect(db_path)
        # Verify schema is migrated (item_ids table exists)
        cursor = conn.cursor()
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='item_ids'"
        )
        if not cursor.fetchone():
            print(
                "[stats_report precompute] item_ids table not present — "
                "schema migration not applied yet, skipping"
            )
            conn.close()
            return False

        if changed_slugs is None:
            from . import precompute_all
            precompute_all(conn)
        else:
            from . import precompute_changed
            precompute_changed(conn, changed_slugs)
        conn.close()
        return True
    except Exception as e:
        print(f"[stats_report precompute] Failed: {e}")
        return False


def _find_sessions_db() -> Optional[str]:
    """Find sessions.db relative to the repo root."""
    here = os.path.abspath(__file__)
    # util/stats_report/precompute/scraper_hook.py — repo root is 3 levels up
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(here))))
    candidate = os.path.join(repo_root, "sessions.db")
    if os.path.exists(candidate):
        return candidate
    # Also check current working directory
    if os.path.exists("sessions.db"):
        return os.path.abspath("sessions.db")
    return None
