#!/usr/bin/env python3
"""
Faction reputation reward track data
Auto-generated from the WalkScape tools API rewards endpoint
Drop-in replacement for util/autogenerated/faction_rewards.py
DO NOT EDIT MANUALLY

Reputation thresholds, tier titles, and faction display names
are hardcoded — the API only publishes 1-based tier indices.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict


@dataclass
class FactionRewardEntry:
    """A single reward item from a faction reputation tier."""
    item_name: str
    quantity: int
    item_type: str
    item_ref: Optional[str] = None


@dataclass
class FactionTier:
    """A reputation tier with its rewards."""
    reputation_required: int
    title: str
    rewards: List[FactionRewardEntry] = field(default_factory=list)


@dataclass
class FactionRewardTrack:
    """Complete reward track for a faction."""
    faction_name: str
    repeating_reward: Optional[str] = None
    repeating_interval: int = 3
    tiers: List[FactionTier] = field(default_factory=list)


ERDWISE = FactionRewardTrack(
    faction_name='Erdwise',
    tiers=[
        FactionTier(reputation_required=5, title='Penny Pincher', rewards=[
            FactionRewardEntry('Chest of Erdwise', 1, 'Container', 'Container.CHEST_OF_ERDWISE'),
            FactionRewardEntry('Proper cape', 1, 'Loot', 'Item.PROPER_CAPE'),
            FactionRewardEntry('Creme brulee', 3, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
        FactionTier(reputation_required=10, title='Street Hawker', rewards=[
            FactionRewardEntry('Chest of Erdwise', 2, 'Container', 'Container.CHEST_OF_ERDWISE'),
            FactionRewardEntry('Proper boots', 1, 'Loot', 'Item.PROPER_BOOTS'),
            FactionRewardEntry('Trinketry chest', 1, 'Container', 'Container.TRINKETRY_CHEST'),
        ]),
        FactionTier(reputation_required=20, title='Novice Trader', rewards=[
            FactionRewardEntry('Chest of Erdwise', 3, 'Container', 'Container.CHEST_OF_ERDWISE'),
            FactionRewardEntry('Proper hat', 1, 'Loot', 'Item.PROPER_HAT'),
            FactionRewardEntry('Trinketry chest', 1, 'Container', 'Container.TRINKETRY_CHEST'),
        ]),
        FactionTier(reputation_required=30, title='Bargain Seeker', rewards=[
            FactionRewardEntry('Chest of Erdwise', 4, 'Container', 'Container.CHEST_OF_ERDWISE'),
            FactionRewardEntry('Proper pants', 1, 'Loot', 'Item.PROPER_PANTS'),
            FactionRewardEntry('Trinketry chest', 1, 'Container', 'Container.TRINKETRY_CHEST'),
        ]),
        FactionTier(reputation_required=45, title='Aspiring Merchant', rewards=[
            FactionRewardEntry('Chest of Erdwise', 5, 'Container', 'Container.CHEST_OF_ERDWISE'),
            FactionRewardEntry('Proper shirt', 1, 'Loot', 'Item.PROPER_SHIRT'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
            FactionRewardEntry('Trinketry chest', 1, 'Container', 'Container.TRINKETRY_CHEST'),
        ]),
    ]
)


HALFLING_REBELS = FactionRewardTrack(
    faction_name='Halfling Rebels',
    tiers=[
        FactionTier(reputation_required=5, title='Rustling Leaf', rewards=[
            FactionRewardEntry('Chest of the Halfling Rebels', 1, 'Container', 'Container.CHEST_OF_THE_HALFLING_REBELS'),
            FactionRewardEntry('Schnitzel', 1, 'Consumable', 'Consumable.SCHNITZEL'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
        FactionTier(reputation_required=10, title='Acorn Whisperer', rewards=[
            FactionRewardEntry('Chest of the Halfling Rebels', 2, 'Container', 'Container.CHEST_OF_THE_HALFLING_REBELS'),
            FactionRewardEntry('Schnitzel', 1, 'Consumable', 'Consumable.SCHNITZEL'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
        FactionTier(reputation_required=20, title='Pub Table Orator', rewards=[
            FactionRewardEntry('Chest of the Halfling Rebels', 3, 'Container', 'Container.CHEST_OF_THE_HALFLING_REBELS'),
            FactionRewardEntry('Schnitzel', 1, 'Consumable', 'Consumable.SCHNITZEL'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
        FactionTier(reputation_required=30, title='Mud Pie Enjoyer', rewards=[
            FactionRewardEntry('Chest of the Halfling Rebels', 4, 'Container', 'Container.CHEST_OF_THE_HALFLING_REBELS'),
            FactionRewardEntry('Schnitzel', 1, 'Consumable', 'Consumable.SCHNITZEL'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
        FactionTier(reputation_required=45, title='Cloak Tugger', rewards=[
            FactionRewardEntry('Chest of the Halfling Rebels', 5, 'Container', 'Container.CHEST_OF_THE_HALFLING_REBELS'),
            FactionRewardEntry('Schnitzel', 1, 'Consumable', 'Consumable.SCHNITZEL'),
            FactionRewardEntry('Creme brulee', 1, 'Consumable', 'Consumable.CREME_BRULEE'),
        ]),
    ]
)


JARVONIA = FactionRewardTrack(
    faction_name='Jarvonia',
    tiers=[
        FactionTier(reputation_required=5, title='Runny Nose', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 1, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Porridge', 2, 'Consumable', 'Consumable.PORRIDGE'),
            FactionRewardEntry('Bread', 2, 'Consumable', 'Consumable.BREAD'),
        ]),
        FactionTier(reputation_required=10, title='Trainee of Cold', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 2, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Mining chest', 3, 'Container', 'Container.MINING_CHEST'),
            FactionRewardEntry('Dynamite', 4, 'Consumable', 'Consumable.DYNAMITE'),
            FactionRewardEntry('Spicy pumpkin juice', 2, 'Consumable', 'Consumable.SPICY_PUMPKIN_JUICE'),
        ]),
        FactionTier(reputation_required=20, title='Frost Apprentice', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 3, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Ice axe', 1, 'Loot', 'Item.ICE_AXE'),
            FactionRewardEntry('Dynamite', 2, 'Consumable', 'Consumable.DYNAMITE'),
            FactionRewardEntry('Spicy pumpkin juice', 1, 'Consumable', 'Consumable.SPICY_PUMPKIN_JUICE'),
        ]),
        FactionTier(reputation_required=30, title='Acolyte of Winter', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 4, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Warm beanie', 1, 'Loot', 'Item.WARM_BEANIE'),
        ]),
        FactionTier(reputation_required=45, title='Friend of Ice', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 5, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Warm jacket', 1, 'Loot', 'Item.WARM_JACKET'),
            FactionRewardEntry('Jarvonian pastry', 3, 'Consumable', 'Consumable.JARVONIAN_PASTRY'),
        ]),
        FactionTier(reputation_required=60, title='Ally of Frost', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 6, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Frozen bait', 1, 'Consumable', 'Consumable.FROZEN_BAIT'),
        ]),
        FactionTier(reputation_required=80, title='Faithful of Snow', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 7, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Zippy kicksled', 1, 'Loot', 'Item.ZIPPY_KICKSLED'),
            FactionRewardEntry('Dynamite', 4, 'Consumable', 'Consumable.DYNAMITE'),
        ]),
        FactionTier(reputation_required=100, title='Disciple of Frost', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 8, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Spicy pumpkin juice', 1, 'Consumable', 'Consumable.SPICY_PUMPKIN_JUICE'),
        ]),
        FactionTier(reputation_required=125, title='Master of Ice', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 9, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Sigil of the Ordained', 1, 'Collectible', 'Collectible.SIGIL_OF_THE_ORDAINED'),
            FactionRewardEntry('Fried fish sandwich', 5, 'Consumable', 'Consumable.FRIED_FISH_SANDWICH'),
            FactionRewardEntry('Spicy pumpkin juice', 1, 'Consumable', 'Consumable.SPICY_PUMPKIN_JUICE'),
        ]),
        FactionTier(reputation_required=150, title='Lord of Blizzard', rewards=[
            FactionRewardEntry('Chest of Jarvonia', 10, 'Container', 'Container.CHEST_OF_JARVONIA'),
            FactionRewardEntry('Jarvonian pastry', 2, 'Consumable', 'Consumable.JARVONIAN_PASTRY'),
        ]),
    ]
)


SYRENTHIA = FactionRewardTrack(
    faction_name='Syrenthia',
    tiers=[
        FactionTier(reputation_required=5, title='Bubble Blower', rewards=[
            FactionRewardEntry('Chest of Syrenthia', 1, 'Container', 'Container.CHEST_OF_SYRENTHIA'),
            FactionRewardEntry('Fin gloves', 1, 'Loot', 'Item.FIN_GLOVES'),
            FactionRewardEntry('Kelp rolls', 5, 'Consumable', 'Consumable.KELP_ROLLS'),
        ]),
        FactionTier(reputation_required=10, title='Tide Trainee', rewards=[
            FactionRewardEntry('Chest of Syrenthia', 2, 'Container', 'Container.CHEST_OF_SYRENTHIA'),
            FactionRewardEntry('Oxygen tank', 1, 'Loot', 'Item.OXYGEN_TANK'),
            FactionRewardEntry('Saltrum', 5, 'Consumable', 'Consumable.SALTRUM'),
        ]),
        FactionTier(reputation_required=20, title='Coral Apprentice', rewards=[
            FactionRewardEntry('Chest of Syrenthia', 3, 'Container', 'Container.CHEST_OF_SYRENTHIA'),
            FactionRewardEntry('Mark of the trident', 1, 'Collectible', 'Collectible.MARK_OF_THE_TRIDENT'),
        ]),
        FactionTier(reputation_required=30, title='Friend of the Underwater', rewards=[
            FactionRewardEntry('Chest of Syrenthia', 4, 'Container', 'Container.CHEST_OF_SYRENTHIA'),
            FactionRewardEntry('Mark of the serpent', 1, 'Collectible', 'Collectible.MARK_OF_THE_SERPENT'),
            FactionRewardEntry('Sea shell', 200, 'Material', 'Material.SEA_SHELL'),
        ]),
        FactionTier(reputation_required=45, title='Reef Explorer', rewards=[
            FactionRewardEntry('Chest of Syrenthia', 5, 'Container', 'Container.CHEST_OF_SYRENTHIA'),
            FactionRewardEntry('Mark of the deep one', 1, 'Collectible', 'Collectible.MARK_OF_THE_DEEP_ONE'),
        ]),
    ]
)


TRELLIN = FactionRewardTrack(
    faction_name='Trellin',
    tiers=[
        FactionTier(reputation_required=5, title='Muddy Wanderer', rewards=[
            FactionRewardEntry('Chest of Trellin', 1, 'Container', 'Container.CHEST_OF_TRELLIN'),
            FactionRewardEntry('Schnitzel', 3, 'Consumable', 'Consumable.SCHNITZEL'),
        ]),
        FactionTier(reputation_required=10, title='Swamp Sprout', rewards=[
            FactionRewardEntry('Chest of Trellin', 2, 'Container', 'Container.CHEST_OF_TRELLIN'),
            FactionRewardEntry('Trusty tent', 1, 'Loot', 'Item.TRUSTY_TENT'),
            FactionRewardEntry('Cooked carp', 10, 'Consumable', 'Consumable.COOKED_CARP'),
        ]),
        FactionTier(reputation_required=20, title='Bog Treader', rewards=[
            FactionRewardEntry('Chest of Trellin', 3, 'Container', 'Container.CHEST_OF_TRELLIN'),
            FactionRewardEntry('Circular root trinket', 1, 'Material', 'Material.CIRCULAR_ROOT_TRINKET'),
            FactionRewardEntry('Salmon pie', 4, 'Consumable', 'Consumable.SALMON_PIE'),
        ]),
        FactionTier(reputation_required=30, title='Marsh Friend', rewards=[
            FactionRewardEntry('Chest of Trellin', 4, 'Container', 'Container.CHEST_OF_TRELLIN'),
            FactionRewardEntry('Mosquito net hat', 1, 'Loot', 'Item.MOSQUITO_NET_HAT'),
            FactionRewardEntry('Cooked swordfish', 10, 'Consumable', 'Consumable.COOKED_SWORDFISH'),
        ]),
        FactionTier(reputation_required=45, title='Keeper of the Mire', rewards=[
            FactionRewardEntry('Chest of Trellin', 5, 'Container', 'Container.CHEST_OF_TRELLIN'),
            FactionRewardEntry('Circular root trinket', 1, 'Material', 'Material.CIRCULAR_ROOT_TRINKET'),
            FactionRewardEntry('Cooked shark', 10, 'Consumable', 'Consumable.COOKED_SHARK'),
        ]),
    ]
)


HERBERTS_GUIDING_GROUNDS = FactionRewardTrack(
    faction_name="Herbert's Guiding Grounds",
    tiers=[
        FactionTier(reputation_required=1, title='Fresh Feet', rewards=[
            FactionRewardEntry('Rusty chest', 1, 'Container', 'Container.RUSTY_CHEST'),
        ]),
        FactionTier(reputation_required=3, title='Basically Trained', rewards=[
            FactionRewardEntry('Rusty chest', 2, 'Container', 'Container.RUSTY_CHEST'),
            FactionRewardEntry('Birch skis', 1, 'Loot', 'Item.BIRCH_SKIS'),
            FactionRewardEntry('Fishing chest', 1, 'Container', 'Container.FISHING_CHEST'),
            FactionRewardEntry('Foraging chest', 1, 'Container', 'Container.FORAGING_CHEST'),
            FactionRewardEntry('Mining chest', 1, 'Container', 'Container.MINING_CHEST'),
            FactionRewardEntry('Woodcutting chest', 1, 'Container', 'Container.WOODCUTTING_CHEST'),
        ]),
        FactionTier(reputation_required=5, title="Herbert's Friend", rewards=[
            FactionRewardEntry('Rusty chest', 3, 'Container', 'Container.RUSTY_CHEST'),
            FactionRewardEntry('Carpentry chest', 1, 'Container', 'Container.CARPENTRY_CHEST'),
            FactionRewardEntry('Cooking chest', 1, 'Container', 'Container.COOKING_CHEST'),
            FactionRewardEntry('Crafting chest', 1, 'Container', 'Container.CRAFTING_CHEST'),
            FactionRewardEntry('Smithing chest', 1, 'Container', 'Container.SMITHING_CHEST'),
        ]),
    ]
)


# ============================================================================
# LOOKUP HELPERS
# ============================================================================

ALL_FACTION_TRACKS: Dict[str, FactionRewardTrack] = {
    'Erdwise': ERDWISE,
    'Halfling Rebels': HALFLING_REBELS,
    'Jarvonia': JARVONIA,
    'Syrenthia': SYRENTHIA,
    'Trellin': TRELLIN,
    'Herbert': HERBERTS_GUIDING_GROUNDS,
}


def get_all_faction_reward_items() -> Dict[str, List[str]]:
    """Get equipment/collectible item names per faction."""
    result = {}
    for faction_name, track in ALL_FACTION_TRACKS.items():
        items = []
        for tier in track.tiers:
            for reward in tier.rewards:
                if reward.item_type in ('Loot', 'Collectible'):
                    items.append(reward.item_name)
        if items:
            result[faction_name] = items
    return result


def get_faction_reward_item_names() -> set:
    """Flat set of all equipment/collectible names from faction rewards."""
    names = set()
    for track in ALL_FACTION_TRACKS.values():
        for tier in track.tiers:
            for reward in tier.rewards:
                if reward.item_type in ('Loot', 'Collectible'):
                    names.add(reward.item_name)
    return names
