#!/usr/bin/env python3
"""
Item Finding Items - category to item mappings
Auto-generated by scrape_item_finding.py
DO NOT EDIT MANUALLY
"""

from typing import List
from util.item_utils import Quantity, DropEntry


class CategoryInstance:
    """Represents an item finding category with its drop table."""
    def __init__(self, name: str, drops: List[DropEntry]):
        self.name = name
        self.drops = drops  # List of DropEntry with relative chances
    
    def expand_with_chance(self, base_chance: float) -> List[DropEntry]:
        """
        Expand this category to actual drops with adjusted chances.
        
        Args:
            base_chance: Base chance from equipment (e.g., 0.5 for 0.5%)
        
        Returns:
            List of DropEntry with actual chances (base_chance * relative_chance)
        """
        expanded = []
        for drop in self.drops:
            # Calculate actual chance: base_chance * (drop_chance / 100)
            actual_chance = base_chance * (drop.chance_percent / 100.0)
            expanded.append(DropEntry(
                item_name=drop.item_name,
                item_ref=drop.item_ref,
                quantity=drop.quantity,
                chance_percent=actual_chance
            ))
        return expanded
    
    def __repr__(self):
        return f"CategoryInstance({self.name}, {len(self.drops)} items)"


class ItemFindingCategory:
    """All item finding categories."""
    
    ADVENTURERS_GUILD_TOKENS = CategoryInstance(
        name="Adventurers' Guild Tokens",
        drops=[
            DropEntry(item_name="Adventurers' guild token", item_ref='Currency.ADVENTURERS_GUILD_TOKEN', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=100.0),
        ]
    )

    CRUSTACEAN = CategoryInstance(
        name='Crustacean',
        drops=[
            DropEntry(item_name='Raw lobster', item_ref='Material.RAW_LOBSTER', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=100.0),
        ]
    )

    ECTOPLASM = CategoryInstance(
        name='Ectoplasm',
        drops=[
            DropEntry(item_name='Ectoplasm', item_ref='Material.ECTOPLASM', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=100.0),
        ]
    )

    FISHING_BAIT = CategoryInstance(
        name='Fishing Bait',
        drops=[
            DropEntry(item_name='Bug bait', item_ref='Consumable.BUG_BAIT', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=50.0),
            DropEntry(item_name='Frozen bait', item_ref='Consumable.FROZEN_BAIT', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=50.0),
        ]
    )

    GOLD_NUGGET = CategoryInstance(
        name='Gold Nugget',
        drops=[
            DropEntry(item_name='Gold nugget', item_ref='Material.GOLD_NUGGET', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=100.0),
        ]
    )

    GOLD_PIECES = CategoryInstance(
        name='Gold Pieces',
        drops=[
            DropEntry(item_name='Coins', item_ref='Currency.COIN', quantity=Quantity(min_qty=1, max_qty=10), chance_percent=100.0),
        ]
    )

    RANDOM_GEM = CategoryInstance(
        name='Random Gem',
        drops=[
            DropEntry(item_name='Rough opal', item_ref='Material.ROUGH_OPAL', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=29.851),
            DropEntry(item_name='Rough star pearl', item_ref='Material.ROUGH_STAR_PEARL', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=29.851),
            DropEntry(item_name='Rough topaz', item_ref='Material.ROUGH_TOPAZ', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=14.925),
            DropEntry(item_name='Rough wrentmarine', item_ref='Material.ROUGH_WRENTMARINE', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=14.925),
            DropEntry(item_name='Rough jade', item_ref='Material.ROUGH_JADE', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=4.975),
            DropEntry(item_name='Rough ruby', item_ref='Material.ROUGH_RUBY', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=2.985),
            DropEntry(item_name='Rough sun stone', item_ref='Material.ROUGH_SUN_STONE', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=1.99),
            DropEntry(item_name='Rough ethernite', item_ref='Material.ROUGH_ETHERNITE', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=0.498),
        ]
    )

    RANDOM_PIECE_OF_JUNK = CategoryInstance(
        name='Random Piece of Junk',
        drops=[
            DropEntry(item_name='Trash', item_ref='Material.TRASH', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=51.546),
            DropEntry(item_name='Fishbone', item_ref='Material.FISHBONE', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.309),
            DropEntry(item_name='Grass', item_ref='Material.GRASS', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=7.732),
            DropEntry(item_name='Mud', item_ref='Material.MUD', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=7.732),
            DropEntry(item_name='Milkweed', item_ref='Material.MILKWEED', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=5.155),
            DropEntry(item_name='Moondaisy', item_ref='Material.MOONDAISY', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=5.155),
            DropEntry(item_name='Sea shell', item_ref='Material.SEA_SHELL', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=5.155),
            DropEntry(item_name='Birch skis', item_ref='Item.BIRCH_SKIS', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=1.546),
            DropEntry(item_name='Clay skydisc', item_ref='Item.CLAY_SKYDISC', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=1.546),
            DropEntry(item_name='Rough opal', item_ref='Material.ROUGH_OPAL', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=1.546),
            DropEntry(item_name='Simple torch', item_ref='Item.SIMPLE_TORCH', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=1.546),
            DropEntry(item_name='Rusty chest', item_ref='Container.RUSTY_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=0.515),
            DropEntry(item_name='Sunken chest', item_ref='Container.SUNKEN_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=0.515),
        ]
    )

    SEA_SHELLS = CategoryInstance(
        name='Sea Shells',
        drops=[
            DropEntry(item_name='Sea shell', item_ref='Material.SEA_SHELL', quantity=Quantity(min_qty=1, max_qty=10), chance_percent=100.0),
        ]
    )

    SKILL_CHEST = CategoryInstance(
        name='Skill Chest',
        drops=[
            DropEntry(item_name='Agility chest', item_ref='Container.AGILITY_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Carpentry chest', item_ref='Container.CARPENTRY_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Cooking chest', item_ref='Container.COOKING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Crafting chest', item_ref='Container.CRAFTING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Fishing chest', item_ref='Container.FISHING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Foraging chest', item_ref='Container.FORAGING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Mining chest', item_ref='Container.MINING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Smithing chest', item_ref='Container.SMITHING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Trinketry chest', item_ref='Container.TRINKETRY_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
            DropEntry(item_name='Woodcutting chest', item_ref='Container.WOODCUTTING_CHEST', quantity=Quantity(min_qty=1, max_qty=1), chance_percent=10.0),
        ]
    )

