#!/usr/bin/env python3
"""
Walkscape Locations Data
Location data extracted from individual location pages on the game wiki.
Auto-generated by scrape_locations.py
DO NOT EDIT MANUALLY
"""

class LocationInfo:
    """Information about a location including all its region tags."""
    def __init__(self, name: str, regions: list):
        self.name = name
        self.regions = regions  # List of all region tags (primary + factions)
        self.primary_region = regions[0] if regions else None
        self.is_underwater = 'underwater' in regions
    
    def is_in_region(self, region: str) -> bool:
        """Check if this location is in the specified region."""
        return region.lower() in [r.lower() for r in self.regions]
    
    def __str__(self):
        return self.name
    
    def __repr__(self):
        return f"LocationInfo({self.name}, {self.regions})"

class Location:
    """Locations in Walkscape with region and faction information."""
    
    @classmethod
    def by_name(cls, name: str):
        """Get location by name string."""
        for attr_name in dir(cls):
            if attr_name.startswith('_'):
                continue
            attr = getattr(cls, attr_name)
            if isinstance(attr, LocationInfo) and attr.name == name:
                return attr
        return None
    
    # GDTE
    BILGEMONT_PORT = LocationInfo("Bilgemont Port", ['gdte', 'erdwise'])
    BLACKSPELL_PORT = LocationInfo("Blackspell Port", ['gdte', 'erdwise'])
    BOG_BOTTOM = LocationInfo("Bog Bottom", ['gdte', 'halfling_rebels'])
    BOG_TOP = LocationInfo("Bog Top", ['gdte', 'halfling_rebels'])
    EVERHAVEN = LocationInfo("Everhaven", ['gdte', 'erdwise', 'trellin'])
    FARSAND_COAST = LocationInfo("Farsand Coast", ['gdte', 'trellin'])
    GRANFIDDICH = LocationInfo("Granfiddich", ['gdte', 'trellin'])
    GRANFIDDICH_SHORES = LocationInfo("Granfiddich Shores", ['gdte', 'trellin'])
    HALFLING_CAMPGROUNDS = LocationInfo("Halfling Campgrounds", ['gdte', 'halfling_rebels'])
    HALFMAW_HIDEOUT = LocationInfo("Halfmaw Hideout", ['gdte', 'halfling_rebels'])
    MANGROVE_FOREST = LocationInfo("Mangrove Forest", ['gdte', 'trellin'])
    OLD_ARENA_RUINS = LocationInfo("Old Arena Ruins", ['gdte', 'erdwise'])
    RED_COAST = LocationInfo("Red Coast", ['gdte', 'erdwise'])
    SALSFIRTH = LocationInfo("Salsfirth", ['gdte', 'trellin'])
    WARRENFIELD = LocationInfo("Warrenfield", ['gdte', 'trellin'])
    WITCHED_WOODS = LocationInfo("Witched Woods", ['gdte', 'halfling_rebels'])

    # JARVONIA
    AZURAZERA = LocationInfo("Azurazera", ['jarvonia'])
    BARBANTOK = LocationInfo("Barbantok", ['jarvonia'])
    BEACH_OF_WOES = LocationInfo("Beach of Woes", ['jarvonia', 'herberts_guiding_grounds'])
    BLACK_EYE_PEAK = LocationInfo("Black Eye Peak", ['jarvonia'])
    CASBRANT_FIELDS = LocationInfo("Casbrant Fields", ['jarvonia'])
    CENTAHAM = LocationInfo("Centaham", ['jarvonia'])
    COLDINGTON = LocationInfo("Coldington", ['jarvonia'])
    DISENCHANTED_FOREST = LocationInfo("Disenchanted Forest", ['jarvonia', 'herberts_guiding_grounds'])
    FORT_OF_PERMAFROST = LocationInfo("Fort of Permafrost", ['jarvonia'])
    FROSTBITE_MOUNTAIN = LocationInfo("Frostbite Mountain", ['jarvonia'])
    FRUSENHOLM = LocationInfo("Frusenholm", ['jarvonia'])
    HORN_OF_RESPITE = LocationInfo("Horn of Respite", ['jarvonia'])
    KALLAHEIM = LocationInfo("Kallaheim", ['jarvonia'])
    NOISELESS_PASS = LocationInfo("Noiseless Pass", ['jarvonia'])
    NOMAD_WOODS = LocationInfo("Nomad Woods", ['jarvonia'])
    NORSACK_PLAINS = LocationInfo("Norsack Plains", ['jarvonia'])
    NURTURING_NOOK_SPRINGS = LocationInfo("Nurturing Nook Springs", ['jarvonia'])
    PIT_OF_PITTANCE = LocationInfo("Pit of Pittance", ['jarvonia', 'herberts_guiding_grounds'])
    PORT_SKILDAR = LocationInfo("Port Skildar", ['jarvonia'])
    SANGUINE_HILLS = LocationInfo("Sanguine Hills", ['jarvonia'])
    WINTERS_END = LocationInfo("Winter's End", ['jarvonia'])
    WINTER_WAVES_GLACIER = LocationInfo("Winter Waves Glacier", ['jarvonia'])

    # SYRENTHIA
    CASBRANTS_GRAVE = LocationInfo("Casbrant's Grave", ['syrenthia', 'underwater'])
    DARKTIDE_TRENCH = LocationInfo("Darktide Trench", ['syrenthia', 'underwater'])
    ELARAS_LAGOON = LocationInfo("Elara's Lagoon", ['syrenthia', 'underwater'])
    KELP_FOREST = LocationInfo("Kelp Forest", ['syrenthia', 'underwater'])
    UNDERWATER_CAVE = LocationInfo("Underwater Cave", ['syrenthia', 'underwater'])
    VASTALUME = LocationInfo("Vastalume", ['syrenthia', 'underwater'])

    # WALLISIA
    BLACKRANE = LocationInfo("Blackrane", ['wallisia'])
    BLACKWATER_FIELDS = LocationInfo("Blackwater Fields", ['wallisia'])
    KILDOME_CROSS = LocationInfo("Kildome Cross", ['wallisia'])
    STALKING_YEW_WOODS = LocationInfo("Stalking Yew Woods", ['wallisia'])
    TENDON_WET_FIELDS = LocationInfo("Tendon Wet Fields", ['wallisia'])
    WRAITHWATER = LocationInfo("Wraithwater", ['wallisia', 'spectral'])

    # WRENTMARK
    CROWN_OF_CINDERS = LocationInfo("Crown of Cinders", ['wrentmark'])
    MYRIADIAN_ARC = LocationInfo("Myriadian Arc", ['wrentmark'])

