#!/usr/bin/env python3
"""
Walkscape Locations Data
Auto-generated from the WalkScape tools API.
Drop-in replacement for util/autogenerated/locations.py
DO NOT EDIT MANUALLY
"""

class LocationInfo:
    """Information about a location including all its region tags."""
    def __init__(self, name: str, regions: list, icon_name: str = None):
        self.name = name
        self.regions = regions
        self.primary_region = regions[0] if regions else None
        self.is_underwater = 'underwater' in regions
        self.icon_name = icon_name

    def is_in_region(self, region: str) -> bool:
        """Check if this location is in the specified region."""
        return region.lower() in [r.lower() for r in self.regions]

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"LocationInfo({self.name}, {self.regions})"

class Location:
    """Locations in Walkscape with region and faction information."""

    @classmethod
    def by_name(cls, name: str):
        """Get location by name string."""
        for attr_name in dir(cls):
            if attr_name.startswith('_'):
                continue
            attr = getattr(cls, attr_name)
            if isinstance(attr, LocationInfo) and attr.name == name:
                return attr
        return None

    AZURAZERA = LocationInfo('Azurazera', ['jarvonia', 'snowy'], 'castle_white_icon.svg')
    BARBANTOK = LocationInfo('Barbantok', ['jarvonia', 'snowy'], 'town_white_icon.svg')
    BEACH_OF_WOES = LocationInfo('Beach of Woes', ['jarvonia', 'herberts_guiding_grounds', 'snowy'], 'coast_white_icon.svg')
    BILGEMONT_PORT = LocationInfo('Bilgemont Port', ['gdte', 'erdwise'], 'port_green_icon.svg')
    BLACK_EYE_PEAK = LocationInfo('Black Eye Peak', ['jarvonia', 'snowy'], 'mountains_icon.svg')
    BLACKRANE = LocationInfo('Blackrane', ['wallisia'], 'town_yellow_icon.svg')
    BLACKSPELL_HARBOUR = LocationInfo('Blackspell Harbour', ['gdte', 'erdwise'], 'blackspell_harbor_icon.svg')
    BLACKWATER_FIELDS = LocationInfo('Blackwater Fields', ['wallisia'], 'blackwater_fields_icon.svg')
    BOG_BOTTOM = LocationInfo('Bog Bottom', ['gdte', 'halfling_rebels', 'underwater'], 'marsh_green_icon.svg')
    BOG_TOP = LocationInfo('Bog Top', ['gdte', 'halfling_rebels'], 'river_green_icon.svg')
    CASBRANT_FIELDS = LocationInfo('Casbrant Fields', ['jarvonia', 'snowy'], 'plains_white_icon.svg')
    CASBRANTS_GRAVE = LocationInfo("Casbrant's Grave", ['syrenthia', 'underwater', 'ghostly'], 'casbrants_grave_icon.svg')
    CENTAHAM = LocationInfo('Centaham', ['jarvonia', 'snowy'], 'city_white_icon.svg')
    COLDINGTON = LocationInfo('Coldington', ['jarvonia', 'snowy'], 'city_white_icon.svg')
    CROWN_OF_CINDERS = LocationInfo('Crown of Cinders', ['wrentmark', 'desert'], 'crown_of_cinders_icon.svg')
    DARKTIDE_TRENCH = LocationInfo('Darktide Trench', ['syrenthia', 'underwater'], 'darktide_trench_icon.svg')
    DISENCHANTED_FOREST = LocationInfo('Disenchanted Forest', ['jarvonia', 'herberts_guiding_grounds', 'snowy'], 'forest_white_icon.svg')
    ELARAS_LAGOON = LocationInfo("Elara's Lagoon", ['syrenthia', 'underwater'], 'elaras_lagoon_icon.svg')
    EVERHAVEN = LocationInfo('Everhaven', ['gdte', 'erdwise', 'trellin'], 'castle_green_icon.svg')
    FARSAND_COAST = LocationInfo('Farsand Coast', ['gdte', 'trellin'], 'coast_green_icon.svg')
    FORT_OF_PERMAFROST = LocationInfo('Fort of Permafrost', ['jarvonia', 'snowy'], 'castle_white_icon.svg')
    FROSTBITE_MOUNTAIN = LocationInfo('Frostbite Mountain', ['jarvonia', 'snowy'], 'mountains_icon.svg')
    FRUSENHOLM = LocationInfo('Frusenholm', ['jarvonia', 'snowy'], 'town_white_icon.svg')
    GRANFIDDICH = LocationInfo('Granfiddich', ['gdte', 'trellin'], 'city_green_icon.svg')
    GRANFIDDICH_SHORES = LocationInfo('Granfiddich Shores', ['gdte', 'trellin'], 'coast_green_icon.svg')
    HALFLING_CAMPGROUNDS = LocationInfo('Halfling Campgrounds', ['gdte', 'halfling_rebels'], 'campgrounds_icon.svg')
    HALFMAW_HIDEOUT = LocationInfo('Halfmaw Hideout', ['gdte', 'halfling_rebels'], 'halfmaw_hideout_icon.svg')
    HORN_OF_RESPITE = LocationInfo('Horn of Respite', ['jarvonia', 'snowy'], 'horn_of_respite_icon.svg')
    KALLAHEIM = LocationInfo('Kallaheim', ['jarvonia', 'snowy'], 'castle_white_icon.svg')
    KELP_FOREST = LocationInfo('Kelp Forest', ['syrenthia', 'underwater'], 'kelp_firest_icon.svg')
    KILDOME_CROSS = LocationInfo('Kildome Cross', ['wallisia'], 'kildome_cross_icon.svg')
    MANGROVE_FOREST = LocationInfo('Mangrove Forest', ['gdte', 'trellin'], 'forest_green_icon.svg')
    MYRIADIAN_ARC = LocationInfo('Myriadian Arc', ['wrentmark', 'desert'], 'myridian_arc_icon.svg')
    NOISELESS_PASS = LocationInfo('Noiseless Pass', ['gdte', 'trellin', 'snowy'], 'plains_white_icon.svg')
    NOMAD_WOODS = LocationInfo('Nomad Woods', ['jarvonia', 'snowy'], 'forest_white_icon.svg')
    NORSACK_PLAINS = LocationInfo('Norsack Plains', ['jarvonia', 'snowy'], 'plains_white_icon.svg')
    NURTURING_NOOK_SPRINGS = LocationInfo('Nurturing Nook Springs', ['jarvonia', 'snowy'], 'hot_springs_icon.svg')
    OLD_ARENA_RUINS = LocationInfo('Old Arena Ruins', ['gdte', 'erdwise'], 'arena_green_icon.svg')
    PIT_OF_PITTANCE = LocationInfo('Pit of Pittance', ['jarvonia', 'herberts_guiding_grounds', 'snowy'], 'quarry_icon.svg')
    PORT_SKILDAR = LocationInfo('Port Skildar', ['jarvonia', 'snowy'], 'port_white_icon.svg')
    RED_COAST = LocationInfo('Red Coast', ['gdte', 'erdwise'], 'coast_green_icon.svg')
    SALSFIRTH = LocationInfo('Salsfirth', ['gdte', 'trellin'], 'city_green_icon.svg')
    SANGUINE_HILLS = LocationInfo('Sanguine Hills', ['jarvonia', 'snowy'], 'hills_white_icon.svg')
    STALKING_YEW_WOODS = LocationInfo('Stalking Yew Woods', ['wallisia'], 'forest_green_icon.svg')
    TENDON_WET_FIELDS = LocationInfo('Tendon Wet Fields', ['wallisia'], 'marsh_green_icon.svg')
    UNDERWATER_CAVE = LocationInfo('Underwater Cave', ['syrenthia', 'underwater'], 'underwater_cave_icon.svg')
    VASTALUME = LocationInfo('Vastalume', ['syrenthia', 'underwater'], 'vastalume_icon.svg')
    WARRENFIELD = LocationInfo('Warrenfield', ['gdte', 'trellin'], 'plains_green_icon.svg')
    WINTER_WAVES_GLACIER = LocationInfo('Winter Waves Glacier', ['jarvonia', 'snowy'], 'glacier_icon.svg')
    WINTERS_END = LocationInfo("Winter's End", ['jarvonia', 'snowy'], 'winters_end_icon.svg')
    WITCHED_WOODS = LocationInfo('Witched Woods', ['gdte', 'halfling_rebels'], 'witch_forest_icon.svg')
    WRAITHWATER = LocationInfo('Wraithwater', ['wallisia', 'ghostly'], 'wraithwater_icon.svg')
