#!/usr/bin/env python3
"""
Pets data from Walkscape wiki
Auto-generated by scrape_pets.py
DO NOT EDIT MANUALLY
"""

from typing import List, Optional, Dict
from dataclasses import dataclass
from util.stats_mixin import StatsMixin

@dataclass
class EggInfo:
    """Information about a pet egg."""
    name: str
    pet_name: str  # Name of the pet that hatches from this egg
    xp_to_hatch: Optional[int] = None  # XP required to hatch


@dataclass
class PetInfo(StatsMixin):
    """Detailed information about a pet at a specific level."""
    name: str
    level: int
    egg_name: Optional[str] = None
    xp_required: Optional[int] = None  # Cumulative XP to reach this level
    requirement_to_gain_xp: Optional[str] = None
    abilities: Optional[List[Dict[str, any]]] = None  # [{name, effect, requirements, cooldown, charges}, ...]
    
    def __post_init__(self):
        """Initialize StatsMixin."""
        # _stats is set from attributes_by_level[self.level] during generation
        # It will already be in the correct nested format
        if not hasattr(self, "_stats"):
            self._stats = {}
        self.gated_stats = {}
        self.requirements = []


class PetLevels:
    """Container for all levels of a pet (like CraftedItem for qualities)."""
    def __init__(self, name: str, egg_name: str, levels: Dict[int, PetInfo]):
        self.name = name
        self.egg_name = egg_name
        self._levels = levels
        
        # Create LEVEL_X attributes for easy access
        for level, pet_info in levels.items():
            setattr(self, f"LEVEL_{level}", pet_info)
    
    def get_level(self, level: int) -> Optional[PetInfo]:
        """Get pet info for a specific level."""
        return self._levels.get(level)
    
    def get_all_levels(self) -> Dict[int, PetInfo]:
        """Get all levels."""
        return self._levels.copy()


class Pet:
    """Enum-like class for all pets."""

    CAMEL = PetLevels(
        name='Camel',
        egg_name='Camel egg',
        levels={
            1: PetInfo(
                name='Camel',
                level=1,
                egg_name='Camel egg',
                xp_required=50000,
                abilities=[
                    {
                        'name': 'Navigate Desert',
                        'effect': 'Allows you to navigate and interact in Desert environments.',
                        'charges': 1,
                    },
                ],
            ),
            2: PetInfo(
                name='Camel',
                level=2,
                egg_name='Camel egg',
                xp_required=150000,
                abilities=[
                    {
                        'name': 'Navigate Desert',
                        'effect': 'Allows you to navigate and interact in Desert environments.',
                        'charges': 1,
                    },
                ],
            ),
            3: PetInfo(
                name='Camel',
                level=3,
                egg_name='Camel egg',
                xp_required=300000,
                abilities=[
                    {
                        'name': 'Navigate Desert',
                        'effect': 'Allows you to navigate and interact in Desert environments.',
                        'charges': 1,
                    },
                    {
                        'name': 'I Miss The Sun',
                        'effect': 'Teleports you to Myriadian Arc.',
                        'cooldown': '12h',
                        'charges': 1,
                    },
                ],
            ),
        }
    )

    CAMEL._levels[1]._stats = {
        'gathering': {
            'wrentmark': {
                'work_efficiency': -30.0,
            },
        },
        'artisan': {
            'wrentmark': {
                'work_efficiency': -20.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 1.0,
            },
            'wrentmark': {
                'steps_add': 2.0,
            },
        },
    }
    CAMEL._levels[2]._stats = {
        'gathering': {
            'wrentmark': {
                'work_efficiency': -15.0,
            },
        },
        'artisan': {
            'wrentmark': {
                'work_efficiency': -10.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 2.0,
            },
            'wrentmark': {
                'steps_add': 1.0,
            },
        },
    }
    CAMEL._levels[3]._stats = {
        'gathering': {
            'wrentmark': {
                'work_efficiency': 5.0,
            },
        },
        'artisan': {
            'wrentmark': {
                'work_efficiency': 2.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 3.0,
            },
            'wrentmark': {
                'steps_add': -1.0,
            },
        },
    }

    CHICKEN = PetLevels(
        name='Chicken',
        egg_name='Chicken egg',
        levels={
            1: PetInfo(
                name='Chicken',
                level=1,
                egg_name='Chicken egg',
                xp_required=35000,
            ),
            2: PetInfo(
                name='Chicken',
                level=2,
                egg_name='Chicken egg',
                xp_required=85000,
            ),
            3: PetInfo(
                name='Chicken',
                level=3,
                egg_name='Chicken egg',
                xp_required=150000,
            ),
            4: PetInfo(
                name='Chicken',
                level=4,
                egg_name='Chicken egg',
                xp_required=250000,
                abilities=[
                    {
                        'name': 'Pecking Order',
                        'effect': 'Completes 5 Foraging actions instantly.',
                        'requirements': 'While doing Foraging.',
                        'cooldown': '4,000 stepsWhile doing Foraging.',
                        'charges': 5,
                    },
                ],
            ),
        }
    )

    CHICKEN._levels[1]._stats = {
        'foraging': {
            'global': {
                'work_efficiency': 2.0,
            },
        },
    }
    CHICKEN._levels[2]._stats = {
        'foraging': {
            'global': {
                'work_efficiency': 4.0,
                'fine_material_finding': 5.0,
                'bonus_xp_percent': 1.0,
            },
        },
    }
    CHICKEN._levels[3]._stats = {
        'foraging': {
            'global': {
                'work_efficiency': 6.0,
                'fine_material_finding': 10.0,
                'bonus_xp_percent': 2.0,
            },
        },
    }
    CHICKEN._levels[4]._stats = {
        'foraging': {
            'global': {
                'work_efficiency': 7.0,
                'fine_material_finding': 15.0,
                'bonus_xp_percent': 3.0,
                'steps_add': -1.0,
            },
        },
    }

    DOLPHIN = PetLevels(
        name='Dolphin',
        egg_name='Dolphin egg',
        levels={
            1: PetInfo(
                name='Dolphin',
                level=1,
                egg_name='Dolphin egg',
                xp_required=35000,
            ),
            2: PetInfo(
                name='Dolphin',
                level=2,
                egg_name='Dolphin egg',
                xp_required=85000,
            ),
            3: PetInfo(
                name='Dolphin',
                level=3,
                egg_name='Dolphin egg',
                xp_required=150000,
            ),
            4: PetInfo(
                name='Dolphin',
                level=4,
                egg_name='Dolphin egg',
                xp_required=250000,
                abilities=[
                    {
                        'name': 'Torpedo Away',
                        'effect': 'Completes 10 Underwater Traveling actions instantly.',
                        'requirements': 'While traveling.While in Underwater location.',
                        'cooldown': '5,000 stepsWhile in Underwater location.',
                        'charges': 5,
                    },
                ],
            ),
        }
    )

    DOLPHIN._levels[1]._stats = {
        'fishing': {
            'global': {
                'work_efficiency': 2.0,
                'chest_finding': 5.0,
            },
        },
    }
    DOLPHIN._levels[2]._stats = {
        'fishing': {
            'global': {
                'work_efficiency': 4.0,
                'chest_finding': 10.0,
            },
        },
    }
    DOLPHIN._levels[3]._stats = {
        'fishing': {
            'global': {
                'work_efficiency': 5.0,
                'chest_finding': 15.0,
                'fine_material_finding': 5.0,
                'bonus_xp_percent': 1.0,
            },
        },
    }
    DOLPHIN._levels[4]._stats = {
        'fishing': {
            'global': {
                'work_efficiency': 6.0,
                'chest_finding': 20.0,
                'fine_material_finding': 10.0,
                'bonus_xp_percent': 2.0,
                'steps_add': -1.0,
            },
        },
    }

    REINDEER = PetLevels(
        name='Reindeer',
        egg_name='Reindeer egg',
        levels={
            1: PetInfo(
                name='Reindeer',
                level=1,
                egg_name='Reindeer egg',
                xp_required=50000,
            ),
            2: PetInfo(
                name='Reindeer',
                level=2,
                egg_name='Reindeer egg',
                xp_required=150000,
            ),
            3: PetInfo(
                name='Reindeer',
                level=3,
                egg_name='Reindeer egg',
                xp_required=300000,
                abilities=[
                    {
                        'name': 'Present Rain',
                        'effect': 'Gives 5 random presents containing items.',
                        'cooldown': '10h',
                        'charges': 15,
                    },
                ],
            ),
        }
    )

    REINDEER._levels[1]._stats = {
        'agility': {
            'global': {
                'work_efficiency': 1.0,
            },
        },
        'global': {
            'jarvonia': {
                'work_efficiency': 1.0,
            },
            'global': {
                'inventory_space': 1.0,
            },
        },
    }
    REINDEER._levels[2]._stats = {
        'agility': {
            'global': {
                'work_efficiency': 2.0,
            },
        },
        'global': {
            'jarvonia': {
                'work_efficiency': 2.0,
            },
            'global': {
                'inventory_space': 2.0,
            },
        },
    }
    REINDEER._levels[3]._stats = {
        'agility': {
            'global': {
                'work_efficiency': 4.0,
            },
        },
        'global': {
            'jarvonia': {
                'work_efficiency': 4.0,
            },
            'global': {
                'inventory_space': 3.0,
            },
        },
    }

    TORTOISE = PetLevels(
        name='Tortoise',
        egg_name='Tortoise egg',
        levels={
            1: PetInfo(
                name='Tortoise',
                level=1,
                egg_name='Tortoise egg',
                xp_required=35000,
            ),
            2: PetInfo(
                name='Tortoise',
                level=2,
                egg_name='Tortoise egg',
                xp_required=85000,
            ),
            3: PetInfo(
                name='Tortoise',
                level=3,
                egg_name='Tortoise egg',
                xp_required=150000,
            ),
            4: PetInfo(
                name='Tortoise',
                level=4,
                egg_name='Tortoise egg',
                xp_required=250000,
                abilities=[
                    {
                        'name': 'Shell Forge',
                        'effect': 'Completes 5 Smelting actions instantly.',
                        'requirements': 'While doing Smelting recipes.',
                        'cooldown': '4,000 stepsNot doing Agility.',
                        'charges': 10,
                    },
                ],
            ),
        }
    )

    TORTOISE._levels[1]._stats = {
        'agility': {
            'global': {
                'work_efficiency': -15.0,
            },
        },
        'smithing': {
            'global': {
                'work_efficiency': 1.0,
                'bonus_xp_percent': 2.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 2.0,
            },
        },
    }
    TORTOISE._levels[2]._stats = {
        'agility': {
            'global': {
                'work_efficiency': -10.0,
            },
        },
        'smithing': {
            'global': {
                'work_efficiency': 2.0,
                'bonus_xp_percent': 4.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 3.0,
            },
        },
    }
    TORTOISE._levels[3]._stats = {
        'agility': {
            'global': {
                'work_efficiency': -5.0,
            },
        },
        'smithing': {
            'global': {
                'work_efficiency': 3.0,
                'bonus_xp_percent': 6.0,
            },
        },
        'global': {
            'global': {
                'inventory_space': 4.0,
            },
        },
    }
    TORTOISE._levels[4]._stats = {
        'smithing': {
            'global': {
                'work_efficiency': 4.0,
                'bonus_xp_percent': 8.0,
                'inventory_space': 5.0,
            },
        },
        'global': {
            'global': {
                'bonus_xp_add': 2.0,
            },
        },
    }


class Egg:
    """Enum-like class for all eggs."""

    CAMEL_EGG = EggInfo(
        name='Camel egg',
        pet_name='Camel',
        xp_to_hatch=50000,
    )

    CHICKEN_EGG = EggInfo(
        name='Chicken egg',
        pet_name='Chicken',
        xp_to_hatch=35000,
    )

    DOLPHIN_EGG = EggInfo(
        name='Dolphin egg',
        pet_name='Dolphin',
        xp_to_hatch=35000,
    )

    REINDEER_EGG = EggInfo(
        name='Reindeer egg',
        pet_name='Reindeer',
        xp_to_hatch=50000,
    )

    TORTOISE_EGG = EggInfo(
        name='Tortoise egg',
        pet_name='Tortoise',
        xp_to_hatch=35000,
    )


# Lookup dictionaries
PETS_BY_NAME = {
    'Camel': Pet.CAMEL,
    'Chicken': Pet.CHICKEN,
    'Dolphin': Pet.DOLPHIN,
    'Reindeer': Pet.REINDEER,
    'Tortoise': Pet.TORTOISE,
}

# Convenience: Get all pet levels as flat list
ALL_PET_LEVELS = []
for pet_levels in PETS_BY_NAME.values():
    ALL_PET_LEVELS.extend(pet_levels.get_all_levels().values())

EGGS_BY_NAME = {
    'Camel egg': Egg.CAMEL_EGG,
    'Chicken egg': Egg.CHICKEN_EGG,
    'Dolphin egg': Egg.DOLPHIN_EGG,
    'Reindeer egg': Egg.REINDEER_EGG,
    'Tortoise egg': Egg.TORTOISE_EGG,
}