#!/usr/bin/env python3
"""
Auto-generated service data from Walkscape wiki.
Auto-generated by scrape_services.py
DO NOT EDIT MANUALLY
"""

from dataclasses import dataclass
from typing import List, Tuple, Optional

from util.autogenerated.locations import Location, LocationInfo
from util.walkscape_constants import Skill
from util.stats_mixin import StatsMixin

class ServiceInstance(StatsMixin):
    """Represents a crafting service location."""
    def __init__(self, name: str, category: Skill, tier: str, location: Location, requirements: dict, stats: dict, gated_stats: dict):
        self.name = name
        self.category = category  # Skill object (e.g., Skill.CARPENTRY)
        self.tier = tier
        self.location = location
        self.requirements = requirements
        self._stats = stats  # {skill: {location: {stat: value}}}
        self.gated_stats = gated_stats  # Includes reputation gates

    def is_valid_for_recipe(self, recipe) -> bool:
        """
        Check if this service can be used for the given recipe.
        Advanced services can craft Basic recipes (backwards compatible).
        
        Args:
            recipe: Recipe object with .service attribute
        
        Returns:
            True if service is valid for recipe, False otherwise
        """
        recipe_service = recipe.service.lower()
        
        # Get service category name
        service_category = self.category.value.lower() if hasattr(self.category, "value") else self.category.lower()
        service_tier = self.tier.lower()
        
        # Check tier compatibility
        # Advanced can do Basic, but not vice versa
        if "basic" in recipe_service and "advanced" in service_tier:
            return True  # Advanced can do Basic recipes
        elif service_tier in recipe_service:
            return True  # Exact match
        elif service_category in recipe_service:
            return True
        elif "advanced" in recipe_service and "basic" in service_tier:
            return False  # Basic cannot do Advanced recipes

        return False

    def is_unlocked(self, character, gearset=None) -> bool:
        """
        Check if service is unlocked for character with optional gearset validation.
        
        Args:
            character: Character object
            gearset: Optional Gearset object for checking gear requirements
        
        Returns:
            True if unlocked, False otherwise
        """
        # Check skill requirements
        for skill, required_level in self.requirements.get('skill', {}).items():
            if character.get_skill_level(skill.lower()) < required_level:
                return False
        
        # Check reputation requirements
        for faction, required_amount in self.requirements.get('reputation', {}).items():
            if character.reputation.get(faction, 0) < required_amount:
                return False
        
        # Check keyword requirements (needs gearset)
        if gearset:
            keyword_counts = self.requirements.get('keyword_counts', {})
            for keyword, required_count in keyword_counts.items():
                if required_count <= 0:
                    continue
                
                # Count items with this keyword
                count = sum(
                    1 for slot, item in gearset.get_all_items()
                    if item and hasattr(item, 'keywords') and
                    any(keyword.lower() == kw.lower() for kw in item.keywords)
                )
                if count < required_count:
                    return False
        
        return True

class Service:
    """Enum-style access to all services."""

    BASIC_SAWMILL_KALLAHEIM = ServiceInstance(
        name='Basic Sawmill',
        category=Skill.CARPENTRY,
        tier='Basic Sawmill',
        location=Location.KALLAHEIM,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_SAWMILL_EVERHAVEN = ServiceInstance(
        name='Basic Sawmill',
        category=Skill.CARPENTRY,
        tier='Basic Sawmill',
        location=Location.EVERHAVEN,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    SAWMILL_OF_BARBANTOK_BARBANTOK = ServiceInstance(
        name='Sawmill of Barbantok',
        category=Skill.CARPENTRY,
        tier='Basic Sawmill',
        location=Location.BARBANTOK,
        requirements={'keyword_counts': {}, 'skill': {'Carpentry': 20}, 'reputation': {}, 'access': []},
        stats={'carpentry': {'global': {'work_efficiency': 17.0}}},
        gated_stats={}
    )

    UNDERWATER_SAWMILL_VASTALUME = ServiceInstance(
        name='Underwater Sawmill',
        category=Skill.CARPENTRY,
        tier='Basic Sawmill',
        location=Location.VASTALUME,
        requirements={'keyword_counts': {'diving gear': 3}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'carpentry': {'global': {'work_efficiency': -10.0, 'no_materials_consumed': 5.0}}},
        gated_stats={}
    )

    CURSED_SAWMILL_WRAITHWATER = ServiceInstance(
        name='Cursed Sawmill',
        category=Skill.CARPENTRY,
        tier='Advanced Sawmill',
        location=Location.WRAITHWATER,
        requirements={'keyword_counts': {}, 'skill': {'Carpentry': 55}, 'reputation': {}, 'access': []},
        stats={'carpentry': {'global': {'work_efficiency': -10.0, 'steps_required': 5.0, 'no_materials_consumed': -5.0}}},
        gated_stats={}
    )

    SAW_IN_HALF_MILL_HALFLING_CAMPGROUNDS = ServiceInstance(
        name='Saw-in-half mill',
        category=Skill.CARPENTRY,
        tier='Advanced Sawmill',
        location=Location.HALFLING_CAMPGROUNDS,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {'halfling_rebels': 5}, 'access': []},
        stats={},
        gated_stats={'reputation': {'halfling_rebels': {5: {'global': {'global': {'double_rewards': 1.0}}}, 10: {'global': {'global': {'double_action': 1.0}}}, 20: {'global': {'global': {'double_rewards': 2.0}}}, 30: {'global': {'global': {'double_action': 2.0}}}, 45: {'global': {'global': {'double_rewards': 3.0}}}}}}
    )

    BASIC_KITCHEN_CENTAHAM = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.CENTAHAM,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_COLDINGTON = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.COLDINGTON,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_KALLAHEIM = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.KALLAHEIM,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_NURTURING_NOOK_SPRINGS = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.NURTURING_NOOK_SPRINGS,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_BLACKSPELL_PORT = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.BLACKSPELL_PORT,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_EVERHAVEN = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.EVERHAVEN,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_HALFLING_CAMPGROUNDS = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.HALFLING_CAMPGROUNDS,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_KITCHEN_SALSFIRTH = ServiceInstance(
        name='Basic Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.SALSFIRTH,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    ALIGHT_KITCHEN_AZURAZERA = ServiceInstance(
        name='Alight Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.AZURAZERA,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'cooking': {'global': {'bonus_xp_percent': 10.0}}},
        gated_stats={}
    )

    UNDERWATER_KITCHEN_VASTALUME = ServiceInstance(
        name='Underwater Kitchen',
        category=Skill.COOKING,
        tier='Basic Kitchen',
        location=Location.VASTALUME,
        requirements={'keyword_counts': {'diving gear': 3}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'cooking': {'global': {'work_efficiency': -10.0, 'no_materials_consumed': 5.0}}},
        gated_stats={}
    )

    EBERHART_MANSION_KITCHEN_GRANFIDDICH = ServiceInstance(
        name='Eberhart Mansion Kitchen',
        category=Skill.COOKING,
        tier='Advanced Kitchen',
        location=Location.GRANFIDDICH,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'cooking': {'global': {'work_efficiency': 5.0}}},
        gated_stats={}
    )

    CURSED_KITCHEN_WRAITHWATER = ServiceInstance(
        name='Cursed Kitchen',
        category=Skill.COOKING,
        tier='Advanced Kitchen',
        location=Location.WRAITHWATER,
        requirements={'keyword_counts': {}, 'skill': {'Cooking': 55}, 'reputation': {}, 'access': []},
        stats={'cooking': {'global': {'work_efficiency': -10.0, 'double_rewards': -5.0, 'steps_required': 5.0}}},
        gated_stats={}
    )

    BASIC_WORKSHOP_FRUSENHOLM = ServiceInstance(
        name='Basic Workshop',
        category=Skill.CRAFTING,
        tier='Basic Workshop',
        location=Location.FRUSENHOLM,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_WORKSHOP_HALFLING_CAMPGROUNDS = ServiceInstance(
        name='Basic Workshop',
        category=Skill.CRAFTING,
        tier='Basic Workshop',
        location=Location.HALFLING_CAMPGROUNDS,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_WORKSHOP_SALSFIRTH = ServiceInstance(
        name='Basic Workshop',
        category=Skill.CRAFTING,
        tier='Basic Workshop',
        location=Location.SALSFIRTH,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    TIDAL_WORKSHOP_VASTALUME = ServiceInstance(
        name='Tidal Workshop',
        category=Skill.CRAFTING,
        tier='Advanced Workshop',
        location=Location.VASTALUME,
        requirements={'keyword_counts': {'diving gear': 3}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'crafting': {'global': {'work_efficiency': -10.0, 'no_materials_consumed': 5.0}}},
        gated_stats={}
    )

    CURSED_WORKSHOP_WRAITHWATER = ServiceInstance(
        name='Cursed Workshop',
        category=Skill.CRAFTING,
        tier='Advanced Workshop',
        location=Location.WRAITHWATER,
        requirements={'keyword_counts': {}, 'skill': {'Crafting': 55}, 'reputation': {}, 'access': []},
        stats={'crafting': {'global': {'work_efficiency': -10.0, 'steps_required': 5.0, 'quality_outcome': -7.0}}},
        gated_stats={}
    )

    BASIC_FORGE_KALLAHEIM = ServiceInstance(
        name='Basic Forge',
        category=Skill.SMITHING,
        tier='Basic Forge',
        location=Location.KALLAHEIM,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_FORGE_BILGEMONT_PORT = ServiceInstance(
        name='Basic Forge',
        category=Skill.SMITHING,
        tier='Basic Forge',
        location=Location.BILGEMONT_PORT,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_FORGE_GRANFIDDICH = ServiceInstance(
        name='Basic Forge',
        category=Skill.SMITHING,
        tier='Basic Forge',
        location=Location.GRANFIDDICH,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    UNDERWATER_FORGE_VASTALUME = ServiceInstance(
        name='Underwater Forge',
        category=Skill.SMITHING,
        tier='Basic Forge',
        location=Location.VASTALUME,
        requirements={'keyword_counts': {'diving gear': 3}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'smithing': {'global': {'work_efficiency': -10.0, 'no_materials_consumed': 5.0}}},
        gated_stats={}
    )

    HEATSTROKE_METALWORKS_MYRIADIAN_ARC = ServiceInstance(
        name='Heatstroke Metalworks',
        category=Skill.SMITHING,
        tier='Advanced Forge',
        location=Location.MYRIADIAN_ARC,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'smithing': {'global': {'work_efficiency': 10.0, 'double_action': 2.0}}},
        gated_stats={}
    )

    CURSED_FORGE_WRAITHWATER = ServiceInstance(
        name='Cursed Forge',
        category=Skill.SMITHING,
        tier='Advanced Forge',
        location=Location.WRAITHWATER,
        requirements={'keyword_counts': {}, 'skill': {'Smithing': 55}, 'reputation': {}, 'access': []},
        stats={'smithing': {'global': {'work_efficiency': -20.0, 'steps_required': 5.0}}},
        gated_stats={}
    )

    FROZEN_FORGE_WINTER_WAVES_GLACIER = ServiceInstance(
        name='Frozen Forge',
        category=Skill.SMITHING,
        tier='Advanced Forge',
        location=Location.WINTER_WAVES_GLACIER,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'smithing': {'global': {'work_efficiency': -20.0, 'double_rewards': 5.0, 'quality_outcome': 15.0}}},
        gated_stats={}
    )

    BASIC_TRINKETRY_BENCH_BILGEMONT_PORT = ServiceInstance(
        name='Basic Trinketry Bench',
        category=Skill.TRINKETRY,
        tier='Basic Trinketry Bench',
        location=Location.BILGEMONT_PORT,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    BASIC_TRINKETRY_BENCH_SALSFIRTH = ServiceInstance(
        name='Basic Trinketry Bench',
        category=Skill.TRINKETRY,
        tier='Basic Trinketry Bench',
        location=Location.SALSFIRTH,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={},
        gated_stats={}
    )

    RUINED_TRINKETRY_BENCH_WINTERS_END = ServiceInstance(
        name='Ruined Trinketry Bench',
        category=Skill.TRINKETRY,
        tier='Basic Trinketry Bench',
        location=Location.WINTERS_END,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'trinketry': {'global': {'work_efficiency': -20.0, 'no_materials_consumed': 3.0}}},
        gated_stats={}
    )

    ERDWISS_TRINKETRY_FACTORY_BLACKSPELL_PORT = ServiceInstance(
        name='Erdwiss Trinketry Factory',
        category=Skill.TRINKETRY,
        tier='Advanced Trinketry Bench',
        location=Location.BLACKSPELL_PORT,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'trinketry': {'global': {'double_rewards': 5.0}}},
        gated_stats={}
    )

    GRANULAR_FACETING_FACILITY_MYRIADIAN_ARC = ServiceInstance(
        name='Granular Faceting Facility',
        category=Skill.TRINKETRY,
        tier='Advanced Trinketry Bench',
        location=Location.MYRIADIAN_ARC,
        requirements={'keyword_counts': {}, 'skill': {}, 'reputation': {}, 'access': []},
        stats={'trinketry': {'global': {'work_efficiency': 5.0}}},
        gated_stats={}
    )

# Helper dictionaries for lookup
SERVICES_BY_NAME = {}
SERVICES_BY_CATEGORY = {}

for attr_name in dir(Service):
    if not attr_name.startswith("_"):
        service = getattr(Service, attr_name)
        if isinstance(service, ServiceInstance):
            # Add to name lookup
            SERVICES_BY_NAME[service.name] = service
            # Add to category lookup
            key = (service.category, service.tier)
            if key not in SERVICES_BY_CATEGORY:
                SERVICES_BY_CATEGORY[key] = []
            SERVICES_BY_CATEGORY[key].append(service)
