#!/usr/bin/env python3
"""
Shop data from Walkscape wiki
Auto-generated by scrape_shops.py
DO NOT EDIT MANUALLY
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict



@dataclass
class ShopItem:
    """An item sold in a shop."""
    item_name: str
    stock: int
    price: int
    currency: str  # 'coins' or 'adventurers_guild_token' or material name
    item_type: str  # Loot, Tool, Consumable, Material, Container, Collectible, Cosmetic
    item_ref: Optional[str] = None


@dataclass
class ShopInfo:
    """Information about a shop."""
    name: str
    building_type: str
    location: str
    region: str
    requirements: List[str] = field(default_factory=list)
    inventory: List[ShopItem] = field(default_factory=list)


# ============================================================================
# SHOP DATA
# ============================================================================

# --- Jarvonia ---

TUNDRA_TRENDS = ShopInfo(
    name='Tundra Trends', building_type='Clothing shop',
    location='Azurazera', region='Jarvonia',
    inventory=[
        ShopItem('Fancy earring', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden ear piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eyebrow piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hearing aid', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two golden piercings', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eye glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Round glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Square glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Thick glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Tinted glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arctic hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bowler Hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Headwrap', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Royal Guard Helmet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Swamp hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Top hat with goggles', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Warm beanie', 1, 650, 'coins', 'Cosmetic', 'Item.WARM_BEANIE'),
        ShopItem('Warm woolen hat', 1, 5000, 'coins', 'Cosmetic', None),
        ShopItem('Blanket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bot Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Caped Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert Vest', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Elegant Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fancy Suit', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Farm Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fur Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hoodie', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Outlander Furs', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Party Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Rancher Overalls', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scarf Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scoop Neck Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Shirt and Jacket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Pullover', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Dress with Necklace', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Strapless Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Training Robes', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Warm woolen coat', 1, 5000, 'coins', 'Cosmetic', None),
        ShopItem('Woodworker\'s Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arrows', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hatchet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Ice staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Large icicle', 1, 5000, 'coins', 'Cosmetic', None),
        ShopItem('One handed sword', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Stick and a bottle', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two-handed sword', 1, 650, 'coins', 'Cosmetic', None),
    ],
)

NORTHSTAR_MERCANTILE = ShopInfo(
    name='Northstar Mercantile', building_type='General store',
    location='Centaham', region='Jarvonia',
    inventory=[
        ShopItem('Simple amulet', 1, 53, 'coins', 'Loot', 'Item.SIMPLE_AMULET'),
        ShopItem('Birch hunting bow', 3, 51, 'coins', 'Tool', 'Item.BIRCH_HUNTING_BOW'),
        ShopItem('Bronze hatchet', 3, 94, 'coins', 'Tool', 'Item.BRONZE_HATCHET'),
        ShopItem('Bronze pickaxe', 3, 63, 'coins', 'Tool', 'Item.BRONZE_PICKAXE'),
        ShopItem('Copper hatchet', 3, 42, 'coins', 'Tool', 'Item.COPPER_HATCHET'),
        ShopItem('Copper pickaxe', 3, 28, 'coins', 'Tool', 'Item.COPPER_PICKAXE'),
        ShopItem('Dull machete', 3, 114, 'coins', 'Tool', 'Item.DULL_MACHETE'),
        ShopItem('Simple chisel', 50, 37, 'coins', 'Tool', 'Item.SIMPLE_CHISEL'),
        ShopItem('Simple gold pan', 3, 56, 'coins', 'Tool', 'Item.SIMPLE_GOLD_PAN'),
        ShopItem('Simple hammer', 50, 54, 'coins', 'Tool', 'Item.SIMPLE_HAMMER'),
        ShopItem('Simple pan', 50, 52, 'coins', 'Tool', 'Item.SIMPLE_PAN'),
        ShopItem('Simple saw', 50, 46, 'coins', 'Tool', 'Item.SIMPLE_SAW'),
        ShopItem('Simple sewing needle', 50, 42, 'coins', 'Tool', 'Item.SIMPLE_SEWING_NEEDLE'),
        ShopItem('Simple wrench', 50, 42, 'coins', 'Tool', 'Item.SIMPLE_WRENCH'),
        ShopItem('Birch plank', 40, 9, 'coins', 'Material', 'Material.BIRCH_PLANK'),
        ShopItem('Copper arrows', 100, 4, 'coins', 'Material', 'Material.COPPER_ARROWS'),
        ShopItem('Pine plank', 20, 16, 'coins', 'Material', 'Material.PINE_PLANK'),
    ],
)

NOT_A_SHOP = ShopInfo(
    name='Not a Shop', building_type='Clothing shop',
    location='Coldington', region='Jarvonia',
    inventory=[
        ShopItem('Carrot', 1, 4000, 'coins', 'Cosmetic', 'Material.CARROT'),
        ShopItem('Smoky eyes', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Antler hood', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Aviator hat with goggles', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Bamboo hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Chaplin Hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Christmas hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Coffee hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Kiwi hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Old wizard hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Pie hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Pirate hat', 1, 4000, 'coins', 'Cosmetic', 'Item.PIRATE_HAT'),
        ShopItem('Pumpkin hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Ruffled wizard hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Sleepy hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Viking helm', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Witch cat hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Wizard Hat', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Hooded Monk Robe', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Hooded outfit', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Light Branded Hoodie', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Ninja outfit', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Plain black t-shirt', 1, 4000, 'coins', 'Cosmetic', None),
        ShopItem('Ice hockey stick', 1, 4000, 'coins', 'Cosmetic', None),
    ],
)

HELPFUL_HERBERTS_HUT = ShopInfo(
    name='Helpful Herbert\'s Hut', building_type='House',
    location='Disenchanted Forest', region='Jarvonia',
    inventory=[
        ShopItem('Herbert\'s boots', 1, 14, 'coins', 'Loot', 'Item.HERBERTS_BOOTS'),
        ShopItem('Herbert\'s cape', 1, 14, 'coins', 'Loot', 'Item.HERBERTS_CAPE'),
        ShopItem('Herbert\'s hat', 1, 14, 'coins', 'Loot', 'Item.HERBERTS_HAT'),
        ShopItem('Herbert\'s pants', 1, 14, 'coins', 'Loot', 'Item.HERBERTS_PANTS'),
        ShopItem('Herbert\'s shirt', 1, 14, 'coins', 'Loot', 'Item.HERBERTS_SHIRT'),
        ShopItem('Stone', 6, 0, 'coins', 'Material', 'Material.STONE'),
        ShopItem('Twine', 3, 0, 'coins', 'Material', 'Material.TWINE'),
        ShopItem('Wooden stick', 6, 0, 'coins', 'Material', 'Material.WOODEN_STICK'),
    ],
)

FORT_OF_PERMAFROST = ShopInfo(
    name='Fort of Permafrost', building_type='Castle',
    location='Fort of Permafrost', region='Jarvonia',
    inventory=[
        ShopItem('Jarvonian letter of passage', 1, 4500, 'coins', 'Collectible', 'Collectible.JARVONIAN_LETTER_OF_PASSAGE'),
    ],
)

JARVOJOY = ShopInfo(
    name='JarvoJoy', building_type='Activity shop',
    location='Frusenholm', region='Jarvonia',
    inventory=[
        ShopItem('Backpack', 1, 4999, 'coins', 'Loot', 'Item.BACKPACK'),
        ShopItem('Birch skis', 10, 31, 'coins', 'Loot', 'Item.BIRCH_SKIS'),
        ShopItem('Oak skis', 3, 89, 'coins', 'Loot', 'Item.OAK_SKIS'),
        ShopItem('Pine skis', 6, 71, 'coins', 'Loot', 'Item.PINE_SKIS'),
        ShopItem('Clay skydisc', 5, 21, 'coins', 'Tool', 'Item.CLAY_SKYDISC'),
        ShopItem('Golden skydisc', 1, 500, 'coins', 'Tool', 'Item.GOLDEN_SKYDISC'),
        ShopItem('Woodpucker', 1, 1500, 'coins', 'Tool', 'Item.WOODPUCKER'),
    ],
)

ADVENTURERS_GUILD_OUTPOST = ShopInfo(
    name='Adventurers\' Guild Outpost', building_type='Outpost',
    location='Horn of Respite', region='Jarvonia',
    inventory=[
        ShopItem('Bert\'s super-skis', 1, 750, 'adventurers_guild_token', 'Loot', 'Item.BERTS_SUPER_SKIS'),
        ShopItem('Bolstered quiver', 1, 150, 'adventurers_guild_token', 'Loot', 'Item.BOLSTERED_QUIVER'),
        ShopItem('Cape of the trailblazer', 1, 2500, 'adventurers_guild_token', 'Loot', 'Item.CAPE_OF_THE_TRAILBLAZER'),
        ShopItem('Quaint quiver', 1, 10, 'adventurers_guild_token', 'Loot', 'Item.QUAINT_QUIVER'),
        ShopItem('Rusty diving torso', 1, 20, 'adventurers_guild_token', 'Loot', 'Item.RUSTY_DIVING_TORSO'),
        ShopItem('Simple life vest', 1, 2, 'adventurers_guild_token', 'Loot', 'Item.SIMPLE_LIFE_VEST'),
        ShopItem('Simple rope', 1, 2, 'adventurers_guild_token', 'Loot', 'Item.SIMPLE_ROPE'),
        ShopItem('Tough rope', 1, 50, 'adventurers_guild_token', 'Loot', 'Item.TOUGH_ROPE'),
        ShopItem('Simple torch', 1, 2, 'adventurers_guild_token', 'Tool', 'Item.SIMPLE_TORCH'),
        ShopItem('Black eye peak wilderness permit', 1, 100, 'adventurers_guild_token', 'Collectible', 'Collectible.BLACK_EYE_PEAK_WILDERNESS_PERMIT'),
        ShopItem('Mysterious northern map', 1, 100, 'adventurers_guild_token', 'Collectible', 'Collectible.MYSTERIOUS_NORTHERN_MAP'),
        ShopItem('Fishing line', 10, 15, 'adventurers_guild_token', 'Material', 'Material.FISHING_LINE'),
        ShopItem('Adventuring guild chest', 10, 20, 'adventurers_guild_token', 'Container', 'Container.ADVENTURING_GUILD_CHEST'),
        ShopItem('Treasure hunter hat', 1, 50, 'adventurers_guild_token', 'Cosmetic', 'Item.TREASURE_HUNTER_HAT'),
        ShopItem('Treasure hunter jacket', 1, 50, 'adventurers_guild_token', 'Cosmetic', 'Item.TREASURE_HUNTER_JACKET'),
        ShopItem('Adventurers\' enamel pin', 1, 2, 'adventurers_guild_token', 'Material', 'Material.ADVENTURERS_ENAMEL_PIN'),
        ShopItem('Adventurers\' enamel pin', 1, 10, 'adventurers_guild_token', 'Material', 'Material.ADVENTURERS_ENAMEL_PIN'),
        ShopItem('Name tag', 1, 10, 'adventurers_guild_token', 'Material', 'Material.NAME_TAG'),
        ShopItem('Name tag', 1, 50, 'adventurers_guild_token', 'Material', 'Material.NAME_TAG'),
        ShopItem('Unidentified remains', 1, 20, 'adventurers_guild_token', 'Material', 'Material.UNIDENTIFIED_REMAINS'),
        ShopItem('Unidentified remains', 1, 100, 'adventurers_guild_token', 'Material', 'Material.UNIDENTIFIED_REMAINS'),
    ],
)

KALLAHEIMS_FROSTY_FINDS = ShopInfo(
    name='Kallaheim\'s Frosty Finds', building_type='General store',
    location='Kallaheim', region='Jarvonia',
    inventory=[
        ShopItem('Keen eye lenses', 1, 184, 'coins', 'Loot', 'Item.KEEN_EYE_LENSES'),
        ShopItem('Lumberjack boots', 1, 196, 'coins', 'Loot', 'Item.LUMBERJACK_BOOTS'),
        ShopItem('Simple ring', 1, 49, 'coins', 'Loot', 'Item.SIMPLE_RING'),
        ShopItem('Copper hatchet', 2, 31, 'coins', 'Tool', 'Item.COPPER_HATCHET'),
        ShopItem('Small sack', 1, 89, 'coins', 'Tool', 'Item.SMALL_SACK'),
        ShopItem('Cooked perch', 20, 13, 'coins', 'Consumable', 'Consumable.COOKED_PERCH'),
        ShopItem('Chocolate', 1, 20, 'coins', 'Material', 'Material.CHOCOLATE'),
        ShopItem('Copper bar', 20, 15, 'coins', 'Material', 'Material.COPPER_BAR'),
        ShopItem('Flax', 10, 15, 'coins', 'Material', 'Material.FLAX'),
        ShopItem('Hemp', 20, 10, 'coins', 'Material', 'Material.HEMP'),
        ShopItem('Milk', 3, 15, 'coins', 'Material', 'Material.MILK'),
        ShopItem('Potato', 20, 5, 'coins', 'Material', 'Material.POTATO'),
        ShopItem('Raw salmon', 20, 14, 'coins', 'Material', 'Material.RAW_SALMON'),
        ShopItem('Raw shrimp', 10, 7, 'coins', 'Material', 'Material.RAW_SHRIMP'),
        ShopItem('Twine', 10, 7, 'coins', 'Material', 'Material.TWINE'),
        ShopItem('Wheat', 5, 10, 'coins', 'Material', 'Material.WHEAT'),
    ],
)

THE_ICY_GOBLET = ShopInfo(
    name='The Icy Goblet', building_type='Tavern',
    location='Kallaheim', region='Jarvonia',
    inventory=[
        ShopItem('Beer', 25, 10, 'coins', 'Consumable', 'Consumable.BEER'),
        ShopItem('Cooked shrimp', 5, 9, 'coins', 'Consumable', 'Consumable.COOKED_SHRIMP'),
        ShopItem('Wine', 10, 35, 'coins', 'Consumable', 'Consumable.WINE'),
        ShopItem('Berries', 5, 8, 'coins', 'Material', 'Material.BERRIES'),
    ],
)

WOODCUTTERS_CABIN = ShopInfo(
    name='Woodcutter\'s Cabin', building_type='House',
    location='Nomad Woods', region='Jarvonia',
    inventory=[
        ShopItem('Steel hatchet', 2, 162, 'coins', 'Tool', 'Item.STEEL_HATCHET'),
    ],
)

FROSTHOOK_EMPORIUM = ShopInfo(
    name='Frosthook Emporium', building_type='Fishing store',
    location='Port Skildar', region='Jarvonia',
    inventory=[
        ShopItem('Rusty diving helmet', 1, 500, 'coins', 'Loot', 'Item.RUSTY_DIVING_HELMET'),
        ShopItem('Simple life vest', 3, 54, 'coins', 'Loot', 'Item.SIMPLE_LIFE_VEST'),
        ShopItem('Basic fishing net', 20, 13, 'coins', 'Tool', 'Item.BASIC_FISHING_NET'),
        ShopItem('Fishing lure', 5, 223, 'coins', 'Tool', 'Item.FISHING_LURE'),
        ShopItem('Large fishing net', 5, 31, 'coins', 'Tool', 'Item.LARGE_FISHING_NET'),
        ShopItem('Wooden fishing pole', 5, 25, 'coins', 'Tool', 'Item.WOODEN_FISHING_POLE'),
        ShopItem('Fishing line', 100, 3, 'coins', 'Material', 'Material.FISHING_LINE'),
        ShopItem('Twine', 20, 4, 'coins', 'Material', 'Material.TWINE'),
    ],
)

BIGLOO = ShopInfo(
    name='Bigloo', building_type='Fishing store',
    location='Winter Waves Glacier', region='Jarvonia',
    inventory=[
        ShopItem('Baby penguin ice lure', 1, 4000, 'coins', 'Tool', 'Item.BABY_PENGUIN_ICE_LURE'),
        ShopItem('Ice netrod', 1, 4000, 'coins', 'Tool', 'Item.ICE_NETROD'),
    ],
)


# --- Grand Duchy of Trellin-Erdwise ---

GOLDN_GRAIL_BILGEMONT = ShopInfo(
    name='Gold\'n Grail Bilgemont', building_type='Tavern',
    location='Bilgemont Port', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Map of Arenum', 1, 25000, 'coins', 'Tool', 'Item.MAP_OF_ARENUM'),
        ShopItem('Cooked salmon', 10, 42, 'coins', 'Consumable', 'Consumable.COOKED_SALMON'),
        ShopItem('Trout soup', 10, 63, 'coins', 'Consumable', 'Consumable.TROUT_SOUP'),
        ShopItem('Wine', 20, 39, 'coins', 'Consumable', 'Consumable.WINE'),
        ShopItem('Rough opal', 4, 189, 'coins', 'Material', 'Material.ROUGH_OPAL'),
        ShopItem('Rough ruby', 1, 3024, 'coins', 'Material', 'Material.ROUGH_RUBY'),
        ShopItem('Rough star pearl', 2, 236, 'coins', 'Material', 'Material.ROUGH_STAR_PEARL'),
        ShopItem('Rough topaz', 1, 1039, 'coins', 'Material', 'Material.ROUGH_TOPAZ'),
    ],
)

GOLDN_GRAIL_BLACKSPELL = ShopInfo(
    name='Gold\'n Grail Blackspell', building_type='Tavern',
    location='Blackspell Port', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Map of Arenum', 1, 25000, 'coins', 'Tool', 'Item.MAP_OF_ARENUM'),
        ShopItem('Cooked salmon', 10, 42, 'coins', 'Consumable', 'Consumable.COOKED_SALMON'),
        ShopItem('Trout soup', 10, 63, 'coins', 'Consumable', 'Consumable.TROUT_SOUP'),
        ShopItem('Wine', 20, 39, 'coins', 'Consumable', 'Consumable.WINE'),
        ShopItem('Rough opal', 4, 189, 'coins', 'Material', 'Material.ROUGH_OPAL'),
        ShopItem('Rough ruby', 1, 3024, 'coins', 'Material', 'Material.ROUGH_RUBY'),
        ShopItem('Rough star pearl', 2, 236, 'coins', 'Material', 'Material.ROUGH_STAR_PEARL'),
        ShopItem('Rough topaz', 1, 1039, 'coins', 'Material', 'Material.ROUGH_TOPAZ'),
    ],
)

GOLDN_GRAIL_EVERHAVEN = ShopInfo(
    name='Gold\'n Grail Everhaven', building_type='Tavern',
    location='Everhaven', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Map of Arenum', 1, 25000, 'coins', 'Tool', 'Item.MAP_OF_ARENUM'),
        ShopItem('Cooked salmon', 10, 42, 'coins', 'Consumable', 'Consumable.COOKED_SALMON'),
        ShopItem('Trout soup', 10, 63, 'coins', 'Consumable', 'Consumable.TROUT_SOUP'),
        ShopItem('Wine', 20, 39, 'coins', 'Consumable', 'Consumable.WINE'),
        ShopItem('Rough opal', 4, 189, 'coins', 'Material', 'Material.ROUGH_OPAL'),
        ShopItem('Rough ruby', 1, 3024, 'coins', 'Material', 'Material.ROUGH_RUBY'),
        ShopItem('Rough star pearl', 2, 236, 'coins', 'Material', 'Material.ROUGH_STAR_PEARL'),
        ShopItem('Rough topaz', 1, 1039, 'coins', 'Material', 'Material.ROUGH_TOPAZ'),
    ],
)

MOSSY_MERCHANTS_BREEZE_MART = ShopInfo(
    name='Mossy Merchant\'s Breeze Mart', building_type='General store',
    location='Everhaven', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Simple bug catching net', 1, 126, 'coins', 'Tool', 'Item.SIMPLE_BUG_CATCHING_NET'),
        ShopItem('Simple magnet', 1, 441, 'coins', 'Tool', 'Item.SIMPLE_MAGNET'),
    ],
)

BUREAU_OF_MOSS = ShopInfo(
    name='Bureau of Moss', building_type='Tavern',
    location='Granfiddich', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Beer', 20, 10, 'coins', 'Consumable', 'Consumable.BEER'),
        ShopItem('Salmon pie', 5, 250, 'coins', 'Consumable', 'Consumable.SALMON_PIE'),
        ShopItem('Schnitzel', 2, 2500, 'coins', 'Consumable', 'Consumable.SCHNITZEL'),
        ShopItem('Trout soup', 5, 250, 'coins', 'Consumable', 'Consumable.TROUT_SOUP'),
    ],
)

FISH_MARKET_STALL = ShopInfo(
    name='Fish Market Stall', building_type='Market stall',
    location='Granfiddich', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Raw anglerfish', 1, 175, 'coins', 'Material', 'Material.RAW_ANGLERFISH'),
        ShopItem('Raw jellyfish', 3, 75, 'coins', 'Material', 'Material.RAW_JELLYFISH'),
        ShopItem('Raw shark', 1, 125, 'coins', 'Material', 'Material.RAW_SHARK'),
        ShopItem('Raw trout', 5, 10, 'coins', 'Material', 'Material.RAW_TROUT'),
    ],
)

FOOD_MARKET_STALL = ShopInfo(
    name='Food Market Stall', building_type='Market stall',
    location='Granfiddich', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Bread', 3, 21, 'coins', 'Consumable', 'Consumable.BREAD'),
        ShopItem('Chocolate', 10, 15, 'coins', 'Material', 'Material.CHOCOLATE'),
        ShopItem('Egg', 10, 5, 'coins', 'Material', 'Material.EGG'),
        ShopItem('Milk', 10, 10, 'coins', 'Material', 'Material.MILK'),
        ShopItem('Potato', 25, 5, 'coins', 'Material', 'Material.POTATO'),
        ShopItem('Tomato', 10, 15, 'coins', 'Material', 'Material.TOMATO'),
    ],
)

TOOL_MARKET_STALL = ShopInfo(
    name='Tool Market Stall', building_type='Market stall',
    location='Granfiddich', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Birch hunting bow', 1, 51, 'coins', 'Tool', 'Item.BIRCH_HUNTING_BOW'),
        ShopItem('Bronze hatchet', 1, 94, 'coins', 'Tool', 'Item.BRONZE_HATCHET'),
        ShopItem('Bronze pickaxe', 1, 63, 'coins', 'Tool', 'Item.BRONZE_PICKAXE'),
        ShopItem('Iron hatchet', 1, 94, 'coins', 'Tool', 'Item.IRON_HATCHET'),
        ShopItem('Iron pickaxe', 1, 94, 'coins', 'Tool', 'Item.IRON_PICKAXE'),
        ShopItem('Iron sickle', 1, 150, 'coins', 'Tool', 'Item.IRON_SICKLE'),
        ShopItem('Oak hunting bow', 1, 200, 'coins', 'Tool', 'Item.OAK_HUNTING_BOW'),
        ShopItem('Sharp knife', 1, 1020, 'coins', 'Tool', 'Item.SHARP_KNIFE'),
        ShopItem('Sharp machete', 1, 1140, 'coins', 'Tool', 'Item.SHARP_MACHETE'),
        ShopItem('Simple chisel', 50, 37, 'coins', 'Tool', 'Item.SIMPLE_CHISEL'),
        ShopItem('Simple hammer', 50, 54, 'coins', 'Tool', 'Item.SIMPLE_HAMMER'),
        ShopItem('Simple pan', 50, 52, 'coins', 'Tool', 'Item.SIMPLE_PAN'),
        ShopItem('Simple saw', 50, 46, 'coins', 'Tool', 'Item.SIMPLE_SAW'),
        ShopItem('Simple sewing needle', 50, 42, 'coins', 'Tool', 'Item.SIMPLE_SEWING_NEEDLE'),
        ShopItem('Simple wrench', 50, 42, 'coins', 'Tool', 'Item.SIMPLE_WRENCH'),
    ],
)

ADVENTURERS_GUILD_SWAMPOST = ShopInfo(
    name='Adventurers\' Guild Swampost', building_type='Outpost',
    location='Halfmaw Hideout', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Bolstered quiver', 1, 150, 'adventurers_guild_token', 'Loot', 'Item.BOLSTERED_QUIVER'),
        ShopItem('Cape of the trailblazer', 1, 2500, 'adventurers_guild_token', 'Loot', 'Item.CAPE_OF_THE_TRAILBLAZER'),
        ShopItem('Quaint quiver', 1, 10, 'adventurers_guild_token', 'Loot', 'Item.QUAINT_QUIVER'),
        ShopItem('Simple life vest', 1, 2, 'adventurers_guild_token', 'Loot', 'Item.SIMPLE_LIFE_VEST'),
        ShopItem('Simple rope', 1, 2, 'adventurers_guild_token', 'Loot', 'Item.SIMPLE_ROPE'),
        ShopItem('Tough rope', 1, 50, 'adventurers_guild_token', 'Loot', 'Item.TOUGH_ROPE'),
        ShopItem('Seth\'s swamp compass', 1, 750, 'adventurers_guild_token', 'Tool', 'Item.SETHS_SWAMP_COMPASS'),
        ShopItem('Simple torch', 1, 2, 'adventurers_guild_token', 'Tool', 'Item.SIMPLE_TORCH'),
        ShopItem('Fishing line', 10, 15, 'adventurers_guild_token', 'Material', 'Material.FISHING_LINE'),
        ShopItem('Adventuring guild chest', 10, 20, 'adventurers_guild_token', 'Container', 'Container.ADVENTURING_GUILD_CHEST'),
        ShopItem('Halfmaw scales', 1, 1, 'adventurers_guild_token', 'Material', 'Material.HALFMAW_SCALES'),
        ShopItem('Halfmaw scales', 1, 5, 'adventurers_guild_token', 'Material', 'Material.HALFMAW_SCALES'),
        ShopItem('Halfmaw teeth', 1, 3, 'adventurers_guild_token', 'Material', 'Material.HALFMAW_TEETH'),
        ShopItem('Halfmaw teeth', 1, 15, 'adventurers_guild_token', 'Material', 'Material.HALFMAW_TEETH'),
    ],
)

PAWS_ARE_US = ShopInfo(
    name='Paws are Us', building_type='Animal shelter',
    location='Salsfirth', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Camel egg', 1, 10000, 'coins', 'Pet', 'Egg.CAMEL_EGG'),
    ],
)

QUAGMIRE_COUTURE = ShopInfo(
    name='Quagmire Couture', building_type='Clothing shop',
    location='Salsfirth', region='Grand Duchy of Trellin-Erdwise',
    inventory=[
        ShopItem('Fancy earring', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden ear piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eyebrow piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hearing aid', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two golden piercings', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eye glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Round glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Square glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sunglasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Thick glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Tinted glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arctic hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bowler Hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hat with a feather', 1, 5000, 'coins', 'Cosmetic', 'Item.HAT_WITH_A_FEATHER'),
        ShopItem('Headwrap', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Royal Guard Helmet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Swamp hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Top hat with goggles', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Warm beanie', 1, 650, 'coins', 'Cosmetic', 'Item.WARM_BEANIE'),
        ShopItem('Blanket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bot Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Caped Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Cloak with a gem', 1, 5000, 'coins', 'Cosmetic', None),
        ShopItem('Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert Vest', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Elegant Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fancy Suit', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Farm Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fur Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hoodie', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Outlander Furs', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Party Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Rancher Overalls', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scarf Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scoop Neck Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Shirt and Jacket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Pullover', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Dress with Necklace', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Strapless Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Training Robes', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Woodworker\'s Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arrows', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hatchet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Ice staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('One handed sword', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Rod of moss', 1, 5000, 'coins', 'Cosmetic', None),
        ShopItem('Staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Stick and a bottle', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two-handed sword', 1, 650, 'coins', 'Cosmetic', None),
    ],
)

WITCHS_HUT = ShopInfo(
    name='Witch\'s Hut', building_type='House',
    location='Witched Woods', region='Grand Duchy of Trellin-Erdwise',
)


# --- Syrenthia ---

CASBRANTS_SUNKEN_SHIP = ShopInfo(
    name='Casbrant\'s Sunken Ship', building_type='Fishing store',
    location='Casbrant\'s Grave', region='Syrenthia',
    inventory=[
        ShopItem('Swashbuckler sword', 1, 2000, 'sea_shell', 'Loot', 'Item.SWASHBUCKLER_SWORD'),
    ],
)

FIN_TASTIC_FASHION = ShopInfo(
    name='Fin-tastic Fashion', building_type='Clothing shop',
    location='Vastalume', region='Syrenthia',
    inventory=[
        ShopItem('Fancy earring', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden ear piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eyebrow piercing', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hearing aid', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two golden piercings', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Golden eye glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Round glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Square glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Thick glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Tinted glasses', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arctic hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bowler Hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Gemmed circlet', 1, 10000, 'coins', 'Cosmetic', None),
        ShopItem('Headwrap', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Royal Guard Helmet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Swamp hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Top hat with goggles', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Warm beanie', 1, 650, 'coins', 'Cosmetic', 'Item.WARM_BEANIE'),
        ShopItem('Blanket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Bot Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Caped Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert Vest', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Elegant Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fancy Suit', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Farm Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Fur Coat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hoodie', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Merfolk dancing dress', 1, 10000, 'coins', 'Cosmetic', None),
        ShopItem('Outlander Furs', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Party Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Rancher Overalls', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scarf Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Scoop Neck Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Shirt and Jacket', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Pullover', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Simple Shirt', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Dress with Necklace', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Sleeveless Gown', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Strapless Dress', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Training Robes', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Woodworker\'s Apron', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Arrows', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Hatchet', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Ice staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Merfolk fish wings', 1, 10000, 'coins', 'Cosmetic', None),
        ShopItem('One handed sword', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Staff', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Stick and a bottle', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Two-handed sword', 1, 650, 'coins', 'Cosmetic', None),
    ],
)

PEARL_OF_THE_SEA = ShopInfo(
    name='Pearl of the Sea', building_type='Tavern',
    location='Vastalume', region='Syrenthia',
    inventory=[
        ShopItem('Beer', 1, 3, 'sea_shell', 'Consumable', 'Consumable.BEER'),
        ShopItem('Saltrum', 1, 50, 'sea_shell', 'Consumable', 'Consumable.SALTRUM'),
        ShopItem('Sea cabbage', 2, 5, 'sea_shell', 'Material', 'Material.SEA_CABBAGE'),
        ShopItem('Sea spinach', 2, 5, 'sea_shell', 'Material', 'Material.SEA_SPINACH'),
        ShopItem('Underwater lotus', 1, 10, 'sea_shell', 'Material', 'Material.UNDERWATER_LOTUS'),
        ShopItem('Sea shell', 1, 10, 'sea_shell', 'Material', 'Material.SEA_SHELL'),
    ],
)

SUNKEN_ANCHOR = ShopInfo(
    name='Sunken Anchor', building_type='General store',
    location='Vastalume', region='Syrenthia',
    inventory=[
        ShopItem('Saltrum', 1, 50, 'sea_shell', 'Consumable', 'Consumable.SALTRUM'),
        ShopItem('Sea cabbage', 2, 5, 'sea_shell', 'Material', 'Material.SEA_CABBAGE'),
        ShopItem('Sea spinach', 2, 5, 'sea_shell', 'Material', 'Material.SEA_SPINACH'),
        ShopItem('Underwater lotus', 1, 10, 'sea_shell', 'Material', 'Material.UNDERWATER_LOTUS'),
    ],
)

UNDERCURRENT = ShopInfo(
    name='Undercurrent', building_type='General store',
    location='Vastalume', region='Syrenthia',
    inventory=[
        ShopItem('Simple chisel', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_CHISEL'),
        ShopItem('Simple hammer', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_HAMMER'),
        ShopItem('Simple pan', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_PAN'),
        ShopItem('Simple saw', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_SAW'),
        ShopItem('Simple sewing needle', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_SEWING_NEEDLE'),
        ShopItem('Simple wrench', 50, 5, 'sea_shell', 'Tool', 'Item.SIMPLE_WRENCH'),
        ShopItem('Underwater map', 1, 4000, 'sea_shell', 'Collectible', 'Collectible.UNDERWATER_MAP'),
        ShopItem('Kelp drift net', 100, 3, 'sea_shell', 'Material', 'Material.KELP_DRIFT_NET'),
    ],
)


# --- Wallisia ---

INNER_PEACE_EATS = ShopInfo(
    name='Inner Peace Eats', building_type='Tavern',
    location='Blackrane', region='Wallisia',
    inventory=[
        ShopItem('Beef stew', 5, 350, 'coins', 'Consumable', 'Consumable.BEEF_STEW'),
        ShopItem('Beer', 50, 10, 'coins', 'Consumable', 'Consumable.BEER'),
        ShopItem('Tasty breakfast', 5, 350, 'coins', 'Consumable', 'Consumable.TASTY_BREAKFAST'),
        ShopItem('Wine', 50, 35, 'coins', 'Consumable', 'Consumable.WINE'),
    ],
)

LOST_SOULSOURCING = ShopInfo(
    name='Lost Soulsourcing', building_type='General store',
    location='Wraithwater', region='Wallisia',
    inventory=[
        ShopItem('Simple chisel', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_CHISEL'),
        ShopItem('Simple hammer', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_HAMMER'),
        ShopItem('Simple pan', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_PAN'),
        ShopItem('Simple saw', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_SAW'),
        ShopItem('Simple sewing needle', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_SEWING_NEEDLE'),
        ShopItem('Simple wrench', 50, 2, 'ectoplasm', 'Tool', 'Item.SIMPLE_WRENCH'),
        ShopItem('Charter of the drowned', 1, 3000, 'ectoplasm', 'Collectible', 'Collectible.CHARTER_OF_THE_DROWNED'),
    ],
)


# --- Wrentmark ---

SOUTHERN_GEM = ShopInfo(
    name='Southern Gem', building_type='General store',
    location='Myriadian Arc', region='Wrentmark',
    inventory=[
        ShopItem('Spice rackpack', 1, 12500, 'coins', 'Loot', 'Item.SPICE_RACKPACK'),
        ShopItem('Simple chisel', 50, 42, 'coins', 'Tool', 'Item.SIMPLE_CHISEL'),
        ShopItem('Simple hammer', 50, 58, 'coins', 'Tool', 'Item.SIMPLE_HAMMER'),
        ShopItem('Simple pan', 50, 56, 'coins', 'Tool', 'Item.SIMPLE_PAN'),
        ShopItem('Simple saw', 50, 50, 'coins', 'Tool', 'Item.SIMPLE_SAW'),
        ShopItem('Simple sewing needle', 50, 46, 'coins', 'Tool', 'Item.SIMPLE_SEWING_NEEDLE'),
        ShopItem('Simple wrench', 50, 46, 'coins', 'Tool', 'Item.SIMPLE_WRENCH'),
        ShopItem('Dried fruit', 2, 5000, 'coins', 'Consumable', 'Consumable.DRIED_FRUIT'),
        ShopItem('Nut mix', 2, 5000, 'coins', 'Consumable', 'Consumable.NUT_MIX'),
        ShopItem('Jade', 3, 2000, 'coins', 'Material', 'Material.JADE'),
        ShopItem('Mahogany plank', 50, 200, 'coins', 'Material', 'Material.MAHOGANY_PLANK'),
        ShopItem('Ruby', 3, 4000, 'coins', 'Material', 'Material.RUBY'),
        ShopItem('Topaz', 3, 1500, 'coins', 'Material', 'Material.TOPAZ'),
        ShopItem('Desert dealer hat', 1, 650, 'coins', 'Cosmetic', None),
        ShopItem('Desert dealer outfit', 1, 650, 'coins', 'Cosmetic', None),
    ],
)


# ============================================================================
# LOOKUP HELPERS
# ============================================================================

ALL_SHOPS: List[ShopInfo] = [
    TUNDRA_TRENDS, NORTHSTAR_MERCANTILE, NOT_A_SHOP, HELPFUL_HERBERTS_HUT,
    FORT_OF_PERMAFROST, JARVOJOY, ADVENTURERS_GUILD_OUTPOST, KALLAHEIMS_FROSTY_FINDS,
    THE_ICY_GOBLET, WOODCUTTERS_CABIN, FROSTHOOK_EMPORIUM, BIGLOO,
    GOLDN_GRAIL_BILGEMONT, GOLDN_GRAIL_BLACKSPELL, GOLDN_GRAIL_EVERHAVEN, MOSSY_MERCHANTS_BREEZE_MART,
    BUREAU_OF_MOSS, FISH_MARKET_STALL, FOOD_MARKET_STALL, TOOL_MARKET_STALL,
    ADVENTURERS_GUILD_SWAMPOST, PAWS_ARE_US, QUAGMIRE_COUTURE, WITCHS_HUT,
    CASBRANTS_SUNKEN_SHIP, FIN_TASTIC_FASHION, PEARL_OF_THE_SEA, SUNKEN_ANCHOR,
    UNDERCURRENT, INNER_PEACE_EATS, LOST_SOULSOURCING, SOUTHERN_GEM,
]

SHOPS_BY_NAME: Dict[str, ShopInfo] = {shop.name: shop for shop in ALL_SHOPS}


def get_shop_item_names() -> set:
    """Get flat set of all equipment/collectible item names sold in shops."""
    names = set()
    for shop in ALL_SHOPS:
        for item in shop.inventory:
            if item.item_type in ('Loot', 'Tool', 'Collectible'):
                names.add(item.item_name)
    return names


def get_items_by_shop() -> Dict[str, List[str]]:
    """Get equipment/collectible item names grouped by shop name."""
    result = {}
    for shop in ALL_SHOPS:
        items = []
        for item in shop.inventory:
            if item.item_type in ('Loot', 'Tool', 'Collectible'):
                items.append(item.item_name)
        if items:
            result[shop.name] = items
    return result
