#!/usr/bin/env python3
"""
Adventurers' Guild Token (AGT) sell-value helpers.

Mirrors util/coin_value.py and util/shell_value.py for the AGT currency.
Used by the UI drop-builder sites to surface how many AGT a drop yields
when sold via its `special_sell` entry, including the FINE variant.

Background (bug 7ee43a0c, 2026-06-30): the column-3 drops pill and the
gearset-comparison currency row both compute "AGT tokens per 1k steps" by
summing `special_sell.quantity` over drops. They skip the separate Fine
drop row (`is_fine`) to avoid double-counting, and re-add the fine
contribution from a field carried on the BASE row — exactly like
`fine_coin_value` (coins) and `fine_shell_value` (shells). AGT had no such
field, so the fine sell value was silently dropped. A normal item like the
Adventurers' enamel pin sells for 2 AGT, but its fine variant sells for 10
AGT — so the pill under-counted any set whose AGT came (partly) from fines.

These helpers resolve directly from `drop.item_ref` to avoid the
item_object loader and its circular import through util.walkscape_constants.
"""


def _special_sell_ag_qty(obj) -> float:
    """Return the AGT special-sell quantity for a Material/Consumable object,
    or 0 when its special_sell does not award Adventurers' Guild Tokens."""
    ss = getattr(obj, 'special_sell', None)
    if not ss:
        return 0.0
    try:
        qty, currency_obj = ss
    except (TypeError, ValueError):
        return 0.0
    # Loaded objects carry a CurrencyInstance (has .name); autogenerated
    # source may carry the raw ref string "Currency.ADVENTURERS_GUILD_TOKEN".
    name = getattr(currency_obj, 'name', None) or str(currency_obj)
    if 'guild token' in name.lower() or 'ADVENTURERS_GUILD_TOKEN' in str(currency_obj):
        return float(qty or 0)
    return 0.0


def get_drop_ag_token_value(drop) -> float:
    """Return the AGT special-sell quantity of a single DropEntry, or 0.

    Currency.ADVENTURERS_GUILD_TOKEN drops award their own quantity (1 by
    default); Material/Consumable refs award via their `special_sell`.
    """
    if not getattr(drop, 'item_ref', None):
        return 0.0
    try:
        ref = drop.item_ref
        if ref == 'Currency.ADVENTURERS_GUILD_TOKEN':
            return 1.0
        if ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            attr_name = ref.split('.', 1)[1]
            if hasattr(Material, attr_name):
                return _special_sell_ag_qty(getattr(Material, attr_name))
        elif ref.startswith('Consumable.'):
            from util.autogenerated.consumables import Consumable
            attr_name = ref.split('.', 1)[1]
            if hasattr(Consumable, attr_name):
                return _special_sell_ag_qty(getattr(Consumable, attr_name))
    except Exception:
        pass
    return 0.0


def get_drop_fine_ag_token_value(drop) -> float:
    """Return the AGT special-sell quantity of the Fine variant of a drop, or 0.

    The Fine variant is a separate Material/Consumable `<NAME>_FINE` whose
    `special_sell` may award AGT at a higher quantity than the base item
    (e.g. Adventurers' enamel pin: base 2 AGT, fine 10 AGT). Mirrors
    util/coin_value.py:get_drop_fine_coin_value.
    """
    if not getattr(drop, 'item_ref', None):
        return 0.0
    try:
        if drop.item_ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            fine_name = drop.item_ref.split('.', 1)[1] + '_FINE'
            if hasattr(Material, fine_name):
                return _special_sell_ag_qty(getattr(Material, fine_name))
        elif drop.item_ref.startswith('Consumable.'):
            from util.autogenerated.consumables import Consumable
            fine_name = drop.item_ref.split('.', 1)[1] + '_FINE'
            if hasattr(Consumable, fine_name):
                return _special_sell_ag_qty(getattr(Consumable, fine_name))
    except Exception:
        pass
    return 0.0


# ---------------------------------------------------------------------------
# Activity AGT-value aggregator
#
# Adventurers' Guild Tokens are a *value* currency, not a single item-finding
# drop: you earn them by selling the activity's drops to the guild (via each
# drop's `special_sell`), and FINE variants sell for MORE AGT. So optimizing
# "steps per adventure token" must roll up the AGT value of EVERY drop —
# including the FMF-boosted fine variants and any direct
# Currency.ADVENTURERS_GUILD_TOKEN drops from gear item-finding — exactly the
# way util/coin_value.compute_coin_targets_for_activity does for coins.
#
# Bug (2026-07-05, report deea604d/f7480f44): the optimizer scored
# 'cat:if:adventurers_guild_tokens' as the narrow ItemFindingCategory drop
# rate (base_spr / IF-stat), which IGNORES the special_sell value of the
# activity's own drops and the FMF-boosted fine contribution. Result: a tool
# giving FMF (e.g. Rusty spyglass) raised the real AGT/1k the UI displays
# (3.78 -> 3.81) yet the optimizer's narrow steps/token went UP (147941 ->
# 148071), so the optimizer preferred a Work-Efficiency stick (Wanderlust)
# whose WE is wasted at the activity's WE cap. Scoring AGT as a value
# aggregate fixes the ranking.
# ---------------------------------------------------------------------------

# Reuse the exact target string the UI already emits for the adventure-token
# priority so no settings migration is needed; the scorer routes this key to
# the value aggregate injected here (see optimize_activity_gearsets.py).
AGT_TARGET = 'cat:if:adventurers_guild_tokens'


def compute_agt_targets_for_activity(activity, drop_rates, stats=None,
                                     collectible_stats=None,
                                     consumable_stats=None):
    """Compute a synthetic steps-per-AGT-value target for an activity.

    Mirrors util/coin_value.compute_coin_targets_for_activity. Sums the AGT
    special-sell value of every drop (base + FMF-boosted fine variant, plus
    direct Currency.ADVENTURERS_GUILD_TOKEN drops from item-finding gear) into
    a single AGT-per-step figure, then returns steps-per-AGT.

    Args:
        activity: The Activity being optimized.
        drop_rates: {item_name: steps_per_item} from
            Activity.get_expected_drop_rate(target_item=None).
        stats / collectible_stats / consumable_stats: the same stats dicts the
            drop_rates were computed under; required to re-expand IF equipment
            drops so their AGT contribution is counted.

    Returns:
        {AGT_TARGET: steps_per_agt}. steps_per_agt is float('inf') when the
        gearset yields no AGT at all — matching the "no target" sentinel used
        elsewhere in the scorer.
    """
    if not drop_rates:
        return {AGT_TARGET: float('inf')}

    # Reuse the coins collector — it rebuilds main + secondary drop tables and
    # expands ItemFindingCategory.* gear/collectible/consumable drops exactly
    # like Activity.get_expected_drop_rate, so AGT-bearing IF drops (the guild
    # token currency itself) are included.
    from util.coin_value import _collect_activity_drops_with_equipment
    all_drops = _collect_activity_drops_with_equipment(
        activity, stats or {}, collectible_stats, consumable_stats,
    )

    agt_per_step = 0.0
    # Dedupe by item_name: drop_rates[name] is already the combined
    # (harmonic-mean) rate across all sources for that item, so iterating each
    # occurrence would double-count. Mirrors compute_coin_targets_for_activity.
    seen_names = set()
    for drop in all_drops:
        if drop.item_name == 'Nothing':
            continue
        if drop.item_name in seen_names:
            continue
        seen_names.add(drop.item_name)

        steps = drop_rates.get(drop.item_name)
        if steps and steps > 0 and steps != float('inf'):
            agt_value = get_drop_ag_token_value(drop)
            if agt_value > 0:
                agt_per_step += (1.0 / steps) * agt_value

        fine_key = f"{drop.item_name} (Fine)"
        fine_steps = drop_rates.get(fine_key)
        if fine_steps and fine_steps > 0 and fine_steps != float('inf'):
            fine_agt_value = get_drop_fine_ag_token_value(drop)
            if fine_agt_value > 0:
                agt_per_step += (1.0 / fine_steps) * fine_agt_value

    steps_per_agt = (1.0 / agt_per_step) if agt_per_step > 0 else float('inf')
    return {AGT_TARGET: steps_per_agt}
