#!/usr/bin/env python3
"""
Coin-value helpers used by the optimizer and the UI to:
  - Look up coin_value / fine_coin_value for a single drop entry.
  - Aggregate expected coins/step (and steps/coin) for an activity given a
    stats dict and the drop_rates dict produced by
    Activity.get_expected_drop_rate.

Provides two synthetic targets used by the gearset optimizer:

  - 'cat:coins'           - total coins earned per step, including chests.
  - 'cat:coins_no_chests' - same, but with all Container.* drops excluded.

Chest values for skill chests live in CHEST_COIN_VALUES below. The wiki
publishes "Average Value(Per Chest)" for most skill chests; Hunting and
Tailoring are computed locally via chest_coin_value.py (same 4-roll
formula, plus 1% fine-material bonus).
"""

# ============================================================================
# CHEST COIN VALUES (single source of truth)
# ============================================================================

# Wiki source of truth: https://wiki.walkscape.app/wiki/Chests/Values
# "Average Value (Per chest)" column — total sell value of all contents
# (no fines). Re-scraped 2026-05-13. All skill chests (including Hunting
# and Tailoring) are now listed directly on the wiki and come straight
# from that table.
CHEST_COIN_VALUES = {
    'Container.AGILITY_CHEST': 64.88,
    'Container.CARPENTRY_CHEST': 100.53,
    'Container.COOKING_CHEST': 69.51,
    'Container.CRAFTING_CHEST': 99.78,
    'Container.FISHING_CHEST': 71.31,
    'Container.FORAGING_CHEST': 76.96,
    'Container.HUNTING_CHEST': 62.76,
    'Container.MINING_CHEST': 86.44,
    'Container.SMITHING_CHEST': 93.92,
    'Container.TAILORING_CHEST': 73.30,
    'Container.TRINKETRY_CHEST': 307.38,
    'Container.WOODCUTTING_CHEST': 81.12,
    'Container.BIRD_NEST': 57.71,
    'Container.COIN_POUCH': 101.52,
    'Container.GEM_POUCH': 136.66,
    'Container.RUSTY_CHEST': 10.19,
    'Container.SUNKEN_CHEST': 70.47,
    'Container.CORAL_CHEST': 93.14,
    'Container.ADVENTURING_GUILD_CHEST': 43.33,
    'Container.CHEST_OF_JARVONIA': 67.98,
    'Container.CHEST_OF_TRELLIN': 36.35,
    'Container.CHEST_OF_ERDWISE': 103.82,
    'Container.CHEST_OF_THE_HALFLING_REBELS': 59.00,
    'Container.CHEST_OF_SYRENTHIA': 117.21,
}


# ============================================================================
# DROP COIN VALUE LOOKUP
# ============================================================================

def get_drop_coin_value(drop) -> float:
    """Return the coin sell value for a single DropEntry.

    Resolves from drop.item_ref directly (avoids the item_object loader and
    its circular import through util.walkscape_constants).

    Returns 0 when the drop isn't sellable (e.g. Collectibles) or the ref
    can't be resolved.
    """
    if drop.item_ref is None:
        # Coins drop - item_name is 'Coins' (chest valuables table entries)
        if drop.item_name == 'Coins':
            return 1.0
        return 0.0

    try:
        ref = drop.item_ref
        if ref == 'Currency.COIN':
            return 1.0
        if ref.startswith('Container.'):
            return float(CHEST_COIN_VALUES.get(ref, 0))
        if ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            attr_name = ref.split('.', 1)[1]
            if hasattr(Material, attr_name):
                obj = getattr(Material, attr_name)
                return float(obj.value or 0)
        elif ref.startswith('Item.'):
            from util.autogenerated.equipment import Item
            attr_name = ref.split('.', 1)[1]
            if hasattr(Item, attr_name):
                obj = getattr(Item, attr_name)
                return float(obj.value or 0)
        elif ref.startswith('Consumable.'):
            from util.autogenerated.consumables import Consumable
            attr_name = ref.split('.', 1)[1]
            if hasattr(Consumable, attr_name):
                obj = getattr(Consumable, attr_name)
                if hasattr(obj, 'value'):
                    return float(obj.value or 0)
    except Exception:
        pass
    return 0.0


def get_drop_fine_coin_value(drop) -> float:
    """Return the coin sell value of the Fine variant of a drop, or 0."""
    if not drop.item_ref:
        return 0.0
    try:
        if drop.item_ref.startswith('Material.'):
            from util.autogenerated.materials import Material
            fine_name = drop.item_ref.split('.', 1)[1] + '_FINE'
            if hasattr(Material, fine_name):
                return float(getattr(Material, fine_name).value or 0)
        elif drop.item_ref.startswith('Consumable.'):
            from util.autogenerated.consumables import Consumable
            fine_name = drop.item_ref.split('.', 1)[1] + '_FINE'
            if hasattr(Consumable, fine_name):
                return float(getattr(Consumable, fine_name).value or 0)
    except Exception:
        pass
    return 0.0


def is_chest_drop(drop) -> bool:
    """Return True when the drop's item_ref points at a Container.*.

    Used by the 'no_chests' variant of the coins target to strip out all
    chest contributions (both the chest itself and whatever nested
    drops would roll out of it — those never appear in an activity's
    drop table, so it's sufficient to drop Container.* entries).
    """
    return bool(drop.item_ref and drop.item_ref.startswith('Container.'))


# ============================================================================
# COIN AGGREGATION FOR ACTIVITIES
# ============================================================================

# The two synthetic target keys the optimizer and worker both understand.
COIN_TARGET = 'cat:coins'
COIN_NO_CHESTS_TARGET = 'cat:coins_no_chests'
COIN_TARGETS = (COIN_TARGET, COIN_NO_CHESTS_TARGET)


def _collect_activity_drops_with_equipment(activity, stats, collectible_stats=None,
                                           consumable_stats=None):
    """Rebuild the full drops list that Activity.get_expected_drop_rate iterates.

    Matches util/autogenerated/activities.py: main table + secondary table +
    equipment IF category expansions (from each of stats / collectible_stats
    / consumable_stats).

    Returned drops are DropEntry instances; IF drops are freshly expanded
    so their chance_percent already reflects the stat value.
    """
    drops = list(activity.drop_table) + list(activity.secondary_drop_table)

    # Item-finding equipment drops. Mirrors the three-loop pattern in the
    # activity scorer so we pick up IF drops from gear, collectibles, and
    # consumables alike.
    try:
        from util.autogenerated.item_finding import ItemFindingCategory
    except ImportError:
        return drops

    def _extend_from(stats_dict, value_in_percent: bool):
        if not stats_dict:
            return
        for stat_name, stat_value in stats_dict.items():
            if not stat_name.startswith('ItemFindingCategory.'):
                continue
            category_const = stat_name.split('.', 1)[1]
            if not hasattr(ItemFindingCategory, category_const):
                continue
            category = getattr(ItemFindingCategory, category_const)
            base_chance = stat_value if value_in_percent else stat_value * 100.0
            drops.extend(category.expand_with_chance(base_chance))

    # Gear stats are already in percentage form (matches activities.py).
    _extend_from(stats, value_in_percent=True)
    _extend_from(collectible_stats, value_in_percent=False)
    _extend_from(consumable_stats, value_in_percent=False)
    return drops


def compute_coin_targets_for_activity(activity, drop_rates, stats=None,
                                      collectible_stats=None,
                                      consumable_stats=None):
    """Compute synthetic steps-per-coin targets for an activity.

    Args:
        activity: The Activity being optimized.
        drop_rates: {item_name: steps_per_item} dict returned from
            Activity.get_expected_drop_rate(target_item=None).
        stats / collectible_stats / consumable_stats: same stats dicts the
            drop_rates were computed under; required to re-expand IF
            equipment drops so their coin contribution is counted.

    Returns:
        Dict suitable for updating drop_rates:
            {'cat:coins': steps_per_coin, 'cat:coins_no_chests': ...}
        Entries are float('inf') when a gearset produces no coins at all —
        matching the "no target" sentinel elsewhere in the scorer.
    """
    if not drop_rates:
        return {COIN_TARGET: float('inf'), COIN_NO_CHESTS_TARGET: float('inf')}

    all_drops = _collect_activity_drops_with_equipment(
        activity, stats or {}, collectible_stats, consumable_stats,
    )

    coins_per_step = 0.0
    coins_per_step_no_chests = 0.0

    # Dedupe by item_name. all_drops can contain the same item multiple
    # times (e.g. an item in main drop_table that also appears via an IF
    # category expansion in _collect_activity_drops_with_equipment). The
    # corresponding drop_rates[name] entry is ALREADY the combined
    # harmonic-mean rate across all sources (see Activity.get_expected_
    # drop_rate's `(existing * steps_per_item) / (existing + steps_per_item)`
    # merge). Iterating each occurrence and adding its `1/steps × coin_value`
    # would double-count items with multiple drop sources, inflating the
    # coins/step total. Mirror the column-3 drops-section.js mergeDrops()
    # behavior — collapse to one entry per name. User-reported 2026-05-25:
    # 257.15 coins/1k steps in stats report vs 216.28 in column-3 drops
    # (~19% over) for an activity with multi-source drops.
    seen_names = set()
    for drop in all_drops:
        if drop.item_name == 'Nothing':
            continue
        if drop.item_name in seen_names:
            continue
        seen_names.add(drop.item_name)

        # Base (non-fine) contribution.
        steps = drop_rates.get(drop.item_name)
        if steps and steps > 0 and steps != float('inf'):
            items_per_step = 1.0 / steps
            coin_value = get_drop_coin_value(drop)
            if coin_value > 0:
                contrib = items_per_step * coin_value
                coins_per_step += contrib
                if not is_chest_drop(drop):
                    coins_per_step_no_chests += contrib

        # Fine-variant contribution, if the scorer produced a fine entry.
        fine_key = f"{drop.item_name} (Fine)"
        fine_steps = drop_rates.get(fine_key)
        if fine_steps and fine_steps > 0 and fine_steps != float('inf'):
            fine_items_per_step = 1.0 / fine_steps
            fine_coin_value = get_drop_fine_coin_value(drop)
            if fine_coin_value > 0:
                contrib = fine_items_per_step * fine_coin_value
                coins_per_step += contrib
                # Fine materials are never chests, so always count in no_chests too.
                coins_per_step_no_chests += contrib

    def _steps_per_coin(cps):
        return (1.0 / cps) if cps > 0 else float('inf')

    return {
        COIN_TARGET: _steps_per_coin(coins_per_step),
        COIN_NO_CHESTS_TARGET: _steps_per_coin(coins_per_step_no_chests),
    }


# ============================================================================
# COIN AGGREGATION FOR RECIPES
# ============================================================================

def _expected_drops_per_craft(chance_percent: float, multi_roll_count: int,
                              avg_qty: float) -> float:
    """Expected number of drops from a single recipe drop entry per craft.

    Mirrors the multi-roll formula used elsewhere: the wiki's `chance_percent`
    for multi-roll side drops is the COMPOUND chance (at least one drop
    over N rolls), so the per-roll probability must be recovered before
    computing the expectation.
    """
    if not chance_percent or chance_percent <= 0 or avg_qty <= 0:
        return 0.0
    c = max(0.0, min(100.0, chance_percent)) / 100.0
    if multi_roll_count and multi_roll_count > 1:
        per_roll = 1.0 - (1.0 - c) ** (1.0 / multi_roll_count)
        return multi_roll_count * per_roll * avg_qty
    return c * avg_qty


def _quality_weighted_output_value(output_obj, percentages) -> float:
    """Expected sell value of a single crafted output, quality-weighted.

    For equipment with a `_quality_values` dict (different sell price per
    quality tier) this is Σ P(q) × value(q). For materials/consumables
    (uniform sell price regardless of craft quality) it collapses to the
    base value — the quality weighting is a no-op because value(q) is
    the same for every q.
    """
    if output_obj is None:
        return 0.0

    # Equipment with per-quality sell values.
    quality_values = getattr(output_obj, '_quality_values', None)
    if quality_values:
        base_value = float(getattr(output_obj, 'value', 0) or 0)
        total = 0.0
        for quality, pct in (percentages or {}).items():
            val = quality_values.get(quality, base_value)
            total += (pct / 100.0) * float(val or 0)
        return total

    # Non-equipment output (material, consumable, etc.) — uniform value.
    return float(getattr(output_obj, 'value', 0) or 0)


def compute_coins_per_craft_for_recipe(recipe, percentages, total_stats=None) -> dict:
    """Compute expected coin yield per craft for a recipe.

    Args:
        recipe: Recipe object (has output_item, quantity, drop_table).
        percentages: {quality_name: percentage} from calculate_quality_weights.
            Used to quality-weight the output's sell value when the output
            is equipment.
        total_stats: Aggregated stat dict. chest_finding multiplies the
            chest drop chance, matching the existing cat:chests scoring.

    Returns:
        {'with_chests': coins_per_craft,
         'no_chests':   coins_per_craft_without_chest_contribution}

    Both values are floats; zero is returned when the recipe produces no
    sellable output (unusual but possible for generic recipes).
    """
    total_stats = total_stats or {}

    # 1) Primary output value (quality-weighted for equipment, flat for mats).
    output_obj = None
    try:
        output_obj = recipe.get_output_item_object()
    except Exception:
        output_obj = None
    output_quantity = int(getattr(recipe, 'quantity', 1) or 1)
    output_value_per_craft = output_quantity * _quality_weighted_output_value(
        output_obj, percentages
    )

    # 2) Side + chest drops from recipe.drop_table. Entries are plain dicts
    #    in the autogenerated recipes.py, unlike activity drop tables which
    #    are DropEntry objects — so we key on string fields directly here.
    chest_finding = float(total_stats.get('chest_finding', 0.0) or 0.0)
    chest_rate_multiplier = 1.0 + chest_finding

    side_coins = 0.0
    chest_coins = 0.0

    for drop in (getattr(recipe, 'drop_table', None) or []):
        if not isinstance(drop, dict):
            continue
        chance_percent = float(drop.get('chance_percent') or 0.0)
        multi_roll_count = int(drop.get('multi_roll_count') or 1)
        qty_min = drop.get('quantity_min', drop.get('quantity', 0)) or 0
        qty_max = drop.get('quantity_max', drop.get('quantity', qty_min)) or qty_min
        try:
            avg_qty = (float(qty_min) + float(qty_max)) / 2.0
        except (TypeError, ValueError):
            avg_qty = 0.0

        ref = drop.get('item_ref') or ''
        is_chest = ref.startswith('Container.')

        if is_chest:
            # Chest drop: existing cat:chests scoring treats the drop as a
            # single roll (multi_roll_count irrelevant for skill chests),
            # with chest_finding multiplying the chance. Coin value is the
            # chest's average sell value from CHEST_COIN_VALUES.
            chest_value = float(CHEST_COIN_VALUES.get(ref, 0) or 0)
            effective_rate = (chance_percent / 100.0) * chest_rate_multiplier
            chest_coins += effective_rate * chest_value
            continue

        # Side drops (e.g. Silver nugget on smelting): resolve the item
        # from the ref so we pick up its sell value.
        expected_drops = _expected_drops_per_craft(chance_percent, multi_roll_count, avg_qty)
        if expected_drops <= 0:
            continue
        item_value = 0.0
        try:
            if ref == 'Currency.COIN':
                item_value = 1.0
            elif ref.startswith('Material.'):
                from util.autogenerated.materials import Material
                attr_name = ref.split('.', 1)[1]
                if hasattr(Material, attr_name):
                    item_value = float(getattr(Material, attr_name).value or 0)
            elif ref.startswith('Item.'):
                from util.autogenerated.equipment import Item
                attr_name = ref.split('.', 1)[1]
                if hasattr(Item, attr_name):
                    item_value = float(getattr(Item, attr_name).value or 0)
            elif ref.startswith('Consumable.'):
                from util.autogenerated.consumables import Consumable
                attr_name = ref.split('.', 1)[1]
                if hasattr(Consumable, attr_name):
                    obj = getattr(Consumable, attr_name)
                    item_value = float(getattr(obj, 'value', 0) or 0)
        except Exception:
            item_value = 0.0
        side_coins += expected_drops * item_value

    with_chests = output_value_per_craft + side_coins + chest_coins
    no_chests = output_value_per_craft + side_coins
    return {'with_chests': with_chests, 'no_chests': no_chests}
