#!/usr/bin/env python3
"""
Shared optimization utilities for gearset optimization.

Provides common functions used across activity, crafting, and travel optimizers
including item filtering, quality ranking, and stat caching.
"""

# Standard library imports
import re
from typing import Dict, List, Optional, Set, Tuple

# ============================================================================
# PET-SKILL-XP PREFERENCE (bug e5145503)
# ============================================================================
#
# Some pets gain XP only while their owner is doing a specific skill
# (e.g. Tiger -> Hunting, Mummy -> Tailoring, Gecko -> Mining,
# Chicken -> Foraging). Players generally want to equip those pets
# whenever they're doing the matching skill so the pet keeps levelling
# up — even if a different pet (e.g. Camel with a tiny global
# +inventory_space stat) would score marginally better on raw metrics.
#
# This module exposes two helpers:
#   * pet_gains_xp_for_skill — checks one pet's
#     `requirement_to_gain_xp` string.
#   * filter_pets_to_skill_xp_relevant — narrows a candidate pool to
#     skill-XP-relevant pets when at least one such (unmaxed) pet is
#     available; otherwise returns the pool unchanged.
#
# Only matches the "While doing <Skill>." pattern. Area-based
# ('While in the Wrentmark area.'), location-based ('While in
# Underwater location.'), and negative ('Not doing Agility.')
# requirements do NOT qualify — those pets earn XP from being
# somewhere/avoiding-something, not from the player's active skill.
#

_PET_XP_SKILL_RE = re.compile(
    r'^\s*while\s+doing\s+([a-z]+)\s*\.?\s*$', re.IGNORECASE
)


def pet_gains_xp_for_skill(pet_info, skill) -> bool:
    """True if ``pet_info`` gains XP from doing the given ``skill``.

    Looks at ``pet_info.requirement_to_gain_xp``. Matches the exact
    "While doing <Skill>." pattern (case-insensitive). All other
    requirement shapes (area, location, negative) return False.

    Both arguments may be None/empty — returns False in those cases
    rather than raising.
    """
    if not pet_info or not skill:
        return False
    req = getattr(pet_info, 'requirement_to_gain_xp', None)
    if not req:
        return False
    m = _PET_XP_SKILL_RE.match(req)
    if not m:
        return False
    return m.group(1).lower() == str(skill).strip().lower()


def _pet_has_global_find_stat(pet_info, find_stats) -> bool:
    """True if ``pet_info`` carries a 'global'-skill-scoped find stat whose
    name is in ``find_stats``.

    Pet stats are nested {skill: {location: {stat: value}}}. A pet whose only
    universally-applicable stat is a global "find" stat (e.g. the Level 4 Mummy
    /Tiger's global +find_collectibles) genuinely boosts the corresponding drop
    category on ANY activity, regardless of the pet's skill specialization.
    """
    if not find_stats:
        return False
    stats = getattr(pet_info, '_stats', None)
    if not isinstance(stats, dict):
        return False
    glob = stats.get('global')
    if not isinstance(glob, dict):
        return False
    for by_loc in glob.values():
        if isinstance(by_loc, dict):
            for stat_name, value in by_loc.items():
                if value and stat_name in find_stats:
                    return True
    return False


def filter_pets_to_skill_xp_relevant(pet_pool, skill, *, pets_by_name=None,
                                     keep_if_global_find_stats=None):
    """Narrow a pet candidate pool to skill-XP-relevant pets when possible.

    If ``skill`` is set and at least one pet in ``pet_pool`` gains XP
    from doing that skill AND is not at max level for its species,
    return the subset of pets meeting both conditions. Otherwise
    return ``pet_pool`` unchanged (as a new list).

    The "not at max level" condition exists because a maxed pet can't
    benefit from extra XP — at that point we let the regular
    stat-based selection take over and pick whatever scores best.

    ``keep_if_global_find_stats`` (bug 2d4f5491): when the optimization is
    targeting a "find" category (e.g. a collectibles report), the skill-XP
    preference must NOT exclude a pet whose global find stat directly boosts
    the target drop. For example, optimizing Alligator hunting → a collectible
    would otherwise narrow the pool to the Tiger (Hunting-XP) and drop the
    Mummy (global +find_collectibles) — even though the Mummy makes the
    collectible drop faster. Any pet carrying a global find stat in this set
    is UNIONED back into the returned pool (never removed), so the optimizer
    scores both and picks whichever is genuinely faster for the target.

    Args:
        pet_pool: iterable of PetInfo instances (the candidates the
            optimizer would otherwise test in the 'pet' slot).
        skill: active skill name (e.g. 'hunting', 'tailoring'). Case
            insensitive.
        pets_by_name: optional override for
            ``util.autogenerated.pets.PETS_BY_NAME``. Tests use this
            to avoid loading the real catalog. If None, the real
            catalog is imported lazily.
        keep_if_global_find_stats: optional set of find-stat names
            (e.g. {'find_collectibles'}) relevant to the current
            optimization target. Pets with a matching global-scoped
            find stat are always retained in the candidate pool.

    Returns:
        A new list. The skill-XP subset (or full pool) plus any
        target-relevant find-stat pets unioned in.
    """
    if not pet_pool:
        return []
    pool = list(pet_pool)
    if not skill:
        return pool

    if pets_by_name is None:
        # Lazy import — keeps util modules loadable without the
        # autogenerated catalog (e.g. for unit tests with mocks).
        from util.autogenerated.pets import PETS_BY_NAME as _PBN
        pets_by_name = _PBN

    relevant = []
    for pet in pool:
        if not pet_gains_xp_for_skill(pet, skill):
            continue
        species_name = getattr(pet, 'name', None)
        if not species_name:
            continue
        pet_levels = pets_by_name.get(species_name)
        if pet_levels is None:
            continue
        try:
            levels = pet_levels._levels
        except AttributeError:
            continue
        if not levels:
            continue
        max_level = max(levels.keys())
        current_level = getattr(pet, 'level', 0) or 0
        if current_level >= max_level:
            # Already maxed — XP preference doesn't apply, fall back
            # to stat-based selection.
            continue
        relevant.append(pet)

    # Base pool: the skill-XP subset when non-empty, else the full pool
    # (the pre-existing behavior).
    base = relevant if relevant else pool

    # Bug 2d4f5491: union in any pet carrying a target-relevant global find
    # stat that the base pool dropped. This never removes candidates — it only
    # re-admits find-stat pets the skill-XP narrowing would otherwise exclude,
    # so the optimizer can still score (and prefer) them for a find-category
    # target like a collectibles report.
    if keep_if_global_find_stats:
        result = list(base)
        for pet in pool:
            if pet in result:
                continue
            if _pet_has_global_find_stat(pet, keep_if_global_find_stats):
                result.append(pet)
        return result

    return base


# ============================================================================
# ITEM FILTERING
# ============================================================================

def filter_items_by_quality(items: list, keep_highest_only: bool = True) -> list:
    """
    Filter items to keep only highest quality per base item.
    
    Args:
        items: List of item objects
        keep_highest_only: If True, keep only highest quality per base
        
    Returns:
        Filtered list of items
    """
    if not keep_highest_only:
        return items
    
    # Group by base name (remove quality suffix)
    by_base = {}
    
    for item in items:
        # Extract base name (remove quality in parentheses)
        base_name = item.name
        if '(' in base_name and ')' in base_name:
            base_name = base_name[:base_name.index('(')].strip()
        
        if base_name not in by_base:
            by_base[base_name] = []
        by_base[base_name].append(item)
    
    # Keep highest quality per base
    filtered = []
    quality_order = {
        'Eternal': 6, 'Perfect': 5, 'Excellent': 4,
        'Great': 3, 'Good': 2, 'Normal': 1, None: 0
    }
    
    for base_name, base_items in by_base.items():
        # Sort by quality (highest first), then by value
        def get_quality_score(item):
            for quality_name, score in quality_order.items():
                if quality_name and f'({quality_name})' in item.name:
                    return (score, item.value)
            return (0, item.value)
        
        # For rings: keep top 2 qualities (player has 2 ring slots)
        is_ring = any(hasattr(item, 'slot') and item.slot == 'ring' for item in base_items)
        if is_ring and len(base_items) > 1:
            sorted_items = sorted(base_items, key=get_quality_score, reverse=True)
            filtered.extend(sorted_items[:2])
        else:
            best_item = max(base_items, key=get_quality_score)
            filtered.append(best_item)
    
    return filtered

def filter_items_by_stats(
    items: list,
    skill: str,
    location,
    character,
    required_stats: Optional[Set[str]] = None
) -> list:
    """
    Filter items to only those with relevant stats for the skill.
    
    Args:
        items: List of item objects
        skill: Skill name (e.g., 'agility', 'carpentry')
        location: Location object or None
        character: Character object
        required_stats: Set of stat names to check for (None = any stat)
        
    Returns:
        Filtered list of items with relevant stats
    """
    filtered = []
    
    for item in items:
        stats = item.get_stats_for_skill(skill, location=location, character=character)
        
        if not stats:
            continue
        
        # If no required stats specified, include any item with stats
        if required_stats is None:
            filtered.append(item)
            continue
        
        # Check if item has any of the required stats
        has_required = any(stat_name in stats and stats[stat_name] != 0 
                          for stat_name in required_stats)
        
        if has_required:
            filtered.append(item)
    
    return filtered

def filter_ignored_items(items: list, ignored_set: Set) -> list:
    """
    Filter out items in the ignored set.
    
    Args:
        items: List of item objects
        ignored_set: Set of Item enum values to ignore
        
    Returns:
        Filtered list without ignored items
    """
    # Extract base names from ignored set
    ignored_names = set()
    for ignored_item in ignored_set:
        if hasattr(ignored_item, 'name'):
            # Remove quality suffix to match base name
            base_name = ignored_item.name
            if '(' in base_name and ')' in base_name:
                base_name = base_name[:base_name.index('(')].strip()
            ignored_names.add(base_name)
    
    # Filter items
    filtered = []
    for item in items:
        base_name = item.name
        if '(' in base_name and ')' in base_name:
            base_name = base_name[:base_name.index('(')].strip()
        
        if base_name not in ignored_names:
            filtered.append(item)
    
    return filtered

# ============================================================================
# DOMINANCE PRUNING
# ============================================================================

def prune_dominated_items(
    items: list,
    skill: str,
    location,
    character,
    relevant_stats: Set[str]
) -> list:
    """
    Remove items that are strictly dominated by another item in the same slot.
    
    An item A is dominated by item B if:
    - A and B fit the same slot
    - For every stat in relevant_stats, B's value >= A's value
    - For at least one stat, B's value > A's value
    
    This safely removes items that can never be optimal, reducing the search
    space without affecting result quality.
    
    Args:
        items: List of item objects (already filtered for relevance)
        skill: Skill name (e.g., 'smithing')
        location: Location object or None
        character: Character object
        relevant_stats: Set of stat names to compare on
        
    Returns:
        Filtered list with dominated items removed
    """
    if not items or not relevant_stats:
        return items
    
    # Group items by their effective slot (ring1/ring2 → ring, tool0-5 → tools)
    items_by_slot = {}
    for item in items:
        if not hasattr(item, 'slot'):
            continue
        slot = item.slot
        if slot not in items_by_slot:
            items_by_slot[slot] = []
        items_by_slot[slot].append(item)
    
    # Items with set-piece gated stats cannot be fairly compared in isolation
    # (their bonuses only unlock when multiple set pieces are equipped), so
    # protect them from being pruned away. They can still dominate other items.
    # Example: Treasure Hunter Hat has only 1% DR as base stats, so it looks
    # dominated by any other hat, but with 3 pieces equipped it grants +20%
    # find_collectibles — a huge bonus that only the set-aware optimizer will find.
    def _has_set_piece_gates(item):
        gated = getattr(item, 'gated_stats', None)
        return bool(gated) and 'set_pieces' in gated and bool(gated['set_pieces'])
    
    # For each slot group, find dominated items
    dominated = set()
    
    for slot, slot_items in items_by_slot.items():
        if len(slot_items) <= 1:
            continue
        
        # Pre-compute stats for all items in this slot
        item_stats = []
        for item in slot_items:
            stats = item.get_stats_for_skill(skill, location=location, character=character)
            # Extract only relevant stats, normalizing so higher is always better.
            # For stats where lower is better (steps_add, steps_percent), negate the value.
            LOWER_IS_BETTER = {'steps_add', 'steps_percent'}
            relevant = {}
            for s in relevant_stats:
                val = stats.get(s, 0.0)
                if s in LOWER_IS_BETTER:
                    val = -val  # Negate so higher is better
                relevant[s] = val
            item_stats.append((item, relevant))
        
        # Check each pair
        for i, (item_a, stats_a) in enumerate(item_stats):
            if id(item_a) in dominated:
                continue
            
            # Protect items with set-piece gated stats from being pruned away.
            # Their stats in isolation grossly understate their value because
            # set bonuses only activate when multiple pieces are equipped.
            if _has_set_piece_gates(item_a):
                continue
            
            # Number of DISTINCT other items that must dominate item_a before
            # it is safe to prune. The ring slot is filled TWICE (ring1 + ring2),
            # so an item dominated by only ONE other item is still the best
            # available pick for the SECOND ring slot once the dominator occupies
            # the first. Pruning it there is wrong.
            #
            # Bug 28230b27: farming collectibles, Collection ring dominated
            # Gold jade ring (both give find_collectibles, but Collection ring
            # also carries inventory_space + a little fine_material_finding).
            # Gold jade got pruned, Collection ring took ring1, and Fine pearl
            # ring (which survived on its fine_material_finding) was the best
            # remaining candidate for ring2 -- so the optimizer equipped a
            # useless-for-collectibles FMF ring instead of the user's owned
            # find_collectibles ring. A ring is only truly redundant when >= 2
            # OTHER items dominate it (enough to fill both ring slots).
            required_dominators = 2 if slot == 'ring' else 1
            dominator_count = 0

            for j, (item_b, stats_b) in enumerate(item_stats):
                if i == j:
                    continue
                
                # For rings: the same base item at a different quality is NOT a
                # dominator -- you can equip both copies across ring1 + ring2, so
                # a higher-quality variant doesn't make the lower one redundant.
                if slot == 'ring' and hasattr(item_a, 'uuid') and hasattr(item_b, 'uuid'):
                    if item_a.uuid == item_b.uuid:
                        continue
                    # Also check by base name (crafted items at different qualities
                    # may have different UUIDs but same base name)
                    name_a = item_a.name.split(' (')[0] if ' (' in item_a.name else item_a.name
                    name_b = item_b.name.split(' (')[0] if ' (' in item_b.name else item_b.name
                    if name_a == name_b:
                        continue
                
                # Check if item_b dominates item_a
                # B must be >= A on all stats, and > on at least one
                all_geq = True
                any_greater = False
                
                for stat in relevant_stats:
                    val_a = stats_a.get(stat, 0.0)
                    val_b = stats_b.get(stat, 0.0)
                    
                    if val_b < val_a:
                        all_geq = False
                        break
                    if val_b > val_a:
                        any_greater = True
                
                if all_geq and any_greater:
                    dominator_count += 1
                    if dominator_count >= required_dominators:
                        dominated.add(id(item_a))
                        break  # enough dominators -- item_a can be pruned
    
    # Filter out dominated items
    result = [item for item in items if id(item) not in dominated]
    return result


# ============================================================================
# KEYWORD VALIDATION
# ============================================================================

def validate_tool_keywords(tools: list, excluded_keywords: Optional[Set[str]] = None) -> bool:
    """
    Validate that tools don't share non-excluded keywords.

    Also enforces "Banned Keyword Groups" where only one item from any keyword
    in the group can be equipped (e.g., Fishing rod/net/cage/spear are mutually exclusive).

    Args:
        tools: List of tool items
        excluded_keywords: Set of keywords that can be shared (e.g., 'tool', 'light source')

    Returns:
        True if valid (no keyword conflicts), False otherwise
    """
    if excluded_keywords is None:
        from util.walkscape_constants import EXCLUDED_TOOL_KEYWORDS
        excluded_keywords = EXCLUDED_TOOL_KEYWORDS

    from util.walkscape_constants import BANNED_KEYWORD_GROUPS

    # Track keywords seen
    seen_keywords = set()
    # Track which banned groups have been used
    used_groups = set()

    for tool in tools:
        if tool is None:
            continue

        if not hasattr(tool, 'keywords'):
            continue

        # Track banned groups this specific tool occupies. A single tool can
        # carry multiple keywords from the same banned group (e.g. Spectral
        # fishing cagespear has both 'Fishing cage' and 'Fishing spear'); it
        # only counts once toward the mutual-exclusion limit.
        tool_groups = set()

        for keyword in tool.keywords:
            keyword_lower = keyword.lower()

            # Skip excluded keywords
            if keyword_lower in excluded_keywords:
                continue

            # Check banned keyword groups
            for i, group in enumerate(BANNED_KEYWORD_GROUPS):
                if keyword_lower in group:
                    if i in used_groups and i not in tool_groups:
                        # Another tool already occupies this banned group
                        return False
                    tool_groups.add(i)
                    break

            # Check for individual keyword conflict
            if keyword_lower in seen_keywords:
                return False

            seen_keywords.add(keyword_lower)

        # After processing this tool's keywords, commit its banned-group usage
        used_groups.update(tool_groups)

    return True

def validate_uuid_uniqueness(items: list, character, allow_ring_duplicates: bool = True) -> bool:
    """
    Validate that items don't exceed owned quantities.
    
    For tools: Each UUID can only be used once (strict uniqueness)
    For rings: Can use same UUID multiple times if owned quantity permits,
               but each specific item object (quality variant) can't exceed its own quantity
    For gear: Each UUID can only be used once (strict uniqueness)
    
    Args:
        items: List of item objects (can include None)
        character: Character object with inventory
        allow_ring_duplicates: If True, allow multiple rings if quantity permits
        
    Returns:
        True if valid (within owned quantities), False otherwise
    """
    # Count UUIDs used and specific item objects used
    uuid_counts = {}
    uuid_to_item = {}  # Track which item each UUID belongs to
    item_identity_counts = {}  # Track specific item objects (by identity) for quality-aware validation
    
    for item in items:
        if item is None:
            continue
        
        if not hasattr(item, 'uuid'):
            continue
        
        uuid = item.uuid
        uuid_counts[uuid] = uuid_counts.get(uuid, 0) + 1
        uuid_to_item[uuid] = item
        
        # Track by item identity (different quality variants are different objects)
        item_id = id(item)
        item_identity_counts[item_id] = item_identity_counts.get(item_id, 0) + 1
    
    # Build UUID cache if not already cached on character (performance optimization)
    if not hasattr(character, '_uuid_cache'):
        character._uuid_cache = {}
        for inv_item, qty in character.items.items():
            if hasattr(inv_item, 'uuid'):
                uuid = inv_item.uuid
                character._uuid_cache[uuid] = character._uuid_cache.get(uuid, 0) + qty
    
    # Check against owned quantities using cache
    for uuid, count_used in uuid_counts.items():
        owned_qty = character._uuid_cache.get(uuid, 0)
        item = uuid_to_item[uuid]
        
        # For tools: strict uniqueness (can only use each UUID once)
        if hasattr(item, 'slot') and item.slot == 'tools':
            if count_used > 1:
                return False
        # For rings: allow duplicates if owned quantity permits
        elif hasattr(item, 'slot') and item.slot == 'ring' and allow_ring_duplicates:
            if count_used > owned_qty:
                return False
        # For all other gear: strict uniqueness (can only use each UUID once)
        else:
            if count_used > 1:
                return False
    
    # Additional check: verify per-item-object counts don't exceed per-object owned quantities
    # This prevents using 2x Excellent when you only own 1 Excellent + 1 Good
    for item in items:
        if item is None or not hasattr(item, 'uuid'):
            continue
        if not (hasattr(item, 'slot') and item.slot == 'ring' and allow_ring_duplicates):
            continue
        
        item_id = id(item)
        count_used = item_identity_counts.get(item_id, 0)
        if count_used <= 1:
            continue
        
        # Check how many of this specific item object the character owns
        item_owned = 0
        for inv_item, qty in character.items.items():
            if inv_item is item:
                item_owned = qty
                break
        
        if count_used > max(item_owned, 1):
            return False
    
    return True

# ============================================================================
# STAT CACHING
# ============================================================================

class StatCache:
    """Cache for item stats to avoid repeated calculations."""
    
    def __init__(self):
        self._cache = {}
    
    def get(self, item, skill: str, location) -> Optional[Dict[str, float]]:
        """Get cached stats or None if not cached."""
        cache_key = (id(item), skill, location.name if location else None)
        return self._cache.get(cache_key)
    
    def set(self, item, skill: str, location, stats: Dict[str, float]):
        """Cache stats for an item."""
        cache_key = (id(item), skill, location.name if location else None)
        self._cache[cache_key] = stats
    
    def get_or_compute(self, item, skill: str, location, character) -> Dict[str, float]:
        """Get cached stats or compute and cache them."""
        cached = self.get(item, skill, location)
        if cached is not None:
            return cached
        
        stats = item.get_stats_for_skill(skill, location=location, character=character)
        self.set(item, skill, location, stats)
        return stats
    
    def clear(self):
        """Clear the cache."""
        self._cache.clear()

# ============================================================================
# GEARSET VALIDATION
# ============================================================================

def is_gearset_complete(gearset_dict: dict, character) -> bool:
    """
    Check if a gearset has all required slots filled.
    
    Args:
        gearset_dict: Dictionary mapping slot names to items
        character: Character object (for tool slot count)
        
    Returns:
        True if all slots filled, False otherwise
    """
    # Required gear slots (always 12)
    required_gear_slots = [
        'head', 'cape', 'neck', 'chest', 'hands', 'legs', 'feet',
        'ring1', 'ring2', 'back', 'primary', 'secondary'
    ]
    
    # Check gear slots
    for slot in required_gear_slots:
        if slot not in gearset_dict or gearset_dict[slot] is None:
            return False
    
    # Check tool slots (use cached value from character for performance)
    max_tool_slots = character.get_tool_slots()
    
    for i in range(max_tool_slots):
        slot = f'tool{i}'
        if slot not in gearset_dict or gearset_dict[slot] is None:
            return False
    
    return True

def item_satisfies_required_keyword(item, keyword, activity) -> bool:
    """
    True if `item` counts toward an activity's required `keyword`.

    Normally this is just "does the item carry the keyword". But if the activity
    has a keyword_level_requirement for that keyword (e.g. Mine violite ore needs
    a Pickaxe that itself requires Mining 60), the item ALSO has to meet that
    minimum skill-level requirement to count. A Spectral pickaxe (Mining 55) has
    the 'pickaxe' keyword but does NOT satisfy a Mining-60 requirement, so it must
    not be counted as fulfilling the requirement during gear selection.
    """
    from util.walkscape_constants import item_has_keyword
    if not item_has_keyword(item, keyword):
        return False
    reqs = getattr(activity, 'requirements', {}) or {}
    kw_lower = str(keyword).lower()
    for r in reqs.get('keyword_level_requirements', []):
        if str(r.get('keyword', '')).lower() != kw_lower:
            continue
        req_skill = str(r.get('skill', '')).lower()
        req_level = r.get('level', 0)
        meets = any(
            x.get('type') == 'skill'
            and str(x.get('skill', '')).lower() == req_skill
            and x.get('level', 0) >= req_level
            for x in (getattr(item, 'requirements', []) or [])
        )
        if not meets:
            return False
    return True


def gearset_meets_keyword_level_requirements(items, activity) -> bool:
    """
    Check tool-keyword minimum-skill-level requirements for an activity.

    Some activities have an "Other Requirement" such as:
        "Have a Pickaxe equipped that requires at least Mining level 60."
    This gates on the equip-level (tier) of the equipped tool, not the
    character's own skill level. For each requirement {keyword, skill, level},
    at least one equipped item must (a) carry that keyword and (b) have its own
    skill requirement for `skill` be >= `level`.

    Args:
        items: Iterable of equipped item instances (None entries allowed).
        activity: Activity object with a `.requirements` dict that may contain
                  a 'keyword_level_requirements' list.

    Returns:
        True if all keyword-level requirements are satisfied (or none exist).
    """
    reqs = getattr(activity, 'requirements', {}) or {}
    keyword_level_requirements = reqs.get('keyword_level_requirements', [])
    if not keyword_level_requirements:
        return True

    for req in keyword_level_requirements:
        req_kw = str(req.get('keyword', '')).lower()
        req_skill = str(req.get('skill', '')).lower()
        req_level = req.get('level', 0)
        if not req_kw:
            continue
        satisfied = False
        for item in items:
            if not item or not getattr(item, 'keywords', None):
                continue
            if not any(req_kw == str(kw).lower() for kw in item.keywords):
                continue
            for r in (getattr(item, 'requirements', []) or []):
                if (r.get('type') == 'skill'
                        and str(r.get('skill', '')).lower() == req_skill
                        and r.get('level', 0) >= req_level):
                    satisfied = True
                    break
            if satisfied:
                break
        if not satisfied:
            return False
    return True

def meets_activity_requirements(gearset_dict: dict, activity, character, input_item=None) -> bool:
    """
    Check if a gearset meets activity requirements.
    
    Uses the unified keyword_counts structure where all gear requirements
    are stored as {keyword: count} pairs.
    
    Args:
        gearset_dict: Dictionary mapping slot names to items
        activity: Activity object with requirements
        character: Character object
        input_item: Optional input item (e.g. arrows) that satisfies keyword requirements
        
    Returns:
        True if requirements met, False otherwise
    """
    # Check skill requirements
    for skill, required_level in activity.skill_requirements.items():
        char_level = character.get_skill_level(skill.lower())
        if char_level < required_level:
            return False
    
    # Check reputation requirements
    for faction, required_amount in activity.requirements.get("reputation", {}).items():
        char_rep = character.reputation.get(faction, 0)
        if char_rep < required_amount:
            return False
    
    # Check achievement points
    required_ap = activity.requirements.get("achievement_points", 0)
    if required_ap > 0:
        from util.walkscape_globals import ACHIEVEMENT_POINTS
        if int(ACHIEVEMENT_POINTS) < required_ap:
            return False
    
    # Check all keyword requirements from keyword_counts
    items = [item for item in gearset_dict.values() if item is not None]
    keyword_counts = activity.requirements.get("keyword_counts", {})
    
    # Check specific item requirements (e.g., "Have item Spectral saw equipped")
    item_requirements = activity.requirements.get("item_requirements", [])
    if item_requirements:
        # Equipped crafted/quality items render their name with a quality
        # suffix, e.g. "Spectral saw (Normal)". Match the required base name
        # against BOTH the full name and the suffix-stripped base name so a
        # required item like "Spectral saw" is satisfied by any quality.
        equipped_names = set()
        for item in items:
            nm = getattr(item, 'name', None)
            if not nm:
                continue
            nm = nm.lower()
            equipped_names.add(nm)
            base = re.sub(r'\s*\([^)]*\)\s*$', '', nm).strip()
            if base:
                equipped_names.add(base)
        for required_name in item_requirements:
            if required_name.lower() not in equipped_names:
                return False
    
    # Build set of keywords satisfied by the input item (e.g. arrows for hunting)
    input_item_keywords = set()
    if input_item and hasattr(input_item, 'keywords'):
        input_item_keywords = {kw.lower() for kw in input_item.keywords}
    elif not input_item and hasattr(activity, 'input_items') and activity.input_items:
        # No input selected — pre-satisfy keywords from activity's input_items definitions
        for ii in activity.input_items:
            if getattr(ii, 'type', '') == 'keyword':
                kw = getattr(ii, 'reference', '').lower()
                if kw:
                    input_item_keywords.add(kw)
    
    for keyword, required_count in keyword_counts.items():
        if required_count <= 0:
            continue
        
        # Count items with this keyword
        count = sum(
            1 for item in items
            if hasattr(item, "keywords") and
            any(keyword.lower() in kw.lower() for kw in item.keywords)
        )
        
        # Input item (e.g. arrows) can satisfy keyword requirements
        if count < required_count and keyword.lower() in input_item_keywords:
            count += 1
        
        if count < required_count:
            return False
    
    # Check tool keyword minimum-skill-level requirements (e.g. a pickaxe that
    # itself requires at least Mining level 60). Enforced in addition to the
    # plain keyword_counts "have a pickaxe" check above.
    if not gearset_meets_keyword_level_requirements(items, activity):
        return False
    
    return True


# ============================================================================
# ACTIVITY OPTIMIZATION
# ============================================================================

def optimize_activity(
    activity,
    character,
    optimize_for='xp_per_step',  # 'xp_per_step', 'steps_per_action', 'steps_per_reward'
    target_item=None,
    max_iterations=100,
    verbose=False
):
    """
    Optimize gearset for an activity using greedy + local search.
    
    This is the shared optimization logic used by all activity optimizers.
    
    Args:
        activity: Activity object to optimize for
        character: Character object
        optimize_for: What to optimize ('xp_per_step', 'steps_per_action', 'steps_per_reward')
        target_item: Optional specific item to optimize drop rate for
        max_iterations: Max local search iterations
        verbose: Print debug output
    
    Returns:
        Tuple of (best_gearset_dict, metrics_dict, iterations)
    """
    from util.activity_metrics import calculate_activity_metrics
    from util.gearset_utils import aggregate_gearset_stats, encode_gearset
    from util.greedy_local_search import optimize_gearset_greedy_local_search, create_multi_level_comparator, prepare_items_by_slot
    from util.walkscape_constants import character_level_from_steps, tool_slots_for_level
    
    # Get tool slots
    total_steps = sum(character.skills.values())
    char_level = character_level_from_steps(total_steps)
    max_tool_slots = tool_slots_for_level(char_level)
    
    # Define slots
    gear_slots = ['head', 'cape', 'neck', 'chest', 'hands', 'legs', 'feet',
                  'ring1', 'ring2', 'back', 'primary', 'secondary']
    tool_slots = [f'tool{i}' for i in range(max_tool_slots)]
    all_slots = gear_slots + tool_slots
    
    # Get items
    all_items = []
    for item, qty in character.items.items():
        if qty == 0 or not hasattr(item, 'slot'):
            continue
        if hasattr(item, 'is_unlocked'):
            if not item.is_unlocked(character, ignore_gear_requirements=True):
                continue
        all_items.append(item)
    
    all_items = filter_items_by_quality(all_items, keep_highest_only=True)
    
    # Prepare items by slot
    items_by_slot = {}
    for slot in all_slots:
        items_by_slot[slot] = []
        for item in all_items:
            if slot.startswith('tool') and item.slot == 'tools':
                items_by_slot[slot].append(item)
            elif slot.startswith('ring') and item.slot == 'ring':
                items_by_slot[slot].append(item)
            elif item.slot == slot:
                items_by_slot[slot].append(item)
        items_by_slot[slot].append(None)
    
    # Scoring function
    def score_function(gearset_dict):
        items = [item for item in gearset_dict.values() if item is not None]
        
        skill = activity.primary_skill.lower()
        location = activity.locations[0] if activity.locations else None
        
        total_stats = aggregate_gearset_stats(
            items=items,
            skill=skill,
            location=location,
            character=character,
            include_level_bonus=True,
            include_collectibles=True,
            activity=activity
        )
        
        metrics = calculate_activity_metrics(
            base_steps=activity.base_steps,
            base_xp=activity.base_xp,
            max_efficiency=activity.max_efficiency,
            work_efficiency=total_stats.get('work_efficiency', 0.0),
            double_action=total_stats.get('double_action', 0.0),
            double_rewards=total_stats.get('double_rewards', 0.0),
            steps_add=int(total_stats.get('steps_add', 0)),
            steps_percent=total_stats.get('steps_percent', 0.0)
        )
        
        # Return score based on optimization goal
        if optimize_for == 'xp_per_step':
            return (-metrics['primary_xp_per_step'],)  # Maximize = minimize negative
        elif optimize_for == 'steps_per_action':
            return (metrics['expected_steps_per_action'],)
        elif optimize_for == 'steps_per_reward':
            return (metrics['steps_per_reward_roll'],)
        else:
            return (metrics['expected_steps_per_action'],)
    
    # Validation function
    def validate_function(gearset_dict):
        # Get tools
        tools = [gearset_dict.get(f'tool{i}') for i in range(max_tool_slots)]
        
        # Check keyword uniqueness
        if not validate_tool_keywords(tools):
            return False
        
        # Check UUID uniqueness
        if not validate_uuid_uniqueness(list(gearset_dict.values()), character):
            return False
        
        # Check activity requirements (diving gear, light sources, etc.)
        if not meets_activity_requirements(gearset_dict, activity, character):
            return False
        
        return True
    
    # Optimize
    is_better = create_multi_level_comparator(primary_minimize=True)
    
    best_gearset, best_scores, iterations = optimize_gearset_greedy_local_search(
        all_items=items_by_slot,
        character=character,
        score_function=score_function,
        is_better=is_better,
        validate_function=validate_function,
        max_iterations=max_iterations,
        verbose=verbose
    )
    
    # Calculate final metrics
    items = [item for item in best_gearset.values() if item is not None]
    skill = activity.primary_skill.lower()
    location = activity.locations[0] if activity.locations else None
    
    total_stats = aggregate_gearset_stats(
        items=items,
        skill=skill,
        location=location,
        character=character,
        include_level_bonus=True,
        include_collectibles=True,
        activity=activity
    )
    
    metrics = calculate_activity_metrics(
        base_steps=activity.base_steps,
        base_xp=activity.base_xp,
        max_efficiency=activity.max_efficiency,
        work_efficiency=total_stats.get('work_efficiency', 0.0),
        double_action=total_stats.get('double_action', 0.0),
        double_rewards=total_stats.get('double_rewards', 0.0),
        steps_add=int(total_stats.get('steps_add', 0)),
        steps_percent=total_stats.get('steps_percent', 0.0)
    )
    
    return best_gearset, metrics, iterations
