#!/usr/bin/env python3
"""
Sea-shell-value helpers used by the optimizer and the UI to:
  - Look up shell_value / fine_shell_value for a single drop entry.
  - Aggregate expected shells/step (and steps/shell) for an activity given a
    stats dict and the drop_rates dict produced by
    Activity.get_expected_drop_rate.

Provides one synthetic target used by the gearset optimizer:

  - 'cat:sea_shells'  - total sea shells earned per step, including:
      1. Direct Material.SEA_SHELL drops from the activity's drop tables
         (or via ItemFindingCategory.SEA_SHELLS expansion from gear).
      2. Fine sea shell drops, folded back into base shells via the
         Material.SEA_SHELL_FINE.special_sell value (10 normals per fine).
      3. Coral chest, Sunken chest, Chest of Syrenthia drops — any
         chest whose contents include sea shells. The expected
         shells-per-chest value is computed dynamically at module load
         and stored in CHEST_SHELL_VALUES.

The 'cat:sea_shells' synthetic mirrors the existing 'cat:coins' synthetic
in util/coin_value.py: the optimizer's _compute_spr_for_target reads the
synthetic value from drop_rates after compute_shell_targets_for_activity
injects it.
"""

from typing import Dict


# ============================================================================
# CHEST SHELL VALUES (computed at module load)
# ============================================================================

# Constants mirroring chest_coin_value.py's chest-shell calculation:
#   - Each chest opens ROLLS_PER_CHEST times.
#   - Each material drop has a 1% chance of being a fine variant.
#   - A fine sea shell sells for 10 normal sea shells (per
#     Material.SEA_SHELL_FINE.special_sell).
#
# Expected shells per chest =
#   ROLLS × P(shell drop per roll) × E[qty per drop] × (0.99 + 0.01 × 10)
#                                                       ^^^^^^^^^^^^^^^^^
#                                                       fine fold factor
_FINE_DROP_RATE = 0.01
_FINE_SHELL_MULTIPLIER = 10  # Material.SEA_SHELL_FINE.special_sell qty
_SHELL_FINE_FACTOR = (1.0 - _FINE_DROP_RATE) * 1 + _FINE_DROP_RATE * _FINE_SHELL_MULTIPLIER
# = 0.99 + 0.10 = 1.09

CHEST_SHELL_VALUES: Dict[str, float] = {}


def _compute_chest_shell_values() -> Dict[str, float]:
    """Scan all Container.* drop tables and build {ref: shells_per_chest}.

    For each container, iterate every drop entry; if the drop is
    Material.SEA_SHELL, contribute its expected shells (chance × avg qty
    × ROLLS × fine factor) to the chest's total. Containers with zero
    sea shell content are omitted from the result.

    Run at module load so the lookup is constant-time at runtime and
    new shell-bearing chests added to the catalog get picked up
    automatically.
    """
    out: Dict[str, float] = {}
    try:
        from util.autogenerated.containers import Container, ROLLS_PER_CHEST
    except ImportError:
        return out

    for attr in dir(Container):
        if attr.startswith('_'):
            continue
        chest = getattr(Container, attr, None)
        if chest is None or not hasattr(chest, 'get_all_drops'):
            continue

        try:
            drops = chest.get_all_drops()
        except Exception:
            continue

        shells_per_chest = 0.0
        for drop in drops:
            if drop is None or drop.item_ref != 'Material.SEA_SHELL':
                continue
            chance = float(drop.chance_percent or 0)
            if chance <= 0:
                continue
            avg_qty = drop.quantity.average if drop.quantity else 0
            if not avg_qty:
                continue
            shells_per_roll = (chance / 100.0) * float(avg_qty) * _SHELL_FINE_FACTOR
            shells_per_chest += shells_per_roll * ROLLS_PER_CHEST

        if shells_per_chest > 0:
            out[f'Container.{attr}'] = shells_per_chest

    return out


CHEST_SHELL_VALUES = _compute_chest_shell_values()


# ============================================================================
# DROP SHELL VALUE LOOKUP
# ============================================================================

def get_drop_shell_value(drop) -> float:
    """Return the expected sea shell yield for a single DropEntry.

    Per drop occurrence (i.e., the value the caller will multiply by
    `items_per_step` or similar):
      - Material.SEA_SHELL              → 1.0
      - Material.SEA_SHELL_FINE         → 10.0 (fine sells for 10 normals)
      - Container.* with shells inside  → CHEST_SHELL_VALUES[ref]
      - everything else                 → 0.0

    Returns 0 for non-shell drops or unresolvable refs.
    """
    if drop is None or drop.item_ref is None:
        return 0.0
    ref = drop.item_ref
    if ref == 'Material.SEA_SHELL':
        return 1.0
    if ref == 'Material.SEA_SHELL_FINE':
        return float(_FINE_SHELL_MULTIPLIER)
    if ref.startswith('Container.'):
        return float(CHEST_SHELL_VALUES.get(ref, 0))
    return 0.0


def get_drop_fine_shell_value(drop) -> float:
    """Return the shell yield of the fine variant of a base drop.

    Mirrors get_drop_fine_coin_value: when the base drop is
    Material.SEA_SHELL the fine variant (Material.SEA_SHELL_FINE) yields
    10 base shells via special_sell. Returns 0 for any other drop —
    chests don't have a "fine variant"; their internal fine shells are
    already folded into CHEST_SHELL_VALUES at module load.
    """
    if drop is None or not drop.item_ref:
        return 0.0
    if drop.item_ref == 'Material.SEA_SHELL':
        return float(_FINE_SHELL_MULTIPLIER)
    return 0.0


def is_shell_chest_drop(drop) -> bool:
    """Return True when the drop's item_ref is a chest that contains shells."""
    return bool(drop and drop.item_ref and drop.item_ref in CHEST_SHELL_VALUES)


# ============================================================================
# SHELL AGGREGATION FOR ACTIVITIES
# ============================================================================

# The synthetic target key the optimizer and worker both understand.
SHELL_TARGET = 'cat:sea_shells'


def _collect_activity_drops_with_equipment(activity, stats, collectible_stats=None,
                                           consumable_stats=None):
    """Rebuild the full drops list that Activity.get_expected_drop_rate iterates.

    Mirrors util.coin_value._collect_activity_drops_with_equipment so the
    shell aggregator picks up every drop the activity scorer saw —
    main + secondary tables plus IF-expanded equipment drops (from
    gear, collectibles, and consumables).
    """
    drops = list(activity.drop_table) + list(activity.secondary_drop_table)

    try:
        from util.autogenerated.item_finding import ItemFindingCategory
    except ImportError:
        return drops

    def _extend_from(stats_dict, value_in_percent: bool):
        if not stats_dict:
            return
        for stat_name, stat_value in stats_dict.items():
            if not stat_name.startswith('ItemFindingCategory.'):
                continue
            category_const = stat_name.split('.', 1)[1]
            if not hasattr(ItemFindingCategory, category_const):
                continue
            category = getattr(ItemFindingCategory, category_const)
            base_chance = stat_value if value_in_percent else stat_value * 100.0
            drops.extend(category.expand_with_chance(base_chance))

    _extend_from(stats, value_in_percent=True)
    _extend_from(collectible_stats, value_in_percent=False)
    _extend_from(consumable_stats, value_in_percent=False)
    return drops


def compute_shell_targets_for_activity(activity, drop_rates, stats=None,
                                       collectible_stats=None,
                                       consumable_stats=None) -> Dict[str, float]:
    """Compute the synthetic steps-per-shell target for an activity.

    Args:
        activity: The Activity being optimized.
        drop_rates: {item_name: steps_per_item} dict returned from
            Activity.get_expected_drop_rate(target_item=None).
        stats / collectible_stats / consumable_stats: same stats dicts the
            drop_rates were computed under; required to re-expand IF
            equipment drops so their shell contribution is counted.

    Returns:
        Dict suitable for updating drop_rates: {'cat:sea_shells': spr}.
        Value is float('inf') when the gearset produces no shells at all
        — matching the "no target" sentinel elsewhere in the scorer.
    """
    if not drop_rates:
        return {SHELL_TARGET: float('inf')}

    all_drops = _collect_activity_drops_with_equipment(
        activity, stats or {}, collectible_stats, consumable_stats,
    )

    shells_per_step = 0.0

    # Dedupe by item_name. drop_rates already harmonic-mean-merges the
    # per-source rates for items that appear in multiple drop tables
    # (main + IF expansion etc.) — see the same dedupe in
    # compute_coin_targets_for_activity for the rationale.
    seen_names = set()
    for drop in all_drops:
        if drop.item_name == 'Nothing':
            continue
        if drop.item_name in seen_names:
            continue
        seen_names.add(drop.item_name)

        # Base contribution.
        steps = drop_rates.get(drop.item_name)
        if steps and steps > 0 and steps != float('inf'):
            items_per_step = 1.0 / steps
            shell_value = get_drop_shell_value(drop)
            if shell_value > 0:
                shells_per_step += items_per_step * shell_value

        # Fine-variant contribution (only meaningful for Material.SEA_SHELL
        # base drops — chests don't have a "(Fine)" key in drop_rates,
        # their internal fine bonus is already folded into
        # CHEST_SHELL_VALUES).
        fine_key = f"{drop.item_name} (Fine)"
        fine_steps = drop_rates.get(fine_key)
        if fine_steps and fine_steps > 0 and fine_steps != float('inf'):
            fine_shell_value = get_drop_fine_shell_value(drop)
            if fine_shell_value > 0:
                fine_items_per_step = 1.0 / fine_steps
                shells_per_step += fine_items_per_step * fine_shell_value

    if shells_per_step <= 0:
        return {SHELL_TARGET: float('inf')}
    return {SHELL_TARGET: 1.0 / shells_per_step}


# ============================================================================
# SHELL AGGREGATION FOR RECIPES
# ============================================================================

def compute_shells_per_craft_for_recipe(recipe, total_stats=None) -> float:
    """Compute expected sea shell yield per craft for a recipe.

    Mirrors compute_coins_per_craft_for_recipe but only counts shell
    contributions: the primary output is included only if it's
    Material.SEA_SHELL/SEA_SHELL_FINE itself (rare/unlikely), and side
    drops are scanned for sea shells, fine sea shells, and shell-bearing
    chests.

    Args:
        recipe: Recipe object (has output_item, quantity, drop_table).
        total_stats: Aggregated stat dict. chest_finding multiplies the
            chest drop chance, matching the existing cat:chests scoring.

    Returns:
        Expected shells per craft (float). Zero when the recipe
        produces no shells.
    """
    total_stats = total_stats or {}
    chest_finding = float(total_stats.get('chest_finding', 0.0) or 0.0)
    chest_rate_multiplier = 1.0 + chest_finding

    shells_per_craft = 0.0

    # 1) Primary output. Only count if it's a sea shell ref directly.
    output_obj = None
    try:
        output_obj = recipe.get_output_item_object()
    except Exception:
        output_obj = None
    if output_obj is not None:
        output_qty = int(getattr(recipe, 'quantity', 1) or 1)
        # MaterialInstance has a `.name` we can compare against the known refs.
        out_name = getattr(output_obj, 'name', '')
        if out_name == 'Sea shell':
            shells_per_craft += float(output_qty)
        elif out_name == 'Sea shell (Fine)':
            shells_per_craft += float(output_qty) * _FINE_SHELL_MULTIPLIER

    # 2) Side + chest drops from recipe.drop_table.
    for drop in (getattr(recipe, 'drop_table', None) or []):
        if not isinstance(drop, dict):
            continue
        chance_percent = float(drop.get('chance_percent') or 0.0)
        multi_roll_count = int(drop.get('multi_roll_count') or 1)
        qty_min = drop.get('quantity_min', drop.get('quantity', 0)) or 0
        qty_max = drop.get('quantity_max', drop.get('quantity', qty_min)) or qty_min
        try:
            avg_qty = (float(qty_min) + float(qty_max)) / 2.0
        except (TypeError, ValueError):
            avg_qty = 0.0

        ref = drop.get('item_ref') or ''

        if ref.startswith('Container.') and ref in CHEST_SHELL_VALUES:
            chest_value = CHEST_SHELL_VALUES[ref]
            effective_rate = (chance_percent / 100.0) * chest_rate_multiplier
            shells_per_craft += effective_rate * chest_value
            continue

        if ref == 'Material.SEA_SHELL':
            # Side drop of base shells. Use the multi-roll formula from
            # coin_value._expected_drops_per_craft.
            if chance_percent <= 0 or avg_qty <= 0:
                continue
            c = max(0.0, min(100.0, chance_percent)) / 100.0
            if multi_roll_count and multi_roll_count > 1:
                per_roll = 1.0 - (1.0 - c) ** (1.0 / multi_roll_count)
                expected_drops = multi_roll_count * per_roll * avg_qty
            else:
                expected_drops = c * avg_qty
            shells_per_craft += expected_drops
            continue

        if ref == 'Material.SEA_SHELL_FINE':
            if chance_percent <= 0 or avg_qty <= 0:
                continue
            c = max(0.0, min(100.0, chance_percent)) / 100.0
            if multi_roll_count and multi_roll_count > 1:
                per_roll = 1.0 - (1.0 - c) ** (1.0 / multi_roll_count)
                expected_drops = multi_roll_count * per_roll * avg_qty
            else:
                expected_drops = c * avg_qty
            shells_per_craft += expected_drops * _FINE_SHELL_MULTIPLIER
            continue

    return shells_per_craft
