#!/usr/bin/env python3
"""
StatsMixin - Shared functionality for items with skill-based, location-aware stats.

This mixin provides:
- get_stats_for_skill(): Get stats filtered by skill and location
- attr(): Get stats in a standard format
- _location_matches(): Check if location matches
- _add_location_stats(): Add stats filtered by location

Used by: Equipment, Collectibles, Consumables, and future stat-bearing items.
"""

from __future__ import annotations
from collections import OrderedDict
from typing import Dict, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from util.walkscape_constants import SkillInstance, LocationInfo

# Bounded LRU cache for get_stats_for_skill results. The key includes id(self),
# but the optimizer creates THROWAWAY instances while scoring -- achievement
# ItemInstances (e.g. Omni-tool AP variants, see equipment.py ItemInstance),
# quality-resolved copies, etc. -- each with a fresh id() that gets cached and
# then never reused or evicted (id() is even recycled after GC). In one
# chests_recipes optimize this grew to ~10.5M entries / ~1 GB and OOMed the
# local (Pyodide ~2 GB WASM) worker -> recipes silently skipped, run hung on
# "Finishing" (bug 7091473e). Cap the cache and LRU-evict the oldest: the
# few-thousand stable catalog entries stay hot (real hits), while ephemeral
# ids evict harmlessly (they were never going to be queried again).
_STATS_CACHE = OrderedDict()
_STATS_CACHE_MAX = 100_000

# Cache mapping a location slug (e.g. 'bilgemont_port') -> LocationInfo.
# The UI sends selectedLocation as a slug (loc.location.id), but
# Location.by_name only matches display names ('Bilgemont Port'). Without slug
# resolution, a location-scoped stat (e.g. {'global': {'gdte': {...}}}) is
# silently dropped whenever the location is passed as a slug, so a strictly
# better location-scoped tool never surfaces as a slot alternative. See bug
# 87e0159a (Seth's swamp compass not suggested for steps-per-chest).
_LOCATION_SLUG_CACHE = {}


def _location_slug(name: str) -> str:
    """Canonical location slug, matching the id the UI sends as selectedLocation.

    Mirrors the server-side transform used to build location ids (see ui/app.py
    loc.name.lower().replace(' ', '_').replace("'", '')).
    """
    return name.lower().replace(' ', '_').replace("'", '')


def _resolve_location_slug(slug: str):
    """Resolve a location slug ('bilgemont_port') to a LocationInfo, or None.

    Falls back to None for unknown slugs so callers can use direct equality.
    """
    if not slug:
        return None
    if not _LOCATION_SLUG_CACHE:
        from util.autogenerated.locations import Location as _Location, LocationInfo as _LocationInfo
        for attr_name in dir(_Location):
            if attr_name.startswith('_'):
                continue
            attr = getattr(_Location, attr_name)
            if isinstance(attr, _LocationInfo):
                _LOCATION_SLUG_CACHE[_location_slug(attr.name)] = attr
    return _LOCATION_SLUG_CACHE.get(slug.lower())


class StatsMixin: 
    """
    Mixin class providing skill-based, location-aware stat functionality.
    
    Classes using this mixin must have:
    - self._stats: Dict with nested structure {skill: {location: {stat: value}}}
    - self.name: str (for error messages)
    - self.gated_stats: Dict (optional) with supported gates:
        - 'skill_level': {skill: {threshold: {skill: {location: {stat: value}}}}}
        - 'activity_completion': {activity: {threshold: {skill: {location: {stat: value}}}}}
        - 'activity': {activity_name: {skill: {location: {stat: value}}}} - stats only while doing activity
        - 'reputation': {faction: {threshold: {skill: {location: {stat: value}}}}}
        - 'set_pieces': {set_name: {threshold: {skill: {location: {stat: value}}}}}
        - 'item_ownership': {item_name: {skill: {location: {stat: value}}}} - stats when owning another item
        - 'travel_steps': {threshold: {skill: {location: {stat: value}}}} - stats gated by total travel steps
    - self.requirements: List (optional, for unlock requirements like reputation, skill level)
    
    Note: 'activity' gates are NOT included in normal stat calculations - they're for
    activity-specific bonuses that only apply when doing that specific activity.
    """
    
    def is_unlocked(self, character=None, ignore_gear_requirements=False) -> bool:
        """
        Check if this item/service is unlocked for the character.
        
        Args:
            character: Character object (optional, will auto-load from my_config if not provided)
            ignore_gear_requirements: If True, skip diving_gear checks (useful for optimization)
        
        Returns:
            True if unlocked, False otherwise
        """
        if hasattr(self, 'has_instance'):
            self = self.get_instance(
                character=character, 
                ignore_gear_requirements=ignore_gear_requirements
            )

        if not hasattr(self, 'requirements') or not self.requirements:
            return True  # No requirements means always unlocked
        
        # Auto-load character if not provided
        if character is None:
            try:
                from my_config import get_character
                character = get_character()
            except Exception:
                return True  # If can't load character, assume unlocked
        
        for req in self.requirements:
            req_type = req.get('type')
            
            if req_type == 'reputation':
                # Check faction reputation
                faction = req.get('faction')
                required_amount = req.get('amount', 0)
                if character.reputation.get(faction, 0) < required_amount:
                    return False
            
            elif req_type == 'skill':
                # Check skill level
                skill = req.get('skill')
                required_level = req.get('level', 0)
                if character.get_skill_level(skill) < required_level:
                    return False
            
            elif req_type == 'character_level':
                # Check character level
                required_level = req.get('level', 0)
                try:
                    from util.walkscape_constants import character_level_from_steps
                    char_level = character_level_from_steps(character.total_steps)
                    if char_level < required_level:
                        return False
                except Exception:
                    # If can't determine character level, assume requirement is met
                    pass
            
            elif req_type == 'diving_gear':
                # Skip if ignoring gear requirements
                if ignore_gear_requirements:
                    continue
                
                # Check diving gear count
                required_count = req.get('count', 3)
                diving_count = sum(
                    1 for item in character.gear.values() 
                    if item and hasattr(item, 'keywords') and 
                    any('diving gear' in kw.lower() for kw in item.keywords)
                )
                if diving_count < required_count:
                    return False
            
            elif req_type == 'achievement_points':
                # Check achievement points
                required_amount = req.get('amount', 0)
                
                # Get character's achievement points
                char_ap = 0
                if hasattr(character, 'achievement_points'):
                    char_ap = character.achievement_points
                else:
                    # Fall back to global AP
                    try:
                        import util.walkscape_globals
                        char_ap = int(util.walkscape_globals.ACHIEVEMENT_POINTS)
                    except (ImportError, AttributeError, ValueError):
                        pass  # If can't check, assume requirement is NOT met
                
                if char_ap < required_amount:
                    return False
            
            elif req_type == 'activity_completion':
                # Check if activity has been completed required number of times
                activity = req.get('activity')
                required_completions = req.get('completions', 0)
                
                # Normalize to build custom stat ID: activityname
                activity_normalized = activity.lower().replace(' ', '_').replace("'", "")
                
                # Check if character has custom_stats set (not None)
                has_completed = False
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    # Character has custom_stats from UI - use it exclusively (don't fall back)
                    # The custom_stat_id for unlock requirements is just the activity name
                    # If key not in dict, it means False (user hasn't toggled it)
                    has_completed = character.custom_stats.get(activity_normalized, False)
                else:
                    # Character doesn't have custom_stats (None or missing) - fall back to my_config
                    try:
                        import my_config
                        activity_upper = activity.upper().replace(" ", "_").replace("'", "")
                        var_name = f"{activity_upper}_{required_completions}_COMPLETIONS"
                        has_completed = getattr(my_config, var_name, False)
                    except (ImportError, AttributeError):
                        pass  # If can't check, assume requirement is NOT met
                
                if not has_completed:
                    return False
            
            elif req_type == 'access':
                # Check region access
                region = req.get('region', '').lower()
                
                # Normalize region name for custom_stats lookup
                region_normalized = region.replace(' ', '_').replace("'", "")
                custom_stat_id = f"access_{region_normalized}"
                
                # Check if character has custom_stats set (not None)
                has_access = True  # Default to True (accessible)
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    # Character has custom_stats from UI - use it exclusively (don't fall back)
                    # If key not in dict, default to True (accessible unless explicitly set to False)
                    has_access = character.custom_stats.get(custom_stat_id, True)
                else:
                    # Character doesn't have custom_stats (None or missing) - fall back to my_config
                    try:
                        import my_config
                        # Check for ACCESS_REGIONNAME variable (e.g., ACCESS_SYRENTHIA)
                        access_var = f'ACCESS_{region.upper()}'
                        has_access = getattr(my_config, access_var, True)  # Default to True if not specified
                    except (ImportError, AttributeError):
                        # If can't check, assume accessible
                        pass
                
                if not has_access:
                    return False
            
            elif req_type == 'category_level_percent':
                # Check percentage of max category level
                # e.g., "Have 10% towards the maximum Gathering level"
                # Max = num_skills_in_category * 99, need total >= percent/100 * max
                import math
                category = req.get('category', '').lower()
                percent = req.get('percent', 0)
                
                CATEGORY_SKILLS = {
                    'gathering': ['fishing', 'foraging', 'hunting', 'mining', 'woodcutting'],
                    'artisan': ['carpentry', 'cooking', 'crafting', 'smithing', 'tailoring', 'trinketry'],
                    'utility': ['agility'],
                }
                
                skills = CATEGORY_SKILLS.get(category, [])
                if not skills:
                    continue  # Unknown category, skip
                
                max_level = len(skills) * 99
                required_total = math.ceil(max_level * percent / 100)
                actual_total = sum(character.get_skill_level(s) for s in skills)
                
                if actual_total < required_total:
                    return False
        
        return True

    def get_missing_requirements(self, character=None, ignore_gear_requirements=False):
        """
        Return a list of human-readable strings describing unmet requirements.
        
        Args:
            character: Character object (optional)
            ignore_gear_requirements: If True, skip diving_gear checks
        
        Returns:
            List of strings like ["Syrenthia reputation 100 (have 42)", "Fishing level 50 (have 32)"]
            Empty list if all requirements are met.
        """
        if hasattr(self, 'has_instance'):
            self = self.get_instance(
                character=character,
                ignore_gear_requirements=ignore_gear_requirements
            )

        if not hasattr(self, 'requirements') or not self.requirements:
            return []

        if character is None:
            try:
                from my_config import get_character
                character = get_character()
            except Exception:
                return ['Character data not loaded']

        missing = []
        for req in self.requirements:
            req_type = req.get('type')

            if req_type == 'reputation':
                faction = req.get('faction')
                required_amount = req.get('amount', 0)
                current = character.reputation.get(faction, 0)
                if current < required_amount:
                    faction_display = faction.replace('_', ' ').title() if faction else 'Unknown'
                    missing.append(f"{faction_display} reputation {required_amount} (have {current})")

            elif req_type == 'skill':
                skill = req.get('skill')
                required_level = req.get('level', 0)
                current = character.get_skill_level(skill)
                if current < required_level:
                    missing.append(f"{skill} level {required_level} (have {current})")

            elif req_type == 'character_level':
                required_level = req.get('level', 0)
                try:
                    from util.walkscape_constants import character_level_from_steps
                    char_level = character_level_from_steps(character.total_steps)
                    if char_level < required_level:
                        missing.append(f"Character level {required_level} (have {char_level})")
                except Exception:
                    pass

            elif req_type == 'diving_gear':
                if ignore_gear_requirements:
                    continue
                required_count = req.get('count', 3)
                diving_count = sum(
                    1 for item in character.gear.values()
                    if item and hasattr(item, 'keywords') and
                    any('diving gear' in kw.lower() for kw in item.keywords)
                )
                if diving_count < required_count:
                    missing.append(f"{required_count}x Diving Gear equipped (have {diving_count})")

            elif req_type == 'achievement_points':
                required_amount = req.get('amount', 0)
                char_ap = 0
                if hasattr(character, 'achievement_points'):
                    char_ap = character.achievement_points
                else:
                    try:
                        import util.walkscape_globals
                        char_ap = int(util.walkscape_globals.ACHIEVEMENT_POINTS)
                    except (ImportError, AttributeError, ValueError):
                        pass
                if char_ap < required_amount:
                    missing.append(f"{required_amount} Achievement Points (have {char_ap})")

            elif req_type == 'activity_completion':
                activity = req.get('activity')
                required_completions = req.get('completions', 0)
                activity_normalized = activity.lower().replace(' ', '_').replace("'", "")
                has_completed = False
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    has_completed = character.custom_stats.get(activity_normalized, False)
                else:
                    try:
                        import my_config
                        activity_upper = activity.upper().replace(" ", "_").replace("'", "")
                        var_name = f"{activity_upper}_{required_completions}_COMPLETIONS"
                        has_completed = getattr(my_config, var_name, False)
                    except (ImportError, AttributeError):
                        pass
                if not has_completed:
                    missing.append(f"Complete {activity} {required_completions}x")

            elif req_type == 'access':
                region = req.get('region', '').lower()
                region_normalized = region.replace(' ', '_').replace("'", "")
                custom_stat_id = f"access_{region_normalized}"
                has_access = True
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    has_access = character.custom_stats.get(custom_stat_id, True)
                else:
                    try:
                        import my_config
                        access_var = f'ACCESS_{region.upper()}'
                        has_access = getattr(my_config, access_var, True)
                    except (ImportError, AttributeError):
                        pass
                if not has_access:
                    region_display = region.replace('_', ' ').title()
                    missing.append(f"Access to {region_display}")

            elif req_type == 'category_level_percent':
                import math
                category = req.get('category', '').lower()
                percent = req.get('percent', 0)
                CATEGORY_SKILLS = {
                    'gathering': ['fishing', 'foraging', 'hunting', 'mining', 'woodcutting'],
                    'artisan': ['carpentry', 'cooking', 'crafting', 'smithing', 'tailoring', 'trinketry'],
                    'utility': ['agility'],
                }
                skills = CATEGORY_SKILLS.get(category, [])
                if not skills:
                    continue
                max_level = len(skills) * 99
                required_total = math.ceil(max_level * percent / 100)
                actual_total = sum(character.get_skill_level(s) for s in skills)
                if actual_total < required_total:
                    missing.append(f"{percent}% {category.title()} level (have {actual_total}/{required_total})")

        return missing

    
    def get_custom_stats_requirements(self, character=None, ignore_gear_requirements=False):
        """
        Return unmet requirements that are specifically gated by custom stats
        (activity_completion, access, travel_steps) — i.e. things the user must
        toggle in the Custom Stats popup, NOT things auto-imported from character data.
        
        Returns:
            List of dicts with 'text' (human-readable) and 'stat_id' (custom stat key).
            Empty list if no custom-stats requirements are unmet.
        """
        if hasattr(self, 'has_instance'):
            self = self.get_instance(
                character=character,
                ignore_gear_requirements=ignore_gear_requirements
            )

        if not hasattr(self, 'requirements') or not self.requirements:
            return []

        if character is None:
            try:
                from my_config import get_character
                character = get_character()
            except Exception:
                return []

        missing = []
        for req in self.requirements:
            req_type = req.get('type')

            if req_type == 'activity_completion':
                activity = req.get('activity')
                required_completions = req.get('completions', 0)
                activity_normalized = activity.lower().replace(' ', '_').replace("'", "")
                has_completed = False
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    has_completed = character.custom_stats.get(activity_normalized, False)
                else:
                    try:
                        import my_config
                        activity_upper = activity.upper().replace(" ", "_").replace("'", "")
                        var_name = f"{activity_upper}_{required_completions}_COMPLETIONS"
                        has_completed = getattr(my_config, var_name, False)
                    except (ImportError, AttributeError):
                        pass
                if not has_completed:
                    missing.append({
                        'text': f"Complete {activity} {required_completions}x",
                        'stat_id': activity_normalized,
                    })

            elif req_type == 'access':
                region = req.get('region', '').lower()
                region_normalized = region.replace(' ', '_').replace("'", "")
                custom_stat_id = f"access_{region_normalized}"
                has_access = True
                if hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    has_access = character.custom_stats.get(custom_stat_id, True)
                else:
                    try:
                        import my_config
                        access_var = f'ACCESS_{region.upper()}'
                        has_access = getattr(my_config, access_var, True)
                    except (ImportError, AttributeError):
                        pass
                if not has_access:
                    region_display = region.replace('_', ' ').title()
                    missing.append({
                        'text': f"Access to {region_display}",
                        'stat_id': custom_stat_id,
                    })

        return missing

    def _location_matches(self, location_key: str, current_location) -> bool:
        """
        Check if a location key matches the current location.
        
        Args:
            location_key: Location key from stats dict (e.g., 'global', 'underwater', '!jarvonia')
            current_location: LocationInfo object or None
        
        Returns:
            True if stats should be included for this location
        """
        # Always include global stats
        if location_key == "global":
            return True
        
        # If no location specified, only include global stats
        if current_location is None:
            return False
        
        # Check for negation (! prefix means "NOT this location")
        is_negated = location_key.startswith("!")
        location_name = location_key[1:] if is_negated else location_key
        
        # Handle string locations (e.g., from generic activities) by treating as region match
        if isinstance(current_location, str):
            # Try to resolve to a LocationInfo so region tags (e.g. 'gdte') work correctly
            from util.autogenerated.locations import Location as _Location
            location_info = _Location.by_name(current_location)
            if location_info is None:
                # selectedLocation arrives from the UI as a slug ('bilgemont_port');
                # by_name only matches display names ('Bilgemont Port'). Resolve the
                # slug so location-scoped stats (e.g. gdte) are respected. See bug
                # 87e0159a.
                location_info = _resolve_location_slug(current_location)
            if location_info is not None:
                matches = location_info.is_in_region(location_name.lower())
            else:
                # Unknown location string — fall back to direct equality
                matches = current_location.lower() == location_name.lower()
        else:
            matches = current_location.is_in_region(location_name.lower())
        
        # Apply negation if needed
        return not matches if is_negated else matches
    
    def _add_location_stats(self, skill_data: dict, location, combined: dict) -> dict:
        """
        Add stats from skill_data to combined dict, filtering by location.
        
        Args:
            skill_data: Dict with location keys mapping to stat dicts
            location: LocationInfo object or None
            combined: Dict to accumulate stats into
        
        Returns:
            Updated combined dict
        """
        for location_key, stats in skill_data.items():
            if isinstance(stats, dict) and self._location_matches(location_key, location):
                for stat_name, stat_value in stats.items():
                    combined[stat_name] = combined.get(stat_name, 0.0) + stat_value
        
        return combined
    
    def get_stats_for_skill(
        self, 
        skill: Union[SkillInstance, str, None] = None, 
        location: Union[LocationInfo, str, None] = None,
        activity: Union[Activity, str, None] = None,
        set_piece_counts: dict = None,
        character=None,
        achievement_points=None,
    ) -> Dict[str, float]:
        """
        Get stats for a specific skill and location.
        
        Args:
            skill: Skill object, skill string, or None for all skills
            location: LocationInfo object, location string, or None
            activity: Activity name string or None
            set_piece_counts: Dict mapping set names to piece counts (for set bonuses)
            character: Character object (optional)
        
        Returns:
            Dict of stat names to values (percentages already converted to decimals)
        """
        # A composite (gearset) produces a FRESH instance per call via
        # get_instance(), so id(self) below is unique every time -> the
        # id()-keyed cache never hits, grows one result dict per scored gearset
        # (12.6M entries / ~1.2 GB in a single chests_recipes optimize, the
        # local-OOM root cause in bug 7091473e), and risks id()-reuse stale
        # hits after GC. Only stable catalog singletons (no has_instance) have a
        # reusable id, so restrict the cache to those. Composites were never
        # getting cache hits, so this is memory-only -- no recompute penalty.
        _is_composite = hasattr(self, 'has_instance')
        if _is_composite:
            self = self.get_instance(
                skill=skill,
                location=location,
                activity=activity,
                set_piece_counts=set_piece_counts,
                character=character,
                achievement_points=achievement_points
            )

        # Create cache key (exclude character to keep key simple)
        skill_key = skill.value if hasattr(skill, 'value') else (skill if skill else None)
        location_key = location.name if hasattr(location, 'name') else (location if location else None)
        activity_key = activity.name if hasattr(activity, 'name') else (activity if activity else None)
        set_key = frozenset(set_piece_counts.items()) if set_piece_counts else None

        cache_key = (id(self), skill_key, location_key, activity_key, set_key)

        # Check cache (stable catalog singletons only -- see note above).
        # LRU: touch on hit so hot stable entries survive ephemeral churn.
        if not _is_composite:
            cached = _STATS_CACHE.get(cache_key)
            if cached is not None:
                _STATS_CACHE.move_to_end(cache_key)
                return cached

        # Calculate stats (original logic)
        result = self._calculate_stats_uncached(skill, location, activity, set_piece_counts, character)

        # Store in cache with an LRU bound (never for ephemeral composites).
        if not _is_composite:
            _STATS_CACHE[cache_key] = result
            if len(_STATS_CACHE) > _STATS_CACHE_MAX:
                _STATS_CACHE.popitem(last=False)  # evict oldest

        return result
    
    def _calculate_stats_uncached(
        self, 
        skill: Union[SkillInstance, str, None] = None, 
        location: Union[LocationInfo, str, None] = None,
        activity: Union[Activity, str, None] = None,
        set_piece_counts: dict = None,
        character=None,
    ) -> Dict[str, float]:
        """Internal method that does the actual stat calculation (uncached)."""
        if not skill:
            # Return combined stats from all skills and locations
            combined = {}
            if isinstance(self._stats, dict):
                for skill_name, skill_data in self._stats.items():
                    if isinstance(skill_data, dict):
                        for loc_or_stat, value in skill_data.items():
                            if isinstance(value, dict):
                                # Location-nested format
                                for stat, stat_val in value.items():
                                    combined[stat] = combined.get(stat, 0.0) + stat_val
                            else:
                                # Direct stat
                                combined[loc_or_stat] = combined.get(loc_or_stat, 0.0) + value
            return self._convert_percentages(combined)
        
        # Import Skill here to avoid circular dependency at module load time
        from util.walkscape_constants import Skill
        
        # Convert skill to SkillInstance object if it's a string
        if isinstance(skill, str):
            skill_upper = skill.upper()
            if hasattr(Skill, skill_upper):
                skill = getattr(Skill, skill_upper)
            else:
                # Unknown skill - this is a bug that should be fixed
                raise ValueError(
                    f"Unknown skill '{skill}'. Valid skills are: "
                    f"{', '.join([s for s in dir(Skill) if not s.startswith('_')])}"
                )
        
        combined = {}
        
        # Iterate through all stats and check if skill matches
        for stats_skill, skill_data in self._stats.items():
            if not isinstance(skill_data, dict):
                continue
            
            # Check if this skill should be included
            if skill.matches_skill(stats_skill):
                # Add location-filtered stats
                combined = self._add_location_stats(skill_data, location, combined)
        
        # Add gated stats if requirements are met (only for items that have them)
        if hasattr(self, 'gated_stats') and self.gated_stats:
            combined = self._add_gated_stats(skill, location, combined, activity, set_piece_counts, character)
        
        # Convert percentages to decimals
        return self._convert_percentages(combined)
    
    def _add_gated_stats(self, skill, location, combined: dict, activity=None, set_piece_counts: dict = None, character=None) -> dict:
        """
        Add gated stats (skill_level, activity_completion, reputation, activity, set_pieces) if requirements are met.
        
        Args:
            skill: SkillInstance object
            location: LocationInfo object or None
            combined: Dict to accumulate stats into
            activity: Activity name string or None
            set_piece_counts: Dict mapping set names to piece counts (for set bonuses)
            character: Character object (if not provided, will load from config)
        
        Returns:
            Updated combined dict
        """
        # Import character to check gates
        if character is None:
            try:
                from my_config import get_character
                character = get_character()
            except ImportError:
                return combined  # Character not available, skip all gated stats
        
        # Check skill_level gates
        if "skill_level" in self.gated_stats:
            for gate_skill, thresholds in self.gated_stats["skill_level"].items():
                char_level = character.get_skill_level(gate_skill)
                for threshold, threshold_stats in thresholds.items():
                    if char_level >= threshold:
                        # Add stats from this threshold
                        for stat_skill, locations in threshold_stats.items():
                            if skill.matches_skill(stat_skill):
                                combined = self._add_location_stats(locations, location, combined)
        
        # Check total_skill_level gates (sum of all skill levels)
        # Structure: {'total_skill_level': {threshold: {skill: {location: {stat: value}}}}}
        if "total_skill_level" in self.gated_stats:
            # Use global total skill level (set by Character init)
            import util.walkscape_globals
            total_level = util.walkscape_globals.get_total_skill_level()
            for threshold, threshold_stats in self.gated_stats["total_skill_level"].items():
                if total_level >= threshold:
                    # Add stats from this threshold
                    for stat_skill, locations in threshold_stats.items():
                        if skill.matches_skill(stat_skill):
                            combined = self._add_location_stats(locations, location, combined)

        # Check total_collectibles gates (number of obtained collectibles)
        # Structure: {'total_collectibles': {threshold: {skill: {location: {stat: value}}}}}
        # Bonuses are CUMULATIVE across every threshold met, mirroring the
        # alien squeaky toy's total_skill_level tiers: e.g. the item collection
        # ring grants +1% chest finding at each of 10/20/30/40/50/60 collectibles,
        # so a player with 60 collectibles gets +6%.
        if "total_collectibles" in self.gated_stats:
            import util.walkscape_globals
            total_collectibles = util.walkscape_globals.get_total_collectibles()
            for threshold, threshold_stats in self.gated_stats["total_collectibles"].items():
                if total_collectibles >= int(threshold):
                    for stat_skill, locations in threshold_stats.items():
                        if skill.matches_skill(stat_skill):
                            combined = self._add_location_stats(locations, location, combined)

        
        # Check activity_completion gates
        if "activity_completion" in self.gated_stats:
            for activity_name, thresholds in self.gated_stats["activity_completion"].items():
                # Normalize activity name for lookup (spaces → underscores, lowercase)
                activity_normalized = activity_name.lower().replace(' ', '_').replace("'", "")
                
                for threshold, threshold_stats in thresholds.items():
                    # Build custom stat ID: itemname_activityname
                    item_name_normalized = self.name.lower().replace(' ', '_').replace("'", "")
                    custom_stat_id = f"{item_name_normalized}_{activity_normalized}"
                    
                    # Check if character has custom_stats set (not None)
                    has_completed = False
                    if character and hasattr(character, 'custom_stats') and character.custom_stats is not None:
                        # Character has custom_stats from UI - use it exclusively (don't fall back)
                        # If key not in dict, it means False (user hasn't toggled it)
                        has_completed = character.custom_stats.get(custom_stat_id, False)
                    else:
                        # Character doesn't have custom_stats (None or missing) - fall back to my_config
                        try:
                            import my_config
                            # Build config variable name: ITEMNAME_ACTIVITYNAME_N_COMPLETIONS
                            item_upper = self.name.upper().replace(" ", "_").replace("'", "")
                            activity_upper = activity_name.upper().replace(" ", "_").replace("'", "")
                            var_name = f"{item_upper}_{activity_upper}_{threshold}_COMPLETIONS"
                            has_completed = getattr(my_config, var_name, False)
                        except (ImportError, AttributeError):
                            pass  # Config not available, skip
                    
                    if has_completed:
                        # Add stats from this threshold
                        for stat_skill, locations in threshold_stats.items():
                            if skill.matches_skill(stat_skill):
                                combined = self._add_location_stats(locations, location, combined)
        
        # Check activity gates (stats that only apply while doing a specific activity)
        # Structure: {'activity': {activity_name: {skill: {location: {stat: value}}}}}
        # Note: No threshold level - activity gates don't have thresholds
        if "activity" in self.gated_stats and activity:
            # Convert activity to lowercase string if it's an object
            activity_name = activity.lower() if isinstance(activity, str) else getattr(activity, 'name', str(activity)).lower()
            
            if activity_name in self.gated_stats["activity"]:
                activity_stats = self.gated_stats["activity"][activity_name]
                # Iterate through skills in activity stats
                for stat_skill, locations in activity_stats.items():
                    if skill.matches_skill(stat_skill):
                        combined = self._add_location_stats(locations, location, combined)
        
        # Check reputation gates
        if "reputation" in self.gated_stats:
            for faction, thresholds in self.gated_stats["reputation"].items():
                faction_rep = character.reputation.get(faction, 0)
                for threshold in sorted(thresholds.keys()):
                    if faction_rep >= threshold:
                        # Add stats from this threshold
                        threshold_stats = thresholds[threshold]
                        for stat_skill, locations in threshold_stats.items():
                            if skill.matches_skill(stat_skill):
                                combined = self._add_location_stats(locations, location, combined)
        
        # Check set_pieces gates (set bonuses based on equipped piece count)
        if "set_pieces" in self.gated_stats and set_piece_counts:
            for set_name, thresholds in self.gated_stats["set_pieces"].items():
                # Get the count of pieces for this set
                equipped_count = set_piece_counts.get(set_name, 0)
                
                # Apply ALL thresholds we qualify for (set bonuses are cumulative per piece)
                # Each threshold adds to the bonus that each equipped piece provides
                # Convert threshold keys to int for proper comparison
                for threshold_str in sorted(thresholds.keys(), key=int):
                    threshold = int(threshold_str)
                    if equipped_count >= threshold:
                        # Add stats from this threshold
                        threshold_stats = thresholds[threshold_str]
                        for stat_skill, locations in threshold_stats.items():
                            if skill.matches_skill(stat_skill):
                                combined = self._add_location_stats(locations, location, combined)
                    # Continue to next threshold (bonuses are cumulative)
        
        # Check item_ownership gates (stats that require owning another item)
        # Structure: {'item_ownership': {item_name: {skill: {location: {stat: value}}}}}
        # Note: No threshold level - item ownership gates don't have thresholds
        if "item_ownership" in self.gated_stats:
            # Check character.items for owned items
            owned_items = set()
            
            if hasattr(character, 'items') and character.items:
                for item in character.items:
                    if hasattr(item, 'name'):
                        owned_items.add(item.name.lower())
            
            # Check each item ownership requirement
            for required_item_name, item_stats in self.gated_stats["item_ownership"].items():
                if required_item_name.lower() in owned_items:
                    # Player owns this item, add its stats
                    for stat_skill, locations in item_stats.items():
                        if skill.matches_skill(stat_skill):
                            combined = self._add_location_stats(locations, location, combined)
        
        # Check travel_steps gates (stats gated by total travel steps walked)
        # Structure: {'travel_steps': {threshold: {skill: {location: {stat: value}}}}}
        if "travel_steps" in self.gated_stats:
            for threshold, threshold_stats in self.gated_stats["travel_steps"].items():
                # Build custom stat ID: petal_finder_travel_steps_125000
                item_name_normalized = self.name.lower().replace(' ', '_').replace("'", "")
                custom_stat_id = f"{item_name_normalized}_travel_steps_{threshold}"
                
                # Check if character has custom_stats set (not None)
                has_completed = False
                if character and hasattr(character, 'custom_stats') and character.custom_stats is not None:
                    has_completed = character.custom_stats.get(custom_stat_id, False)
                else:
                    # Fall back to my_config
                    try:
                        import my_config
                        item_upper = self.name.upper().replace(" ", "_").replace("'", "")
                        var_name = f"{item_upper}_TRAVEL_STEPS_{threshold}"
                        has_completed = getattr(my_config, var_name, False)
                    except (ImportError, AttributeError):
                        pass
                
                if has_completed:
                    for stat_skill, locations in threshold_stats.items():
                        if skill.matches_skill(stat_skill):
                            combined = self._add_location_stats(locations, location, combined)
        
        return combined
    
    def _convert_percentages(self, stats: dict) -> dict:
        """
        Convert percentage stats to decimal format based on Attribute definitions.
        
        Args:
            stats: Dict of stat names to values
        
        Returns:
            Dict with percentages converted to decimals
        """
        # Import here to avoid circular dependency
        from util.walkscape_constants import Attribute
        
        converted = {}
        for attribute_name, value in stats.items():
            attribute_upper = attribute_name.upper()
            if hasattr(Attribute, attribute_upper):
                attribute_obj = getattr(Attribute, attribute_upper)
                if attribute_obj.is_percentage:
                    converted[attribute_name] = value / 100.0
                else:
                    converted[attribute_name] = value
            else:
                # Unknown attribute, keep as-is
                converted[attribute_name] = value
        
        return converted
    
    def attr(
        self, 
        skill: Union[SkillInstance, str, None] = None, 
        location: Union[LocationInfo, str, None] = None,
        activity: Union[Activity, str, None] = None,
        set_piece_counts: dict = None,
    ) -> Dict[str, float]:
        """
        Get attributes in standard format.
        
        Args:
            skill: Skill object, skill string, or None for all skills
                   - Skill.TRAVEL: combines agility + traveling + global
                   - None: combines all skills
                   - specific skill: gets that skill + global
            location: Location string or LocationInfo object
            activity: Activity name string or Activity object (optional, for activity-specific stats)
            set_piece_counts: Dict mapping set names to piece counts (for set bonuses)
        
        Returns:
            Dict of stat names to values (percentages as decimals, flat stats as numbers)
        """
        return self.get_stats_for_skill(skill, location=location, activity=activity, set_piece_counts=set_piece_counts)
    
    def abbreviate_name(self) -> str:
        """
        Abbreviate item name by taking first 3 chars of each word,
        skipping prepositions/articles, and handling quality tiers.
        
        Examples:
        - "Hydrilium Sickle (Perfect)" -> "Hyd Sic Per"
        - "Iron Sickle (Great)" -> "Iro Sic Gre"
        - "Ring of Homesickness" -> "Rin Hom"
        
        Returns:
            Abbreviated name string
        """
        if not hasattr(self, 'name'):
            return "???"
        
        # Remove parentheses and split
        name = self.name.replace('(', '').replace(')', '')
        words = name.split()
        
        # Words to skip
        skip_words = {'of', 'the', 'a', 'an', 'in', 'on', 'at', 'to', 'for', 'with'}
        
        # Take first 3 chars of each word (skip articles/prepositions)
        abbreviated = []
        for word in words:
            if word.lower() not in skip_words:
                abbreviated.append(word[:3].capitalize())
        
        return ' '.join(abbreviated)
