#!/usr/bin/env python3
"""
Walkscape Constants
All static game data that doesn't change per user.
Re-exports all autogenerated data for convenient access.
"""

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional, Union


# ============================================================================
# QUALITY MAPPINGS
# ============================================================================

# Map from display name (in item names) to gearset export format
QUALITY_NAME_TO_EXPORT = {
    'Eternal': 'ethereal',
    'Perfect': 'legendary',
    'Excellent': 'epic',
    'Great': 'rare',
    'Good': 'uncommon',
    'Normal': 'common'
}

# Map from gearset export format to display name
QUALITY_EXPORT_TO_NAME = {
    'ethereal': 'ETERNAL',
    'legendary': 'PERFECT',
    'epic': 'EXCELLENT',
    'rare': 'GREAT',
    'uncommon': 'GOOD',
    'common': 'NORMAL'
}


# ============================================================================
# KEYWORD CONSTANTS
# ============================================================================

# Keywords that can be shared between tools (no uniqueness constraint)
# These are CATEGORIZATION keywords - NOT "Banned Keywords" per the wiki.
# Note: "Foraging tool" and "Fishing tool" are BANNED (not listed here).
# Other skill tool keywords are categorization only; their sub-keywords
# (Pickaxe, Hatchet, etc.) are the actual banned keywords.
# See: https://wiki.walkscape.app/wiki/Keywords/en
EXCLUDED_TOOL_KEYWORDS = frozenset({
    'regional',
    'tool',
    'light source',
    'achievement reward',
    'faction reward',
    'activity tool',
    'crafting tool',      # Categorization (banned sub-keywords: Wrench, Screwdriver)
    'smithing tool',      # Categorization (banned sub-keywords: Smithing hammer, Bellows)
    'woodcutting tool',   # Categorization (banned sub-keyword: Hatchet)
    'mining tool',        # Categorization (banned sub-keyword: Pickaxe)
    'carpentry tool',     # Categorization (banned sub-keywords: Saw, Chisel)
    'cooking tool',       # Categorization (banned sub-keywords: Cooking knife, Cooking pan, Cutting board)
    'adventuring tool set',
    'spectral',
    'tailoring tool',     # Categorization (banned sub-keywords: Needle, Scissors)
    'skydisc',            # Activity keyword (not banned) - multiple skydiscs allowed
    'upgradeable',        # Categorization (marks an upgradeable tool); NOT banned -
    'upgradable',         # multiple upgradeable tools (Log splitter + Log basket, etc.)
                          # can be equipped together. See bug dd4b6aea.
    # --- The tools-API migration added these categorization keywords to item
    # keyword lists (pre-migration tools did not carry them). They are skill /
    # skill-category / location / "while travelling" scope markers, NOT tool
    # uniqueness constraints: multiple tools may share them (e.g. a Fishing rod
    # and a Comfy fishing chair both carry 'Fishing'). Exclude them so the tool
    # keyword-uniqueness check does not falsely ban equipping them together.
    'agility', 'carpentry', 'cooking', 'crafting', 'fishing', 'foraging',
    'hunting', 'mining', 'smithing', 'tailoring', 'trinketry', 'woodcutting',
    'gathering', 'artisan', 'utility',          # skill categories
    'travelling', 'traveling',                  # while-travelling scope
    'jarvonia', 'erdwise', 'trellin', 'syrenthia', 'halfling rebels',
    'gdte', 'swamp',                            # region / location scopes
    # --- Remaining non-banned EQUIPMENT keywords per the wiki Keywords page
    # (https://wiki.walkscape.app/wiki/Keywords). Everything that is NOT a
    # "Banned Keyword" can be shared across tools. The banned ones (Hatchet,
    # Pickaxe, Sickle, Saw, Chisel, Wrench, Needle, Scissors, Pliers, Ruler,
    # Sander, Knife, Hunting bow, Smithing hammer, Bellows, Basket, Toolbox,
    # Local map, Log splitter, Magnetic, Magnifying lens, Cutting mat, Gold
    # pan, Bug catching net, Climbing gear, Life vest, Pins, Foraging/Fishing
    # tool and the Fishing rod/net/cage/spear/lure/rod-rest group) are
    # intentionally absent so they still enforce uniqueness.
    'amulet', 'aquatic', 'cooking pot', 'cutting board', 'ring', 'screwdriver',
    'shield', 'skill book', 'skis', 'socks', 'spices', 'water', 'weapon',
    'desert', 'ghostly', 'snowy', 'underwater',          # location keywords
    'diving gear', 'diving gear set', 'advanced diving gear',
    'advanced diving gear set', 'expert diving gear', 'expert diving gear set',
    'proper gear', 'proper gear set', 'treasure hunter set',   # gear-set keywords
})

# "Banned Keyword Groups" per the wiki - only ONE item from ANY keyword in the
# group can be equipped at a time. Each frozenset is a mutually exclusive group.
# See: https://wiki.walkscape.app/wiki/Fishing_rod_Keyword
BANNED_KEYWORD_GROUPS = [
    frozenset({'fishing rod', 'fishing net', 'fishing cage', 'fishing spear'}),
]

# Keywords that are handled specially in optimization (not generic requirements)
SPECIAL_REQUIREMENT_KEYWORDS = frozenset({
    'diving gear',
    'advanced diving gear',
    'light source',
    'skis'
})


# ============================================================================
# KEYWORD HELPER FUNCTIONS
# ============================================================================

def get_diving_gear_requirement(keyword_counts: dict) -> int:
    """
    Get diving gear requirement from keyword_counts.
    
    Handles the fact that 'advanced diving gear' items also have 'diving gear' keyword.
    
    Args:
        keyword_counts: Dictionary of keyword -> count from activity requirements
        
    Returns:
        Number of diving gear items required
    """
    # Advanced diving gear takes precedence
    if keyword_counts.get('advanced diving gear', 0) > 0:
        return keyword_counts['advanced diving gear']
    return keyword_counts.get('diving gear', 0)


def item_has_keyword(item, keyword: str) -> bool:
    """
    Check if item has a specific keyword (case-insensitive, EXACT match).

    IMPORTANT: This must be an EXACT case-insensitive match, not a substring
    match. Substring matching causes "Fishing rod rest" to incorrectly satisfy
    a "fishing rod" requirement (because "fishing rod" is a substring of
    "fishing rod rest"). Activity keyword requirements like
    `keyword_counts={'fishing rod': 1}` distinguish between "fishing rod",
    "fishing rod rest", "fishing cage", "fishing tool", etc., and we must
    respect that distinction.

    Args:
        item: Item object with keywords attribute
        keyword: Keyword to check for

    Returns:
        True if item has the keyword (exact, case-insensitive), False otherwise
    """
    if not hasattr(item, 'keywords'):
        return False
    return any(keyword.lower() == kw.lower() for kw in item.keywords)


def pet_provides_keyword(pet, keyword: str) -> bool:
    """
    Check if a pet's passive abilities advertise a given keyword via
    `provides_keyword` (e.g. Gecko Level 4 "Clever Climber" exposes
    provides_keyword='climbing gear', so an equipped Gecko L4 should
    satisfy activity/route requirements for climbing gear).

    Accepts either a PetInfo (single level) or a PetLevels container.
    Case-insensitive match.
    """
    if pet is None or not keyword:
        return False
    kw = keyword.lower()

    # PetInfo (single level) — has .abilities directly
    abilities = getattr(pet, 'abilities', None) or []
    if not abilities and hasattr(pet, '_levels'):
        # PetLevels container — collect abilities across all levels
        for lvl in pet._levels.values():
            abilities = list(abilities) + list(getattr(lvl, 'abilities', None) or [])

    for ability in abilities:
        if not isinstance(ability, dict):
            continue
        provided = ability.get('provides_keyword')
        if not provided:
            continue
        if isinstance(provided, str):
            if provided.lower() == kw:
                return True
        else:
            # Accept list/tuple/set of keywords too
            try:
                for p in provided:
                    if isinstance(p, str) and p.lower() == kw:
                        return True
            except TypeError:
                pass
    return False


def item_has_any_keyword(item, keywords: set) -> bool:
    """
    Check if item has any of the specified keywords.
    
    Args:
        item: Item object with keywords attribute
        keywords: Set of keywords to check for
        
    Returns:
        True if item has any of the keywords, False otherwise
    """
    if not hasattr(item, 'keywords'):
        return False
    item_keywords = {kw.lower() for kw in item.keywords}
    return bool(item_keywords & {k.lower() for k in keywords})


# ============================================================================
# ENUMS - Must be defined BEFORE importing autogenerated files
# ============================================================================
# Region enum
class SortingType(Enum):
    """Types for Sorting"""
    RECIPE = "recipe"
    ACTIVITY = "activity"
    TRAVEL = "travel"

# Sorting enum for optimizers
class Sorting(Enum):
    """Sorting options for optimization results
    
    Format: (sort_direction, metric_key, display_name, types, duplicable)
    - sort_direction: "+metric" for maximize, "-metric" for minimize
    - metric_key: Actual key in metrics dict
    - display_name: User-friendly name for display
    - types: List of SortingType enums this metric applies to
    - duplicable: Whether this priority can appear multiple times in the list
    """
    
    def __new__(cls, sort_direction, metric_key, display_name, types, duplicable=False):
        """Create enum with tuple values while maintaining backward compatibility"""
        obj = object.__new__(cls)
        obj._value_ = sort_direction  # Keep original value for backward compat
        obj._sort_direction = sort_direction
        obj._metric_key = metric_key
        obj._display_name = display_name
        obj._types = types
        obj._duplicable = duplicable
        return obj
    
    # Enum values: (sort_direction, metric_key, display_name, SortingType, duplicable)
    STEPS_PER_REWARD_ROLL = ("-steps_per_reward_roll", "steps_per_reward_roll", "Minimize Steps/Target", [SortingType.ACTIVITY], True)
    MATERIALS = ("-materials_for_target", "materials_for_target", "Materials for X Quality", [SortingType.RECIPE], True)
    TOTAL_CRAFTS_FOR_TARGET = ("-total_crafts", "total_crafts", "Total Crafts for X Quality", [SortingType.RECIPE], True)
    STEPS_PER_CRAFT = ("-expected_steps_per_item", "expected_steps_per_item", "Expected Steps/Craft", [SortingType.RECIPE])
    DISPLAYED_STEPS_PER_CRAFT = ("-current_steps", "current_steps", "Displayed Steps/Craft", [SortingType.RECIPE])
    MATERIALS_PER_CRAFT = ("-materials_per_craft", "materials_per_craft", "Materials/Craft", [SortingType.RECIPE])
    TOTAL_XP_PER_STEP = ("+total_xp_per_step", "total_xp_per_step", "Total XP/Step (of all skills)", [SortingType.ACTIVITY])
    XP_PER_STEP = ("+primary_xp_per_step", "primary_xp_per_step", "Primary XP/Step", [SortingType.ACTIVITY, SortingType.RECIPE, SortingType.TRAVEL])
    TOTAL_XP = ("+total_xp_for_action", "total_xp_for_action", "Total XP per Action (of all skills)", [SortingType.ACTIVITY])
    EXPECTED_STEPS_PER_ACTION = ("-expected_steps_per_action", "expected_steps_per_action", "Expected Steps/Action", [SortingType.ACTIVITY])
    DISPLAYED_STEPS_PER_ACTION = ("-current_steps_activity", "current_steps_activity", "Displayed Steps/Action", [SortingType.ACTIVITY])
    TOTAL_STEPS = ("-steps_for_target", "steps_for_target", "Total Steps for X Quality", [SortingType.RECIPE], True)
    # Tree-aware version of TOTAL_STEPS: scores recipe steps PLUS the cost
    # of producing the input materials (sum of children's steps_per_item
    # weighted by per-craft input quantity at the gearset's NMC/DR/QO).
    # Used by the crafting tree's per-node optimizer so picking gear that
    # raises QO (which reduces required crafts and therefore input mats)
    # gets credit for the downstream savings, not just the local-recipe
    # speed. Falls back to steps_for_target::Q when no children are wired
    # in (so single-recipe / non-tree callers behave unchanged). See the
    # CHILD_INPUT_SPECS plumbing in optimize_craft_gearsets.py.
    TOTAL_TREE_STEPS = ("-total_tree_steps_for_target", "total_tree_steps_for_target", "Total Tree Steps for X Quality", [SortingType.RECIPE], True)
    PRIMARY_XP = ("+primary_xp_per_action", "primary_xp_per_action", "Primary XP per Action", [SortingType.ACTIVITY, SortingType.RECIPE])
    STEPS_PER_CHEST = ("-steps_for_chest", "steps_for_chest", "Average Steps/Chest", [SortingType.TRAVEL])
    MATERIALS_PER_CHEST = ("-materials_per_chest", "materials_per_chest", "Materials/Target Item", [SortingType.RECIPE], True)
    # Duplicable recipe metric: expected steps to produce one target item
    # (cat:chests / cat:if:* / etc.). Mirrors MATERIALS_PER_CHEST but
    # scores steps instead of materials so users can directly minimize
    # time-per-drop for a specific IF category.
    STEPS_PER_CHEST_RECIPE = ("-steps_per_chest_recipe", "steps_per_chest_recipe", "Steps/Target Item", [SortingType.RECIPE], True)
    STEPS_FOR_BUDGET = ("-steps_for_budget", "steps_for_budget", "Steps for Budget", [SortingType.RECIPE])
    XP_PER_MATERIAL = ("+xp_per_material", "xp_per_material", "XP/Material Consumed", [SortingType.RECIPE])
    AVG_TRAVEL_STEPS = ("-avg_travel_steps", "avg_travel_steps", "Average Steps", [SortingType.TRAVEL])
    # Column-3 travel optimizer priorities (see optimize_travel_gearsets.calculate_travel_metrics).
    # TRAVEL_TOTAL_STEPS is the default sole priority — minimizes the raw route
    # step count (identical to the pre-priority-list behaviour). It reuses the
    # 'total_steps' metric key that calculate_travel_metrics already populates.
    TRAVEL_TOTAL_STEPS = ("-total_steps", "total_steps", "Total Steps", [SortingType.TRAVEL])
    # Duplicable per-target metric: expected steps to find one of a given
    # item-finding target (chests via chest_finding, or a cat:if:* item-finding
    # category) over the whole route. Scored under composite key
    # "travel_steps_per_target::<target>" so multiple targets can coexist,
    # mirroring STEPS_PER_REWARD_ROLL on the activity optimizer.
    TRAVEL_STEPS_PER_TARGET = ("-travel_steps_per_target", "travel_steps_per_target", "Steps/Target Item", [SortingType.TRAVEL], True)

    @property
    def is_reverse(self):
        """Check if this sorting should be reversed (descending/maximize)"""
        return self._sort_direction.startswith('+')
    
    @property
    def stat_key(self):
        """Get the stat key without the +/- prefix (legacy)"""
        return self._sort_direction[1:]
    
    @property
    def metric_key(self):
        """Get the actual key used in metrics dict"""
        return self._metric_key

    @property
    def types(self):
        """Get the types for sorting"""
        return self._types
    
    @property
    def display_name(self):
        """Get user-friendly display name"""
        return self._display_name
    
    @property
    def duplicable(self):
        """Whether this priority can appear multiple times in the sorting list"""
        return self._duplicable
    
    def get_sort_value(self, metrics: dict) -> float:
        """Get the sortable value from metrics dict (negated if maximizing).
        
        This is the single-enum lookup. Prefer SortingEntry.get_sort_value when
        you have a per-entry target (e.g. duplicable metrics like
        steps_per_reward_roll appearing twice with different target categories).
        """
        value = metrics.get(self._metric_key, 0.0)
        return -value if self.is_reverse else value
    
    def get_sort_from_number(self, metric): 
        """Legacy method for backward compatibility"""
        if self.is_reverse:
            return -metric
        return metric

    # ------------------------------------------------------------------
    # Priority-list helpers
    #
    # Historically `priority_list` was a list of bare Sorting enums and
    # `weights` was a Dict[Sorting, int]. That data model collapsed when
    # the UI started allowing the same metric to appear twice with
    # different targets (e.g. "minimize steps per normal item" then
    # "minimize steps per chest" as a tiebreaker): the dict keyed by
    # Sorting silently overwrote the first entry's target with the
    # second, so the optimizer scored against only one target.
    #
    # The new model is a list of SortingEntry values where each entry
    # owns its own target and weight. These helpers accept either bare
    # Sorting enums (wrapped into default entries via _as_entry) or
    # SortingEntry instances, so existing callsites keep working.
    # ------------------------------------------------------------------

    @staticmethod
    def _as_entry(item):
        """Coerce a bare Sorting enum into a default SortingEntry.
        
        Leaves SortingEntry instances untouched. Used by the comparison
        helpers so callers can pass either shape.
        """
        if isinstance(item, SortingEntry):
            return item
        return SortingEntry(sort=item)

    @staticmethod
    def compare_by_priority(metrics_a: dict, metrics_b: dict, priority_list: list) -> bool:
        """
        Compare two metrics dicts using priority list.
        
        Args:
            metrics_a: First metrics dict
            metrics_b: Second metrics dict
            priority_list: List of SortingEntry (or bare Sorting) items in
                priority order. Each entry may carry its own target to
                resolve duplicable metrics to distinct composite keys.
        
        Returns:
            True if A is strictly better than B, False otherwise.
        """
        entries = [Sorting._as_entry(e) for e in priority_list]
        for entry in entries:
            val_a = entry.get_sort_value(metrics_a)
            val_b = entry.get_sort_value(metrics_b)
            
            if val_a < val_b:
                return True  # A is better (lower is better after negation)
            elif val_a > val_b:
                return False  # B is better
            # Equal, continue to next priority
        
        return False  # All equal
    
    @staticmethod
    def is_better(metrics_new: dict, metrics_old: dict, priority_list: list) -> bool:
        """
        Check if new metrics are better than old metrics.
        
        Args:
            metrics_new: New metrics dict to test
            metrics_old: Old/current metrics dict (can be None for first iteration)
            priority_list: List of SortingEntry (or bare Sorting) items in
                priority order.
        
        Returns:
            True if new metrics are better, False otherwise
        """
        if metrics_old is None:
            return True  # First valid result is always "better"
        
        return Sorting.compare_by_priority(metrics_new, metrics_old, priority_list)

    @staticmethod
    def calculate_floors(priority_list, weights, baseline_metrics, max_metrics):
        """
        Calculate floor values for each metric based on weights.
        
        Floor = baseline + (max_achievable - baseline) × (weight / 100)
        
        For entries with weight=100%, returns None at that key (they use
        dynamic floors tracked during local search, identical to current
        is_better behavior).
        
        Floors are keyed by the *composite* metric key (e.g.
        "steps_per_reward_roll::cat:chests") so duplicable metrics with
        different targets get independent floors.
        
        Args:
            priority_list: List of SortingEntry (or bare Sorting)
            weights: Legacy Dict[Sorting, int]. Used as a fallback when
                a priority entry is a bare Sorting enum without its own
                weight attribute. When an item in priority_list is a
                SortingEntry, its own .weight is authoritative.
            baseline_metrics: Dict of metric values with no gear
            max_metrics: Dict of best metric values from greedy passes
        
        Returns:
            Dict mapping composite metric_key → floor value (None for
            100% weight metrics)
        """
        import math
        floors = {}
        # Defensive: weights may be None at legacy CLI callsites.
        weights = weights or {}
        for raw in priority_list:
            entry = Sorting._as_entry(raw)
            # Per-entry weight on SortingEntry wins; bare enums fall back
            # to the legacy weights dict; missing → 100.
            if isinstance(raw, SortingEntry):
                weight = entry.weight
            else:
                weight = weights.get(entry.sort, 100)
            
            key = entry.metric_key
            baseline = baseline_metrics.get(key, baseline_metrics.get(entry.sort.metric_key, 0.0))
            max_val = max_metrics.get(key, max_metrics.get(entry.sort.metric_key, 0.0))
            
            if weight >= 100:
                floors[key] = None  # Dynamic floor (strict no-regression)
            elif weight == 0:
                floors[key] = None  # Ignored completely — no floor constraint
            else:
                # Handle inf/nan: if both are inf or equal, floor = baseline (unconstrained)
                if math.isinf(baseline) and math.isinf(max_val):
                    floors[key] = baseline  # Both inf — metric is unconstrained
                elif math.isinf(baseline) or math.isinf(max_val):
                    floors[key] = baseline  # One is inf — use baseline as safe default
                else:
                    floor_val = baseline + (max_val - baseline) * (weight / 100.0)
                    floors[key] = floor_val if not math.isnan(floor_val) else baseline
        
        return floors

    @staticmethod
    def is_better_with_floors(metrics_new, metrics_old, priority_list, weights, static_floors):
        """
        Compare gearsets using a threshold-based weight system.

        Weight semantics:
          - weight=100: strict priority — optimize fully (no regression allowed)
          - weight=1-99: threshold — the floor is a MINIMUM, not a target.
                         Once both gearsets clear the floor, keep optimizing:
                         whichever is better on the raw metric wins. If they
                         tie on this metric, fall through to the next entry.
                         If one gearset clears the floor and the other doesn't,
                         the one that clears wins (the floor is a hard
                         minimum). If neither clears the floor, the one that
                         is closer to clearing wins (strict raw compare).
          - weight=0: ignored entirely — no constraint, no optimization

        Algorithm:
        1. If metrics_old is None → True (first result always wins).
        2. For each entry in priority order:
           a. weight=0: skip.
           b. weight=100: strict lex — improvement → True, regression → False.
           c. weight=1-99 (threshold):
              - If one meets the floor and the other doesn't: the one that
                meets wins (accept/reject accordingly).
              - Otherwise (both meet or both fail): strict raw compare on
                this metric. Better → True, worse → False, equal → continue.
        3. All entries exhausted → False (equal).

        Design note: Older versions of this function skipped the raw-value
        compare when both gearsets cleared the floor, which made it
        impossible for the local search to catch Pareto improvements on
        weighted metrics (e.g. swapping a legs item that trades wasted WE
        for real chest-finding when XP is unchanged). That caused
        user-visible "why didn't it swap?" bugs. The floor now behaves as a
        minimum constraint on top of normal priority-order optimization.
        """
        if metrics_old is None:
            return True

        import math
        entries = [Sorting._as_entry(e) for e in priority_list]

        def _weight(entry):
            w = entry.weight
            if weights is not None and entry.sort in weights:
                w = weights[entry.sort]
            return w

        for entry in entries:
            weight = _weight(entry)

            if weight == 0:
                continue  # ignored entirely

            new_sort = entry.get_sort_value(metrics_new)
            old_sort = entry.get_sort_value(metrics_old)

            if not math.isfinite(new_sort) or not math.isfinite(old_sort):
                continue

            if weight >= 100:
                # Strict: improvement → accept, regression → reject
                if new_sort < old_sort:
                    return True
                elif new_sort > old_sort:
                    return False
                # equal → continue
                continue

            # Threshold (weight 1..99)
            key = entry.metric_key
            floor = static_floors.get(key)
            if floor is None:
                floor = static_floors.get(entry.sort.metric_key)

            if floor is None or not math.isfinite(floor):
                # No floor computed — treat as strict raw compare
                if new_sort < old_sort:
                    return True
                elif new_sort > old_sort:
                    return False
                continue

            # floor is stored as a raw metric value (not sort-space).
            # get_sort_value negates maximize metrics, so convert floor too.
            floor_sort = -floor if entry.sort.is_reverse else floor

            # "meets" means at or better than the breakpoint.
            # Lower sort value = better (after negation for maximize metrics).
            new_meets = new_sort <= floor_sort
            old_meets = old_sort <= floor_sort

            if new_meets and not old_meets:
                return True   # new clears the hard minimum, old doesn't
            if not new_meets and old_meets:
                return False  # old clears the hard minimum, new doesn't

            # Both meet or both fail → strict raw compare on this metric.
            # This is the key difference from the older threshold-skip
            # behavior: the floor is a minimum, not a target, so we keep
            # optimizing past it.
            if new_sort < old_sort:
                return True
            if new_sort > old_sort:
                return False
            # equal → continue to next priority
        return False  # all entries exhausted, equal


# ============================================================================
# SORTING ENTRY
# ============================================================================
#
# A SortingEntry is one slot in an optimizer's priority list. It carries:
#   - sort: the Sorting enum (defines direction + base metric key)
#   - target: optional string that targets this metric at a specific
#     drop category (e.g. 'cat:chests'), item, or quality. Only meaningful
#     for duplicable metrics. The composite metric_key becomes
#     "<sort.metric_key>::<target>" so that two entries with the same
#     Sorting enum but different targets produce independent values on
#     the same gearset metrics dict.
#   - weight: 0-100 weight used by floor/tiebreaker logic in
#     is_better_with_floors. Defaults to 100 (strict).
#
# This class replaces the previous (priority_list, weights_dict,
# targets_dict) trio that collapsed when a metric appeared twice.
# ============================================================================

def _compose_metric_key(base_key: str, target: Optional[str]) -> str:
    """Build the composite metrics-dict key for (base_key, target)."""
    if not target:
        return base_key
    return f"{base_key}::{target}"


@dataclass(frozen=True)
class SortingEntry:
    """One entry in an optimizer's priority list.
    
    Pairs a Sorting enum with an optional target and weight so duplicable
    metrics (e.g. steps_per_reward_roll) can appear multiple times with
    different targets and be tracked independently on the same gearset.
    """
    sort: 'Sorting'
    target: Optional[str] = None
    weight: int = 100
    
    @property
    def metric_key(self) -> str:
        """Composite metric-dict key: base key or base::target."""
        return _compose_metric_key(self.sort.metric_key, self.target)
    
    @property
    def is_reverse(self) -> bool:
        """Pass-through for direction (maximize metrics are reverse-sorted)."""
        return self.sort.is_reverse
    
    @property
    def display_name(self) -> str:
        """Pass-through display name for UI panels (e.g. alternatives)."""
        return self.sort.display_name
    
    def get_sort_value(self, metrics: dict) -> float:
        """Get the sortable value from metrics dict (negated if maximizing).
        
        Lookup order:
          1. Composite key "<base>::<target>" (if target set)
          2. Bare base key (legacy / target-agnostic fallback)
          3. 0.0
        
        The fallback chain means older code that only populates the bare
        key still works correctly when a target-aware entry happens to
        be passed in — the entry just sees the target-agnostic value.
        """
        value = metrics.get(self.metric_key)
        if value is None and self.target:
            value = metrics.get(self.sort.metric_key)
        if value is None:
            value = 0.0
        return -value if self.sort.is_reverse else value
    
    def __repr__(self) -> str:
        target_part = f", target={self.target!r}" if self.target else ""
        weight_part = f", weight={self.weight}" if self.weight != 100 else ""
        return f"SortingEntry({self.sort.name}{target_part}{weight_part})"


# ============================================================================
# X-PER-Y RATIO SORTING HELPERS
# ============================================================================
#
# The recipe optimizer settings UI models every priority as a generic
# X-per-Y ratio (e.g. materials per quality, xp per step) plus a separate
# "budget" mode. Internally the scorer still runs on the named legacy
# Sorting enum values because all 10 current X/Y combinations plus budget
# already correspond to metrics computed by optimize_craft_gearsets.
#
# The helpers below translate between the UI dict form and the internal
# SortingEntry used by the optimizer. Novel X/Y combinations that don't
# map to an existing legacy metric are skipped (returning None). Adding
# support for additional combos is a follow-up — the XY_RATIO enum value
# is reserved for that future extension.
# ============================================================================

# X direction: True means "more is better" (maximize), False means
# "less is better" (minimize). Used by the UI and the future XY_RATIO
# scorer so there's a single source of truth for ratio direction.
XY_MAXIMIZE_X_AXES = {'xp', 'total_crafts'}
XY_MINIMIZE_X_AXES = {'materials', 'expected_steps', 'displayed_steps', 'action'}


def xy_is_maximize(x_axis: str) -> bool:
    """Return True if X-per-Y ratios on this X axis should be maximized."""
    return x_axis in XY_MAXIMIZE_X_AXES


# Map each (X, Y) pair that the UI exposes to the legacy Sorting enum
# that already scores it. Target handling is per-entry (quality name,
# chest category) and stored on the SortingEntry.target field.
#
# Structure: (x, y) -> Sorting enum value (resolved lazily below since
# Sorting is defined earlier in the module).
_XY_TO_LEGACY_SORTING_NAMES = {
    ('materials',       'quality'):     'MATERIALS',               # materials_for_target (quality target)
    ('total_crafts',    'quality'):     'TOTAL_CRAFTS_FOR_TARGET', # total_crafts (quality target)
    ('expected_steps',  'quality'):     'TOTAL_STEPS',             # steps_for_target (quality target)
    ('expected_steps',  'craft'):       'STEPS_PER_CRAFT',         # expected_steps_per_item
    ('displayed_steps', 'craft'):       'DISPLAYED_STEPS_PER_CRAFT', # current_steps
    ('materials',       'craft'):       'MATERIALS_PER_CRAFT',     # materials_per_craft
    ('xp',              'step'):        'XP_PER_STEP',             # primary_xp_per_step
    ('xp',              'action'):      'PRIMARY_XP',              # primary_xp_per_action
    ('materials',       'target_item'): 'MATERIALS_PER_CHEST',     # materials per target item
    ('expected_steps',  'target_item'): 'STEPS_PER_CHEST_RECIPE',  # steps per target item (AGT, chests, ectoplasm, ...)
    ('xp',              'materials'):   'XP_PER_MATERIAL',         # xp_per_material
}


# X-only/Y-only axes that name the SAME physical quantity. The split is
# a UI/dropdown convention (only certain axes can appear on each side),
# not a semantic difference. When resolving an (x, y) pair we substitute
# these aliases so that e.g. (total_crafts, materials) auto-resolves via
# (materials, craft) — they describe the same dominance ordering.
#
# Direction: maps an X-side name to its Y-side equivalent (and vice
# versa). Symmetric — alias[alias[k]] == k.
_XY_AXIS_ALIASES = {
    'total_crafts':   'craft',
    'craft':          'total_crafts',
    'expected_steps': 'step',
    'step':           'expected_steps',
}


def _resolve_xy_pair(x: str, y: str, table: dict) -> Optional[str]:
    """Resolve an (x, y) pair to a Sorting enum name in the given table.

    Tries the direct pair first, then the inverse pair (y, x), then the
    same two with axis-alias substitutions applied. The inverse fallback
    works because for ordering gearsets, X/Y and Y/X always produce the
    same answer — A has more crafts/material than B iff A has fewer
    materials/craft than B. The existing enum's min/max direction on
    the inverse metric is automatically the correct comparison for the
    original (x, y) request, so no "inverted" flag is needed on the
    resulting SortingEntry.

    Lookup order:
      1. (x, y)                              — direct
      2. (y, x)                              — inverse
      3. (alias(x), alias(y))                — alias-direct
      4. (alias(y), alias(x))                — alias-inverse

    Returns the Sorting enum NAME (string) or None if nothing matches.
    """
    if not x or not y:
        return None
    # 1. Direct
    name = table.get((x, y))
    if name:
        return name
    # 2. Inverse (X/Y == Y/X for ordering)
    name = table.get((y, x))
    if name:
        return name
    # 3+4. Apply axis aliases. Substitute when the canonical form is
    # different — total_crafts ↔ craft, expected_steps ↔ step.
    ax = _XY_AXIS_ALIASES.get(x)
    ay = _XY_AXIS_ALIASES.get(y)
    if ax is not None or ay is not None:
        cx = ax if ax is not None else x
        cy = ay if ay is not None else y
        # 3. alias-direct
        name = table.get((cx, cy))
        if name:
            return name
        # 4. alias-inverse
        name = table.get((cy, cx))
        if name:
            return name
    return None


def xy_entry_to_sorting_entry(entry: dict) -> Optional['SortingEntry']:
    """Translate a UI dict entry (ratio or budget) into a SortingEntry.

    Returns None when the (x, y) pair doesn't correspond to a scored
    metric yet. The caller is responsible for dropping those from the
    active priority list (they'll be preserved on the session so the UI
    keeps showing them to the user).

    Args:
        entry: Dict with fields {mode, x, y, weight, quality, targetItem,
            budgetMats, budgetTarget, hiddenInQuick} as produced by
            migrate_recipe_sorting.

    Returns:
        SortingEntry for scored entries, None for unsupported combos.
    """
    if not isinstance(entry, dict):
        return None

    mode = entry.get('mode')
    weight = entry.get('weight', 100)
    try:
        weight_int = max(0, min(100, int(weight)))
    except (ValueError, TypeError):
        weight_int = 100

    if mode == 'budget':
        return SortingEntry(sort=Sorting.STEPS_FOR_BUDGET, weight=weight_int)

    if mode != 'ratio':
        return None

    x = entry.get('x')
    y = entry.get('y')
    pair = (x, y)

    sorting_name = _resolve_xy_pair(x, y, _XY_TO_LEGACY_SORTING_NAMES)
    if not sorting_name:
        return None

    sorting_enum = getattr(Sorting, sorting_name, None)
    if sorting_enum is None:
        return None

    # Per-entry target: quality for y='quality' entries, category (e.g.
    # cat:chests) for y='target_item' entries. Legacy entries without an
    # explicit target fall through to the optimizer's defaults.
    target = None
    if y == 'quality':
        quality = entry.get('quality')
        if isinstance(quality, str) and quality:
            target = quality
    elif y == 'target_item':
        ti = entry.get('targetItem')
        if isinstance(ti, str) and ti:
            target = ti

    return SortingEntry(sort=sorting_enum, target=target, weight=weight_int)


def xy_entries_to_sorting_entries(
    entries: list,
    *,
    include_hidden: bool = True,
    logger=None,
) -> List['SortingEntry']:
    """Translate a UI sorting list (new dict form) into a SortingEntry list.

    Args:
        entries: List of dict entries in the new X-per-Y form.
        include_hidden: If False, entries with hiddenInQuick=True are
            skipped. The optimizer itself should typically pass True
            (hidden-from-Quick is a UI concept, not a scoring concept);
            the Quick panel pass False when rendering its filtered view.
        logger: Optional callable(str) for warnings on unsupported combos.

    Returns:
        List of SortingEntry — entries that couldn't be resolved are
        silently dropped. Order of the input list is preserved.
    """
    result: List[SortingEntry] = []
    if not entries:
        return result
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        if not include_hidden and entry.get('hiddenInQuick'):
            continue
        se = xy_entry_to_sorting_entry(entry)
        if se is None:
            if logger:
                x = entry.get('x')
                y = entry.get('y')
                logger(f"[xy-sort] skipping unsupported X/Y combo: x={x!r}, y={y!r}")
            continue
        result.append(se)
    return result


# ============================================================================
# ACTIVITY X-PER-Y RATIO SORTING HELPERS
# ============================================================================
#
# Activities use the same X-per-Y dict shape as recipes but a different
# axis catalog. Recipe-only concepts (Materials, Crafts, Quality) are
# absent because activities don't consume inputs, don't have a craft
# event, and don't roll quality outcomes. Activity-only concepts
# (Reward roll as a sub-action denominator) replace them.
#
# The user-facing "Steps" axis covers both the X (numerator, "Steps")
# and Y (denominator, "per Step") roles — the recipe split between
# 'expected_steps' (X-only) and 'step' (Y-only) collapses into a single
# 'steps' value here. Internally that still maps to the right legacy
# metric: (steps, action) → expected_steps_per_action,
# (xp, steps) → primary_xp_per_step.
#
# Like the recipe table, only X/Y combos that already have a scored
# metric in optimize_activity_gearsets.py / activity_metrics.py are
# mapped. Novel combos return None — the UI keeps showing them but
# they don't contribute to scoring until a future XY_RATIO scorer
# lands.
# ============================================================================

# Direction sets specifically for the activity axis catalog. Kept
# separate from the recipe sets because the activity catalog uses the
# merged 'steps' axis (= recipe 'expected_steps' + 'step') and adds
# 'reward_roll' / 'total_xp'. The two catalogs are also free to diverge
# in direction conventions later if game mechanics demand it.
XY_ACTIVITY_MAXIMIZE_X_AXES = {'xp', 'total_xp'}
XY_ACTIVITY_MINIMIZE_X_AXES = {'action', 'steps', 'reward_roll'}


def xy_activity_is_maximize(x_axis: str) -> bool:
    """Return True if activity X-per-Y ratios on this X axis should be maximized."""
    return x_axis in XY_ACTIVITY_MAXIMIZE_X_AXES


# Map each (X, Y) pair the activity UI exposes to the legacy Sorting
# enum that already scores it. Per-entry target (e.g. cat:chests) goes
# on SortingEntry.target.
#
# Combos NOT in this table (e.g. xp/target_item, action/reward_roll)
# don't have a precomputed metric yet — they're preserved on the
# session for the UI but don't contribute to scoring. When the
# XY_RATIO scorer lands we can drop the table and compute generically.
_XY_ACTIVITY_TO_LEGACY_SORTING_NAMES = {
    # Steps-as-numerator
    ('steps',     'action'):      'EXPECTED_STEPS_PER_ACTION',  # expected_steps_per_action
    ('steps',     'reward_roll'): 'STEPS_PER_REWARD_ROLL',      # steps_per_reward_roll (no target)
    ('steps',     'target_item'): 'STEPS_PER_REWARD_ROLL',      # steps_per_reward_roll::cat:* (duplicable)
    # Primary XP
    ('xp',        'steps'):       'XP_PER_STEP',                # primary_xp_per_step
    ('xp',        'action'):      'PRIMARY_XP',                 # primary_xp_per_action
    # Total XP (all skills combined)
    ('total_xp',  'steps'):       'TOTAL_XP_PER_STEP',          # total_xp_per_step
    ('total_xp',  'action'):      'TOTAL_XP',                   # total_xp_for_action
}


def xy_activity_entry_to_sorting_entry(entry: dict) -> Optional['SortingEntry']:
    """Translate a UI activity dict entry (ratio) into a SortingEntry.

    Returns None when the (x, y) pair doesn't correspond to a scored
    metric yet. The caller is responsible for dropping those from the
    active priority list (they're preserved on the session so the UI
    keeps showing them to the user).

    Activity entries do NOT support 'budget' mode — activities have no
    finite produce-N-mats goal. They also do NOT carry a 'quality'
    field. The 'targetItem' field is only meaningful for y='target_item'.

    Args:
        entry: Dict with fields {mode, x, y, weight, targetItem,
            hiddenInQuick, editing} as produced by
            migrate_activity_sorting_to_xy.

    Returns:
        SortingEntry for scored entries, None for unsupported combos.
    """
    if not isinstance(entry, dict):
        return None

    mode = entry.get('mode')
    weight = entry.get('weight', 100)
    try:
        weight_int = max(0, min(100, int(weight)))
    except (ValueError, TypeError):
        weight_int = 100

    if mode != 'ratio':
        return None

    x = entry.get('x')
    y = entry.get('y')
    pair = (x, y)

    sorting_name = _resolve_xy_pair(x, y, _XY_ACTIVITY_TO_LEGACY_SORTING_NAMES)
    if not sorting_name:
        return None

    sorting_enum = getattr(Sorting, sorting_name, None)
    if sorting_enum is None:
        return None

    # Per-entry target: only meaningful for y='target_item'. Activity
    # targets are richer than recipe targets (cat:chests, cat:fine,
    # cat:collectibles, cat:gems, cat:coins, cat:if:*, etc.) — the
    # bridge is target-shape-agnostic, the optimizer's scorer handles
    # category lookup.
    target = None
    if y == 'target_item':
        ti = entry.get('targetItem')
        if isinstance(ti, str) and ti:
            target = ti

    return SortingEntry(sort=sorting_enum, target=target, weight=weight_int)


def xy_activity_entries_to_sorting_entries(
    entries: list,
    *,
    include_hidden: bool = True,
    logger=None,
) -> List['SortingEntry']:
    """Translate a UI activity sorting list (new dict form) into a SortingEntry list.

    Args:
        entries: List of dict entries in the new X-per-Y form.
        include_hidden: If False, entries with hiddenInQuick=True are
            skipped. The optimizer itself should typically pass True
            (hidden-from-Quick is a UI concept, not a scoring concept);
            the Quick panel passes False when rendering its filtered view.
        logger: Optional callable(str) for warnings on unsupported combos.

    Returns:
        List of SortingEntry — entries that couldn't be resolved are
        silently dropped. Order of the input list is preserved.
    """
    result: List[SortingEntry] = []
    if not entries:
        return result
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        if not include_hidden and entry.get('hiddenInQuick'):
            continue
        se = xy_activity_entry_to_sorting_entry(entry)
        if se is None:
            if logger:
                x = entry.get('x')
                y = entry.get('y')
                logger(f"[xy-activity-sort] skipping unsupported X/Y combo: x={x!r}, y={y!r}")
            continue
        result.append(se)
    return result


# Region enum
class Region(Enum):
    """Regions or Location keywords in Walkscape"""
    JARVONIA = "jarvonia"
    GDTE = "gdte"
    TRELLIN = "trellin"
    ERDWISE = "erdwise"
    HALFLING_REBELS = "halfling_rebels"
    SYRENTHIA = "syrenthia"
    WALLISIA = "wallisia"
    WRENTMARK = "wrentmark"
    # keywords
    UNDERWATER = "underwater"
    SPECTRAL = "spectral"


# Skill class with matching methods
class SkillInstance:
    """Individual skill instance with matching methods"""
    
    def __init__(self, name: str, value: str, component_skills: list = None):
        """
        Args:
            name: Display name (e.g., "COOKING")
            value: Internal value (e.g., "cooking")
            component_skills: List of skill values this skill combines (for TRAVEL)
        """
        self.name = name
        self.value = value
        self.component_skills = component_skills or [value]
    
    def matches_skill(self, stats_skill: str) -> bool:
        """
        Check if this skill matches a stats skill key.
        
        Args:
            stats_skill: Skill key from stats dict (e.g., "cooking", "global", "agility", "gathering", "artisan", "utility")
        
        Returns:
            True if this skill should include stats from stats_skill
        
        Examples:
            Skill.COOKING.matches_skill("cooking") -> True
            Skill.COOKING.matches_skill("global") -> True
            Skill.COOKING.matches_skill("artisan") -> True (cooking is artisan)
            Skill.FORAGING.matches_skill("gathering") -> True (foraging is gathering)
            Skill.AGILITY.matches_skill("utility") -> True (agility is utility)
            Skill.TRAVEL.matches_skill("agility") -> True
            Skill.TRAVEL.matches_skill("traveling") -> True
            Skill.TRAVEL.matches_skill("global") -> True
        """
        # Handle None stats_skill (from malformed data)
        if stats_skill is None:
            return False
        
        stats_skill_lower = stats_skill.lower()
        
        # Always match global
        if stats_skill_lower == "global":
            return True
        
        # Check skill categories (for pets and other items that use categories).
        # We check against component_skills (not just self.value) so that combined
        # skills like TRAVEL (component_skills=["agility", "traveling"]) correctly
        # pick up utility-category stats (since agility IS utility). This is what
        # causes items like Aerofibril (stats under "utility") to apply when
        # optimizing traveling gearsets.
        if stats_skill_lower == "gathering":
            # Gathering: Fishing, Foraging, Mining, Woodcutting, Hunting
            gathering_skills = {"fishing", "foraging", "mining", "woodcutting", "hunting"}
            return any(cs.lower() in gathering_skills for cs in self.component_skills)
        
        if stats_skill_lower == "artisan":
            # Artisan: Carpentry, Cooking, Crafting, Smithing, Trinketry, Tailoring
            artisan_skills = {"carpentry", "cooking", "crafting", "smithing", "trinketry", "tailoring"}
            return any(cs.lower() in artisan_skills for cs in self.component_skills)
        
        if stats_skill_lower == "utility":
            # Utility: Agility (and combined skills containing agility, e.g. TRAVEL)
            return any(cs.lower() == "agility" for cs in self.component_skills)
        
        # Check if stats_skill is in our component skills
        return stats_skill_lower in self.component_skills
    
    def get_component_skills(self) -> list:
        """Get all component skills (for iterating when combining stats)"""
        return self.component_skills.copy()
    
    def __str__(self):
        return self.name
    
    def __repr__(self):
        return f"Skill.{self.name}"
    
    def __eq__(self, other):
        if isinstance(other, SkillInstance):
            return self.value == other.value
        return False
    
    def __hash__(self):
        return hash(self.value)


# Skill enum - container for all skill instances
class Skill:
    """Container for all skill instances - use like Skill.COOKING, Skill.TRAVEL, etc."""
    AGILITY = SkillInstance("AGILITY", "agility")
    CARPENTRY = SkillInstance("CARPENTRY", "carpentry")
    COOKING = SkillInstance("COOKING", "cooking")
    CRAFTING = SkillInstance("CRAFTING", "crafting")
    FISHING = SkillInstance("FISHING", "fishing")
    FORAGING = SkillInstance("FORAGING", "foraging")
    MINING = SkillInstance("MINING", "mining")
    SMITHING = SkillInstance("SMITHING", "smithing")
    # Special: Smelting is a sub-skill of Smithing. Recipes are categorized as
    # "smithing", but the subset in SMELTING_RECIPE_NAMES (bar smelting) also
    # picks up "smelting"-scoped stats (e.g. Tortoise L4's +2 bonus XP). Plain
    # SMITHING does NOT match the "smelting" scope, so non-smelting smithing
    # recipes are unaffected. Resolve a recipe to this skill ONLY when its name
    # is in util.autogenerated.pets.SMELTING_RECIPE_NAMES.
    SMELTING = SkillInstance("SMELTING", "smelting", ["smithing", "smelting"])
    TRINKETRY = SkillInstance("TRINKETRY", "trinketry")
    WOODCUTTING = SkillInstance("WOODCUTTING", "woodcutting")
    HUNTING = SkillInstance("HUNTING", "hunting")
    TAILORING = SkillInstance("TAILORING", "tailoring")
    GLOBAL = SkillInstance("GLOBAL", "global")
    TRAVELING = SkillInstance("TRAVELING", "traveling")
    # Special: combines multiple skills; used when actually getting final travel stats, 
    # not just "when traveling" stats
    TRAVEL = SkillInstance("TRAVEL", "travel", ["agility", "traveling"])  

class ServiceCategory(Enum):
    BANK = "Bank"
    TRINKETRY = "Trinketry"
    SMITHING = "Smithing"
    COOKING = "Cooking"
    CARPENTRY = "Carpentry"
    CRAFTING = "Crafting"

class ServiceTier(Enum):
    BASIC = 1
    ADVANCED = 2

class ServicePrefix(Enum):
    BANK = "B:"
    TRINKETRY = "T:"
    COOKING = "K:"
    CARPENTRY = "C:"
    SMITHING = "S:"
    CRAFTING = "R:"


# ============================================================================
# AUTOGENERATED DATA - Import after enums to avoid circular imports
# ============================================================================

from util.attributes import * 
from util.autogenerated.locations import Location, LocationInfo
from util.autogenerated.equipment import Item
from util.autogenerated.materials import Material
from util.autogenerated.consumables import Consumable
from util.autogenerated.recipes import Recipe, RECIPES_BY_NAME, RECIPES_BY_SKILL
from util.autogenerated.services import Service, SERVICES_BY_NAME, SERVICES_BY_CATEGORY
from util.autogenerated.collectibles import Collectible, COLLECTIBLES_BY_NAME, by_export_name as collectible_by_export_name
from util.autogenerated.routes import RAW_ROUTES
from util.autogenerated.activities import Activity, ACTIVITIES_BY_NAME
from util.autogenerated.export_names import get_item_from_export_name, EXPORT_NAME_TO_ITEM
from util.autogenerated.containers import Container, CONTAINERS_BY_NAME, UNIQUE_OPENABLES, SKILL_CHESTS
from util.autogenerated.pets import Pet, Egg, EGGS_BY_NAME, PETS_BY_NAME


# ============================================================================
# SERVICE HELPER FUNCTIONS
# ============================================================================
def base_service(service: ServiceCategory, location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring service visit."""
    # Location enum values are LocationInfo objects with .name attribute
    if isinstance(location, Location):
        loc_str = location.name
    elif hasattr(location, 'name'):
        loc_str = location.name
    else:
        loc_str = str(location)
    prefix = ServicePrefix[service.name].value
    if tier == ServiceTier.ADVANCED:
        prefix = prefix[:-1] + "A:"  # Change "X:" to "XA:"
    return prefix + loc_str

def b(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring bank visit."""
    return base_service(ServiceCategory.BANK, location, tier)

def t(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring trinketry bench visit."""
    return base_service(ServiceCategory.TRINKETRY, location, tier)

def cook(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring cooking service visit."""
    return base_service(ServiceCategory.COOKING, location, tier)

def carp(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring carpentry service visit."""
    return base_service(ServiceCategory.CARPENTRY, location, tier)

def smith(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring smithing service visit."""
    return base_service(ServiceCategory.SMITHING, location, tier)

def craft(location: Union[Location, str], tier: ServiceTier = ServiceTier.BASIC) -> str:
    """Mark location as requiring crafting service visit."""
    return base_service(ServiceCategory.CRAFTING, location, tier)

# Advanced service shortcuts
def ta(location: Union[Location, str]) -> str:
    """Advanced trinketry bench."""
    return t(location, ServiceTier.ADVANCED)

def cooka(location: Union[Location, str]) -> str:
    """Advanced cooking service."""
    return cook(location, ServiceTier.ADVANCED)

def carpa(location: Union[Location, str]) -> str:
    """Advanced carpentry service."""
    return carp(location, ServiceTier.ADVANCED)

def smitha(location: Union[Location, str]) -> str:
    """Advanced smithing service."""
    return smith(location, ServiceTier.ADVANCED)

def crafta(location: Union[Location, str]) -> str:
    """Advanced crafting service."""
    return craft(location, ServiceTier.ADVANCED)


# ============================================================================
# XP AND LEVEL TABLES
# ============================================================================

# XP required for each level (index = level, value = total XP needed)
#   X0       X1       X2       X3       X4       X5       X6        X7        X8       X9        X0
LEVEL_XP = [
             0,       83,      174,     276,     388,     512,     650,      801,      969,
    #10
    1154,    1358,    1584,    1833,    2107,    2411,    2746,    3115,     3523,     3973,
    #20
    4470,    5018,    5624,    6291,    7028,    7842,    8740,    9730,     10824,    12031,
    #30
    13363,   14833,   16456,   18247,   20224,   22406,   24815,   27473,    30408,    33648,
    #40
    37224,   41171,   45529,   50339,   55649,   61512,   67983,   75127,    83014,    91721,
    #50
    101333,  111945,  123660,  136594,  150872,  166636,  184040,  203254,   224466,   247886,  
    #60
    273742,  302288,  333804,  368599,  407015,  449428,  496254,  547953,   605032,   668051,
    #70
    737627,  814445,  899257,  992895,  1096278, 1210421, 1336443, 1475581,  1629200,  1798808, 
    #80
    1986068, 2192818, 2421087, 2673114, 2951373, 3258594, 3597792, 3972294,  4385776,  4842295, 
    #90
    5346332, 5902831, 6517253, 7195629, 7944614, 8771558, 9684577, 10692629, 11805606, 13034431,
]


def xp_to_level(xp: int) -> int:
    """Convert XP to level"""
    for level, required_xp in enumerate(LEVEL_XP, start=1):
        if xp < required_xp:
            return level - 1
    return 99  # Max level


def level_to_xp(level: int) -> int:
    """Get XP required for a level"""
    if level < 1:
        return 0
    if level > 99:
        return LEVEL_XP[-1]
    return LEVEL_XP[level - 1]


def xp_equate(level: float) -> int:
    """XP equation algorithm for character level"""
    return int(level + 300 * (2 ** (level / 7)))


def xp_to_level_character(level: int) -> float:
    """Calculate the experience needed to level up character level"""
    xp = 0.0
    for i in range(1, level + 1):
        xp += xp_equate(float(i))
    return (int(xp / 4) * 4.6)


def character_level_from_steps(steps: int) -> int:
    """Calculate character level from total steps"""
    char_level = 1
    while char_level < 999:
        required_xp = xp_to_level_character(char_level + 1)
        if steps < required_xp:
            break
        char_level += 1
    return char_level


def tool_slots_for_level(char_level: int) -> int:
    """Get number of tool slots available at a given character level"""
    if char_level >= 80:
        return 6
    elif char_level >= 50:
        return 5
    elif char_level >= 20:
        return 4
    else:
        return 3
