#!/usr/bin/env python3
"""
Activity flavour-text descriptions, keyed by activity display name.

The WalkScape tools API does not publish activity descriptions, so this
overlay mirrors them from the wiki-sourced legacy activities.py. Applied
by emit_activities(). Drop this once the API exposes descriptions.
"""

ACTIVITY_DESCRIPTIONS = {
    'Alligator hunting': 'You go through the swamp, armed with your bow and arrows. Ready to turn gators into your newest accessories and maybe even get some cool scars out of it.',
    'Antique market assessor': 'The antique market in Blackspell Port is hectic, and it takes time to find buyers and sellers for various goods. You occasionally find a profitable transaction with a gem or rare item.',
    'Apprentice for Loif': 'Old man Loif Ulfrand needs many things, including hot drinks, tools sharpened, and his hair cut. But you occasionally get some experience tinkering with his tools when he falls asleep.',
    'Bear hunting': "Large claw scratches on trees indicate that you're on the right track to find bears in the surrounding area. Your senses are focused, and your body is ready to take one down.",
    'Bird feeding': 'You use some plants you have on you to lure in the local birds, bringing them close enough to observe before they take them and leave behind a mess of feathers.',
    'Bird watching': 'You carefully observe the birds of the area and make note of their appearances, calls, homes, and habits. As they fly off, you occasionally see them drop interesting items.',
    'Bodysurfing': "Before entering the water, you check the conditions: wind magnitude and direction, presence and size of rocks, presence of fishermen, boats or dangerous animals. You've even chatted with the locals. Everything is right. You go for a swim among the waves.",
    'Bog fishing (Net)': 'You cast net into the bog. The water is murky, but you can still see the fish swimming around. You wait patiently for them to get caught in your net.',
    'Bog fishing (Spear)': 'While under the waters of the bog, you ready your fishing spear, primed to strike any fish that comes close enough. The murky water makes it difficult to see, but you are determined to catch something.',
    'Box trapping': 'You set up a simple trapping system with a boxtrap. When a critter goes under it, it falls onto it, trapping it inside the box.',
    'Branch trimming': 'Cleaning up the branches near the ground helps prevent forest fires in these parts.',
    'Brig repair': 'You take part in repairs due to wear and tear of small vessels. Timbers, nails, rigging, fittings and ropes are at your disposal. The foreman gives the orders and you execute them masterfully. Maybe one day you will be the one giving the orders.',
    'Butterfly catching': 'Catching butterflies requires patience and a good net. Although chasing them is fun, the most efficient option is to catch them when they are still. Admiring them and releasing them afterwards preserves their role in the delicate natural balance.',
    'Cave diving': 'You bravely (or stupidly) dive into the dark, vast caves. This activity is one of the most dangerous in all of Arenum. It sure does make your heart pump and adrenaline fill your veins.',
    'Classic skiing': 'On your beginner cross-country skiing journey, every glide is filled with wonder. The snowy trails are your playground, where you learn the rhythm of the skis and embrace the serene beauty of the winter woods.',
    'Cleaning the holy fountain': "The temple leaders trust you enough to help with their holy fountain's upkeep. They allow you to fish through it with a net to keep the water clear, earning their respect.",
    'Cliff foraging': 'Perched on the edge of the towering cliff, you carefully explore the rugged terrain, searching for wild mountain herbs, resilient mushrooms, and other edible treasures that thrive in this elevated environment.',
    'Coral cutting': "Corals, some as big as small trees, surround you. You swing your hatchet at their stumps and chop them down one by one. Unlike trees on the surface, they don't hit the ground but float up instead.",
    'Crab tracking': 'Walking across the beach, you search for clues of nearby crabs. They leave specific prints in the sand, but unfortunately, those are often washed away by the water tides.',
    'Cut bamboo': 'You strike the bamboo with your hatchet. It makes a satisfying crunching sound.',
    'Cut birch trees': 'You swing your axe with all your might, determined to bring down the towering birch trees.',
    'Cut ectoplasm trees': 'The trees here look like they are torn from another realm, their eerie look and the ghostly energy they exude makes them intimidating even before attempting to fell them. You are eager to process the logs they will bring.',
    'Cut mangrove trees': 'While being careful not to trip over their entangling roots, you are working hard to get some logs of these fascinatingly shaped trees.',
    'Cut maple trees': 'With steady swings of your axe, you work to bring down the resilient maple trees, their sturdy trunks requiring persistence to overcome.',
    'Cut oak trees': "Steadfastly, you chop away at the towering oak trees, their sprawling branches reaching out like nature's embrace.",
    'Cut pine trees': 'You swing your axe with determination to bring down the pine trees.',
    'Cut spruce trees': 'Gripping your axe tightly, you channel your strength to strike down the towering spruce trees.',
    'Cut teak trees': 'Sweat on your forehead, blisters on your fingers, but you are determined to get some logs of this durable and strong wood.',
    'Cut willow trees': 'The wide trunks of these willows are proving to be a challenge, but with your skillful and powerful swings you manage to topple them one by one.',
    'Cut yew trees': 'The yew trees are sturdy and can take a lot more effort before they can be felled. Though with time, you manage to bring them down to segment into logs.',
    'Deer hunting': 'You look for deer droppings in the forest, a sure indication that they are to be found in the surrounding area. Your bow and arrow are ready to shoot one down.',
    'Dragonfly catching': 'You use your net to chase after and catch dragonflies that dart back and forth rapidly throughout the area.',
    'Drift net hunting': 'You untangle the huge net before setting it in the water. It can catch fish and other water creatures in hundreds, if the sea gods smile upon you.',
    'Ectoplasm fishing': 'The water here glows in strange and eerie hues that radiate with a ghostly energy. You wonder what the fish here eat and if you are even using the proper tool to catch them. Your mind wanders to the attempt of trying to cook them later to see if they are even edible.',
    'Ectoplasm slime hunting': 'You occasionally see the ectoplasm trails of the ghosts form together to create pestering slimes. With your hunting bow and some arrows, you can help destabilize them.',
    'Emergency darkness escape (Swamp)': "You've lost your light source and will have to find your way out of where you are through the dark. You must be careful to make your way out and avoid any dangerous creatures that may lurk in the shadows.",
    'Emergency desert escape': "You've lost your camel and will soon succumb to the desert elements. You will have to wander out from the harsh environment however possible.",
    'Emergency swim escape': "You've lost your diving gear and are running out of air. You must swim to the shore as fast as you can, but without panicking. You know that if you ascend too quickly, you could suffer from decompression sickness.",
    'Emergency swim escape (Swamp)': "You've lost your diving gear and are running out of air. You must swim to the shore as fast as you can, but without panicking. You know that if you ascend too quickly, you could suffer from decompression sickness.",
    'Erdwise dumpster diving': 'Amidst the labyrinthine alleyways of the city, you explore the forgotten corners, sifting through discarded odds and ends in hopes of unearthing hidden treasures among the cast-offs.',
    'Explore bog bottom': 'You follow your underwater map and explore the hidden path in the murky depths at the bottom of the bog. They seem to twist and turn endlessly, but they are leading you somewhere. You just have to keep swimming.',
    'Explore underwater cave': 'You follow your underwater map and explore the paths of the underwater cave. They seem to twist and turn endlessly, but they are leading you somewhere. You just have to keep swimming.',
    'Firewood making': "With patience, sweat, effort and your trusty hatchet, you split the logs mercilessly. If only you could split them with your bare hands. You'd have to be a superhero, to say the least.",
    'Flame stoking': 'When Helga rings the bell, you stoke the flames. A simple life.',
    'Flooded field scavenging': 'You wade through the wet fields in search of viable plants and materials that have managed to survive and even thrive in this damp environment.',
    'Flooded river fishing (Rod)': 'You cast your fishing rod into the flooded river waters, hoping to catch some unique fish that have adapted to their new environment.',
    'Forest foraging': "Amidst the winter forest, you venture with a keen eye, foraging for hidden treasures beneath the blanket of snow, embracing the thrill of discovering nature's edible offerings.",
    'Fossil mining': 'Lured by the wonders of the past you focus your attention on finding ancient fossils.',
    'GDTE skydisc course': "In intermediate skydisc golfing, you're developing a keen sense of strategy. Each course presents a new challenge, as you adeptly curve your disc around obstacles, honing your skills with every calculated throw.",
    'Ghost tag': "You chase around the spirited ghosts of Wraithwater participating in a game of tag. Each time it feels like you get close, they take the opportunity to phase through something. It feels like you will never not be 'it' against these opponents.",
    'Glacier foraging': 'You search far and wide through the empty glacier. You learn a lot about yourself, but is there anything here to find?',
    'Gold panning': 'This is rudimentary gold mining technique that takes advantage of sedimentary deposits in rivers. First, the pan is submerged in the bottom sand. Then, by shaking it by hand, the gravel is loosened until only the sand and possible gold nuggets are left.',
    'Graveyard foraging': "You tread through the graveyard and look for unique things out of place that have come loose from the floods in the area. It isn't grave robbing if it isn't still in the grave, right?",
    'Guard duty': "As a guard in the Wallisian Empire, you've got bills to pay, and this is how you do it. You watch over the kingdom, ensuring you get paid for your watchful eyes.",
    'Halfmaw tracking': 'You set out to track signs of the Halfmaw in the swamp to report back on its whereabouts. It may help the guild in a proper hunt against it later.',
    'Horseshoe making': "Using strong metal, you forge a shoe that will protect a horse's hoof in medium to hard terrain. Although nails are used for its fixation, the horse does not suffer since the hoof is not sensitive, similar to a very thick human fingernail.",
    'House jumping': 'With feline grace you travel around the city, using any architectural feature as help: walls, roofs, balconies, streetlights. They all bend to your wishes.',
    'Hull repair': 'You are no longer an apprentice carpenter, so you repair larger vessels without a problem. Your foreman trusts your skills and good judgment. You know when to be effective and when to be efficient. Your toolkit is professional, just like you.',
    'Hut jumping': "You climb up on an unlit lamppost, scanning the surroundings. You hear footsteps nearby, so you hurry over to the adjoining rooftop with a small jump. A tile comes loose and falls to the ground, causing a clatter. You'll have to be more careful next time.",
    'Ice sculpting': 'Armed with ice shaping tools and saws, you transform an ice cube into something else, either functional or artistic. The fleetness of this piece of art is proportional to the ambient temperature, its duration ranging from minutes to permanent.',
    'Isthmus sea fishing (Net)': 'In the coastal waters of the isthmus, you cast your net out, aiming to catch a variety of creatures that thrive in this area.',
    'Jarvonia skydisc course': "As a beginner in skydisc golfing, each throw is a new discovery. You learn to gauge the wind and navigate around trees, enjoying the game's simplicity and the joy of watching the disc soar towards the basket.",
    'Kayaking': "You check the paddles, seat and general condition of the kayak before putting it in the water. On yourself, helmet and waterproof clothing. The weather couldn't be better: sunshine, pleasant temperature and a light breeze. Let's enjoy a good paddling session!",
    'Kelp foraging': 'With an abundance of kelp swaying around you, you meticulously inspect each one before carefully plucking the best.',
    'Lake fishing': 'You carefully attach your bait with frosty fingers and cast it out upon the calm surface of the lake.',
    'Large sail repair': 'The large sail has seen some rough storms and is riddled with holes. You work quickly and precisely to patch up its holes, making it almost as good as new.',
    'Litter looting': 'Amongst the hustle and bustle of the city, you comb through discarded odds and ends, hoping to stumble upon a hidden gem among the common debris.',
    'Lizard hunting': 'You look for any clues of many lizard species living in the surrounding area. Hunting them is not dangerous, but surely tedious.',
    'Magnet fishing': 'Pulling stuff out of a water body with a strong magnet rarely pays the bills, but helps a couple of good causes: it cleans the environment and it helps solve crimes. Be mindful of the regulations around it and have fun! You could pull anything!',
    'Merfolk dancing': "Performing the merfolk dance like the underwater folk do requires a lot of skill. With each attempt, you're getting better at moving in unison with the other dancers, until you achieve a seamless flow, resembling a school of fish in their synchronized movement.",
    'Merfolk farm foraging': "Your Communal Sea Farm access grants you the freedom to forage in the endless underwater farm fields. Here, you'll find a vast array of plants waiting to be picked.",
    'Mine adamant ore': 'Finding the tough adamant rocks before you, you bring your best equipment out in attempts to remove the ore from the rock.',
    'Mine coal': "Each strike of your trusty pickaxe uncovers the veins of coal, essential in providing fuel for the realm's blacksmiths to forge weapons and armor that defend the kingdom.",
    'Mine copper ore': 'The rhythmic clinks of your pickaxe hitting the rocky surface fill the air as you persistently mine for copper ore.',
    'Mine crystal coal': 'Such large and beautiful rocks. It seems like such a shame to attempt mining from them, but the potential chunks they shatter into hold too much use to be left alone.',
    'Mine ectoplasm rocks': 'Outcrops of large rocks that seem to glow with the eerie, ghostly energy of the surrounding area. You swing your pickaxe at it in hopes of taking pieces of it with you for refinement.',
    'Mine farganite ore': 'With sweat and tears, you slowly extract some of the farganite despite its tremendous hardness.',
    'Mine gold ore': 'You notice glints of gold among the rocks and immediately get to mining it in hopes of finding the motherlode.',
    'Mine iron ore': 'Each of your swings reveals the humble beauty of iron ore, a reliable commodity with a wide range of practical uses.',
    'Mine silver ore': 'Out of the corner of your eye, you catch the sight of sliver rocks and get to work on tracing the vein of silver ore within.',
    'Mine tarsilium ore': 'In your venture to mine tarsilium ore, the deep, echoing chambers of the earth become your canvas, and the discovery of each new vein feels like unearthing a piece of history.',
    'Mine tarsilium ore (Underwater)': "The light is bad underwater, but it's not different than a cave. With tarsilium, it's always hard to see the black ore in a dark environment.",
    'Mine tin ore': 'The sound of your pickaxe resonates through the mining site as you tirelessly chip away, uncovering the hidden veins of tin ore waiting to be discovered.',
    'Mine violite ore': 'You assess the violet rocks of hard violite in front of you and plot your path to best extract ores from them without hurting yourself in the process.',
    'Mine volcanic rock': 'Swinging your pickaxe underwater is challenging, but occasionally upon striking the volcanic rock a big enough piece breaks loose which you then stuff in your backpack.',
    'Mountain climbing': 'You prepare for your climb. It is a beautiful day with sunshine and no wind. Still, as you slowly climb, your heart skips a beat and you lose grip on one foot. What a scare! Finally you reach the top and look proudly at the world beneath your feet.',
    'Plains foraging': 'With each gentle stride across the plains, you immerse yourself in the natural abundance, gathering wild berries, seeds, and tender shoots that thrive in the soil beneath your feet.',
    'Predator fishing (Spear)': 'Driven by the hunt, you slice through the deep water, hyper-aware of your surroundings. Every fiber of your being is primed to strike any predator before it can strike you.',
    'Rabbit tracking': 'You pay attention to the nibbled plants, broken twigs, and rabbit footprints in the ground as you search for the critters.',
    'Repair the bank': 'Using some ectoplasm with your carpentry skills, you repair the necessities of the bank to restore it back to being usable.',
    'Rescue team': 'Use information from the search teams to actively go and carry out rescue operations.',
    'Ridge scrambling': 'Now we are talking. This wall is almost vertical and there are no easily accessible grab points. You climb it with tenacity, feeling your muscles suffer to give you the power you need. The top tastes like blood and glory. You scream with the air you have left.',
    'Run for your life': 'You feel claustrophobic as the darkness closes in around you and feel like you are being watched. You start to run for your life, with no sense of direction.',
    'Sandcastle building': "Building sandcastles on the beach is all about easygoing creativity. Your sandy creations may not last long, but it's a simple pleasure in the moment.",
    'Sea fishing (Cage)': 'A nutrient dense current brings all sorts of crustaceans to the area.',
    'Sea fishing (Net)': 'Along the shoreline, you find a secluded spot and cast your net into the calm waters, enjoying the peaceful solitude of sea fishing.',
    'Sea fishing (Rod)': 'Along the shoreline, you find a secluded spot and cast your rod into the calm waters, enjoying the peaceful solitude of sea fishing.',
    'Sea fishing (Spear)': 'With spear grasped firmly, you swim loops around the shipwreck, ever vigilant for any large fish that dares to approach within striking distance.',
    'Search team': 'Help the adventuring guild locate and find information on open permits that have not returned.',
    'Seashell searching': 'You search carefully along the coast for any valuable seashells or pearls.',
    'Shoreline scramble': 'You angle around the ridges of the narrow shoreline and dart amongst the nearby wreckages and rock formations of the area. Losing your footing around here would make quite the splash in the waters below.',
    'Skate skiing': 'Skate skiing brings a sense of adventure. You tackle varied terrains with newfound confidence, each stride stronger and more assured, as you explore the vast, snow-covered expanses.',
    'Sledding': "As you grip the sled's handles and push off, you feel the rush of adrenaline course through your veins. The world blurs around you, and for a moment, you're a winter speedster conquering the snow-covered hill.",
    'Small sail repair': "Using a sturdy needle and thread, you carefully sew multiple patches of fabric to repair the boat's sails. They will not be as good as new, but will surely last for a while.",
    'Soup kitchen volunteering': 'Still dressed in your street clothes, you put on an apron and following the instructions of the chef, you start serving hot soup to those who need it most. When everyone has received their ration, you feel a mix of pride, modesty and a sense of community.',
    'Spelunking': 'You crawl on the hard ground like a lizard. Ominous thoughts cloud your mind almost paralyzing you. You manage to push them aside for a moment and continue. Soon enough a new unexplored path unveils itself and fills you with joy.',
    'Spring bat tracking': 'The bats leave the cave flying towards the north-east. Following the bats from their spring home, running day and night to find where their next home is. You might not be back here for a while.',
    'Spring cave foraging': "Bats make their home in the springtime here. It's dark, better bring a light.",
    'Squirrel hunting': 'You have seen them all the time, but now they try to hide from you. The squirrels are your prey and your arrows will bring them down.',
    'Stone quarrying': 'Rock and stone!',
    'Summer cave foraging': "Bats make their home in the summertime here. It's dark, better bring a light.",
    'Surface copper mining': 'Still on the surface, you mine outcrops of rocks that vaguely look to contain copper ore, the rocks are tough to give any up.',
    'Surface salt mining': 'Extracting salt in a mine is hard work because you get dehydrated very quickly due to the constant contact with the salt. Luckily for you, these halite (salt rock) crystals are on the well-ventilated surface and come off easily when you hit them with a pickaxe.',
    'Surface swimming': "You've been told that swimming is a way to maintain good health, so after a few lessons, you feel confident to try it for yourself.",
    'Surface tin mining': 'Finding outcropped rocks on the surface potentially containing tin ore, you will need fortitude and perseverance to mine them out.',
    'Swamp foraging': 'You search through the murky land and water for valuable flowers and plants.',
    'Tinkering': "You scratch your chin as you think about how you can fix this junk. You come up with a thousand ways to do it, but for most of them you're missing components. You look around the workshop, searching for something specific. There it is! Let's get to work.",
    'Treasure hunt': "The Adventurer's Guild has set a challenge to find some special items around the Horn of Respite. How long will it take you to find them all?",
    'Trellin dumpster diving': 'Amidst the labyrinthine alleyways of the city, you explore the forgotten corners, sifting through discarded odds and ends in hopes of unearthing hidden treasures among the cast-offs.',
    'Underwater aqueduct construction': 'You build and reinforce the natural water pipeline heading towards the Halfling Campground.',
    'Underwater aqueduct digging': "Dig the way for the carpenters who come behind you. Removing the debris in the way, while ensuring the area doesn't collapse.",
    'Underwater basket weaving': 'You deftly weave the thin pieces of coral into a basket. The process is slow and tedious, but the end result fills your heart with pride of your creation.',
    'Underwater swimming': 'Swimming through the various paths and caves of the vast underwater city of Vastalume proves challenging. You must evade the bustling sea creatures, both sentient and non-sentient.',
    'Unicorn hunting': 'You can feel them watching you with their menacingly unfazed stares, their horns pointed and ready to strike at you. You would crush them with a boulder if you could, but your hunting bow and arrows will have to do.',
    'Vegetable chopping': "It's a stressful environment with the chef yelling at you and having no clue what to do, but you occasionally chop a vegetable the correct way.",
    'Venture into the bog': 'You venture into the gloomy mists outside of Granfiddich, trying to find the landmarks you recognize from following the bats, to get into the bog.',
    'Venture into the hideout': 'You venture into the gloomy mists outside of Blackspell Port, thick roots and even trees through the marshes blocking your way into the hideout.',
    'Venture into the woods': 'You venture into the gloomy mists outside of Salsfirth, a dense network of foliage blocking your way to get into the woods.',
    'Wine grape stomping': 'With bare feet so as not to break the seeds, you step on the grapes. You move from the center of the press towards the ends, thus facilitating fermentation, since the pressure exerted on the fruit allows contact with the yeasts in charge of the process.',
    'Wolf hunting': 'You follow large paw prints in the ground in search of the widespread forest hunter, the wolf. Your bow and arrow is ready to strike one down.',
    'Wood carving': 'Shaping wood using a sharp object, such as a knife, is an ancient form of craftsmanship. There is a great variety of art and iconography: from small figurines and toys, to ceremonial or war masks, to large mosaics and towering totem poles.',
    'Wreck diving': "You dive deep into the shipwreck that is Casbrant's grave, hoping to find treasure.",
}
