#!/usr/bin/env python3
"""
Add missing _FINE variants for all materials in the API fine_materials list.
"""
import json, re, subprocess
from pathlib import Path

fine_list = json.loads(Path('temp_gear_app_cache/api_fine_materials.json').read_text())
content = Path('util/autogenerated/materials.py').read_text()

# Build map of existing MaterialInstance names -> enum names
existing = {}
for m in re.finditer(r'    ([A-Z_0-9]+) = MaterialInstance\(\s*\n\s*name="([^"]+)"', content):
    existing[m.group(2).lower()] = m.group(1)

added = []
for item_id in fine_list:
    # Convert API id to display name by looking up in existing
    # Try to find the base material
    base_enum = None
    base_name = None
    for name, enum in existing.items():
        # Match by converting item_id to name format
        normalized = item_id.replace('_', ' ')
        if name == normalized or name == normalized.replace("'s", 's'):
            base_enum = enum
            base_name = name
            break

    if not base_enum:
        continue

    fine_enum = base_enum + '_FINE'
    fine_name_display = existing.get(base_name + ' (fine)')  # check if already exists differently

    # Check if fine version already exists
    if fine_enum in content:
        continue

    # Find the base block and insert fine version after it
    # Pattern: find the block ending with "    )\n\n" after the base enum
    pattern = rf'(    {re.escape(base_enum)} = MaterialInstance\(\n(?:        [^\n]+\n)*    \)\n)'
    m = re.search(pattern, content)
    if not m:
        continue

    # Get keywords and value from base
    block = m.group(1)
    kw_match = re.search(r"keywords=(\[[^\]]*\])", block)
    keywords = kw_match.group(1) if kw_match else '[]'
    val_match = re.search(r"value=(\d+)", block)
    value = val_match.group(1) if val_match else '0'

    # Build the display name from base
    base_display = re.search(r'name="([^"]+)"', block).group(1)
    fine_display = f"{base_display} (Fine)"

    fine_block = f'''
    {fine_enum} = MaterialInstance(
        name="{fine_display}",
        keywords={keywords},
        value={value},
    )'''

    # Insert after the base block
    content = content.replace(m.group(1), m.group(1) + fine_block + '\n', 1)
    added.append(fine_display)

Path('util/autogenerated/materials.py').write_text(content)
print(f"Added {len(added)} fine material variants:")
for n in sorted(added):
    print(f"  + {n}")

r = subprocess.run(['python3', '-m', 'py_compile', 'util/autogenerated/materials.py'], capture_output=True)
print("✓ Compiles OK" if r.returncode == 0 else f"✗ {r.stderr.decode()[:200]}")
