#!/usr/bin/env python3
"""
Remove gear items that were incorrectly added to materials.py.
These items have gearType in the API and should be in equipment.py only.
"""
import json
import re
import subprocess
from pathlib import Path

CACHE_FILE = Path('temp_gear_app_cache/api_items_categorized_fresh.json')
MATS_FILE = Path('util/autogenerated/materials.py')

# Load gear item names from API
with open(CACHE_FILE) as f:
    categories = json.load(f)

gear_names = set()
for cat in categories:
    for subcat in cat.get('categories', []):
        for item in subcat.get('items', []):
            if item.get('gearType'):
                gear_names.add(item['name'].lower())

print(f"Gear items in API: {len(gear_names)}")

# Items that must stay in materials.py because they're used as recipe ingredients
# (these have gearType in API but are also crafting inputs)
KEEP_IN_MATERIALS = {
    'simple sewing needle', 'simple bowstring', 'strong bowstring',
    'boxtrap', 'camo face paint', 'bright camo face paint',
    'copper arrows', 'bronze arrows', 'iron arrows', 'steel arrows',
    'farganite arrows', 'tarsilium arrows', 'kelp drift net',
    'bamboo hunting bow', 'birch hunting bow', 'oak hunting bow',
    'spectral hunting bow', 'bamboo toolbox', 'pine toolbox',
    'linen cloth', 'tough linen cloth', 'durable fabric cutting mat',
}
gear_names -= KEEP_IN_MATERIALS

# Also keep anything referenced in recipes.py as Material.*
recipes_content = Path('util/autogenerated/recipes.py').read_text()
import re as _re
recipe_mat_refs = set(_re.findall(r'Material\.([A-Z_]+)', recipes_content))
# Convert enum names back to lowercase item names by checking materials.py
mats_content = Path('util/autogenerated/materials.py').read_text()
for enum_name in recipe_mat_refs:
    # Find the name= for this enum
    m = _re.search(rf'{enum_name} = MaterialInstance\(\s*name="([^"]+)"', mats_content)
    if m:
        gear_names.discard(m.group(1).lower())

# Read materials.py
content = MATS_FILE.read_text()

# Find MaterialInstance blocks that are actually gear items
# Pattern: ENUM_NAME = MaterialInstance(\n    name="...",\n    ...\n)
pattern = r'(\n    [A-Z_0-9]+ = MaterialInstance\(\n(?:        [^\n]+\n)*    \)\n)'

removed = []
def check_and_remove(m):
    block = m.group(1)
    name_match = re.search(r'name="([^"]+)"', block)
    if name_match:
        name = name_match.group(1).lower()
        if name in gear_names:
            removed.append(name_match.group(1))
            return ''  # Remove this block
    return block

new_content = re.sub(pattern, check_and_remove, content)

print(f"Removed {len(removed)} gear items from materials.py:")
for n in sorted(removed):
    print(f"  - {n}")

MATS_FILE.write_text(new_content)

# Verify
r = subprocess.run(['python3', '-m', 'py_compile', str(MATS_FILE)], capture_output=True)
if r.returncode == 0:
    print("✓ materials.py compiles OK")
else:
    print(f"✗ {r.stderr.decode()[:300]}")
