#!/usr/bin/env python3
"""Fix keywords in materials.py: title-case, remove skill names, deduplicate."""
import re, subprocess
from pathlib import Path

REMOVE = {
    'agility', 'carpentry', 'cooking', 'crafting', 'fishing',
    'foraging', 'hunting', 'mining', 'smithing', 'tailoring',
    'trinketry', 'woodcutting', 'global', 'gathering', 'artisan',
    'tool',
}

def clean_kw(kw):
    kw = kw.strip()
    if kw.lower() in REMOVE:
        return None
    if ' ' in kw and kw[0].isupper():
        return kw
    parts = kw.replace('_', ' ').split()
    if len(parts) > 1:
        return parts[0].title() + ' ' + ' '.join(p.lower() for p in parts[1:])
    return kw.title()

content = Path('util/autogenerated/materials.py').read_text()

def fix_line(m):
    inner = m.group(1)
    if not inner.strip():
        return m.group(0)
    items = re.findall(r"'([^']*)'", inner)
    cleaned = []
    seen = set()
    for kw in items:
        c = clean_kw(kw)
        if c and c.lower() not in seen:
            cleaned.append(c)
            seen.add(c.lower())
    return f"keywords={repr(cleaned)}"

new = re.sub(r"keywords=\[([^\]]*)\]", fix_line, content)
changes = sum(1 for a, b in zip(content.split('\n'), new.split('\n')) if a != b)
Path('util/autogenerated/materials.py').write_text(new)
print(f"Fixed {changes} keyword lines")

r = subprocess.run(['python3', '-m', 'py_compile', 'util/autogenerated/materials.py'], capture_output=True)
print("✓ Compiles OK" if r.returncode == 0 else f"✗ {r.stderr.decode()[:200]}")
