#!/usr/bin/env python3
"""
Ingest all gear items from gear.walkscape.app API into equipment.py.

Reads temp_gear_app_cache/api_items_categorized_fresh.json and generates
ItemInstance / CraftedItem entries for all gear items missing from equipment.py.

Usage:
    python3 util/scrapers/ingest_gear_from_api.py
"""

import json
import re
import subprocess
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================

CACHE_FILE = Path('temp_gear_app_cache/api_items_categorized_fresh.json')
EQUIP_FILE = Path('util/autogenerated/equipment.py')

# Map API stat names to our internal stat names
STAT_MAP = {
    'work_efficiency': 'work_efficiency',
    'double_action': 'double_action',
    'double_rewards': 'double_rewards',
    'steps_required': 'steps_add',       # flat steps (isPercent=false)
    'steps_required_percent': 'steps_percent',  # % steps (isPercent=true)
    'chest_finding': 'chest_finding',
    'fine_material_finding': 'fine_material_finding',
    'find_collectibles': 'find_collectibles',
    'find_gems': 'find_gems',
    'find_bird_nests': 'find_bird_nests',
    # "That's A Wrap" pet passive: 7% chance to roll the linens table twice.
    # Exact API stat key TBD until embargo lifts — map the likely spellings.
    'find_linens': 'find_linens',
    'roll_linens': 'find_linens',
    'roll_linens_twice': 'find_linens',
    'linens_table': 'find_linens',
    'find_bird_nest': 'ItemFindingCategory.BIRD_NEST',
    'no_materials_consumed': 'no_materials_consumed',
    'quality_outcome': 'quality_outcome',
    'bonus_experience': 'bonus_xp_percent',   # isPercent=true
    'bonus_experience_flat': 'bonus_xp_add',  # isPercent=false
    'inventory_space': 'inventory_space',
    'roll_special_table': 'ItemFindingCategory.ECTOPLASM',  # Spectral ectoplasm finding
}

RARITY_MAP = {
    'common': 'common',
    'uncommon': 'uncommon',
    'rare': 'rare',
    'epic': 'epic',
    'legendary': 'legendary',
    'ethereal': 'ethereal',
}

QUALITY_MAP = {
    'common': 'Normal',
    'uncommon': 'Good',
    'rare': 'Great',
    'epic': 'Excellent',
    'legendary': 'Perfect',
    'ethereal': 'Eternal',
}

VALUE_MAP = {
    'none': 0, 'extremelyLow': 1, 'veryLow': 2, 'low': 3, 'lowMedium': 4,
    'medium': 5, 'lowHigh': 6, 'mediumHigh': 7, 'high': 8, 'veryHigh': 9,
    'expensive': 10, 'veryExpensive': 11,
}


def extract_item_value(item, rarity_key=None):
    """Coins/value from itemValue.

    The API changed itemValue from a string tier (legacy, mapped via VALUE_MAP)
    to a dict: {'currency': 'none'|'money', 'value': None | {rarity: number}}.
    - legacy str  -> VALUE_MAP lookup
    - dict, value None -> 0 (e.g. Pet Egg / valueless items)
    - dict, value {rarity: n} -> the number for the item's rarity (or the given
      rarity_key for per-quality crafted values); falls back to the sole/max entry.
    """
    iv = item.get('itemValue')
    if isinstance(iv, str):
        return VALUE_MAP.get(iv, 0)
    if isinstance(iv, dict):
        val = iv.get('value')
        if isinstance(val, dict) and val:
            key = (rarity_key or item.get('quality') or item.get('rarity') or '').lower()
            if key in val and val[key] is not None:
                return val[key]
            nums = [v for v in val.values() if isinstance(v, (int, float))]
            if not nums:
                return 0
            return nums[0] if len(nums) == 1 else max(nums)
        return val or 0  # None -> 0, or a bare number
    return 0


def name_to_enum(name):
    """Convert item name to Python enum constant."""
    n = re.sub(r"[^\w\s-]", '', name)
    n = n.replace(' ', '_').replace('-', '_').upper()
    n = re.sub(r'_+', '_', n).strip('_')
    if n and n[0].isdigit():
        n = '_' + n
    return n


# Skill names that should NOT be stored as keywords
SKILL_KEYWORDS_TO_REMOVE = {
    'agility', 'carpentry', 'cooking', 'crafting', 'fishing',
    'foraging', 'hunting', 'mining', 'smithing', 'tailoring',
    'trinketry', 'woodcutting', 'global', 'gathering', 'artisan',
    'tool',
}


def clean_keywords(raw_keywords):
    """Clean API keywords: title-case, replace underscores, remove skill names."""
    cleaned = []
    for kw in (raw_keywords or []):
        kw_lower = kw.lower().strip()
        # Skip skill names
        if kw_lower in SKILL_KEYWORDS_TO_REMOVE:
            continue
        # Convert snake_case to Title case with spaces
        display = kw_lower.replace('_', ' ').title()
        # Special cases to match existing conventions
        display = display.replace('Diving Gear', 'Diving gear')
        display = display.replace('Advanced Diving Gear', 'Advanced diving gear')
        display = display.replace('Expert Diving Gear', 'Expert diving gear')
        display = display.replace('Light Source', 'Light source')
        display = display.replace('Achievement Reward', 'Achievement reward')
        display = display.replace('Hunting Bow', 'Hunting bow')
        display = display.replace('Hunting Trap', 'Hunting trap')
        display = display.replace('Hunting Net', 'Hunting net')
        display = display.replace('Fishing Net', 'Fishing net')
        display = display.replace('Fishing Rod', 'Fishing rod')
        display = display.replace('Fishing Spear', 'Fishing spear')
        display = display.replace('Fishing Tool', 'Fishing tool')
        display = display.replace('Bug Catching Net', 'Bug catching net')
        display = display.replace('Carpentry Tool', 'Carpentry tool')
        display = display.replace('Adventuring Tool Set', 'Adventuring tool set')
        display = display.replace('Skill Book', 'Skill book')
        display = display.replace('Cutting Mat', 'Cutting mat')
        cleaned.append(display)
    return cleaned


# CollectibleOwned requirement type aliases (exact API key TBD until embargo lifts,
# so accept the likely spellings). Works like the alien squeaky toy's total-skill-level
# gate, but keyed on how many collectibles the player owns.
COLLECTIBLE_OWNED_TYPES = {'collectibleOwned', 'collectiblesOwned', 'collectible_owned'}
# Inner requirement keys that could hold the threshold count, tried in order.
_COLLECTIBLE_COUNT_KEYS = ('amount', 'count', 'collectibles', 'value', 'threshold', 'levels')


def _collectible_threshold(reqs):
    """If a requirements list contains a CollectibleOwned gate, return its integer
    threshold; otherwise return None. Defensive about the exact inner key name."""
    for req in (reqs or []):
        if req.get('type', '') in COLLECTIBLE_OWNED_TYPES:
            rdata = req.get('requirement', {}) or {}
            for key in _COLLECTIBLE_COUNT_KEYS:
                if key in rdata and rdata[key] is not None:
                    try:
                        return int(rdata[key])
                    except (TypeError, ValueError):
                        continue
            # Gate present but threshold unreadable — treat as tier 1 so the
            # bonus at least applies once the player owns any collectibles.
            return 1
    return None


def parse_collectible_gated_attrs(attrs, item_name=''):
    """Parse CollectibleOwned-gated attrs into the total_collectibles gated dict.

    Returns {'total_collectibles': {threshold: {skill: {location: {stat: value}}}}}
    or {} if none. Mirrors the base parse_attrs stat mapping/scaling exactly, but
    keys each attr's stats under its collectible-count threshold. Tiers are
    cumulative (the applier sums every threshold met), matching the ring spec
    (e.g. +1% chest finding at each of 10/20/30/40/50/60 collectibles).
    """
    gated = {}
    for attr in (attrs or []):
        threshold = _collectible_threshold(attr.get('requirements') or [])
        if threshold is None:
            continue
        attr_stats = attr.get('stats') or []
        reqs = attr.get('requirements') or []

        skill = 'global'
        location = 'global'
        for req in reqs:
            req_type = req.get('type', '')
            req_data = req.get('requirement', {}) or {}
            if req_type == 'mainSkill':
                skill = req_data.get('skill', 'global')
            elif req_type == 'mainSkillType':
                skill = req_data.get('type', 'global')
            elif req_type == 'location':
                location = req_data.get('location', 'global')
            elif req_type == 'locationHasKeywords':
                kws = req_data.get('keywords', []) or []
                if kws:
                    location = kws[0]
            elif req_type == 'realm':
                location = req_data.get('realm', 'global')

        for s in attr_stats:
            stat_name = s.get('stat', '')
            value = s.get('value', 0)
            is_percent = s.get('isPercent', True)
            is_negative = s.get('isNegative', False)

            if stat_name == 'steps_required':
                mapped = 'steps_percent' if is_percent else 'steps_add'
            elif stat_name == 'bonus_experience':
                mapped = 'bonus_xp_percent' if is_percent else 'bonus_xp_add'
            else:
                mapped = STAT_MAP.get(stat_name)
            if not mapped:
                continue

            if is_percent and mapped not in ('steps_add', 'bonus_xp_add', 'quality_outcome', 'inventory_space'):
                stored_value = round(value * 100, 4)
            else:
                stored_value = value
            if is_negative:
                stored_value = -abs(stored_value)

            g = gated.setdefault('total_collectibles', {}).setdefault(threshold, {})
            g = g.setdefault(skill, {}).setdefault(location, {})
            g[mapped] = round(g.get(mapped, 0) + stored_value, 4)

    return gated


SET_BONUS_TYPE = 'distinctKeywordItemsEquipped'


def _set_bonus_gate(reqs):
    """If a requirements list has a distinctKeywordItemsEquipped gate, return
    (quantity:int, setname:str) from its first keyword; else None.

    setname is the keyword with underscores -> spaces (e.g. 'treasure_hunter_set'
    -> 'treasure hunter set'), matching the existing gated_stats['set_pieces'] keys.
    """
    for req in (reqs or []):
        if req.get('type', '') == SET_BONUS_TYPE:
            rdata = req.get('requirement', {}) or {}
            kws = rdata.get('keywords') or []
            if not kws:
                continue
            try:
                qty = int(rdata.get('quantity', 1))
            except (TypeError, ValueError):
                qty = 1
            return qty, str(kws[0]).replace('_', ' ')
    return None


def parse_set_bonus_attrs(attrs):
    """Parse distinctKeywordItemsEquipped-gated attrs into the set_pieces gated dict.

    Returns {'set_pieces': {setname: {quantity: {skill: {location: {stat: value}}}}}}
    or {} if none. Mirrors the OLD Treasure hunter set representation exactly, so
    the '... if wearing at least N <set> items' bonus stays gated (not baked into
    always-on base stats). Same stat mapping/scaling as parse_attrs.
    """
    gated = {}
    for attr in (attrs or []):
        gate = _set_bonus_gate(attr.get('requirements') or [])
        if gate is None:
            continue
        qty, setname = gate

        skill = 'global'
        location = 'global'
        for req in (attr.get('requirements') or []):
            req_type = req.get('type', '')
            req_data = req.get('requirement', {}) or {}
            if req_type == 'mainSkill':
                skill = req_data.get('skill', 'global')
            elif req_type == 'mainSkillType':
                skill = req_data.get('type', 'global')
            elif req_type == 'location':
                location = req_data.get('location', 'global')
            elif req_type == 'locationHasKeywords':
                kws = req_data.get('keywords', []) or []
                if kws:
                    location = kws[0]
            elif req_type == 'realm':
                location = req_data.get('realm', 'global')

        for s in (attr.get('stats') or []):
            stat_name = s.get('stat', '')
            value = s.get('value', 0)
            is_percent = s.get('isPercent', True)
            is_negative = s.get('isNegative', False)
            if stat_name == 'steps_required':
                mapped = 'steps_percent' if is_percent else 'steps_add'
            elif stat_name == 'bonus_experience':
                mapped = 'bonus_xp_percent' if is_percent else 'bonus_xp_add'
            else:
                mapped = STAT_MAP.get(stat_name)
            if not mapped:
                continue
            if is_percent and mapped not in ('steps_add', 'bonus_xp_add', 'quality_outcome', 'inventory_space'):
                stored_value = round(value * 100, 4)
            else:
                stored_value = value
            if is_negative:
                stored_value = -abs(stored_value)
            g = gated.setdefault('set_pieces', {}).setdefault(setname, {}).setdefault(qty, {})
            g = g.setdefault(skill, {}).setdefault(location, {})
            g[mapped] = round(g.get(mapped, 0) + stored_value, 4)
    return gated


def _resolve_special_table(item_name):
    """Map a 'roll_special_table' stat to its ItemFindingCategory by item name.

    The API doesn't say WHICH special table the item rolls, so infer from the
    item name: Adventurers' guild items roll the AGT table; spectral/ectoplasm
    gear rolls the ectoplasm table. Defaults to ectoplasm (the original hardcode)
    for unknown items, which should be reviewed.
    """
    n = (item_name or '').lower()
    if 'guild' in n or 'adventurer' in n:
        return 'ItemFindingCategory.ADVENTURERS_GUILD_TOKENS'
    if 'spectral' in n or 'ectoplasm' in n:
        return 'ItemFindingCategory.ECTOPLASM'
    print(f"  ⚠ roll_special_table on '{item_name}' — unknown table, defaulting to ECTOPLASM; review")
    return 'ItemFindingCategory.ECTOPLASM'


def parse_attrs(attrs, item_name=''):
    """Parse itemAttrs into nested stats dict {skill: {location: {stat: value}}}.

    Attrs gated behind a CollectibleOwned requirement are SKIPPED here — they are
    conditional (not always-on) and are handled by parse_collectible_gated_attrs().
    """
    stats = {}
    for attr in (attrs or []):
        # Skip collectible-gated attrs — routed to gated_stats['total_collectibles'].
        if _collectible_threshold(attr.get('requirements') or []) is not None:
            continue
        # Skip set-bonus attrs — routed to gated_stats['set_pieces'] (conditional,
        # not always-on). Without this the '... if wearing N set items' tiers get
        # summed into base stats (e.g. Treasure hunter bandolier +40% always-on).
        if _set_bonus_gate(attr.get('requirements') or []) is not None:
            continue
        attr_stats = attr.get('stats') or []
        reqs = attr.get('requirements') or []

        # Determine skill from requirements
        skill = 'global'
        location = 'global'
        for req in reqs:
            req_type = req.get('type', '')
            req_data = req.get('requirement', {})
            if req_type == 'mainSkill':
                skill = req_data.get('skill', 'global')
            elif req_type == 'mainSkillType':
                # Skill type like "gathering", "artisan" — maps to composite skill
                skill = req_data.get('type', 'global')
            elif req_type == 'location':
                location = req_data.get('location', 'global')
            elif req_type == 'locationHasKeywords':
                kws = req_data.get('keywords', [])
                if kws:
                    location = kws[0]  # e.g. 'underwater', 'spectral'
            elif req_type == 'realm':
                location = req_data.get('realm', 'global')

        for s in attr_stats:
            stat_name = s.get('stat', '')
            value = s.get('value', 0)
            is_percent = s.get('isPercent', True)
            is_negative = s.get('isNegative', False)

            # Map stat name
            if stat_name == 'steps_required':
                mapped = 'steps_percent' if is_percent else 'steps_add'
            elif stat_name == 'bonus_experience':
                mapped = 'bonus_xp_percent' if is_percent else 'bonus_xp_add'
            elif stat_name == 'roll_special_table':
                # The special table rolled is item-specific and NOT in the stat
                # payload — resolve it from the item name (e.g. Adventurers' guild
                # buckler -> AGT; Spectral gear -> ectoplasm).
                mapped = _resolve_special_table(item_name)
            else:
                mapped = STAT_MAP.get(stat_name)

            # Unknown/new stat types (e.g. the 3 new unused stats in this API
            # revision) aren't in STAT_MAP → skip silently rather than crash.
            if not mapped:
                continue

            # Convert: API stores as decimal (0.05 = 5%), we store as percentage (5.0)
            if is_percent and mapped not in ('steps_add', 'bonus_xp_add', 'quality_outcome', 'inventory_space'):
                stored_value = round(value * 100, 4)
            else:
                stored_value = value

            if is_negative:
                stored_value = -abs(stored_value)

            if skill not in stats:
                stats[skill] = {}
            if location not in stats[skill]:
                stats[skill][location] = {}
            # Accumulate (some items have multiple attrs for same stat)
            existing = stats[skill][location].get(mapped, 0)
            stats[skill][location][mapped] = round(existing + stored_value, 4)

    return stats


def parse_requirements(reqs):
    """Parse requirements list into our format."""
    result = []
    for req in (reqs or []):
        req_type = req.get('type', '')
        req_data = req.get('requirement', {})
        if req_type == 'skillLevel':
            result.append({
                'type': 'skill',
                'skill': req_data.get('skill', '').title(),
                'level': req_data.get('level', 1)
            })
        elif req_type == 'totalSkillLevel':
            result.append({
                'type': 'total_skill_level',
                'value': req_data.get('levels', 0)
            })
        elif req_type == 'reputation':
            result.append({
                'type': 'reputation',
                'faction': req_data.get('faction', ''),
                'amount': req_data.get('amount', 0)
            })
    return result


def get_existing_names():
    """Get set of item names already in equipment.py."""
    content = EQUIP_FILE.read_text()
    names = set()
    for m in re.finditer(r'name="([^"]+)"', content):
        names.add(m.group(1).lower())
    for m in re.finditer(r"name='([^']+)'", content):
        names.add(m.group(1).lower())
    return names


def format_stats(stats):
    """Format stats dict as Python literal."""
    if not stats:
        return '{}'
    lines = ['{']
    for skill, locs in stats.items():
        lines.append(f"            '{skill}': {{")
        for loc, stat_map in locs.items():
            stat_str = ', '.join(f"'{k}': {v}" for k, v in stat_map.items())
            lines.append(f"                '{loc}': {{{stat_str}}},")
        lines.append('            },')
    lines.append('        }')
    return '\n        '.join(lines)


def generate_item_instance(item):
    """Generate ItemInstance code for a non-crafted item."""
    name = item['name']
    enum_name = name_to_enum(name)
    uuid = item.get('id', f'item-{enum_name.lower()}')
    slot = item.get('gearType', 'tool')
    keywords = clean_keywords(item.get('keywords', []))
    rarity = item.get('quality', 'common')
    value = extract_item_value(item)
    reqs = parse_requirements(item.get('requirements', []))
    stats = parse_attrs(item.get('itemAttrs', []), name)
    gated = parse_collectible_gated_attrs(item.get('itemAttrs', []), name)
    gated.update(parse_set_bonus_attrs(item.get('itemAttrs', [])))

    kw_str = repr(keywords)
    req_str = repr(reqs) if reqs else '[]'
    stats_str = format_stats(stats)
    gated_str = repr(gated) if gated else '{}'

    return f'''
    {enum_name} = ItemInstance(
        name="{name}",
        uuid="item-{uuid}",
        stats={stats_str},
        slot="{slot}",
        keywords={kw_str},
        value={value},
        rarity='{rarity}',
        location_reqs=[],
        gated_stats={gated_str},
        requirements={req_str}
    )
'''


def generate_crafted_item(item):
    """Generate CraftedItem code for a crafted item."""
    name = item['name']
    enum_name = name_to_enum(name)
    uuid = item.get('id', f'item-{enum_name.lower()}')
    slot = item.get('gearType', 'tool')
    keywords = clean_keywords(item.get('keywords', []))
    value = extract_item_value(item)
    reqs = parse_requirements(item.get('requirements', []))

    # Base stats (common quality)
    base_stats = parse_attrs(item.get('itemAttrs', []), name)

    # Quality stats — API gives additions per quality, but CraftedItem.update() replaces
    # entire skill keys. So we need to compute CUMULATIVE stats (base + additions) for each quality.
    quality_stats = {}
    quality_values = {}
    for qa in (item.get('itemQualityAttrs') or []):
        q = qa.get('quality', '')
        q_name = QUALITY_MAP.get(q, q.title())
        q_additions = parse_attrs(qa.get('attributes', []), name)
        
        # Deep merge: base_stats + q_additions
        cumulative = {}
        # Start with base stats
        for skill, locs in base_stats.items():
            cumulative[skill] = {}
            for loc, stat_map in locs.items():
                cumulative[skill][loc] = dict(stat_map)
        # Add quality additions
        for skill, locs in q_additions.items():
            if skill not in cumulative:
                cumulative[skill] = {}
            for loc, stat_map in locs.items():
                if loc not in cumulative[skill]:
                    cumulative[skill][loc] = {}
                for stat, val in stat_map.items():
                    cumulative[skill][loc][stat] = round(cumulative[skill][loc].get(stat, 0) + val, 4)
        
        if cumulative:
            quality_stats[q_name] = cumulative
        quality_values[q_name] = extract_item_value(item, rarity_key=q)

    kw_str = repr(keywords)
    req_str = repr(reqs) if reqs else '[]'
    base_str = format_stats(base_stats)
    qs_str = repr(quality_stats) if quality_stats else '{}'
    qv_str = repr(quality_values) if quality_values else '{}'

    return f'''
    {enum_name} = CraftedItem(
        name="{name}",
        uuid="item-{uuid}",
        base_stats={base_str},
        quality_stats={qs_str},
        quality_values={qv_str},
        slot="{slot}",
        keywords={kw_str},
        value={value},
        requirements={req_str}
    )
'''


def main():
    print("Loading categorized items from API cache...")
    with open(CACHE_FILE) as f:
        categories = json.load(f)

    # Collect all gear items
    all_gear = []
    for cat in categories:
        for subcat in cat.get('categories', []):
            for item in subcat.get('items', []):
                if item.get('gearType'):  # Has a gear slot = it's equipment
                    all_gear.append(item)

    print(f"Total gear items in API: {len(all_gear)}")

    # Get existing names
    existing = get_existing_names()
    print(f"Items already in equipment.py: {len(existing)}")

    # Get material names to exclude (items that are in materials.py shouldn't be in equipment.py)
    mat_content = Path('util/autogenerated/materials.py').read_text()
    material_names = set()
    for m in re.finditer(r'name="([^"]+)"', mat_content):
        material_names.add(m.group(1).lower())

    # Also exclude items with type "material" or "consumable" in the API
    # These are crafting inputs, not equipment.
    # 'lore' items (new type) provide no gameplay benefit yet — skip them too.
    EXCLUDE_TYPES = {'material', 'consumable', 'collectible', 'lore'}

    # Find missing items
    missing = []
    for i in all_gear:
        name_lower = i['name'].lower()
        if name_lower in existing:
            continue
        if name_lower in material_names:
            continue
        if i.get('type', '') in EXCLUDE_TYPES:
            continue
        missing.append(i)

    print(f"Missing from equipment.py: {len(missing)}")

    if not missing:
        print("Nothing to add!")
        return

    # Generate code
    new_code = []
    crafted_count = 0
    instance_count = 0

    for item in missing:
        item_type = item.get('type', '')
        is_crafted = item_type == 'crafted'

        if is_crafted:
            new_code.append(generate_crafted_item(item))
            crafted_count += 1
        else:
            new_code.append(generate_item_instance(item))
            instance_count += 1

    print(f"  ItemInstance: {instance_count}")
    print(f"  CraftedItem: {crafted_count}")

    # Insert before the lookup dictionaries
    content = EQUIP_FILE.read_text()
    insert_marker = '\n\n# Lookup dictionaries'
    if insert_marker not in content:
        insert_marker = '\n\nITEMS_BY_NAME'
    if insert_marker not in content:
        # Append at end of Item class
        insert_marker = '\n\n\n# Lookup'

    joined = ''.join(new_code)
    if insert_marker in content:
        content = content.replace(insert_marker, joined + insert_marker, 1)
    else:
        content = content.rstrip() + '\n' + joined + '\n'

    EQUIP_FILE.write_text(content)
    print(f"\nWrote {len(missing)} new items to equipment.py")

    # Verify
    r = subprocess.run(['python3', '-m', 'py_compile', str(EQUIP_FILE)], capture_output=True)
    if r.returncode == 0:
        print("✓ equipment.py compiles OK")
    else:
        print(f"✗ Compile error: {r.stderr.decode()[:500]}")


if __name__ == '__main__':
    main()
