#!/usr/bin/env python3
"""Ingest items from the tools API, sharded by subtype.

Items are discriminated by `type` enum and nullable `gearType` /
`consumableType`. Output goes to one Python file per legacy autogen target:

    items.type=material               → materials.py
    items.type=consumable             → consumables.py
    items.type=collectible            → collectibles.py
    items.type=container              → containers.py
    items.type=currency               → currency.py
    items.type=egg                    → eggs.py
    items.type IN (crafted, loot)
        AND gearType is non-null      → equipment.py
    items.type=loot AND gearType=None → loot_items.py
                                        (drop-only items, e.g. trinkets)

Each entry preserves the API shape verbatim including:
  - keywords / requirements / itemAttrs / buffs / tables: nullable
    arrays. None means "this concept doesn't apply", [] means "applies
    but empty".
  - gearType / consumableType: nullable. None on a non-gear/non-consumable.
"""
from __future__ import annotations
import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from util.scrapers.tools_api_client import ToolsAPIClient  # noqa: E402
from util.scrapers.tools_api_transform import write_python_data_module  # noqa: E402


SHARDS = [
    # (filename, var_name, predicate, docstring)
    ('materials.py', 'MATERIALS',
     lambda d: d.get('type') == 'material',
     'Materials — items with type=material.'),
    ('consumables.py', 'CONSUMABLES',
     lambda d: d.get('type') == 'consumable',
     'Consumables — items with type=consumable; consumableType ∈ {food, immediate}.'),
    ('collectibles.py', 'COLLECTIBLES',
     lambda d: d.get('type') == 'collectible',
     'Collectibles — items with type=collectible.'),
    ('containers.py', 'CONTAINERS',
     lambda d: d.get('type') == 'container',
     'Containers — items with type=container (chests/bags).'),
    ('currency.py', 'CURRENCY',
     lambda d: d.get('type') == 'currency',
     'Currency — items with type=currency.'),
    ('eggs.py', 'EGGS',
     lambda d: d.get('type') == 'egg',
     'Pet eggs — items with type=egg.'),
    ('equipment.py', 'EQUIPMENT',
     lambda d: d.get('type') in ('crafted', 'loot') and d.get('gearType'),
     'Equipment — items with type=crafted OR type=loot, where gearType '
     'is non-null. Covers all wearable gear (head, chest, hands, ring, '
     'tool, ...) including drop-equipment like Adventuring hunting bow.'),
    ('loot_items.py', 'LOOT_ITEMS',
     lambda d: d.get('type') == 'loot' and not d.get('gearType'),
     'Loot items — type=loot with no gearType (e.g. compass trinket, '
     'eel trinket — recipe materials that drop from activities).'),
]


def run(client: ToolsAPIClient, *, use_cache: bool = True) -> int:
    items = client.list('items', use_cache=use_cache)
    print(f'  [items              ] hydrating {len(items)} items …')
    detail: Dict[str, Dict[str, Any]] = {}
    for it in items:
        iid = it.get('id')
        if not iid:
            continue
        try:
            detail[iid] = client.get('items', iid, use_cache=use_cache)
        except Exception as e:
            print(f"    [skip] items/{iid}: {e}", file=sys.stderr)

    out_dir = Path(__file__).resolve().parent.parent / 'autogenerated'
    total = 0
    for fname, var_name, pred, doc in SHARDS:
        shard = {iid: d for iid, d in detail.items() if pred(d)}
        write_python_data_module(
            str(out_dir / fname), var_name, shard, docstring=doc,
        )
        total += len(shard)
        print(f'    {fname:35s} {len(shard):4d}')

    # Sanity: every item should land in exactly one shard
    assigned = sum(1 for d in detail.values() if any(p(d) for _, _, p, _ in SHARDS))
    leftover = len(detail) - assigned
    if leftover:
        print(f'  [items] WARNING: {leftover} items did not match any shard')
    print(f'  [items              ] {total:4d} items across {len(SHARDS)} shards')
    return total


if __name__ == '__main__':
    raise SystemExit(0 if run(ToolsAPIClient()) else 1)
