#!/usr/bin/env python3
"""
Master ingest driver — pulls every (non-recipe) entity from the WalkScape
tools API and regenerates the `<entity>.py` files in
util/autogenerated/.

Recipes are owned by another agent and explicitly excluded.

Per-entity ingest scripts (ingest_<entity>_from_tools_api.py) call into
this driver. Run this directly to regenerate everything at once:

    python3 util/scrapers/ingest_all_from_tools_api.py

For complex entities (locations, shops, routes, pets, items subtypes,
activities), this driver delegates to the per-entity ingest module which
contains the custom transform.

Final step (unless --skip-emit): runs old_shape_emitters.emit_all() to
regenerate the legacy class-shape files the application actually imports
(equipment.py with the Item class, locations.py with Location/LocationInfo,
materials.py, consumables.py, services.py, export_names.py, …). The fetch
phases above only populate the tools-API cache and intermediate dumps; the
emit step is what produces the consumable, importable modules. Skipping it
leaves util/autogenerated in a raw-dict shape that the app cannot import.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from util.scrapers.tools_api_client import ToolsAPIClient  # noqa: E402
from util.scrapers.tools_api_dump import dump_endpoint  # noqa: E402


# Simple entities — generic dump (no transform), just preserve API shape
# in a Python dict-of-dicts keyed by id.
SIMPLE_ENTITIES = [
    # (api_endpoint, output_filename, python_var_name, docstring)
    ('abilities', 'abilities.py', 'ABILITIES',
     'Abilities — character/equipment passive and active abilities.'),
    ('achievements', 'achievements.py', 'ACHIEVEMENTS',
     'Achievements — game achievements with their rewards.'),
    ('buildings', 'buildings.py', 'BUILDINGS',
     'Buildings — building catalogue (icons + names).'),
    ('cooldowns', 'cooldowns.py', 'COOLDOWNS',
     'Cooldowns — exactly one of seconds/minutes/hours/days/steps/actions '
     'is non-null per cooldown; the others are null on purpose.'),
    ('factions', 'factions.py', 'FACTIONS',
     'Factions — faction id, color, reputation key, icon.'),
    ('global_variables', 'global_variables.py', 'GLOBAL_VARIABLES',
     'Global variables — game-wide tunables (e.g. fine-input bonus tables).'),
    ('keywords', 'keywords.py', 'KEYWORDS',
     'Keywords — keyword catalogue including bannedKeywords list.'),
    ('loot_tables', 'loot_tables.py', 'LOOT_TABLES',
     'Loot tables — drop tables referenced by activities/items/recipes.'),
    ('rewards', 'rewards.py', 'REWARDS',
     'Rewards — quest/achievement/faction reward bundles.'),
    ('skills', 'skills.py', 'SKILLS',
     'Skills — skill catalogue with type (gathering/artisan/utility) + icons.'),
    ('stats', 'stats.py', 'STATS',
     'Stats — stat metadata (work_efficiency, double_rewards, etc.).'),
    ('terrain_modifiers', 'terrain_modifiers.py', 'TERRAIN_MODIFIERS',
     'Terrain modifiers — referenced by routes.options[].terrainModifiers; '
     'each carries its own requirements[] (e.g. "2 light sources" → '
     'distinctKeywordItemsEquipped requirement).'),
]


def _autogen_dir() -> Path:
    return Path(__file__).resolve().parent.parent / 'autogenerated'


def run_simple(client: ToolsAPIClient, *, use_cache: bool = True) -> None:
    out_dir = _autogen_dir()
    for endpoint, fname, var_name, doc in SIMPLE_ENTITIES:
        out_path = out_dir / fname
        n = dump_endpoint(
            client, endpoint, str(out_path), var_name,
            use_cache=use_cache, docstring=doc,
        )
        print(f'  [{endpoint:20s}] {n:4d} entities → {fname}')


def run_complex(client: ToolsAPIClient, *, use_cache: bool = True) -> None:
    """Delegate to per-entity custom ingest modules.

    `shops` is intentionally excluded: the tools API does not yet expose
    per-item stock/price/currency, so the wiki-scraped util/autogenerated/
    shops.py (class shape: ShopItem/ShopInfo/ALL_SHOPS, consumed by ui/app.py
    and ui/crafting_tree.py) remains the source of truth. Running the shops
    ingest here would clobber it with an incomplete raw-dict and there is no
    shops emitter to restore it. Re-enable only once the API exposes the full
    shop shape AND a shops emitter is added to old_shape_emitters.EMITTERS.
    """
    from util.scrapers import ingest_locations_from_tools_api as locs
    from util.scrapers import ingest_routes_from_tools_api as routes
    from util.scrapers import ingest_pets_from_tools_api as pets
    from util.scrapers import ingest_items_from_tools_api as items
    from util.scrapers import ingest_activities_from_tools_api as acts

    locs.run(client, use_cache=use_cache)
    routes.run(client, use_cache=use_cache)
    pets.run(client, use_cache=use_cache)
    items.run(client, use_cache=use_cache)
    acts.run(client, use_cache=use_cache)


def run_internal_ids(client: ToolsAPIClient, *, use_cache: bool = True) -> int:
    """Final step: fetch internal ids for every cached item via
    POST /items/ids and write them to
    util/cache/tools_api_cache/_internal_ids.json.

    The internal id is the API's internal UUID for an item — the
    legacy equipment.py used these as the `uuid` field, and saved
    user gearsets reference items by this UUID. We need them as a
    side-channel because the regular /items/id/<id> detail endpoint
    does not expose the internal UUID.
    """
    items_list = client.list('items', use_cache=use_cache)
    api_ids = [it.get('id') for it in items_list if it.get('id')]
    print(f'  [internal_ids       ] resolving {len(api_ids)} items …')
    mapping = client.lookup_internal_ids(api_ids, target='base')
    out_path = _autogen_dir().parent / 'cache' / 'tools_api_cache' / '_internal_ids.json'
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(mapping, indent=2, sort_keys=True),
        encoding='utf-8',
    )
    print(f'  [internal_ids       ] wrote {len(mapping)} entries → {out_path.name}')
    return len(mapping)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--no-cache', action='store_true',
                   help='Bypass disk cache for this run')
    p.add_argument('--prod', action='store_true',
                   help='Use production endpoint instead of dev')
    p.add_argument('--simple-only', action='store_true',
                   help='Skip locations/shops/routes/pets/items/activities')
    p.add_argument('--complex-only', action='store_true',
                   help='Only run the custom-transform entities')
    p.add_argument('--skip-internal-ids', action='store_true',
                   help='Skip the final POST /items/ids batch lookup')
    p.add_argument('--skip-emit', action='store_true',
                   help='Skip the final old-shape emit step that regenerates '
                        'the legacy class-shape autogenerated files the app '
                        'imports (equipment.py, locations.py, materials.py, …). '
                        'Without this step the autogenerated files stay in a '
                        'raw-dict shape the app cannot import.')
    args = p.parse_args()

    base = ('https://tools-api.dev.walkscape.app' if args.prod
            else 'https://tools-api-dev.dev.walkscape.app')
    client = ToolsAPIClient(base_url=base)
    use_cache = not args.no_cache
    print(f'[ingest-all] base={client.base_url} cache={"on" if use_cache else "off"}')

    if not args.complex_only:
        print('\n=== simple entities ===')
        run_simple(client, use_cache=use_cache)
    if not args.simple_only:
        print('\n=== complex entities (custom transforms) ===')
        run_complex(client, use_cache=use_cache)
    if not args.skip_internal_ids:
        print('\n=== internal id lookup ===')
        run_internal_ids(client, use_cache=use_cache)
    if not args.skip_emit:
        print('\n=== emit legacy class-shape files (final step) ===')
        # Imported lazily: emit_all reads only the tools-API cache (just
        # populated above) and has no dependency on the network client.
        from util.scrapers.old_shape_emitters import emit_all
        paths = emit_all()
        for name, p_ in paths.items():
            print(f'  [{name:14s}] wrote {p_.name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
