#!/usr/bin/env python3
"""
Patch item_ref=None entries in activities.py by looking up items
directly from the autogenerated files without triggering circular imports.

Usage:
    python3 util/scrapers/patch_activity_item_refs.py
"""

import re
from pathlib import Path

# ============================================================================
# Build lookup by reading files directly (no imports)
# ============================================================================

def extract_names_from_file(filepath, class_names):
    """Extract {name.lower(): 'TYPE.ENUM'} from a Python file by regex."""
    content = Path(filepath).read_text()
    lookup = {}
    type_prefix_default = class_names[0][1] if class_names else 'Item'
    for class_name, type_prefix in class_names:
        # Match: ENUM_NAME = TypeClass( ... name="Item Name"
        # or:    ENUM_NAME = TypeClass( name="Item Name"
        pattern = rf'^\s+([A-Z_0-9]+)\s*=\s*{class_name}\s*\('
        for m in re.finditer(pattern, content, re.MULTILINE):
            enum_name = m.group(1)
            # Find the name= field after this match
            start = m.end()
            name_match = re.search(r'name=["\']([^"\']+)["\']', content[start:start+500])
            if name_match:
                item_name = name_match.group(1).lower()
                lookup[item_name] = f"{type_prefix}.{enum_name}"
    # Also handle: ENUM_NAME = DICT['Item Name'] pattern (used in collectibles)
    dict_pattern = r"^\s+([A-Z_0-9]+)\s*=\s*\w+\['([^']+)'\]"
    for m in re.finditer(dict_pattern, content, re.MULTILINE):
        enum_name = m.group(1)
        item_name = m.group(2).lower()
        if item_name not in lookup:
            lookup[item_name] = f"{type_prefix_default}.{enum_name}"
    return lookup


def build_lookup():
    """Build a comprehensive name→ref lookup from all autogenerated files."""
    lookup = {}

    # Equipment items
    lookup.update(extract_names_from_file('util/autogenerated/equipment.py', [
        ('ItemInstance', 'Item'),
        ('CraftedItem', 'Item'),
        ('AchievementItem', 'Item'),
    ]))

    # Materials
    lookup.update(extract_names_from_file('util/autogenerated/materials.py', [
        ('MaterialInstance', 'Material'),
    ]))

    # Collectibles
    lookup.update(extract_names_from_file('util/autogenerated/collectibles.py', [
        ('CollectibleInstance', 'Collectible'),
    ]))

    # Consumables
    lookup.update(extract_names_from_file('util/autogenerated/consumables.py', [
        ('ConsumableItem', 'Consumable'),
    ]))

    # Containers
    lookup.update(extract_names_from_file('util/autogenerated/containers.py', [
        ('ContainerInfo', 'Container'),
    ]))

    # Pets
    lookup.update(extract_names_from_file('util/autogenerated/pets.py', [
        ('PetInstance', 'Pet'),
    ]))

    # Currency
    lookup.update(extract_names_from_file('util/autogenerated/currency.py', [
        ('CurrencyInstance', 'Currency'),
    ]))

    return lookup


# ============================================================================
# Patch activities.py
# ============================================================================

def patch_activities(lookup):
    return patch_file(lookup, Path('util/autogenerated/activities.py'))


def patch_file(lookup, path):
    content = path.read_text()

    # Find all item_ref=None entries (excluding Nothing and Coins which are intentional)
    # Also handle double-quoted item names
    pattern = r'DropEntry\(item_name=[\'"]([^\'"]+)[\'"], item_ref=None,'
    
    patched = 0
    skipped = []
    
    def replace_ref(m):
        nonlocal patched
        item_name = m.group(1)
        
        # Skip intentional None entries
        if item_name in ('Nothing', 'Coins'):
            return m.group(0)
        
        # Look up the item
        ref = lookup.get(item_name.lower())
        if ref:
            patched += 1
            return m.group(0).replace("item_ref=None", f'item_ref="{ref}"')
        else:
            skipped.append(item_name)
            return m.group(0)
    
    new_content = re.sub(pattern, replace_ref, content)
    
    if new_content != content:
        path.write_text(new_content)
        print(f"  Patched {patched} item_refs")
    else:
        print(f"  No changes needed")
    
    # Deduplicate skipped
    skipped_unique = sorted(set(skipped))
    if skipped_unique:
        print(f"  Still unresolved ({len(skipped_unique)}): {', '.join(skipped_unique[:20])}")
    
    return patched


if __name__ == '__main__':
    print("Building item lookup from autogenerated files...")
    lookup = build_lookup()
    print(f"  Found {len(lookup)} items")

    print("\nPatching activities.py...")
    patched = patch_activities(lookup)

    print("\nPatching containers.py...")
    patched_c = patch_file(lookup, Path('util/autogenerated/containers.py'))

    print("\nVerifying...")
    import subprocess
    r = subprocess.run(['python3', '-m', 'py_compile', 'util/autogenerated/activities.py'], capture_output=True)
    if r.returncode == 0:
        print("  ✓ activities.py compiles OK")
    else:
        print(f"  ✗ {r.stderr.decode()}")
