#!/usr/bin/env python3
"""
Download location icons from Walkscape wiki.

Uses the locations.py file to get icon names for each location,
then downloads the SVG icons from the wiki.

Icons are saved to: assets/icons/locations/{icon_filename}
"""

import requests
import sys
import os
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from util.scrapers.scraper_utils import sanitize_filename

# ============================================================================
# CONFIGURATION
# ============================================================================

BASE_OUTPUT_DIR = Path('assets/icons/locations')

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def download_icon(icon_filename: str, output_path: Path) -> bool:
    """Download a single icon SVG file."""
    if not icon_filename:
        return False
    
    try:
        # Build wiki URL for the file
        # MediaWiki uses Title_Case filenames (e.g., Castle_White_Icon.svg)
        # but we store them lowercase locally
        name_part, ext = icon_filename.rsplit('.', 1)
        wiki_filename = '_'.join(word.capitalize() for word in name_part.split('_')) + '.' + ext
        url = f'https://wiki.walkscape.app/wiki/File:{wiki_filename}'
        
        print(f"  Fetching page: {url}")
        
        # First, get the file page to find the actual image URL
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        
        # Parse the page to find the actual SVG URL
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Find the link to the full resolution file
        # Look for <a href="/images/...svg">
        img_link = None
        for link in soup.find_all('a', href=True):
            href = link.get('href', '')
            if href.startswith('/images/') and icon_filename.lower() in href.lower():
                img_link = href
                break
        
        if not img_link:
            print(f"    ✗ Could not find image link on page")
            return False
        
        # Make URL absolute
        if img_link.startswith('/'):
            img_link = 'https://wiki.walkscape.app' + img_link
        
        print(f"  Downloading: {img_link}")
        
        # Download the actual SVG file
        img_response = requests.get(img_link, timeout=10)
        img_response.raise_for_status()
        
        # Create parent directory if needed
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Save to file
        with open(output_path, 'wb') as f:
            f.write(img_response.content)
        
        print(f"    ✓ Saved to {output_path}")
        return True
    except Exception as e:
        print(f"    ✗ Error: {e}")
        return False

def get_location_icons():
    """Get all location icons from locations.py."""
    # Import here to avoid circular import
    try:
        from util.autogenerated.locations import Location
        
        icons = set()  # Use set to avoid duplicates
        
        # Iterate through all Location attributes
        for attr_name in dir(Location):
            if attr_name.startswith('_'):
                continue
            attr = getattr(Location, attr_name)
            if hasattr(attr, 'icon_name') and attr.icon_name:
                icons.add(attr.icon_name)
        
        return sorted(icons)
    except ImportError as e:
        print(f"✗ Could not import locations.py: {e}")
        return []

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == '__main__':
    print("=== Location Icon Scraper ===\n")
    
    print("Reading location icons from locations.py...")
    icon_filenames = get_location_icons()
    
    if not icon_filenames:
        print("✗ No location icons found")
        sys.exit(1)
    
    print(f"✓ Found {len(icon_filenames)} unique location icons\n")
    
    print("Downloading icons...\n")
    
    success_count = 0
    for icon_filename in icon_filenames:
        # Output path (flat structure in locations directory, lowercase)
        output_filename = icon_filename.lower()
        output_path = BASE_OUTPUT_DIR / output_filename
        
        print(f"{icon_filename} → {output_filename}")
        if download_icon(icon_filename, output_path):
            success_count += 1
        print()  # Empty line between downloads
    
    print(f"✓ Downloaded {success_count}/{len(icon_filenames)} icons")
    print(f"✓ Icons saved to {BASE_OUTPUT_DIR}/")
