#!/usr/bin/env python3
"""
Re-backfill inventory_value for all sessions, now including coins.

The first backfill (20260311_120006) may have set values to 0 if item
resolution failed. This re-runs with coins included in the total.
"""

import json


def run(conn):
    """Called by apply_migrations.py with an open sqlite3 connection."""
    from util.autogenerated.export_names import get_item_from_export_name

    cursor = conn.cursor()
    cursor.execute("""
        SELECT uuid, character_config
        FROM sessions
        WHERE character_config IS NOT NULL
    """)
    rows = cursor.fetchall()

    updated = 0
    total_value_all = 0

    for uuid, config_json in rows:
        try:
            config = json.loads(config_json) if isinstance(config_json, str) else config_json
        except (json.JSONDecodeError, TypeError):
            continue

        owned_items = config.get('owned_items', [])
        coins = config.get('coins', 0) or 0
        inventory_value = coins

        for export_name in owned_items:
            try:
                item = get_item_from_export_name(export_name)
                if item and hasattr(item, 'value') and item.value:
                    inventory_value += item.value
            except Exception:
                pass

        cursor.execute(
            "UPDATE sessions SET inventory_value = ? WHERE uuid = ?",
            (inventory_value, uuid)
        )
        updated += 1
        total_value_all += inventory_value

    conn.commit()
    print(f"    Re-backfilled {updated} sessions (with coins), total: {total_value_all:,}")
