"""effective_bitmap — compute Static_Maximal_Bitmap per (skill, location, quality_mode).

Two-phase algorithm:
  Phase 1: For each owned, unlocked, non-hidden item NOT in runtime_eval set,
           look up its dominators_bitmap. AND with character's owned-and-unlocked
           bitmap. If result is zero, item is in maximal set.
  Phase 2: For runtime-eval items (custom_stat / AchievementItem), compute
           effective stats given character state, do mini per-slot dominance
           check against current maximal set, add if not dominated.
"""

from typing import Dict, Optional, Set

from .bitmap_ops import (
    bitmap_and_is_nonzero,
    empty_bitmap,
    iter_set_bits,
    set_bit,
)
from .state_snapshot import CharacterStateSnapshot


def _check_unlock(item, state: CharacterStateSnapshot) -> bool:
    """Return True iff every requirement on item is satisfied by state."""
    reqs = getattr(item, "requirements", None) or []
    for req in reqs:
        if not isinstance(req, dict):
            continue
        rt = req.get("type")
        if rt == "achievement_points":
            if state.achievement_points < req.get("amount", 0):
                return False
        elif rt == "activity_completion":
            # Gated stats use custom_stats UI toggles. We don't enforce
            # activity_completion as an UNLOCK gate (it's a gated_stats trigger).
            # Items with this as a requirement (rare) just check the toggle.
            toggle_keys = [
                str(req.get("activity", "")).lower().replace(" ", "_"),
                f"{req.get('activity', '')}_{req.get('completions', '')}",
            ]
            if not any(state.custom_stats.get(k, False) for k in toggle_keys if k):
                return False
        elif rt == "category_level_percent":
            cat = (req.get("category") or "").lower()
            need = req.get("percent", 0)
            if state.category_total_pct(cat) < need:
                return False
        elif rt == "character_level":
            if state.character_level < req.get("level", 0):
                return False
        elif rt == "reputation":
            faction = (req.get("faction") or "").lower()
            need = req.get("amount", 0)
            if state.reputation.get(faction, 0) < need:
                # Try fuzzy match (factions sometimes capitalized differently)
                found = False
                for k, v in state.reputation.items():
                    if k.lower() == faction and v >= need:
                        found = True
                        break
                if not found:
                    return False
        elif rt == "skill":
            skill = (req.get("skill") or "").lower()
            need = req.get("level", 0)
            if state.skill_levels.get(skill, 1) < need:
                return False
        # Unknown types: ignore (fail-open)
    return True


def _build_owned_unlocked_bitmap(state: CharacterStateSnapshot, db) -> bytearray:
    """Build bitmap of items the character owns AND has unlocked.
    Hide flags are already baked into state.owned_items at snapshot construction.
    This function additionally applies item-level unlock requirements.
    """
    # Memoized per snapshot. compute_effective_owned_bitmap calls this once per
    # result-row scope (hundreds of times) with the SAME snapshot during a
    # single stale-check, and the result depends only on `state` (+ the static
    # item_id_map / catalog). Rebuilding the identical bitmap each time was a
    # top stale-check cost on populated characters. Cache on the frozen-
    # dataclass instance (non-field attr -> doesn't affect __eq__/prev!=curr).
    # Consumers only ever read it via bytes(owned_unlocked), never mutate.
    cached = state.__dict__.get('_owned_unlocked_cache')
    if cached is not None:
        return cached
    from .precompute.build_item_ids import get_item_id_map, get_max_item_id
    item_id_map = get_item_id_map(db)
    max_id = get_max_item_id(db)
    bm = empty_bitmap(max_id)

    # Build a slug->item_object lookup for unlock checking
    item_lookup = _build_catalog_lookup()

    for slug, quality in state.owned_items:
        item_id = item_id_map.get((slug, quality))
        if item_id is None:
            continue
        item_obj = item_lookup.get(slug)
        if item_obj is not None and not _check_unlock(item_obj, state):
            continue
        set_bit(bm, item_id)
    object.__setattr__(state, '_owned_unlocked_cache', bm)
    return bm


_CATALOG_CACHE = None


def _build_catalog_lookup() -> Dict[str, object]:
    """Cached lookup of slug -> item object for unlock checks."""
    global _CATALOG_CACHE
    if _CATALOG_CACHE is not None:
        return _CATALOG_CACHE
    import util.walkscape_constants  # noqa: F401
    from util.autogenerated.equipment import Item, ItemInstance, AchievementItem, CraftedItem
    from util.autogenerated.consumables import Consumable, ConsumableItem
    out: Dict[str, object] = {}
    for src_cls in (Item, Consumable):
        for n in dir(src_cls):
            if n.startswith("_"):
                continue
            v = getattr(src_cls, n, None)
            if isinstance(v, (ItemInstance, AchievementItem, CraftedItem, ConsumableItem)):
                out[n.lower()] = v
    _CATALOG_CACHE = out
    return out


def _resolve_quality_instance(item_obj, quality):
    """Resolve a catalog item + quality to the object that actually carries
    stats for that quality.

    CraftedItems store stats on per-quality instances (NORMAL..ETERNAL); the
    base object has no ``_stats``. Return the matching instance so callers that
    recompute effective stats (Phase 1 no-dominators inclusion, Phase 2
    runtime comparison) see real stats instead of an empty dict. Non-crafted
    items (ItemInstance / ConsumableItem / AchievementItem) carry stats
    directly and are returned unchanged.
    """
    try:
        from util.autogenerated.equipment import CraftedItem
    except Exception:
        return item_obj
    if isinstance(item_obj, CraftedItem):
        try:
            from .precompute.build_item_ids import _tier_to_crafted_key
            attr = _tier_to_crafted_key(str(quality).lower()).upper()
        except Exception:
            attr = str(quality).upper()
        inst = getattr(item_obj, attr, None)
        if inst is not None:
            return inst
    return item_obj


_ID_TO_ITEM_CACHE = None


def _get_id_to_item_map(db) -> Dict[int, tuple]:
    """Process-cached ``{item_id: (slug, quality, resolved_item_obj)}``.

    This map is CHARACTER-INDEPENDENT: it is derived solely from the static
    ``item_ids`` master index and the autogenerated catalog. Building it
    resolves every CraftedItem's per-quality instance (getattr -> _get_quality
    -> deep-copy), and compute_effective_owned_bitmap used to rebuild the whole
    map once per result-row scope -- hundreds of full passes over the master
    index per stale-check (the single largest load-time cost on populated
    characters: ~700k _resolve_quality_instance calls / ~12M deepcopies).

    The master index is fixed for the life of the process (the item_ids table
    is populated at startup), so build the map once -- same process-lifetime
    cache pattern as ``_CATALOG_CACHE``.
    """
    global _ID_TO_ITEM_CACHE
    if _ID_TO_ITEM_CACHE is not None:
        return _ID_TO_ITEM_CACHE
    from .precompute.build_item_ids import get_item_id_map
    item_id_map = get_item_id_map(db)
    catalog = _build_catalog_lookup()
    out: Dict[int, tuple] = {}
    for (slug, quality), iid in item_id_map.items():
        item_obj = catalog.get(slug)
        if item_obj is not None:
            item_obj = _resolve_quality_instance(item_obj, quality)
        out[iid] = (slug, quality, item_obj)
    _ID_TO_ITEM_CACHE = out
    return out


def compute_effective_owned_bitmap(
    state: CharacterStateSnapshot,
    skill: str,
    location: str,
    service: str = "NONE",
    quality_mode: str = "activity",
    db=None,
    required_keywords: Optional[Set[str]] = None,
) -> bytes:
    """Return Static_Maximal_Bitmap for the (skill, location, quality_mode) scope.

    required_keywords: the activity's mandatory tool keywords (e.g.
    {'fishing cage'} for Sea fishing (Cage)). When set, Phase 3 additionally
    includes the best owned tool(s) that SATISFY each required keyword, even
    if a higher-stat tool of a DIFFERENT banned-keyword group (e.g. a fishing
    spear/net) globally dominates them. This is what makes a keyword-gated
    activity go stale when the user crafts the required tool: the spear can't
    do cage fishing, so the lobster pot must count toward the cage scope's
    maximal set on its own keyword-restricted merits (jwbail 2026-06-30,
    bug 4038424d: "crafted lobster pots, owned, but Sea fishing (Cage) never
    re-optimizes to suggest the cage"). Global dominance is left untouched —
    for activities that do NOT require the cage, the spear correctly dominates
    it and nothing changes.
    """
    from .precompute.build_item_ids import get_max_item_id
    from .precompute.scan_runtime_eval import get_runtime_eval_set
    from .precompute.build_dominators import _effective_stats_in_scope, _statically_dominates, _get_item_slot

    if db is None:
        raise ValueError("db connection is required")

    max_id = get_max_item_id(db)
    if max_id == 0:
        return bytes(empty_bitmap(0))

    runtime_eval_ids = get_runtime_eval_set(db)
    owned_unlocked = _build_owned_unlocked_bitmap(state, db)
    maximal = empty_bitmap(max_id)

    cursor = db.cursor()

    # Reverse map: id -> (slug, quality, item_obj). Process-cached and
    # character-independent (see _get_id_to_item_map). For CraftedItems the
    # resolved object is the per-quality instance (NORMAL..ETERNAL) so the
    # no-dominators inclusion branch (Phase 1) and the runtime-eval comparison
    # (Phase 2) compute real effective stats -- base CraftedItem._stats is
    # absent. Without this, a quality change to a find-stat tool with no
    # dominator row in a scope never flips a bit and the scope never goes
    # stale (jwbail 2026-06-15: golden cutting mat Excellent->Perfect not
    # flagging the tailoring chest).
    id_to_item = _get_id_to_item_map(db)

    # ── Phase 1: precomputed dominators ─────────────────────────────
    for item_id in iter_set_bits(bytes(owned_unlocked)):
        if item_id in runtime_eval_ids:
            continue
        cursor.execute(
            "SELECT dominators_bitmap FROM item_static_dominators "
            "WHERE item_id = ? AND skill = ? AND location = ? AND quality_mode = ?",
            (item_id, skill, location, quality_mode),
        )
        row = cursor.fetchone()
        if row is None:
            # No dominators row means no item dominates this one in this scope
            # (or item doesn't participate in this scope). Include it if it
            # has any effective stats here.
            slug, quality, item_obj = id_to_item.get(item_id, (None, None, None))
            if item_obj is not None:
                eff = _effective_stats_in_scope(item_obj, skill, location, quality_mode)
                if eff:
                    set_bit(maximal, item_id)
            continue
        dominators_bitmap = row[0]
        if not bitmap_and_is_nonzero(dominators_bitmap, bytes(owned_unlocked)):
            set_bit(maximal, item_id)

    # ── Phase 2: runtime-eval items ─────────────────────────────────
    # For each runtime-eval item the character owns, compute its effective
    # stats in this scope, then check if it's dominated by anything currently
    # in maximal set OR vice versa.
    runtime_owned: Dict[int, tuple] = {}
    for item_id in iter_set_bits(bytes(owned_unlocked)):
        if item_id in runtime_eval_ids:
            slug, quality, item_obj = id_to_item.get(item_id, (None, None, None))
            if item_obj is None:
                continue
            # Compute effective stats accounting for character state
            eff = _runtime_eval_stats(item_obj, state, skill, location, quality_mode)
            if eff:
                runtime_owned[item_id] = (slug, quality, item_obj, eff)

    if runtime_owned:
        # For each runtime item, compare against same-slot items already in maximal
        for self_id, (self_slug, self_quality, self_item, self_eff) in runtime_owned.items():
            self_slot = _get_item_slot(self_item)
            if not self_slot:
                continue
            dominated = False
            # Compare against each currently-maximal item in same slot
            for other_id in iter_set_bits(bytes(maximal)):
                other_slug, other_quality, other_item = id_to_item.get(other_id, (None, None, None))
                if other_item is None:
                    continue
                if _get_item_slot(other_item) != self_slot:
                    continue
                from .precompute.build_dominators import _effective_stats_in_scope
                other_eff = _effective_stats_in_scope(other_item, skill, location, quality_mode)
                if not other_eff:
                    continue
                if _statically_dominates(other_eff, self_eff):
                    dominated = True
                    break
            if not dominated:
                set_bit(maximal, self_id)

    # ── Phase 3: keyword-gated activity tools ───────────────────────
    # For an activity that HARD-REQUIRES a tool keyword (keyword_counts, e.g.
    # 'fishing cage'), the globally-maximal set above is the wrong pool: a
    # higher-WE fishing spear/net statically dominates the lobster pot, so the
    # cage never enters the maximal set and acquiring it never flips a bit —
    # the scope stays "not stale" forever and the report never re-optimizes to
    # suggest the cage (bug 4038424d). The spear/net cannot actually perform
    # cage fishing, so within the cage-required scope they do NOT dominate the
    # cage. Re-evaluate dominance RESTRICTED to the keyword-satisfying owned
    # tools and include the survivors. This is purely additive — it can only
    # set more bits, never clear one — so non-keyword-gated scopes (the vast
    # majority) are unaffected.
    if required_keywords:
        _augment_keyword_gated_tools(
            maximal, required_keywords, owned_unlocked, runtime_eval_ids,
            id_to_item, state, skill, location, quality_mode,
        )

    return bytes(maximal)


def _augment_keyword_gated_tools(
    maximal, required_keywords, owned_unlocked, runtime_eval_ids,
    id_to_item, state, skill, location, quality_mode,
):
    """Set bits for owned tools that are non-dominated WITHIN each required
    keyword's satisfying pool. Mutates ``maximal`` in place.

    Dominance is recomputed only among items that share the required keyword,
    so a fishing spear (which lacks 'fishing cage') can never suppress the
    lobster pot in a cage-required scope. Per-slot, per-keyword.
    """
    from .precompute.build_dominators import (
        _effective_stats_in_scope, _statically_dominates, _get_item_slot,
    )

    req_lower = {str(k).lower() for k in required_keywords if k}
    if not req_lower:
        return

    def _eff_for(item_id, item_obj):
        if item_id in runtime_eval_ids:
            return _runtime_eval_stats(item_obj, state, skill, location, quality_mode)
        return _effective_stats_in_scope(item_obj, skill, location, quality_mode)

    # Gather owned-unlocked items that satisfy at least one required keyword
    # and have effective stats in this scope.
    # cand: item_id -> (item_obj, eff, slot, {satisfied required keywords})
    cand = {}
    for item_id in iter_set_bits(bytes(owned_unlocked)):
        slug, quality, item_obj = id_to_item.get(item_id, (None, None, None))
        if item_obj is None:
            continue
        kws = {str(k).lower() for k in (getattr(item_obj, "keywords", None) or [])}
        matched = kws & req_lower
        if not matched:
            continue
        eff = _eff_for(item_id, item_obj)
        if not eff:
            continue
        cand[item_id] = (item_obj, eff, _get_item_slot(item_obj), matched)

    if not cand:
        return

    # For each required keyword, keep the non-dominated satisfiers (per slot).
    # Restricting the dominance comparison to same-keyword items is the whole
    # point: cross-group tools (spear vs cage) never compete here.
    for kw in req_lower:
        group = [(iid, obj, eff, slot)
                 for iid, (obj, eff, slot, matched) in cand.items() if kw in matched]
        for self_id, self_obj, self_eff, self_slot in group:
            dominated = False
            for other_id, other_obj, other_eff, other_slot in group:
                if other_id == self_id or other_slot != self_slot:
                    continue
                if _statically_dominates(other_eff, self_eff):
                    # Strict domination wins; on a mutual/equal tie keep the
                    # lower id so we never drop BOTH members of a tie.
                    if not _statically_dominates(self_eff, other_eff) or other_id < self_id:
                        dominated = True
                        break
            if not dominated:
                set_bit(maximal, self_id)


def _runtime_eval_stats(item, state: CharacterStateSnapshot, skill: str, location: str, quality_mode: str):
    """Compute effective stats for a runtime-eval item given character state.

    For AchievementItem: use achievement_points to accumulate stats.
    For custom_stat items: use state.custom_stats UI toggles to gate stats.
    """
    from .precompute.build_dominators import _effective_stats_in_scope
    import util.walkscape_constants  # noqa: F401
    from util.autogenerated.equipment import AchievementItem

    if isinstance(item, AchievementItem):
        # Resolve to ItemInstance at character's AP, then get its scope-effective stats
        try:
            instance = item._get_stats_for_ap(state.achievement_points)
            return _effective_stats_in_scope(instance, skill, location, quality_mode)
        except Exception:
            return {}

    # custom_stat / activity_completion-gated: walk gated_stats with state.custom_stats
    base = _effective_stats_in_scope(item, skill, location, quality_mode) or {}
    gated = getattr(item, "gated_stats", None) or {}
    ac_block = gated.get("activity_completion", None)
    if isinstance(ac_block, dict):
        for activity_name, thresholds in ac_block.items():
            # Toggle key convention: depends on UI; check both common patterns
            keys = (
                str(activity_name).lower().replace(" ", "_"),
                f"{getattr(item, 'name', '').lower().replace(' ', '_')}_{str(activity_name).lower().replace(' ', '_')}",
            )
            if any(state.custom_stats.get(k, False) for k in keys):
                if isinstance(thresholds, dict):
                    for thresh, stat_block in thresholds.items():
                        # Apply via _effective_stats_in_scope on a synthetic raw
                        if isinstance(stat_block, dict):
                            for s_key, by_loc in stat_block.items():
                                if s_key not in (skill, "global"):
                                    continue
                                if isinstance(by_loc, dict):
                                    for loc_key, stats_dict in by_loc.items():
                                        if loc_key in ("global", location) or (loc_key.startswith("!") and location != loc_key[1:]):
                                            if isinstance(stats_dict, dict):
                                                for stat, val in stats_dict.items():
                                                    try:
                                                        base[stat] = base.get(stat, 0.0) + float(val)
                                                    except (TypeError, ValueError):
                                                        pass
    return base
