"""metric_inputs — compute hash of inputs that affect row metric without
affecting dominance_bitmap.

For activities and recipes:
  - effective_we_skill_level = min(state.skill_levels[primary_skill], source.we_cap)

For activity rows (xp/coins/chests/new_items, NOT chests_recipes):
  - state.ring_quantities so quantity-only hide changes (own 2x Good ring,
    hide one) trigger stale even when set membership is unchanged.
"""

import hashlib
from typing import Optional

# 2026-06-16 (jwbail): index of custom_stat_id -> set of skills its gated stat
# affects, derived from item gated_stats['activity_completion']. The gated-stat
# resolver (util/stats_mixin._add_gated_stats) keys on f"{item_name}_{activity}"
# (e.g. "screwdriver_tinkering"), which matches the UI custom-stats toggle id.
# Used to scope which stale rows a custom-stat toggle re-flags: only scopes
# whose primary skill the gated stat applies to (or 'global'). Built lazily.
_CUSTOM_STAT_SKILLS = None


def _custom_stat_skill_index():
    global _CUSTOM_STAT_SKILLS
    if _CUSTOM_STAT_SKILLS is not None:
        return _CUSTOM_STAT_SKILLS
    idx = {}
    try:
        import util.walkscape_constants  # noqa: F401
        from util.autogenerated.equipment import Item
        for n in dir(Item):
            if n.startswith('_'):
                continue
            v = getattr(Item, n, None)
            gs = getattr(v, 'gated_stats', None)
            if not isinstance(gs, dict):
                continue
            ac = gs.get('activity_completion')
            if not isinstance(ac, dict):
                continue
            item_name = (getattr(v, 'name', '') or '').lower().replace(' ', '_').replace("'", '')
            for activity, thresholds in ac.items():
                act_norm = str(activity).lower().replace(' ', '_').replace("'", '')
                csid = f"{item_name}_{act_norm}"
                skills = idx.setdefault(csid, set())
                if isinstance(thresholds, dict):
                    for _thr, tstats in thresholds.items():
                        if isinstance(tstats, dict):
                            for sk in tstats.keys():
                                skills.add(str(sk).lower())
    except Exception:
        idx = {}
    _CUSTOM_STAT_SKILLS = idx
    return idx


_PET_SKILLS = None


def _pet_skill_index():
    """pet species (lowercase) -> set of skills its stats touch (all levels)."""
    global _PET_SKILLS
    if _PET_SKILLS is not None:
        return _PET_SKILLS
    idx = {}
    try:
        import util.walkscape_constants  # noqa: F401
        from util.autogenerated.pets import PETS_BY_NAME
        for species, plevels in PETS_BY_NAME.items():
            skills = set()
            levels = plevels.get_all_levels() if hasattr(plevels, 'get_all_levels') else {}
            for _lvl, info in (levels or {}).items():
                st = getattr(info, '_stats', None) or {}
                if isinstance(st, dict):
                    for sk in st.keys():
                        skills.add(str(sk).lower())
            idx[str(species).lower()] = skills
    except Exception:
        idx = {}
    _PET_SKILLS = idx
    return _PET_SKILLS


_SKILL_GATE_THRESHOLDS = None


def _skill_gate_thresholds():
    """skill (lowercase) -> sorted tuple of skill_level gate thresholds across
    items. Flags stale when a level-up crosses a gated-stat threshold ABOVE the
    WE cap (which effective_we_level can't see — e.g. screwdriver +4% DR at 50)."""
    global _SKILL_GATE_THRESHOLDS
    if _SKILL_GATE_THRESHOLDS is not None:
        return _SKILL_GATE_THRESHOLDS
    raw = {}
    try:
        import util.walkscape_constants  # noqa: F401
        from util.autogenerated.equipment import Item
        for n in dir(Item):
            if n.startswith('_'):
                continue
            v = getattr(Item, n, None)
            gs = getattr(v, 'gated_stats', None)
            if not isinstance(gs, dict):
                continue
            sl = gs.get('skill_level')
            if not isinstance(sl, dict):
                continue
            for gate_skill, thresholds in sl.items():
                if isinstance(thresholds, dict):
                    s = raw.setdefault(str(gate_skill).lower(), set())
                    for t in thresholds.keys():
                        try:
                            s.add(int(t))
                        except (TypeError, ValueError):
                            pass
    except Exception:
        raw = {}
    _SKILL_GATE_THRESHOLDS = {k: tuple(sorted(v)) for k, v in raw.items()}
    return _SKILL_GATE_THRESHOLDS

from .state_snapshot import CharacterStateSnapshot


def _resolve_primary_skill(category: str, subcategory: str, source_name: str) -> Optional[str]:
    """Resolve the activity/recipe's primary skill for WE-cap calculation."""
    try:
        import util.walkscape_constants  # noqa: F401
        from util.autogenerated.activities import ACTIVITIES_BY_NAME
        from util.autogenerated.recipes import RECIPES_BY_NAME
    except ImportError:
        return None

    if category == "chests_recipes":
        recipe = RECIPES_BY_NAME.get(source_name)
        if recipe is not None:
            v = getattr(recipe, "skill", None)
            if v:
                return (v if isinstance(v, str) else getattr(v, "name", "")).lower()
    else:
        activity = ACTIVITIES_BY_NAME.get(source_name)
        if activity is not None:
            v = getattr(activity, "skill", None) or getattr(activity, "primary_skill", None)
            if v:
                return (v if isinstance(v, str) else getattr(v, "name", "")).lower()
    return None


def _resolve_we_cap(category: str, source_name: str) -> int:
    """Resolve the WE cap for the source. For activities, this is the
    activity's required level (WE bonuses cap there). For recipes, similar.
    Returns 99 if unknown (no cap effectively).
    """
    try:
        import util.walkscape_constants  # noqa: F401
        from util.autogenerated.activities import ACTIVITIES_BY_NAME
        from util.autogenerated.recipes import RECIPES_BY_NAME
    except ImportError:
        return 99

    if category == "chests_recipes":
        recipe = RECIPES_BY_NAME.get(source_name)
        if recipe is not None:
            return int(getattr(recipe, "level", None) or 99)
    else:
        activity = ACTIVITIES_BY_NAME.get(source_name)
        if activity is not None:
            # Activities have requirements list; find skill level requirement
            for req in (getattr(activity, "requirements", None) or []):
                if isinstance(req, dict) and req.get("type") == "skill":
                    return int(req.get("level", 99))
            # Fall back to activity.level if exposed
            return int(getattr(activity, "level", None) or getattr(activity, "min_level", None) or 99)
    return 99


def compute_metric_inputs_hash(
    state: CharacterStateSnapshot,
    category: str,
    subcategory: str,
    source_name: str,
    location: str,
    service: str,
    db=None,
) -> str:
    """Return SHA256 hex (truncated to 16 chars) of metric inputs."""
    primary_skill = _resolve_primary_skill(category, subcategory, source_name) or ""
    we_cap = _resolve_we_cap(category, source_name)
    effective_we_level = min(state.skill_levels.get(primary_skill, 1), we_cap)

    parts = [str(effective_we_level)]

    # 2026-06-16 (jwbail): include ONLY the custom stats relevant to this scope
    # so toggling a custom stat re-flags just the scopes it can affect — not
    # every row. A gated-stat custom stat (e.g. screwdriver_tinkering -> WE+9%
    # on Crafting) is relevant when its gated stat's skill matches this scope's
    # primary skill (or is 'global'). Custom stats NOT in the gated-stats index
    # (e.g. unlock-requirement toggles like skate_skiing, or access_*) can
    # affect item availability broadly, so include them for every scope (safe).
    if state.custom_stats:
        _idx = _custom_stat_skill_index()
        _pskill = (primary_skill or '').lower()
        _relevant = []
        for _csid, _val in sorted(state.custom_stats.items()):
            _skills = _idx.get(_csid)
            if _skills is None:
                _relevant.append(f"{_csid}={_val}")           # unknown -> include (safe)
            elif 'global' in _skills or (_pskill and _pskill in _skills):
                _relevant.append(f"{_csid}={_val}")           # gated stat hits this scope's skill
        if _relevant:
            parts.append("cs:" + ",".join(_relevant))

    _pskill = (primary_skill or '').lower()

    # 2026-06-16 (jwbail): owned pets relevant to this scope (species+level), so
    # adding a pet or leveling one re-flags only the scopes its stats affect.
    _owned_pets = getattr(state, 'owned_pets', None)
    if _owned_pets:
        _pidx = _pet_skill_index()
        _prel = []
        for _sp, _lvl in sorted(_owned_pets):
            _psk = _pidx.get(_sp)
            if _psk is None or 'global' in _psk or (_pskill and _pskill in _psk):
                _prel.append(f"{_sp}:{_lvl}")
        if _prel:
            parts.append("pet:" + ",".join(_prel))

    # 2026-06-16 (jwbail): level-gated stat thresholds met for this scope's
    # skill, so crossing a gate (e.g. Crafting 50 -> screwdriver +4% DR) re-flags
    # even when the level is at/above the WE cap (effective_we_level can't see it).
    if _pskill:
        _gthr = _skill_gate_thresholds().get(_pskill)
        if _gthr:
            _plevel = state.skill_levels.get(_pskill, 1)
            _met = [str(t) for t in _gthr if _plevel >= t]
            if _met:
                parts.append("glvl:" + ",".join(_met))

    # Activity rows include ring_quantities so quantity-only hide changes flag stale
    if category in ("xp", "coins", "chests", "new_items"):
        for (slug, quality), count in sorted(state.ring_quantities.items()):
            parts.append(f"ring:{slug}:{quality}:{count}")

    payload = "|".join(parts).encode()
    return hashlib.sha256(payload).hexdigest()[:16]
