"""Shared crafting-tree optimization engine.

Single source of truth for per-node crafting-tree gear optimization, used by
BOTH the server background task (app._run_crafting_tree_optimization, via a
subprocess executor) and the in-browser local (Pyodide) path (via an
in-process executor). Keeping ONE implementation prevents server/local drift.
"""
from typing import Optional, Dict, Any


def _auto_pick_input_items_for_activity(activity, session_data: Optional[Dict[str, Any]], skill_name: str) -> Dict[int, Dict[str, Any]]:
    """Pick the best-owned input item for each of an activity's input_items slots.

    Mirrors the JS logic in optimize-button.js::_autoSelectInputItems: for every
    keyword-type input requirement, find all owned items that satisfy the keyword
    (and meet the minimum level), score them by the sum of abs(stat values) on
    the activity's skill + global, and return the top one.

    Material-type inputs (e.g. Ectoplasm for Repair the Bank) are resolved to
    the specific material directly.

    Returns a dict keyed by input-item index (0-based) whose values match the
    shape column3.selectedInputItems uses on the frontend:
        {itemId, uuid, name, icon_path, rarity, quality, keywords, stats,
         is_fine, is_generic, input_type, input_reference}

    Returns {} if the activity has no input requirements or nothing suitable
    is owned.
    """
    if not activity or not getattr(activity, 'input_items', None):
        return {}

    owned_items = set((session_data or {}).get('owned_items', []) or [])
    if not owned_items:
        return {}

    from util.autogenerated.export_names import get_item_from_export_name
    from util.autogenerated.materials import MaterialInstance

    # Pre-build a catalog of owned resolved items for scoring.
    owned_resolved = []
    for export_name in owned_items:
        base = export_name
        quality_name = None
        for suffix, qname in (
            ('_common', 'Normal'), ('_uncommon', 'Good'), ('_rare', 'Great'),
            ('_epic', 'Excellent'), ('_legendary', 'Perfect'), ('_ethereal', 'Eternal'),
        ):
            if export_name.endswith(suffix):
                base = export_name[:-len(suffix)]
                quality_name = qname
                break
        item = get_item_from_export_name(base)
        if item is None:
            continue
        owned_resolved.append((item, quality_name, export_name))

    result = {}
    skill_lower = (skill_name or '').lower()

    def _score_item_for_skill(item):
        """Sum abs(stat_value) for the activity's skill + global."""
        stats = getattr(item, '_stats', None) or getattr(item, 'stats', None) or {}
        total = 0.0
        for sk, locs in (stats or {}).items():
            if sk.lower() != skill_lower and sk.lower() != 'global':
                continue
            for stat_vals in (locs or {}).values():
                if not isinstance(stat_vals, dict):
                    continue
                for v in stat_vals.values():
                    try:
                        total += abs(float(v))
                    except (TypeError, ValueError):
                        continue
        return total

    def _pack(item, quality_name=None, input_type='keyword', input_reference=''):
        quality_to_rarity = {
            'Normal': 'common', 'Good': 'uncommon', 'Great': 'rare',
            'Excellent': 'epic', 'Perfect': 'legendary', 'Eternal': 'ethereal',
        }
        rarity = quality_to_rarity.get(quality_name or '', None) or getattr(item, 'rarity', 'common') or 'common'
        # Short id: Material.COPPER_ARROWS -> copper_arrows, Item.GHOST_TRAP_PACK -> ghost_trap_pack
        item_id = getattr(item, 'export_name', None) or (
            getattr(item, 'name', '').lower().replace(' ', '_').replace("'", '').replace('(', '').replace(')', '')
        )
        # Icon path: derive from name. All input items (arrows, traps, etc.) are
        # MaterialInstance objects and live under /materials/.
        icon_filename = getattr(item, 'name', '').replace(' (Fine)', '').replace(' ', '_').lower() + '.svg'
        icon_path = f"/assets/icons/items/materials/{icon_filename}"

        # Include the raw stats dict so the frontend combined-stats-section
        # can apply input-item bonuses to the calculation (it filters out
        # items without a `stats` property).
        raw_stats = getattr(item, '_stats', None) or {}

        return {
            'itemId': item_id,
            'uuid': getattr(item, 'uuid', None),
            'name': getattr(item, 'name', ''),
            'icon_path': icon_path,
            'rarity': rarity,
            'quality': quality_name,
            'keywords': list(getattr(item, 'keywords', []) or []),
            'stats': raw_stats,
            'is_fine': '(Fine)' in str(getattr(item, 'name', '')),
            'is_generic': False,
            'input_type': input_type,
            'input_reference': input_reference,
        }

    for idx, ii in enumerate(activity.input_items):
        input_type = getattr(ii, 'type', '')
        reference = getattr(ii, 'reference', '') or ''
        min_level = getattr(ii, 'level', None) or 0

        if input_type == 'keyword':
            kw = reference.lower().replace('_', ' ')
            candidates = []
            for item, qname, _ex in owned_resolved:
                kws = [k.lower() for k in (getattr(item, 'keywords', []) or [])]
                if not any(k.replace('_', ' ') == kw for k in kws):
                    continue
                # Min-level check via requirements
                if min_level > 0:
                    reqs = getattr(item, 'requirements', []) or []
                    skill_req = next((r for r in reqs if (r.get('type') if isinstance(r, dict) else getattr(r, 'type', None)) == 'skill'), None)
                    if skill_req is not None:
                        level = skill_req.get('level') if isinstance(skill_req, dict) else getattr(skill_req, 'level', 0)
                        if (level or 0) < min_level:
                            continue
                candidates.append((item, qname))
            if not candidates:
                continue
            scored = [((_score_item_for_skill(it), it, q)) for (it, q) in candidates]
            scored.sort(key=lambda t: t[0], reverse=True)
            best_item, best_q = scored[0][1], scored[0][2]
            result[idx] = _pack(best_item, quality_name=best_q, input_type='keyword', input_reference=reference)

        elif input_type == 'material':
            # reference is like "Material.ECTOPLASM" — resolve directly.
            from util.autogenerated.materials import Material
            ref_attr = reference.split('.', 1)[-1] if '.' in reference else reference
            mat = getattr(Material, ref_attr, None)
            if mat is not None and isinstance(mat, MaterialInstance):
                result[idx] = _pack(mat, input_type='material', input_reference=reference)

    return result


def _cumulative_steps_per_item(nodes: list) -> dict:
    """Map each node_id -> the FULL cost (in steps) to produce ONE unit of that
    node's item, including its entire material subtree.

    Bug d9aaf5af: the per-node recipe optimizer scores gear by
    total_tree_steps_for_target, whose downstream term is
    `input_ratio × child_steps_per_item`. That term was fed each child's
    LOCAL `steps_per_item` (the recipe/activity's own step cost), NOT the
    child's cumulative subtree cost. When a child is itself produced from a
    deep/expensive chain (e.g. Ruby <- Shape a ruby <- Rough ruby from a Gem
    pouch chest at ~28.5k steps each), the parent recipe (Silver ruby ring)
    only "saw" ~122 steps per ruby instead of the true ~11.3k, so
    no_materials_consumed / double_rewards / quality_outcome gear — which cuts
    how many rubies (and therefore rough rubies) are needed — was undervalued
    by ~90x and the optimizer picked locally-fast work_efficiency gear. A
    materials-focused imported gearset then beat the "optimized" one by 200k+
    steps.

    The cumulative per-item cost is a bottom-up rollup:
        cumulative(node) = local_steps_per_item(node)
                         + Σ_children (child.eff_qty / node.eff_qty)
                                       × cumulative(child)
    where `child.eff_qty / node.eff_qty` is how many child items the solved
    tree consumes per single parent item. This reconstructs the tree total
    (verified against saved node metrics). Leaf/activity/chest/bank nodes have
    no children, so their cumulative == local steps_per_item.

    Returns {node_id: cumulative_steps_per_item(float)}. Nodes with missing or
    non-finite metrics fall back to their local steps_per_item (or 0.0).
    """
    children_by_parent: dict = {}
    for n in nodes:
        pid = n.get("parent_id")
        if pid:
            children_by_parent.setdefault(pid, []).append(n)
    by_id = {n["node_id"]: n for n in nodes}

    def _local(n):
        m = n.get("metrics") or {}
        v = m.get("steps_per_item")
        if v is None:
            v = m.get("self_steps")
        try:
            v = float(v) if v is not None else 0.0
        except (TypeError, ValueError):
            v = 0.0
        if v < 0 or v == float("inf"):
            return 0.0
        return v

    def _eff_qty(n):
        q = n.get("effective_quantity")
        try:
            q = float(q) if q is not None else 0.0
        except (TypeError, ValueError):
            q = 0.0
        return q

    memo: dict = {}
    visiting: set = set()

    def _cum(node_id):
        if node_id in memo:
            return memo[node_id]
        node = by_id.get(node_id)
        if node is None:
            return 0.0
        # Guard against cycles (should not happen in a tree) — treat as leaf.
        if node_id in visiting:
            return _local(node)
        visiting.add(node_id)
        total = _local(node)
        parent_qty = _eff_qty(node)
        for child in children_by_parent.get(node_id, []):
            child_cum = _cum(child["node_id"])
            child_qty = _eff_qty(child)
            if parent_qty > 0 and child_qty > 0:
                ratio = child_qty / parent_qty
            else:
                # No solved quantities to derive the ratio — fall back to the
                # child's per-craft requirement so we still credit SOME
                # downstream cost rather than silently dropping it.
                try:
                    ratio = float(child.get("base_requirement_amount", 1) or 1)
                except (TypeError, ValueError):
                    ratio = 1.0
            total += ratio * child_cum
        visiting.discard(node_id)
        memo[node_id] = total
        return total

    return {n["node_id"]: _cum(n["node_id"]) for n in nodes}


def _select_route_finalists(cheap, band=1.10):
    """Pick the Best(auto) route candidates worth a full optimize.

    `cheap` is a list of (cheap_steps_per_item, candidate) from the fast
    gear-aware ranking pass. Returns every candidate whose cheap estimate is
    within `band`x of the best FINITE estimate -- i.e. the clear winner plus
    any genuine near-tie -- preserving input order. Non-finite estimates
    (None/inf, a route that failed to optimize) are dropped. Returns [] when
    nothing is finite.

    Split out so the within-10% rule is unit-testable without the optimizer
    subprocess (bug f5a30d6b).
    """
    finite = [(s, c) for (s, c) in cheap
              if s is not None and s != float("inf")]
    if not finite:
        return []
    best = min(s for s, _ in finite)
    return [c for (s, c) in finite if s <= best * band]


def _chest_target_name_for_node(node):
    """Resolve the chest a chest-source node should optimize for.

    Crafting-tree chest nodes (e.g. Rough ethernite sourced from Gem pouches
    that drop from Guard duty) are remapped to their PARENT ACTIVITY for gear
    optimization, because the per-node worker only understands activity/recipe
    sources. That remap used to silently drop the chest identity: the node was
    optimized with NO sorting target and TARGET_ITEM=None, so the scorer's
    comparator fell back to "any reward roll counts" (see optimize_activity_
    gearsets._relevant_drop_names) and optimized the activity for generic drops
    instead of the specific chest. The user then had to run the standalone
    activity optimizer (which lets them pick cat:chests) and import the gearset
    to get a good result. Bug b24a13f8.

    Returns the Container's display name (e.g. 'Gem pouch') so the caller can
    set it as the steps_per_reward_roll sorting target + headline TARGET_ITEM —
    the same signals the standalone cat:chests path produces. Falls back to
    'cat:chests' (still a chest, just not the specific one) when the container
    enum can't be resolved.
    """
    chest_id = node.get("underlying_source_id") or node.get("source_id")
    if not chest_id:
        return "cat:chests"
    try:
        from util.autogenerated.containers import Container
        cont = getattr(Container, str(chest_id), None)
        name = getattr(cont, "name", None)
        if name:
            return name
    except Exception:
        pass
    return "cat:chests"


def optimize_crafting_tree(
    session_uuid: str,
    nodes: list,
    global_settings: dict,
    session_data,
    ui_config: dict,
    task: dict,
    node_ids: list = None,
    depth_optimize: bool = False,
    *,
    node_executor,
    log,
):
    """Shared crafting-tree node-optimization core (server + local Pyodide).

    Extracted verbatim from app._run_crafting_tree_optimization so the server
    (subprocess executor) and the in-browser local path (in-process executor)
    run byte-identical logic -- no drift.

    node_executor(request_data) -> a result-like object exposing .returncode,
    .stdout and .stderr (subprocess.CompletedProcess on the server; an
    equivalent shim in Pyodide). It MAY raise subprocess.TimeoutExpired or a
    generic Exception -- the per-node loop catches both.

    `task` is the shared progress/result sink (same dict shape the
    /crafting-tree/optimize-status poll reads): completed_nodes[], pending,
    total, final_nodes, status. `log(msg, session_uuid)` matches app.log's
    signature.
    """
    import subprocess  # noqa: F401  (used by `except subprocess.TimeoutExpired`)

    # --- Gear-aware Best(auto) route resolution (bug 9b3527ef) ----------------
    # The per-node optimize loop is wrapped in a reusable pass so it can run
    # over the real tree AND over trial deepcopies of a single Best(auto)
    # node's candidate-route subtrees. `record` gates progress / completed-node
    # bookkeeping so trial runs don't corrupt the task status. The parameters
    # are named to match the original closure variables so the loop body below
    # is unchanged except for the _record_completed / _dec_pending wrappers.
    def _optimize_pass(nodes, eligible, _children_by_parent, _optimization_cache, record=True, fast_rank=False):
        def _record_completed(entry):
            if record:
                task["completed_nodes"].append(entry)
        def _dec_pending():
            if record:
                task["pending"] = max(0, task.get("pending", 1) - 1)
        for node in eligible:
            try:
                # Determine the activity/recipe ID for the worker
                node_source_type = node.get("source_type", "activity")
                # Resolve 'best' to the underlying source type
                if node_source_type == "best":
                    node_source_type = node.get("underlying_source_type", "activity")
                # Skip shop/bank nodes — nothing to optimize
                if node_source_type in ("bank", "shop"):
                    _dec_pending()
                    continue
                node_activity_id = None
                node_recipe_id = None
                # Chest-source nodes carry a chest identity that is lost when we
                # remap source_type to "activity" below. Capture the chest's
                # target name so the per-node optimize scores chests-per-step
                # for THIS chest, not any-reward. None for non-chest nodes.
                # Bug b24a13f8.
                node_chest_target = None
                node_service_id = node.get("selected_service_id")
                node_location = node.get("selected_location_id")

                if node_source_type == "recipe":
                    node_recipe_id = node.get("underlying_source_id") or node.get("source_id")
                    # Resolve service location for the optimizer
                    if not node_location and node_service_id and node_service_id not in ('__best__', '__none__'):
                        from util.autogenerated.services import Service, ServiceInstance
                        for attr_name in dir(Service):
                            if attr_name.startswith('_'):
                                continue
                            svc = getattr(Service, attr_name)
                            if isinstance(svc, ServiceInstance) and attr_name == node_service_id:
                                if hasattr(svc.location, 'name'):
                                    node_location = svc.location.name
                                break
                    # If still no location, try to get it from the best service in stats_used
                    if not node_location:
                        svc_name = node.get("metrics", {}).get("stats_used", {}).get("service_name", "")
                        if svc_name and "(" in svc_name:
                            # Extract location from "Service Name (Location)"
                            node_location = svc_name.split("(")[-1].rstrip(")")
                    # For no-service recipes: if user picked a specific location, use it;
                    # if '__best__', clear it so the worker tests all locations
                    if node_location == '__best__':
                        node_location = None
                elif node_source_type in ("activity", "chest"):
                    if node_source_type == "activity":
                        node_activity_id = node.get("underlying_source_id") or node.get("source_id")
                    else:
                        # Chest: optimize for the parent activity that drops the chest
                        node_activity_id = node.get("parent_activity_id")
                        # Preserve the chest identity BEFORE the remap so the
                        # per-node optimizer targets THIS chest (e.g. Gem pouch)
                        # and not any-reward. Bug b24a13f8.
                        node_chest_target = _chest_target_name_for_node(node)
                        node_source_type = "activity"  # Worker only understands activity, not chest

                # Guard: skip if we couldn't resolve an activity or recipe ID
                if node_source_type == "recipe" and not node_recipe_id:
                    log(f"Crafting tree: skipping node {node['node_id']} — no recipe ID", session_uuid)
                    _dec_pending()
                    continue
                if node_source_type in ("activity",) and not node_activity_id:
                    log(f"Crafting tree: skipping node {node['node_id']} — no activity ID", session_uuid)
                    _dec_pending()
                    continue

                # Shared gearset: check if we already optimized the same source+location.
                # The cache key includes locked_slots so two nodes with the same
                # source but different lock sets don't share an optimization
                # result (which would silently leak one node's locks into
                # another). Empty lock map → empty tuple, key stays stable.
                #
                # locked_slots values are dicts ({itemId, quality, level}) which
                # are unhashable. Reduce to a scalar (itemId or stringified
                # value) so the resulting tuple is hashable. The full dict is
                # stashed on the node and passed to the worker separately —
                # the cache key only needs to disambiguate "same item pinned"
                # vs "different item pinned", which itemId+quality+level
                # already capture.
                node_locked_slots = node.get("locked_slots") or {}
                def _hashable_lock_value(v):
                    if isinstance(v, dict):
                        return (v.get("itemId"), v.get("quality"), v.get("level"))
                    return v
                _locked_key = tuple(sorted(
                    (slot, _hashable_lock_value(info))
                    for slot, info in node_locked_slots.items()
                )) if node_locked_slots else ()
                # Compute the include flags up front so they can be added
                # to the cache key. Without this, toggling Optimize Pets /
                # Optimize Consumables and re-running gives a cache hit
                # from the old run (different flags, same node) so the
                # previous gearset is reused unchanged. User reported
                # 2026-05-15: "If I have the optimize pets/consumables
                # checked, it doesn't optimize for pets/consumables at
                # all". The chain was wired correctly; the cache was
                # silently masking the new flags.
                _include_consumables_for_cache = bool(
                    global_settings.get("optimize_consumables",
                        ui_config.get("include_consumables",
                            ui_config.get("activity_include_consumables", False)
                            or ui_config.get("recipe_include_consumables", False)))
                )
                _include_pets_for_cache = bool(
                    global_settings.get("optimize_pets",
                        ui_config.get("include_pets", False))
                )
                cache_key = (node_source_type, node_recipe_id or node_activity_id, node_location or '', node_service_id or '', _locked_key, _include_pets_for_cache, _include_consumables_for_cache, node_chest_target or '')
                if cache_key in _optimization_cache:
                    cached = _optimization_cache[cache_key]
                    node["gear_config"]["optimized_export"] = cached.get("gearset_export")
                    node["gear_config"]["optimized_stats"] = cached.get("stats", {})
                    cached_inputs = cached.get("selected_input_items") or {}
                    if cached_inputs:
                        node["gear_config"]["selected_input_items"] = cached_inputs
                    # Persist the cached optimizer pet/consumable picks on the node
                    # so cache hits behave the same as fresh optimization runs. Without
                    # this, two nodes sharing the same source+location got different
                    # treatment: the first run persisted optimized_pet, the second
                    # (cache hit) silently dropped it. Bug 9ce474f8 (darkbow): the
                    # optimizer picked a pet/consumable but they never appeared on
                    # the second cached node.
                    cached_opt_pet = cached.get("optimized_pet")
                    cached_opt_cons = cached.get("optimized_consumable")
                    node["gear_config"]["optimized_pet"] = cached_opt_pet
                    node["gear_config"]["optimized_consumable"] = cached_opt_cons
                    # Persist the cached slot_alternatives on the node so the
                    # tree-node slot popup's "Non-owned/Locked Upgrades"
                    # section works on cache hits too. Without this, two
                    # nodes sharing the same (source, location, locks)
                    # cache key got different treatment — the first run
                    # persisted slot_alternatives, the second (cache hit)
                    # silently dropped them and the popup showed
                    # "Optimize Slot & Equip" instead of upgrades.
                    cached_slot_alts = cached.get("slot_alternatives")
                    if cached_slot_alts is not None:
                        node["gear_config"]["slot_alternatives"] = cached_slot_alts
                    _record_completed({
                        "node_id": node["node_id"],
                        "gearset_export": cached.get("gearset_export"),
                        "stats": cached.get("stats", {}),
                        "metrics": cached.get("metrics", {}),
                        "selected_input_items": cached_inputs,
                        "optimized_pet": cached_opt_pet,
                        "optimized_consumable": cached_opt_cons,
                        # Echo the cached slot_alternatives wrapper so the
                        # frontend's optimize-status polling can apply it
                        # onto its local node.gear_config — same round-trip
                        # the optimized_pet/consumable fields rely on. Without
                        # this, cache hits left the popup empty even when the
                        # original optimize had upgrades to show. Mirror of
                        # the non-cache append below.
                        "slot_alternatives": cached_slot_alts,
                    })
                    _dec_pending()
                    log(f"Crafting tree: reusing gearset for node {node['node_id']} (shared with {cache_key[1]})", session_uuid)
                    continue

                # Build optimization request — pick correct default metric for source type
                sorting_priority = []
                opt_targets = node.get("gear_config", {}).get("optimization_targets", [])
                # For activity/chest nodes: optimize for steps_per_reward_roll (minimize steps to get
                # one drop of the target material). This is the same metric the standalone activity
                # optimizer uses and correctly values DA+DR together. Using expected_steps_per_action
                # would ignore DR and pick FMF items that are irrelevant for material farming.
                #
                # For recipe nodes with a non-Normal target_quality, use steps_for_target so the
                # optimizer factors in p(target_quality) and picks QO-boosting gear when that's
                # the bottleneck. For Normal targets (or Material/Consumable outputs, which the
                # worker remaps to Normal), expected_steps_per_item is equivalent and simpler.
                _user_target_quality = global_settings.get("target_quality", "Normal")
                if node_source_type in ("activity", "chest"):
                    default_metric = "steps_per_reward_roll"
                elif _user_target_quality and _user_target_quality != "Normal":
                    default_metric = "steps_for_target"
                else:
                    default_metric = "expected_steps_per_item"
                for t in opt_targets:
                    target_key = t.get("target", default_metric)
                    # Remap recipe-only metrics to activity equivalents when source is activity/chest
                    if node_source_type in ("activity", "chest"):
                        RECIPE_TO_ACTIVITY = {
                            "expected_steps_per_item": "steps_per_reward_roll",
                            "current_steps": "current_steps_activity",
                            "materials_per_craft": "steps_per_reward_roll",
                            "materials_for_target": "steps_per_reward_roll",
                            "total_crafts": "steps_per_reward_roll",
                            "steps_for_target": "steps_per_reward_roll",
                            "steps_for_budget": "steps_per_reward_roll",
                            "xp_per_material": "primary_xp_per_step",
                        }
                        target_key = RECIPE_TO_ACTIVITY.get(target_key, target_key)
                    sorting_priority.append([target_key, t.get("weight", 100)])
                # If no targets specified, use sensible defaults (worker module defaults will apply).
                # For steps_for_target we also attach the target_quality as the third tuple element
                # so the SortingEntry.target field is populated — that's what drives the
                # per-quality composite key (steps_for_target::Perfect) used for scoring.
                #
                # Bonez565 bug 424b34f7 (2026-05-17): "change default optimization to
                # target fine drops when fine materials are selected". When the
                # global use_fine flag is on AND the source is an activity (or
                # chest), default the per-node target to 'cat:fine' so the scorer
                # uses FMF-aware metrics (fine_item synthetic target) instead of
                # raw rewards. The scorer recognises this pair as
                # ('steps_per_reward_roll', 'cat:fine') == optimize for fine
                # material yield. Recipes are unaffected — their output is the
                # recipe.output_item regardless of fine, so the existing
                # quality-aware default is correct.
                if not sorting_priority:
                    if default_metric == "steps_for_target":
                        sorting_priority = [[default_metric, 100, _user_target_quality]]
                    elif (node_source_type in ("activity", "chest")
                            and global_settings.get("use_fine")):
                        sorting_priority = [[default_metric, 100, "cat:fine"]]
                    elif node_chest_target:
                        # Chest-source node: target the specific chest so the
                        # scorer optimizes chests-per-step (values chest_finding
                        # + DA/DR for THIS chest via the steps_per_reward_roll::
                        # <chest> composite), matching the standalone cat:chests
                        # path the user had to fall back to. Bug b24a13f8.
                        sorting_priority = [[default_metric, 100, node_chest_target]]
                    else:
                        sorting_priority = [[default_metric, 100]]

                request_data = {
                    "type": "crafting_tree_node",
                    "id": node_recipe_id or node_activity_id or "",
                    "node_source_type": node_source_type,
                    "node_activity_id": node_activity_id,
                    "node_recipe_id": node_recipe_id,
                    "node_service_id": node_service_id,
                    "node_location": node_location,
                    "sorting_priority": sorting_priority,
                    "character_config": session_data or {},
                    "ui_config": ui_config,
                    # Pets / consumables flags consumed by the optimize
                    # worker (optimize_worker.py reads include_pets +
                    # include_consumables — NOT the optimize_* keys).
                    # Wire the per-tree global_settings toggles
                    # (optimize_pets / optimize_consumables) THROUGH to
                    # the worker via the include_* keys it actually uses.
                    # Falls back to ui_config so the regular settings
                    # modal toggles (include_pets / include_consumables)
                    # also flow through when the per-tree toggles aren't
                    # set. Computed once above (the cache key needs the
                    # same values) so we reuse the bools here. Was
                    # previously hardcoded to False, which is why users
                    # with a useful pet/consumable for the target saw no
                    # effect on tree optimization.
                    "include_consumables": _include_consumables_for_cache,
                    "include_pets": _include_pets_for_cache,
                    # Tree-node opt-in toggles (Optimize Pets / Optimize
                    # Consumables in the crafting-tree global settings).
                    # Kept for back-compat with any worker code that still
                    # reads these — primary signal is the include_* keys
                    # above.
                    "optimize_pets": bool(global_settings.get("optimize_pets", False)),
                    "optimize_consumables": bool(global_settings.get("optimize_consumables", False)),
                    # Per-slot locks pinned via the tree-node slot popup. The
                    # worker honors these as hard constraints: locked items
                    # MUST be in the final gearset for that slot. Same dict
                    # already used for cache_key isolation above.
                    "locked_slots": node_locked_slots,
                    # Chest-source nodes: tell the worker which chest to treat
                    # as the headline TARGET_ITEM so it emits the chest composite
                    # and values chest_finding. None for non-chest nodes. Bug b24a13f8.
                    "target_item": node_chest_target,
                    # Propagate the user's target quality so the per-node optimizer
                    # picks gear that biases toward Quality Outcome for Perfect
                    # targets, rather than falling back to Normal (CRAFTING_BUGS.md).
                    "target_quality": global_settings.get("target_quality", "Normal"),
                    # Always request the slot-popup's "Non-owned/Locked Upgrades"
                    # data for tree nodes — the popup is always available from a
                    # tree-node card, so there's no point gating this. Without
                    # this flag, the worker's tree-node branches still skip the
                    # alternatives compute (mirrors the standard activity/recipe
                    # paths which only run when the request opts in).
                    "show_non_owned_alternatives": True,
                    # Set by the route-ranking phase only: tells the worker to
                    # run a fast greedy estimate (no deep 2/4-swap search) so we
                    # can RANK Best(auto) routes cheaply. The winning route is
                    # re-optimized at full depth afterward (bug f5a30d6b).
                    "fast_rank": bool(fast_rank),
                }

                # Tree-aware downstream cost specs for recipe nodes. Builds
                # a list of {item_ref, req_amount, child_steps_per_item} from
                # this node's children in the saved tree state. The worker
                # passes the list to optimize_craft_gearsets.CHILD_INPUT_SPECS,
                # which the per-quality scoring loop uses to compute the
                # total_tree_steps_for_target metric (recipe steps + cost of
                # producing inputs). When the list is empty (no children, or
                # children have no metrics yet because they haven't been
                # calculated), the optimizer falls back to local-only steps —
                # matches the pre-fix behavior.
                #
                # Children's metrics come from the last calculate_tree() pass.
                # If the user re-clicks Optimize before the tree recalculates,
                # children may carry stale metrics; that's fine — the optimizer
                # still has a non-zero downstream signal pointing in the right
                # direction. A future improvement is to re-run calculate_tree
                # after each per-node optimization to keep child metrics fresh
                # within a single batch.
                if node_source_type == "recipe":
                    _kids = _children_by_parent.get(node["node_id"], [])
                    _specs = []
                    # Cumulative per-item cost of every node's item (local recipe
                    # steps PLUS its entire material subtree). Feeding the child's
                    # LOCAL steps_per_item here undercounts deep chains and makes
                    # the optimizer ignore how much NMC/DR/quality gear saves
                    # downstream (bug d9aaf5af). Computed from the freshly
                    # calculate_tree'd metrics so effective_quantity ratios are
                    # current for this batch.
                    _cum_cost = _cumulative_steps_per_item(nodes)
                    for _kid in _kids:
                        _kid_metrics = _kid.get("metrics") or {}
                        # Prefer the cumulative subtree cost; fall back to the
                        # local per-item (then total_steps) if the rollup could
                        # not be computed for this child.
                        _kid_steps = _cum_cost.get(_kid.get("node_id"))
                        if _kid_steps is None or _kid_steps <= 0:
                            _kid_steps = _kid_metrics.get("steps_per_item")
                        if _kid_steps is None:
                            # Fall back to total_steps for leaf nodes that may
                            # only populate one or the other.
                            _kid_steps = _kid_metrics.get("total_steps")
                        try:
                            _kid_steps = float(_kid_steps) if _kid_steps is not None else 0.0
                        except (TypeError, ValueError):
                            _kid_steps = 0.0
                        if _kid_steps <= 0 or _kid_steps == float("inf"):
                            continue
                        _req = _kid.get("base_requirement_amount", 1)
                        try:
                            _req = float(_req) if _req is not None else 0.0
                        except (TypeError, ValueError):
                            _req = 0.0
                        if _req <= 0:
                            continue
                        _specs.append({
                            "item_ref": _kid.get("item_id") or "",
                            "req_amount": _req,
                            "child_steps_per_item": _kid_steps,
                        })
                    if _specs:
                        request_data["child_input_specs"] = _specs
                        log(
                            f"  [ct-worker] Tree-aware: {len(_specs)} child input "
                            f"specs for recipe {node_recipe_id}",
                            session_uuid,
                        )

                # Auto-select the best-owned input item for activity nodes that
                # declare `input_items` (e.g. arrows for hunting, ectoplasm for
                # Repair the Bank). Without this, the per-node optimizer runs
                # without INPUT_ITEM set and the user sees 0 DR/WE contribution
                # from their arrows — which silently under-counts drops.
                if node_source_type == "activity" and node_activity_id:
                    try:
                        from util.autogenerated.activities import ACTIVITIES_BY_NAME
                        _act = ACTIVITIES_BY_NAME.get(node_activity_id)
                        if _act and getattr(_act, 'input_items', None):
                            # User-pinned input items take precedence over the
                            # auto-pick. Stored on node.gear_config under
                            # `user_input_items` (set by the slot popup with
                            # always-lock semantics). The auto-pick fills any
                            # remaining slots so partial pins still work.
                            gear_cfg = node.get("gear_config") or {}
                            user_inputs = gear_cfg.get("user_input_items") or {}
                            # Normalize keys (JSON round-trip) to int for
                            # internal use, then back to str for the worker.
                            user_inputs_by_idx = {
                                int(k): v for k, v in user_inputs.items() if v is not None
                            }
                            picked = _auto_pick_input_items_for_activity(
                                _act, session_data, getattr(_act, 'primary_skill', '') or ''
                            )
                            # Merge: auto-picks first, user pins overlay.
                            merged = dict(picked) if picked else {}
                            merged.update(user_inputs_by_idx)
                            if merged:
                                request_data["input_items"] = {str(k): v for k, v in merged.items()}
                                request_data["use_fine_inputs"] = bool(
                                    global_settings.get("use_fine_materials", False)
                                )
                                _src = []
                                for k, v in merged.items():
                                    tag = "USER" if k in user_inputs_by_idx else "auto"
                                    _src.append((k, v.get('name'), tag))
                                log(
                                    f"  [ct-worker] Input items for {node_activity_id}: {_src}",
                                    session_uuid,
                                )
                    except Exception as _e:
                        log(f"  [ct-worker] Auto-pick input items failed: {_e}", session_uuid)

                log(f"Crafting tree: optimizing node {node['node_id']} ({node_source_type}) recipe={node_recipe_id} activity={node_activity_id} service={node_service_id} location={node_location} chest_target={node_chest_target!r} include_pets={_include_pets_for_cache} include_consumables={_include_consumables_for_cache}", session_uuid)

                # Per-node optimize via the injected executor. Returns a
                # result-like object exposing .returncode / .stdout / .stderr
                # (subprocess.CompletedProcess on the server; an equivalent
                # shim for the in-process local path), so the parsing below is
                # byte-identical for both.
                result = node_executor(request_data)
                # Parse result from stdout
                if result.returncode == 0 and result.stdout.strip():
                    import json as _json
                    opt_result = _json.loads(result.stdout.strip())
                    if opt_result.get("success"):
                        gearset_export = opt_result.get("gearset_export")
                        opt_stats = opt_result.get("stats", {})
                        opt_metrics = opt_result.get("metrics", {})

                        # Log key optimizer output for determinism debugging
                        if result.stderr:
                            for line in result.stderr.splitlines():
                                if any(kw in line for kw in ('Found ', 'After ', 'Converged', 'items in inventory', 'WE:', 'QO:', 'service', 'Service')):
                                    log(f"  [ct-worker] {line.strip()}", session_uuid)

                        # Log the final stats for determinism debugging
                        we = opt_stats.get('work_efficiency', 0)
                        dr = opt_stats.get('double_rewards', 0)
                        qo = opt_stats.get('quality_outcome', 0)
                        log(f"  [ct-worker] Result stats: WE={we*100:.1f}% DR={dr*100:.1f}% QO={qo:.0f}", session_uuid)
                        # Log the actual items in the gearset
                        items_in_gearset = opt_result.get('items', {})
                        if items_in_gearset:
                            items_str = ', '.join(f"{s}:{n}" for s, n in sorted(items_in_gearset.items()) if n)
                            log(f"  [ct-worker] Gearset items: {items_str}", session_uuid)

                        node["gear_config"]["optimized_export"] = gearset_export
                        node["gear_config"]["optimized_stats"] = opt_stats

                        # Persist the optimizer's pet + consumable picks on the
                        # node so:
                        # (a) the gear-preview tile renders them visually,
                        # (b) _decode_gearset_stats can re-apply them on later
                        #     re-decodes (location/service change, page reload).
                        # encode_gearset() does NOT include pet/consumable in
                        # the export string — gearset_utils.Gearset has no
                        # _pet/_consumable slot. Without persisting these
                        # separately, the optimizer's pick was silently lost.
                        # User-reported (Xavlamin bug d3ce19e5): "no pets and
                        # consumables. Please fix."
                        sel_pet_meta = opt_result.get("selected_pet")
                        sel_cons_meta = opt_result.get("selected_consumable")
                        if sel_pet_meta and isinstance(sel_pet_meta, dict):
                            # Worker stores: {name, level, variant}. Map to
                            # the same shape locked_slots uses (itemId =
                            # lowercased species, level, name) so the same
                            # _decode_gearset_stats overlay path works.
                            species_name = sel_pet_meta.get("name") or ""
                            # Persist the FULL meta dict so icon_path / type
                            # / max_level / etc. survive the round-trip to the
                            # frontend. Bug 331d38da: previously we only
                            # persisted {itemId, name, level, variant} —
                            # missing icon_path made the gear-slot-grid fall
                            # back to placeholder.svg (which doesn't exist),
                            # rendering a broken image whose alt text leaked
                            # the name as visible text.
                            node["gear_config"]["optimized_pet"] = {
                                **sel_pet_meta,
                                "itemId": species_name.lower().replace(" ", "_"),
                                "name": species_name,
                                "level": int(sel_pet_meta.get("level") or 0),
                                "variant": sel_pet_meta.get("variant") or "normal",
                                "type": "pet",
                            }
                            log(
                                f"  [ct-worker] Persisted selected pet on node: "
                                f"{species_name} lvl {sel_pet_meta.get('level')}",
                                session_uuid,
                            )
                        else:
                            node["gear_config"]["optimized_pet"] = None
                        if sel_cons_meta and isinstance(sel_cons_meta, dict):
                            cons_name = sel_cons_meta.get("name") or ""
                            # Persist the full meta dict — icon_path, is_fine,
                            # type all need to round-trip to the frontend so
                            # the gear preview tile + the Equip flow render
                            # the icon and the cyan Fine outline.
                            # Bug 331d38da follow-up.
                            node["gear_config"]["optimized_consumable"] = {
                                **sel_cons_meta,
                                "itemId": (
                                    sel_cons_meta.get("itemId")
                                    or cons_name.lower().replace(" ", "_").replace("'", "")
                                ),
                                "name": cons_name,
                                "type": "consumable",
                            }
                            log(
                                f"  [ct-worker] Persisted selected consumable on node: {cons_name}",
                                session_uuid,
                            )
                        else:
                            node["gear_config"]["optimized_consumable"] = None

                        # Lock-conflict detection: if the user pinned specific
                        # items via node.locked_slots, check whether the
                        # constrained optimizer result still satisfies the
                        # activity/recipe keyword requirements. When it does
                        # not (e.g. locked a non-hatchet into the only tool
                        # slot needed for Cut Birch), stash a short warning
                        # string that the frontend renders as a yellow ⚠️
                        # on the card and aggregates into summary.lock_warnings.
                        lock_warning = None
                        if node_locked_slots:
                            try:
                                from ui.crafting_tree import _check_locked_gearset_conflicts
                                req_obj = None
                                if node_source_type == 'activity' and node_activity_id:
                                    from util.autogenerated.activities import Activity
                                    req_obj = getattr(Activity, node_activity_id.upper(), None)
                                elif node_source_type == 'recipe' and node_recipe_id:
                                    from util.autogenerated.recipes import Recipe
                                    # Recipe IDs are stored as Title-cased names
                                    # (e.g. "Iron Sickle"); the autogen module
                                    # exposes them on the Recipe class via
                                    # attribute access.
                                    req_obj = (
                                        getattr(Recipe, node_recipe_id.upper().replace(' ', '_'), None)
                                        or getattr(Recipe, node_recipe_id, None)
                                    )
                                if req_obj is not None:
                                    # Pass selected_input_items so input
                                    # keywords (arrows/plant/fabric) count
                                    # toward the requirement — without this
                                    # the warning fires "Arrows missing"
                                    # for hunting activities even when the
                                    # input slot has arrows. opt_result
                                    # echoes selected_input_items back from
                                    # the worker (see optimize_worker.py
                                    # crafting_tree_node activity result).
                                    _ws_input_items = (
                                        opt_result.get("selected_input_items")
                                        or (node.get("gear_config") or {}).get("user_input_items")
                                        or (node.get("gear_config") or {}).get("selected_input_items")
                                        or {}
                                    )
                                    lock_warning = _check_locked_gearset_conflicts(
                                        req_obj, gearset_export, node_locked_slots,
                                        _ws_input_items,
                                    )
                            except Exception as _exc:
                                log(f"  [ct-worker] lock-conflict check raised {_exc!r}; skipping", session_uuid)
                        # Always set the field so a previous warning clears
                        # when the user unlocks a conflicting item.
                        node["gear_config"]["lock_warning"] = lock_warning

                        # Persist the worker's slot_alternatives onto the node
                        # so the tree-node slot popup's "Non-owned/Locked
                        # Upgrades" section can render. The popup at
                        # ui/static/js/components/tree-node-card.js (~L2136)
                        # reads gearConfig.slot_alternatives and splits it
                        # into the two passes for the popup — without this
                        # save, the worker's alternatives output was
                        # silently dropped and the popup permanently showed
                        # the "Optimize Slot & Equip" button. Always set
                        # the field (even to an empty wrapper) so the
                        # popup can distinguish "computed but no upgrades"
                        # from "alternatives never computed".
                        _opt_alts = opt_result.get("alternatives")
                        _opt_locked_alts = opt_result.get("locked_alternatives")
                        if _opt_alts is not None or _opt_locked_alts is not None:
                            node["gear_config"]["slot_alternatives"] = {
                                "alternatives": _opt_alts or {},
                                "locked_alternatives": _opt_locked_alts or {},
                            }
                        else:
                            node["gear_config"]["slot_alternatives"] = None

                        # If worker found a best location for a no-service recipe, store it on the node
                        best_location = opt_result.get("best_location")
                        if best_location:
                            node["selected_location_id"] = best_location

                        # Cache for shared gearset reuse. Includes optimized_pet
                        # / optimized_consumable so that two nodes sharing the same
                        # (source, location, locks, include flags) cache key see the
                        # same auto-picked pet/consumable. Without this, the first
                        # node persisted them via the node["gear_config"] mutation
                        # below, but the second node (cache hit) read them from a
                        # cache entry that didn't have them. Bug 9ce474f8.
                        _opt_pet_for_cache = node["gear_config"].get("optimized_pet") if "gear_config" in node else None
                        _opt_cons_for_cache = node["gear_config"].get("optimized_consumable") if "gear_config" in node else None
                        _optimization_cache[cache_key] = {
                            "gearset_export": gearset_export,
                            "stats": opt_stats,
                            "metrics": opt_metrics,
                            "selected_input_items": opt_result.get("selected_input_items") or {},
                            "optimized_pet": _opt_pet_for_cache,
                            "optimized_consumable": _opt_cons_for_cache,
                            # Cache the slot_alternatives wrapper too so a
                            # second node sharing the same cache key gets
                            # the same upgrade list on the popup. Mirrors
                            # the optimized_pet/consumable caching above.
                            "slot_alternatives": node["gear_config"].get("slot_alternatives"),
                        }

                        # Persist the resolved input item(s) on the node so the
                        # frontend can render them in the gear preview and copy
                        # them to column3.selectedInputItems on Equip.
                        sii = opt_result.get("selected_input_items") or {}
                        if sii:
                            node["gear_config"]["selected_input_items"] = sii

                        # Recompute every node's metrics from the freshly
                        # mutated gear_configs. This refreshes
                        # node['metrics']['steps_per_item'] across the whole
                        # tree so the next eligible node (a parent, since
                        # `eligible` is sorted bottom-up) builds its
                        # `child_input_specs` from POST-optimization child
                        # metrics — the missing piece that made the
                        # tree-aware optimization deterministic in one pass.
                        #
                        # Without this call, _kid.get("metrics") returned the
                        # children's PRE-batch metrics and the optimizer
                        # was effectively running coordinate descent across
                        # batches: each click started from the prior click's
                        # output, sometimes converging, sometimes oscillating
                        # between local optima (user-reported 408k → 383k →
                        # 384k cycles). Bug f178049a + 04a95d91 (originally
                        # bc299b02, reverted by 9f944750, re-applied here).
                        #
                        # `calculate_tree` only walks the existing nodes and
                        # recomputes math (no optimizer, no LP, no
                        # subprocess) — fast even for ~12-node trees.
                        try:
                            from ui.crafting_tree import calculate_tree as _ct_calc, _load_game_data as _ct_load
                            _ct_calc(
                                nodes,
                                global_settings,
                                _ct_load(),
                                session_data,
                            )
                        except Exception as _ct_err:
                            log(
                                f"  [ct-worker] calculate_tree refresh failed for node "
                                f"{node['node_id']}: {_ct_err!r} — parents in this batch "
                                f"may use stale child metrics",
                                session_uuid,
                            )

                        _record_completed({
                            "node_id": node["node_id"],
                            "gearset_export": gearset_export,
                            "stats": opt_stats,
                            "metrics": opt_metrics,
                            "alternatives": node.get("alternatives", []),
                            "selected_location_id": best_location or node.get("selected_location_id"),
                            "selected_input_items": sii,
                            # best_location is ONLY populated when the worker
                            # auto-resolved the location (no user pick). Frontend
                            # uses its presence to distinguish "worker chose this"
                            # vs "user locked this and worker just respected it",
                            # so it can render "Best → X" only for the first case.
                            "best_location": best_location,
                            # Echo the optimizer's pet/consumable picks so the
                            # frontend can persist them onto its local node copy.
                            # Set on node["gear_config"] above (sel_pet_meta /
                            # sel_cons_meta block), but the frontend tracks its
                            # own copy of nodes — without echoing here, the
                            # picks were silently lost on the round-trip and
                            # selected_pet_id/selected_consumable_id stayed null
                            # in the persisted tree state. Bug 9ce474f8.
                            "optimized_pet": node["gear_config"].get("optimized_pet"),
                            "optimized_consumable": node["gear_config"].get("optimized_consumable"),
                            # Echo the slot_alternatives wrapper so the
                            # frontend's optimize-status polling can apply
                            # it onto its local node.gear_config — same
                            # mutate-server-then-echo pattern as
                            # optimized_pet above. Without this, the popup's
                            # "Non-owned/Locked Upgrades" section was empty
                            # after every optimize because the wrapper was
                            # set on the backend's request-body copy of the
                            # node but never reached the frontend's local
                            # copy. Bug 331d38da.
                            "slot_alternatives": node["gear_config"].get("slot_alternatives"),
                        })
                    else:
                        error_msg = opt_result.get("error", "Unknown error")
                        log(f"Crafting tree node optimization failed: {error_msg}", session_uuid)
                        _record_completed({
                            "node_id": node["node_id"],
                            "error": error_msg,
                        })
                else:
                    stderr_msg = result.stderr[:500] if result.stderr else "No output"
                    stdout_msg = result.stdout[:500] if result.stdout else "No stdout"
                    log(f"Crafting tree worker failed: stderr={stderr_msg} stdout={stdout_msg}", session_uuid)
                    _record_completed({
                        "node_id": node["node_id"],
                        "error": f"Worker failed (exit {result.returncode}): {stderr_msg[:200]}",
                    })

            except subprocess.TimeoutExpired:
                _record_completed({
                    "node_id": node["node_id"],
                    "error": "Optimization timed out",
                })
            except Exception as e:
                log(f"Crafting tree optimization error: {e}", session_uuid)
                _record_completed({
                    "node_id": node["node_id"],
                    "error": str(e),
                })

            _dec_pending()


    import copy as _copy
    from ui.crafting_tree import (
        calculate_tree as _ct_calc,
        _load_game_data as _ct_load,
        on_source_change as _ct_on_source_change,
        descendant_ids as _ct_descendant_ids,
        route_candidates as _ct_route_candidates,
        _best_auto_children_ambiguous as _ct_ambiguous,
    )
    _game_data = _ct_load()
    _skip_shops = global_settings.get("skip_shops", True)

    def _eligible_filter(n):
        if n.get("source_type") == "bank":
            return False
        if n.get("gear_config", {}).get("mode") != "auto":
            return False
        if node_ids and n["node_id"] not in node_ids:
            return False
        return True

    # Best(auto) nodes that are route-ambiguous (>=2 candidate subtrees) and in
    # scope for this request. For these the gear-independent underlying pick
    # (_pick_best_underlying_source) can be wrong; we re-optimize each candidate
    # route's subtree and keep the one with the lowest optimized steps/item.
    route_best_nodes = [
        n for n in nodes
        if n.get("source_type") == "best"
        and _eligible_filter(n)
        and _ct_ambiguous(n.get("available_sources") or [])
    ]
    route_best_nodes.sort(key=lambda n: (-(n.get("depth") or 0), n.get("node_id") or ""))

    # Seed progress so the status endpoint shows activity during the (slow)
    # route trials, which run with record=False.
    _initial_eligible = [n for n in nodes if _eligible_filter(n)]
    task["total"] = len(_initial_eligible)
    task["pending"] = len(_initial_eligible)

    ROUTE_FINALIST_BAND = 1.10  # routes within 10% of the best CHEAP estimate
                                # also get a full optimize before the final pick

    def _build_route_trial(_bn_id, _cand):
        """Deepcopy the live tree and switch _bn_id onto _cand's route.

        Returns (_trial, _sub_elig, _tcbp) or None on failure.
        """
        _trial = _copy.deepcopy(nodes)
        try:
            _trial = _ct_on_source_change(_trial, _bn_id, _cand, _game_data, session_data, True)
        except Exception as _e:
            log(f"  [ct-route] on_source_change failed for {_bn_id} "
                f"cand={_cand.get('type')}:{_cand.get('source_id')}: {_e!r}", session_uuid)
            return None
        _sub_ids = _ct_descendant_ids(_trial, _bn_id) | {_bn_id}
        _sub_elig = [n for n in _trial
                     if n["node_id"] in _sub_ids
                     and n.get("source_type") != "bank"
                     and n.get("gear_config", {}).get("mode") == "auto"]
        _sub_elig.sort(key=lambda n: (-(n.get("depth") or 0), n.get("node_id") or ""))
        _tcbp = {}
        for _n in _trial:
            _pid = _n.get("parent_id")
            if _pid:
                _tcbp.setdefault(_pid, []).append(_n)
        return _trial, _sub_elig, _tcbp

    def _trial_steps_per_item(_trial, _sub_elig, _tcbp, _bn_id, fast_rank):
        """Optimize a candidate subtree and read the Best(auto) node's
        steps/item. fast_rank=True runs the cheap greedy estimate (for
        ranking); fast_rank=False runs the full deep optimize (final quality).
        """
        _optimize_pass(_trial, _sub_elig, _tcbp, {}, record=False, fast_rank=fast_rank)
        _ct_calc(_trial, global_settings, _game_data, session_data)
        _tbn = next((n for n in _trial if n["node_id"] == _bn_id), None)
        _spi = (_tbn or {}).get("metrics", {}).get("steps_per_item")
        try:
            return float(_spi) if _spi is not None else float("inf")
        except (TypeError, ValueError):
            return float("inf")

    resolved_ids = set()  # node_ids already gear-optimized via a winning trial
    for _bn in route_best_nodes:
        _bn_id = _bn["node_id"]
        _cands = _ct_route_candidates(_bn.get("available_sources") or [], skip_shops=_skip_shops)
        if len(_cands) <= 1:
            continue

        # --- Phase 1: cheap, gear-aware ranking of EVERY candidate route. ----
        # A greedy (swaps-off, single-iteration) optimize is fast and good
        # enough to RANK routes; it is NOT used as the final gearset. This
        # replaces the old "full deep optimize for every route" loop that blew
        # past the client's 120s poll budget on trees with several multi-route
        # Best(auto) nodes (bug f5a30d6b). Route correctness (bug 9b3527ef) is
        # preserved: the estimate is gear-aware, and near-ties are settled by a
        # full optimize in Phase 2.
        _cheap = []  # (cheap_spi, _cand)
        for _cand in _cands:
            _built = _build_route_trial(_bn_id, _cand)
            if _built is None:
                continue
            try:
                _spi = _trial_steps_per_item(_built[0], _built[1], _built[2], _bn_id, True)
            except Exception as _e:
                log(f"  [ct-route] cheap-rank failed for {_bn_id} "
                    f"cand={_cand.get('type')}:{_cand.get('source_id')}: {_e!r}", session_uuid)
                continue
            log(f"  [ct-route] {_bn.get('item_id')} via "
                f"{_cand.get('type')}:{_cand.get('source_id')} -> cheap steps/item={_spi:.1f}",
                session_uuid)
            _cheap.append((_spi, _cand))

        _finalists = _select_route_finalists(_cheap, ROUTE_FINALIST_BAND)
        if not _finalists:
            continue

        # --- Phase 2: full optimize for the best route + any within 10%. -----
        # Usually exactly one finalist; only a genuine near-tie (<=10% on the
        # cheap estimate) triggers a second full optimize, bounding the extra
        # cost while protecting route correctness on close calls.
        _best_spi = float("inf")
        _best_trial = None
        _best_cand = None
        for _cand in _finalists:
            _built = _build_route_trial(_bn_id, _cand)
            if _built is None:
                continue
            try:
                _spi = _trial_steps_per_item(_built[0], _built[1], _built[2], _bn_id, False)
            except Exception as _e:
                log(f"  [ct-route] full trial failed for {_bn_id} "
                    f"cand={_cand.get('type')}:{_cand.get('source_id')}: {_e!r}", session_uuid)
                continue
            log(f"  [ct-route] {_bn.get('item_id')} via "
                f"{_cand.get('type')}:{_cand.get('source_id')} -> full steps/item={_spi:.1f}",
                session_uuid)
            if _spi < _best_spi:
                _best_spi = _spi
                _best_trial = _built[0]
                _best_cand = _cand
        if _best_trial is None or _best_cand is None:
            continue
        # Splice the winning route's subtree into the live node list, keeping
        # the node itself as Best(auto) but pinning the gear-aware underlying.
        _win_sub_ids = _ct_descendant_ids(_best_trial, _bn_id)
        _win_children = [n for n in _best_trial if n["node_id"] in _win_sub_ids]
        _win_bn = next((n for n in _best_trial if n["node_id"] == _bn_id), None)
        if _win_bn is None:
            continue
        _win_bn["source_type"] = "best"
        _win_bn["source_id"] = "__best__"
        _win_bn["underlying_source_type"] = _best_cand.get("type")
        _win_bn["underlying_source_id"] = _best_cand.get("source_id")
        _old_sub_ids = _ct_descendant_ids(nodes, _bn_id)
        nodes[:] = ([n for n in nodes
                     if n["node_id"] != _bn_id and n["node_id"] not in _old_sub_ids]
                    + [_win_bn] + _win_children)
        resolved_ids |= ({_bn_id} | _win_sub_ids)
        log(f"  [ct-route] {_bn.get('item_id')}: chose "
            f"{_best_cand.get('type')}:{_best_cand.get('source_id')} "
            f"(steps/item={_best_spi:.1f})", session_uuid)

    # Refresh metrics after any splices so the main pass + parents see fresh
    # child metrics.
    try:
        _ct_calc(nodes, global_settings, _game_data, session_data)
    except Exception:
        pass

    # Main pass: optimize everything in scope not already optimized inside a
    # winning route trial.
    _main_eligible = [n for n in nodes
                      if _eligible_filter(n) and n["node_id"] not in resolved_ids]
    _main_eligible.sort(key=lambda n: (-(n.get("depth") or 0), n.get("node_id") or ""))
    _main_cbp = {}
    for _n in nodes:
        _pid = _n.get("parent_id")
        if _pid:
            _main_cbp.setdefault(_pid, []).append(_n)
    _resolved_best = [n for n in route_best_nodes if n["node_id"] in resolved_ids]
    task["total"] = len(_main_eligible) + len(_resolved_best)
    task["pending"] = len(_main_eligible) + len(_resolved_best)
    _optimize_pass(nodes, _main_eligible, _main_cbp, {}, record=True)

    # Emit completed entries for the resolved Best(auto) nodes (progress + so
    # the frontend can apply gear even before it adopts the full tree).
    for _bn in _resolved_best:
        _bn2 = next((n for n in nodes if n["node_id"] == _bn["node_id"]), None)
        if _bn2 is None:
            continue
        _gc = _bn2.get("gear_config", {}) or {}
        task["completed_nodes"].append({
            "node_id": _bn2["node_id"],
            "gearset_export": _gc.get("optimized_export"),
            "stats": _gc.get("optimized_stats", {}),
            "metrics": _bn2.get("metrics", {}),
            "route_resolved": True,
            "underlying_source_type": _bn2.get("underlying_source_type"),
            "underlying_source_id": _bn2.get("underlying_source_id"),
        })
        task["pending"] = max(0, task.get("pending", 1) - 1)

    # Route resolution rebuilds subtrees (new node_ids), so the frontend can't
    # merge by node_id alone — hand it the full updated tree to adopt.
    task["final_nodes"] = nodes
    task["status"] = "complete"

